export default {
  'en': {
    'login': 'Login',
    'signup': 'Sign Up',
    'reset-password': 'Reset Password',
    'confirm-code': 'Confirm Code',
    'CODE_ON_THE_WAY_TIP': 'Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.',
    'PW_POLICY_TIP': '1. at least 8 characters.\n' +
      '2. must have lowercase characters.\n' +
      '3. must have uppercase characters.\n' +
      '4. must have symbol characters.',
    'You are already logged in as': 'You are already logged in as',
    'Sign out': 'Sign Out',
    'Bad Response.': 'Bad Response.',
    'Email': 'Email',
    'Password': 'Password',
    'Sign in': 'Sign In',
    'Confirm': 'Confirm',
    'Don\'t have an account?': 'Don\'t have an account?',
    'Sign up': 'Sign Up',
    'or': 'or',
    'Forgot your password?': 'Forgot your password?',
    'Create account': 'Create Account',
    'Username': 'Username',
    'Confirm Password': 'Confirm Password',
    'New Password': 'New Password',
    'By signing up, you agree to our': 'By signing up, you agree to our',
    'Terms of Service': 'Terms of Service',
    ' and ': ' and ',
    'Privacy Policy': 'Privacy Policy',
    'Already have an account?': 'Already have an account?',
    'Reset password': 'Reset Password',
    'Enter the code sent to your email': 'Enter the code sent to your email',
    'Send code': 'Send Code',
    'Resend code': 'Resend Code',
    'Back to login': 'Back to Login',
    'Enter your email': 'Enter your email',
    'Invalid Password': 'Invalid Password',
    'Passwords do not match.': 'Passwords do not match.',
    'Password must be at least 8 characters.': 'Password must be at least 8 characters.',
    'We have sent a numeric verification code to your email address at': 'We have sent a numeric verification code to your email address at',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Unsupported sign-in step:',
  },
  'zh-CN': {
    'login': '登录',
    'signup': '注册',
    'reset-password': '重置密码',
    'confirm-code': '确认验证码',
    'PW_POLICY_TIP': '1. 密码长度至少8个字符\n' +
      '2. 密码必须包含小写字母\n' +
      '3. 密码必须包含大写字母\n' +
      '4. 密码必须包含特殊字符',
    'CODE_ON_THE_WAY_TIP': '验证码已发送。请输入我们发送给您的验证码以登录。可能需要一分钟才能收到。',
    'Sign in to your account': '登录到您的账户',
    'You are already logged in as': '您当前已登录为',
    'Sign out': '退出登录',
    'Bad Response.': '请求失败。',
    'Email': '邮箱',
    'Password': '密码',
    'Sign in': '登录',
    'Confirm': '确认',
    'Don\'t have an account?': '还没有账户？',
    'Sign up': '注册',
    'or': '或',
    'Forgot your password?': '忘记密码？',
    'Create account': '创建账户',
    'Username': '用户名',
    'Confirm Password': '确认密码',
    'New Password': '新密码',
    'By signing up, you agree to our': '注册即表示您同意我们的',
    'Terms of Service': '服务条款',
    ' and ': '和',
    'Privacy Policy': '隐私政策',
    'Already have an account?': '已经有账户？',
    'Reset password': '重置密码',
    'Enter the code sent to your email': '输入发送到您邮箱的验证码',
    'Send code': '发送验证码',
    'Resend code': '重新发送验证码',
    'Back to login': '返回登录',
    'Enter your email': '请输入您的邮箱',
    'Invalid Password': '密码无效',
    'Passwords do not match.': '两次输入的密码不一致。',
    'Password must be at least 8 characters.': '密码至少需要 8 个字符。',
    'We have sent a numeric verification code to your email address at': '我们已向此邮箱发送数字验证码：',
    'COUNTDOWN_SUFFIX': '秒',
    'Unsupported sign-in step:': '不支持的登录步骤：'
  },
  'zh-Hant': {
    'login': '登入',
    'signup': '註冊',
    'reset-password': '重置密碼',
    'confirm-code': '確認驗證碼',
    'CODE_ON_THE_WAY_TIP': '驗證碼已發送。請輸入我們發送給您的驗證碼以登入。可能需要一分鐘才能收到。',
    'PW_POLICY_TIP': '1. 密碼長度至少8個字符\n' +
      '2. 密碼必須包含小寫字母\n' +
      '3. 密碼必須包含大寫字母\n' +
      '4. 密碼必須包含特殊字符',
    'Sign in to your account': '登入到您的帳戶',
    'You are already logged in as': '您目前已登入為',
    'Sign out': '登出',
    'Bad Response.': '請求失敗。',
    'Email': '電子郵件',
    'Password': '密碼',
    'Sign in': '登入',
    'Confirm': '確認',
    'Don\'t have an account?': '還沒有帳戶？',
    'Sign up': '註冊',
    'or': '或',
    'Forgot your password?': '忘記密碼？',
    'Create account': '建立帳戶',
    'Username': '用戶名',
    'Confirm Password': '確認密碼',
    'New Password': '新密碼',
    'By signing up, you agree to our': '註冊即表示您同意我們的',
    'Terms of Service': '服務條款',
    ' and ': '和',
    'Privacy Policy': '隱私政策',
    'Already have an account?': '已經有帳戶？',
    'Reset password': '重置密碼',
    'Enter the code sent to your email': '輸入發送到您郵箱的驗證碼',
    'Send code': '發送驗證碼',
    'Resend code': '重新發送驗證碼',
    'Back to login': '返回登入',
    'Enter your email': '請輸入您的電子郵件',
    'Invalid Password': '密碼無效',
    'Passwords do not match.': '兩次輸入的密碼不一致。',
    'Password must be at least 8 characters.': '密碼至少需要 8 個字元。',
    'We have sent a numeric verification code to your email address at': '我們已向此電子郵件地址發送數字驗證碼：',
    'COUNTDOWN_SUFFIX': '秒',
    'Unsupported sign-in step:': '不支援的登入步驟：'
  },
  'ja': {
    'login': 'ログイン',
    'signup': 'サインアップ',
    'reset-password': 'パスワードをリセットする',
    'confirm-code': 'コードを確認する',
    'CODE_ON_THE_WAY_TIP': 'コードが送信されました。ログインするには、送信したコードを入力してください。届くまでに1分ほどかかる場合があります。',
    'PW_POLICY_TIP': '1. パスワードは8文字以上であること。\n' +
      '2. パスワードには小文字を含める必要があります。\n' +
      '3. パスワードには大文字を含める必要があります。\n' +
      '4. パスワードには記号を含める必要があります。',
    'Sign in to your account': 'アカウントにサインイン',
    'You are already logged in as': '現在のログインユーザー',
    'Sign out': 'ログアウト',
    'Bad Response.': 'リクエストに失敗しました。',
    'Email': 'メール',
    'Password': 'パスワード',
    'Sign in': 'サインイン',
    'Confirm': '確認',
    'Don\'t have an account?': 'アカウントをお持ちでないですか？',
    'Sign up': 'サインアップ',
    'or': 'または',
    'Forgot your password?': 'パスワードをお忘れですか？',
    'Create account': 'アカウントを作成',
    'Username': 'ユーザー名',
    'New Password': '新しいパスワード',
    'Confirm Password': 'パスワードを確認する',
    'By signing up, you agree to our': 'サインアップすると、次の内容に同意したものとみなされます',
    'Terms of Service': '利用規約',
    ' and ': 'および',
    'Privacy Policy': 'プライバシーポリシー',
    'Already have an account?': 'すでにアカウントをお持ちですか？',
    'Reset password': 'パスワードをリセットする',
    'Enter the code sent to your email': 'メールに送信されたコードを入力してください',
    'Send code': 'コードを送信',
    'Resend code': 'コードを再送信',
    'Back to login': 'ログインに戻る',
    'Enter your email': 'メールアドレスを入力してください',
    'Invalid Password': '無効なパスワード',
    'Passwords do not match.': 'パスワードが一致しません。',
    'Password must be at least 8 characters.': 'パスワードは 8 文字以上である必要があります。',
    'We have sent a numeric verification code to your email address at': '次のメールアドレスに数字の確認コードを送信しました:',
    'COUNTDOWN_SUFFIX': '秒',
    'Unsupported sign-in step:': '未対応のサインイン手順:'
  }
}
