export default {
  'en': {
    'CODE_ON_THE_WAY_TIP': 'Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.',
  },
  'zh-CN': {
    'CODE_ON_THE_WAY_TIP': '验证码已发送。请输入我们发送给您的验证码以登录。可能需要一分钟才能收到。',
    'Sign in to your account': '登录到您的账户',
    'Email': '电子邮箱',
    'Password': '密码',
    'Sign in': '登录',
    'Confirm': '确认',
    'Don\'t have an account?': '还没有账户？',
    'Sign up': '注册',
    'or': '或 ',
    'Forgot your password?': '忘记密码？',
    'Create account': '创建您的账户',
    'Username': '用户名',
    'Confirm Password': '确认密码',
    'New Password': '新密码',
    'By signing up, you agree to our': '注册即表示您同意我们的 ',
    'Terms of Service': '服务条款',
    'Privacy Policy': '隐私政策',
    'Already have an account?': '已经有账户？',
    'Reset password': '重置您的密码',
    'Enter the code sent to your email': '输入发送到您邮箱的验证码',
    'Send code': '发送验证码',
    'Resend code': '重新发送验证码',
    'Back to login': '返回登录',
    'Enter your email': '请输入您的电子邮箱'
  },
  'zh-Han': {
    'CODE_ON_THE_WAY_TIP': '驗證碼已發送。請輸入我們發送給您的驗證碼以登入。可能需要一分鐘才能收到。',
    'Sign in to your account': '登入到您的帳戶',
    'Email': '電子郵箱',
    'Password': '密碼',
    'Sign in': '登入',
    'Confirm': '確認',
    'Don\'t have an account?': '還沒有帳戶？',
    'Sign up': '註冊',
    'or': '或 ',
    'Forgot your password?': '忘記密碼？',
    'Create account': '創建您的帳戶',
    'Username': '用戶名',
    'Confirm Password': '確認密碼',
    'New Password': '新密碼',
    'By signing up, you agree to our': '註冊即表示您同意我們的 ',
    'Terms of Service': '服務條款',
    'Privacy Policy': '隱私政策',
    'Already have an account?': '已經有帳戶？',
    'Reset password': '重置您的密碼',
    'Enter the code sent to your email': '輸入發送到您郵箱的驗證碼',
    'Send code': '發送驗證碼',
    'Resend code': '重新發送驗證碼',
    'Back to login': '返回登入',
    'Enter your email': '請輸入您的電子郵箱'
  },
  'ja': {
    'CODE_ON_THE_WAY_TIP': 'コードが送信されました。ログインするには、送信したコードを入力してください。届くまでに1分ほどかかる場合があります。',
    'Sign in to your account': 'アカウントにサインイン',
    'Email': 'メール',
    'Password': 'パスワード',
    'Sign in': 'サインイン',
    'Confirm': '確認',
    'Don\'t have an account?': 'アカウントをお持ちでないですか？',
    'Sign up': 'サインアップ',
    'or': 'または ',
    'Forgot your password?': 'パスワードをお忘れですか？',
    'Create account': 'アカウントを作成する',
    'Username': 'ユーザー名',
    'New Password': '新しいパスワード',
    'Confirm Password': 'パスワードを確認する',
    'By signing up, you agree to our': 'サインアップすることで、あなたは私たちの ',
    'Terms of Service': '利用規約',
    'Privacy Policy': 'プライバシーポリシー',
    'Already have an account? ': 'すでにアカウントをお持ちですか？',
    'Reset password': 'パスワードをリセットする',
    'Enter the code sent to your email': 'メールに送信されたコードを入力してください',
    'Send code': 'コードを送信',
    'Resend code': 'コードを再送信',
    'Back to login': 'ログインに戻る',
    'Enter your email': 'メールアドレスを入力してください'
  }
}
