export default {
  'en': {
    'login': 'Login',
    'signup': 'Sign Up',
    'reset-password': 'Reset Password',
    'confirm-code': 'Confirm Code',
    'CODE_ON_THE_WAY_TIP': 'Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.',
    'PW_POLICY_TIP': '1. at least 8 characters.\n' +
      '2. must have lowercase characters.\n' +
      '3. must have uppercase characters.\n' +
      '4. must have symbol characters.',
    'You are already logged in as': 'You are already logged in as',
    'Sign out': 'Sign Out',
    'Bad Response.': 'Bad Response.',
    'Email': 'Email',
    'Password': 'Password',
    'Sign in': 'Sign In',
    'Confirm': 'Confirm',
    'Don\'t have an account?': 'Don\'t have an account?',
    'Sign up': 'Sign Up',
    'or': 'or',
    'Forgot your password?': 'Forgot your password?',
    'Create account': 'Create Account',
    'Username': 'Username',
    'Confirm Password': 'Confirm Password',
    'New Password': 'New Password',
    'By signing up, you agree to our': 'By signing up, you agree to our',
    'Terms of Service': 'Terms of Service',
    ' and ': ' and ',
    'Privacy Policy': 'Privacy Policy',
    'Already have an account?': 'Already have an account?',
    'Reset password': 'Reset Password',
    'Enter the code sent to your email': 'Enter the code sent to your email',
    'Send code': 'Send Code',
    'Resend code': 'Resend Code',
    'Back to login': 'Back to Login',
    'Enter your email': 'Enter your email',
    'Invalid Password': 'Invalid Password',
    'Passwords do not match.': 'Passwords do not match.',
    'We have sent a numeric verification code to your email address at': 'We have sent a numeric verification code to your email address at',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Unsupported sign-in step:',
    'AUTH_ERROR_GENERIC': 'Authentication failed. Please try again.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Incorrect email or password.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Your account is not confirmed yet. Please verify it with the code we sent.',
    'AUTH_ERROR_USERNAME_EXISTS': 'This username is already taken.',
    'AUTH_ERROR_USER_NOT_FOUND': 'We could not find an account for that email address.',
    'AUTH_ERROR_CODE_MISMATCH': 'The verification code is incorrect.',
    'AUTH_ERROR_CODE_EXPIRED': 'The verification code has expired. Please request a new one.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Too many requests. Please wait a moment and try again.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Too many failed attempts. Please wait a moment and try again.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'We could not send the verification code. Please try again later.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'You are already signed in.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Some information is invalid. Please check your input and try again.',
  },
  'zh-CN': {
    'login': '登录',
    'signup': '注册',
    'reset-password': '重置密码',
    'confirm-code': '确认验证码',
    'CODE_ON_THE_WAY_TIP': '验证码已发送。请输入我们发送给您的验证码以登录。可能需要一分钟才能收到。',
    'PW_POLICY_TIP': '1. 密码长度至少8个字符\n' +
      '2. 密码必须包含小写字母\n' +
      '3. 密码必须包含大写字母\n' +
      '4. 密码必须包含特殊字符',
    'Sign in to your account': '登录到您的账户',
    'You are already logged in as': '您当前已登录为',
    'Sign out': '退出登录',
    'Bad Response.': '请求失败。',
    'Email': '邮箱',
    'Password': '密码',
    'Sign in': '登录',
    'Confirm': '确认',
    'Don\'t have an account?': '还没有账户？',
    'Sign up': '注册',
    'or': '或',
    'Forgot your password?': '忘记密码？',
    'Create account': '创建账户',
    'Username': '用户名',
    'Confirm Password': '确认密码',
    'New Password': '新密码',
    'By signing up, you agree to our': '注册即表示您同意我们的',
    'Terms of Service': '服务条款',
    ' and ': '和',
    'Privacy Policy': '隐私政策',
    'Already have an account?': '已经有账户？',
    'Reset password': '重置密码',
    'Enter the code sent to your email': '输入发送到您邮箱的验证码',
    'Send code': '发送验证码',
    'Resend code': '重新发送验证码',
    'Back to login': '返回登录',
    'Enter your email': '请输入您的邮箱',
    'Invalid Password': '密码无效',
    'Passwords do not match.': '两次输入的密码不一致。',
    'We have sent a numeric verification code to your email address at': '我们已向此邮箱发送数字验证码：',
    'COUNTDOWN_SUFFIX': '秒',
    'Unsupported sign-in step:': '不支持的登录步骤：',
    'AUTH_ERROR_GENERIC': '认证失败，请重试。',
    'AUTH_ERROR_INVALID_CREDENTIALS': '邮箱或密码错误。',
    'AUTH_ERROR_USER_NOT_CONFIRMED': '账户尚未完成验证，请使用我们发送的验证码完成验证。',
    'AUTH_ERROR_USERNAME_EXISTS': '该用户名已被占用。',
    'AUTH_ERROR_USER_NOT_FOUND': '未找到与该邮箱地址对应的账户。',
    'AUTH_ERROR_CODE_MISMATCH': '验证码不正确。',
    'AUTH_ERROR_CODE_EXPIRED': '验证码已过期，请重新获取。',
    'AUTH_ERROR_TOO_MANY_REQUESTS': '请求过于频繁，请稍后再试。',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': '失败次数过多，请稍后再试。',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': '验证码发送失败，请稍后再试。',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': '您已登录。',
    'AUTH_ERROR_INVALID_PARAMETER': '输入信息无效，请检查后重试。'
  },
  'zh-Hant': {
    'login': '登入',
    'signup': '註冊',
    'reset-password': '重置密碼',
    'confirm-code': '確認驗證碼',
    'CODE_ON_THE_WAY_TIP': '驗證碼已發送。請輸入我們發送給您的驗證碼以登入。可能需要一分鐘才能收到。',
    'PW_POLICY_TIP': '1. 密碼長度至少8個字符\n' +
      '2. 密碼必須包含小寫字母\n' +
      '3. 密碼必須包含大寫字母\n' +
      '4. 密碼必須包含特殊字符',
    'Sign in to your account': '登入到您的帳戶',
    'You are already logged in as': '您目前已登入為',
    'Sign out': '登出',
    'Bad Response.': '請求失敗。',
    'Email': '電子郵件',
    'Password': '密碼',
    'Sign in': '登入',
    'Confirm': '確認',
    'Don\'t have an account?': '還沒有帳戶？',
    'Sign up': '註冊',
    'or': '或',
    'Forgot your password?': '忘記密碼？',
    'Create account': '建立帳戶',
    'Username': '用戶名',
    'Confirm Password': '確認密碼',
    'New Password': '新密碼',
    'By signing up, you agree to our': '註冊即表示您同意我們的',
    'Terms of Service': '服務條款',
    ' and ': '和',
    'Privacy Policy': '隱私政策',
    'Already have an account?': '已經有帳戶？',
    'Reset password': '重置密碼',
    'Enter the code sent to your email': '輸入發送到您郵箱的驗證碼',
    'Send code': '發送驗證碼',
    'Resend code': '重新發送驗證碼',
    'Back to login': '返回登入',
    'Enter your email': '請輸入您的電子郵件',
    'Invalid Password': '密碼無效',
    'Passwords do not match.': '兩次輸入的密碼不一致。',
    'We have sent a numeric verification code to your email address at': '我們已向此電子郵件地址發送數字驗證碼：',
    'COUNTDOWN_SUFFIX': '秒',
    'Unsupported sign-in step:': '不支援的登入步驟：',
    'AUTH_ERROR_GENERIC': '驗證失敗，請再試一次。',
    'AUTH_ERROR_INVALID_CREDENTIALS': '電子郵件或密碼錯誤。',
    'AUTH_ERROR_USER_NOT_CONFIRMED': '帳戶尚未完成驗證，請使用我們發送的驗證碼完成驗證。',
    'AUTH_ERROR_USERNAME_EXISTS': '此用戶名已被使用。',
    'AUTH_ERROR_USER_NOT_FOUND': '找不到與該電子郵件地址對應的帳戶。',
    'AUTH_ERROR_CODE_MISMATCH': '驗證碼不正確。',
    'AUTH_ERROR_CODE_EXPIRED': '驗證碼已過期，請重新取得。',
    'AUTH_ERROR_TOO_MANY_REQUESTS': '請求過於頻繁，請稍後再試。',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': '失敗次數過多，請稍後再試。',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': '無法發送驗證碼，請稍後再試。',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': '您已登入。',
    'AUTH_ERROR_INVALID_PARAMETER': '輸入資訊無效，請檢查後再試。'
  },
  'ja': {
    'login': 'ログイン',
    'signup': 'サインアップ',
    'reset-password': 'パスワードをリセットする',
    'confirm-code': 'コードを確認する',
    'CODE_ON_THE_WAY_TIP': 'コードが送信されました。ログインするには、送信したコードを入力してください。届くまでに1分ほどかかる場合があります。',
    'PW_POLICY_TIP': '1. パスワードは8文字以上であること。\n' +
      '2. パスワードには小文字を含める必要があります。\n' +
      '3. パスワードには大文字を含める必要があります。\n' +
      '4. パスワードには記号を含める必要があります。',
    'Sign in to your account': 'アカウントにサインイン',
    'You are already logged in as': '現在のログインユーザー',
    'Sign out': 'ログアウト',
    'Bad Response.': 'リクエストに失敗しました。',
    'Email': 'メール',
    'Password': 'パスワード',
    'Sign in': 'サインイン',
    'Confirm': '確認',
    'Don\'t have an account?': 'アカウントをお持ちでないですか？',
    'Sign up': 'サインアップ',
    'or': 'または',
    'Forgot your password?': 'パスワードをお忘れですか？',
    'Create account': 'アカウントを作成',
    'Username': 'ユーザー名',
    'New Password': '新しいパスワード',
    'Confirm Password': 'パスワードを確認する',
    'By signing up, you agree to our': 'サインアップすると、次の内容に同意したものとみなされます',
    'Terms of Service': '利用規約',
    ' and ': 'および',
    'Privacy Policy': 'プライバシーポリシー',
    'Already have an account?': 'すでにアカウントをお持ちですか？',
    'Reset password': 'パスワードをリセットする',
    'Enter the code sent to your email': 'メールに送信されたコードを入力してください',
    'Send code': 'コードを送信',
    'Resend code': 'コードを再送信',
    'Back to login': 'ログインに戻る',
    'Enter your email': 'メールアドレスを入力してください',
    'Invalid Password': '無効なパスワード',
    'Passwords do not match.': 'パスワードが一致しません。',
    'We have sent a numeric verification code to your email address at': '次のメールアドレスに数字の確認コードを送信しました:',
    'COUNTDOWN_SUFFIX': '秒',
    'Unsupported sign-in step:': '未対応のサインイン手順:',
    'AUTH_ERROR_GENERIC': '認証に失敗しました。もう一度お試しください。',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'メールアドレスまたはパスワードが正しくありません。',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'アカウントの確認がまだ完了していません。送信されたコードで確認してください。',
    'AUTH_ERROR_USERNAME_EXISTS': 'このユーザー名は既に使用されています。',
    'AUTH_ERROR_USER_NOT_FOUND': 'そのメールアドレスに対応するアカウントが見つかりません。',
    'AUTH_ERROR_CODE_MISMATCH': '確認コードが正しくありません。',
    'AUTH_ERROR_CODE_EXPIRED': '確認コードの有効期限が切れています。新しいコードをリクエストしてください。',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'リクエストが多すぎます。しばらく待ってからやり直してください。',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': '失敗回数が多すぎます。しばらく待ってからやり直してください。',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': '確認コードを送信できませんでした。しばらくしてからもう一度お試しください。',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'すでにサインインしています。',
    'AUTH_ERROR_INVALID_PARAMETER': '入力内容が正しくありません。確認してからやり直してください。'
  },
  'de': {
    'login': 'Anmelden',
    'signup': 'Registrieren',
    'reset-password': 'Passwort zurücksetzen',
    'confirm-code': 'Code bestätigen',
    'CODE_ON_THE_WAY_TIP': 'Dein Code ist unterwegs. Um dich anzumelden, gib den Code ein, den wir dir gesendet haben. Es kann eine Minute dauern, bis er ankommt.',
    'PW_POLICY_TIP': '1. Mindestens 8 Zeichen.\n' +
      '2. Muss Kleinbuchstaben enthalten.\n' +
      '3. Muss Großbuchstaben enthalten.\n' +
      '4. Muss Sonderzeichen enthalten.',
    'You are already logged in as': 'Du bist bereits angemeldet als',
    'Sign out': 'Abmelden',
    'Bad Response.': 'Fehlerhafte Antwort.',
    'Email': 'E-Mail',
    'Password': 'Passwort',
    'Sign in': 'Anmelden',
    'Confirm': 'Bestätigen',
    'Don\'t have an account?': 'Noch kein Konto?',
    'Sign up': 'Registrieren',
    'or': 'oder',
    'Forgot your password?': 'Passwort vergessen?',
    'Create account': 'Konto erstellen',
    'Username': 'Benutzername',
    'Confirm Password': 'Passwort bestätigen',
    'New Password': 'Neues Passwort',
    'By signing up, you agree to our': 'Mit der Registrierung stimmst du unseren',
    'Terms of Service': 'Nutzungsbedingungen',
    ' and ': ' und ',
    'Privacy Policy': 'Datenschutzrichtlinie',
    'Already have an account?': 'Bereits ein Konto?',
    'Reset password': 'Passwort zurücksetzen',
    'Enter the code sent to your email': 'Gib den an deine E-Mail gesendeten Code ein',
    'Send code': 'Code senden',
    'Resend code': 'Code erneut senden',
    'Back to login': 'Zurück zur Anmeldung',
    'Enter your email': 'E-Mail-Adresse eingeben',
    'Invalid Password': 'Ungültiges Passwort',
    'Passwords do not match.': 'Passwörter stimmen nicht überein.',
    'We have sent a numeric verification code to your email address at': 'Wir haben einen numerischen Bestätigungscode an deine E-Mail-Adresse gesendet:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Nicht unterstützter Anmeldeschritt:',
    'AUTH_ERROR_GENERIC': 'Authentifizierung fehlgeschlagen. Bitte versuche es erneut.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Falsche E-Mail oder falsches Passwort.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Dein Konto ist noch nicht bestätigt. Bitte verifiziere es mit dem Code, den wir gesendet haben.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Dieser Benutzername ist bereits vergeben.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Wir konnten kein Konto für diese E-Mail-Adresse finden.',
    'AUTH_ERROR_CODE_MISMATCH': 'Der Verifizierungscode ist falsch.',
    'AUTH_ERROR_CODE_EXPIRED': 'Der Verifizierungscode ist abgelaufen. Bitte fordere einen neuen an.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Zu viele Anfragen. Bitte warte einen Moment und versuche es erneut.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Zu viele fehlgeschlagene Versuche. Bitte warte einen Moment und versuche es erneut.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Wir konnten den Verifizierungscode nicht senden. Bitte versuche es später erneut.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Du bist bereits angemeldet.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Einige Angaben sind ungültig. Bitte überprüfe deine Eingabe und versuche es erneut.'
  },
  'nl': {
    'login': 'Inloggen',
    'signup': 'Registreren',
    'reset-password': 'Wachtwoord resetten',
    'confirm-code': 'Code bevestigen',
    'CODE_ON_THE_WAY_TIP': 'Je code is onderweg. Om in te loggen, voer de code in die we je hebben gestuurd. Het kan een minuutje duren voordat deze aankomt.',
    'PW_POLICY_TIP': '1. Minimaal 8 tekens.\n' +
      '2. Moet kleine letters bevatten.\n' +
      '3. Moet hoofdletters bevatten.\n' +
      '4. Moet speciale tekens bevatten.',
    'You are already logged in as': 'Je bent al ingelogd als',
    'Sign out': 'Uitloggen',
    'Bad Response.': 'Slechte reactie.',
    'Email': 'E-mail',
    'Password': 'Wachtwoord',
    'Sign in': 'Inloggen',
    'Confirm': 'Bevestigen',
    'Don\'t have an account?': 'Nog geen account?',
    'Sign up': 'Registreren',
    'or': 'of',
    'Forgot your password?': 'Wachtwoord vergeten?',
    'Create account': 'Account aanmaken',
    'Username': 'Gebruikersnaam',
    'Confirm Password': 'Wachtwoord bevestigen',
    'New Password': 'Nieuw wachtwoord',
    'By signing up, you agree to our': 'Door je te registreren, ga je akkoord met onze',
    'Terms of Service': 'Servicevoorwaarden',
    ' and ': ' en ',
    'Privacy Policy': 'Privacybeleid',
    'Already have an account?': 'Al een account?',
    'Reset password': 'Wachtwoord resetten',
    'Enter the code sent to your email': 'Voer de code in die naar je e-mail is gestuurd',
    'Send code': 'Code versturen',
    'Resend code': 'Code opnieuw versturen',
    'Back to login': 'Terug naar inloggen',
    'Enter your email': 'Voer je e-mailadres in',
    'Invalid Password': 'Ongeldig wachtwoord',
    'Passwords do not match.': 'Wachtwoorden komen niet overeen.',
    'We have sent a numeric verification code to your email address at': 'We hebben een numerieke verificatiecode gestuurd naar je e-mailadres:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Niet-ondersteunde inlogstap:',
    'AUTH_ERROR_GENERIC': 'Authenticatie mislukt. Probeer het opnieuw.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Onjuist e-mailadres of wachtwoord.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Je account is nog niet bevestigd. Verifieer het met de code die we hebben gestuurd.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Deze gebruikersnaam is al in gebruik.',
    'AUTH_ERROR_USER_NOT_FOUND': 'We konden geen account vinden voor dat e-mailadres.',
    'AUTH_ERROR_CODE_MISMATCH': 'De verificatiecode is onjuist.',
    'AUTH_ERROR_CODE_EXPIRED': 'De verificatiecode is verlopen. Vraag een nieuwe aan.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Te veel verzoeken. Wacht even en probeer het opnieuw.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Te veel mislukte pogingen. Wacht even en probeer het opnieuw.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'We konden de verificatiecode niet versturen. Probeer het later opnieuw.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Je bent al ingelogd.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Bepaalde informatie is ongeldig. Controleer je invoer en probeer het opnieuw.'
  },
  'fr': {
    'login': 'Connexion',
    'signup': 'Inscription',
    'reset-password': 'Réinitialiser le mot de passe',
    'confirm-code': 'Confirmer le code',
    'CODE_ON_THE_WAY_TIP': 'Votre code est en route. Pour vous connecter, saisissez le code que nous vous avons envoyé. Il peut mettre une minute à arriver.',
    'PW_POLICY_TIP': '1. Au moins 8 caractères.\n' +
      '2. Doit contenir des lettres minuscules.\n' +
      '3. Doit contenir des lettres majuscules.\n' +
      '4. Doit contenir des caractères spéciaux.',
    'You are already logged in as': 'Vous êtes déjà connecté en tant que',
    'Sign out': 'Se déconnecter',
    'Bad Response.': 'Mauvaise réponse.',
    'Email': 'E-mail',
    'Password': 'Mot de passe',
    'Sign in': 'Se connecter',
    'Confirm': 'Confirmer',
    'Don\'t have an account?': 'Pas encore de compte ?',
    'Sign up': 'S\'inscrire',
    'or': 'ou',
    'Forgot your password?': 'Mot de passe oublié ?',
    'Create account': 'Créer un compte',
    'Username': 'Nom d\'utilisateur',
    'Confirm Password': 'Confirmer le mot de passe',
    'New Password': 'Nouveau mot de passe',
    'By signing up, you agree to our': 'En vous inscrivant, vous acceptez nos',
    'Terms of Service': 'Conditions d\'utilisation',
    ' and ': ' et ',
    'Privacy Policy': 'Politique de confidentialité',
    'Already have an account?': 'Vous avez déjà un compte ?',
    'Reset password': 'Réinitialiser le mot de passe',
    'Enter the code sent to your email': 'Entrez le code envoyé à votre e-mail',
    'Send code': 'Envoyer le code',
    'Resend code': 'Renvoyer le code',
    'Back to login': 'Retour à la connexion',
    'Enter your email': 'Entrez votre e-mail',
    'Invalid Password': 'Mot de passe invalide',
    'Passwords do not match.': 'Les mots de passe ne correspondent pas.',
    'We have sent a numeric verification code to your email address at': 'Nous avons envoyé un code de vérification numérique à votre adresse e-mail :',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Étape de connexion non prise en charge :',
    'AUTH_ERROR_GENERIC': 'Échec de l\'authentification. Veuillez réessayer.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'E-mail ou mot de passe incorrect.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Votre compte n\'est pas encore confirmé. Veuillez le vérifier avec le code que nous avons envoyé.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Ce nom d\'utilisateur est déjà pris.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Nous n\'avons pas pu trouver de compte pour cette adresse e-mail.',
    'AUTH_ERROR_CODE_MISMATCH': 'Le code de vérification est incorrect.',
    'AUTH_ERROR_CODE_EXPIRED': 'Le code de vérification a expiré. Veuillez en demander un nouveau.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Trop de requêtes. Veuillez patienter un moment et réessayer.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Trop de tentatives échouées. Veuillez patienter un moment et réessayer.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Nous n\'avons pas pu envoyer le code de vérification. Veuillez réessayer plus tard.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Vous êtes déjà connecté.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Certaines informations sont invalides. Veuillez vérifier votre saisie et réessayer.'
  },
  'af': {
    'login': 'Aanmeld',
    'signup': 'Registreer',
    'reset-password': 'Stel wagwoord terug',
    'confirm-code': 'Bevestig kode',
    'CODE_ON_THE_WAY_TIP': 'Jou kode is op pad. Om aan te meld, voer die kode in wat ons vir jou gestuur het. Dit kan \'n minuut neem om te arriveer.',
    'PW_POLICY_TIP': '1. Ten minste 8 karakters.\n' +
      '2. Moet kleinletters bevat.\n' +
      '3. Moet hoofletter bevat.\n' +
      '4. Moet simboolkarakters bevat.',
    'You are already logged in as': 'Jy is reeds aangemeld as',
    'Sign out': 'Teken uit',
    'Bad Response.': 'Slegte respons.',
    'Email': 'E-pos',
    'Password': 'Wagwoord',
    'Sign in': 'Teken in',
    'Confirm': 'Bevestig',
    'Don\'t have an account?': 'Het jy nie \'n rekening nie?',
    'Sign up': 'Registreer',
    'or': 'of',
    'Forgot your password?': 'Wagwoord vergeet?',
    'Create account': 'Skep rekening',
    'Username': 'Gebruikersnaam',
    'Confirm Password': 'Bevestig wagwoord',
    'New Password': 'Nuwe wagwoord',
    'By signing up, you agree to our': 'Deur te registreer, stem jy in tot ons',
    'Terms of Service': 'Diensvoorwaardes',
    ' and ': ' en ',
    'Privacy Policy': 'Privaatheidsbeleid',
    'Already have an account?': 'Het jy reeds \'n rekening?',
    'Reset password': 'Stel wagwoord terug',
    'Enter the code sent to your email': 'Voer die kode in wat na jou e-pos gestuur is',
    'Send code': 'Stuur kode',
    'Resend code': 'Stuur kode weer',
    'Back to login': 'Terug na aanmelding',
    'Enter your email': 'Voer jou e-posadres in',
    'Invalid Password': 'Ongeldige wagwoord',
    'Passwords do not match.': 'Wagwoorde stem nie ooreen nie.',
    'We have sent a numeric verification code to your email address at': 'Ons het \'n numeriese verifikasiekode na jou e-posadres gestuur:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Nie-ondersteunde aanmeldstap:',
    'AUTH_ERROR_GENERIC': 'Verifikasie het misluk. Probeer asseblief weer.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Verkeerde e-pos of wagwoord.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Jou rekening is nog nie bevestig nie. Verifieer dit met die kode wat ons gestuur het.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Hierdie gebruikersnaam is reeds geneem.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Ons kon nie \'n rekening vind vir daardie e-posadres nie.',
    'AUTH_ERROR_CODE_MISMATCH': 'Die verifikasiekode is verkeerd.',
    'AUTH_ERROR_CODE_EXPIRED': 'Die verifikasiekode het verstryk. Versoek asseblief \'n nuwe een.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Te veel versoeke. Wag asseblief \'n oomblik en probeer weer.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Te veel mislukte pogings. Wag asseblief \'n oomblik en probeer weer.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Ons kon nie die verifikasiekode stuur nie. Probeer asseblief later weer.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Jy is reeds aangemeld.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Sommige inligting is ongeldig. Kontroleer jou invoer en probeer weer.'
  },
  'ca': {
    'login': 'Inicia sessió',
    'signup': 'Registra\'t',
    'reset-password': 'Restableix la contrasenya',
    'confirm-code': 'Confirma el codi',
    'CODE_ON_THE_WAY_TIP': 'El teu codi està en camí. Per iniciar sessió, introdueix el codi que t\'hem enviat. Pot trigar un minut a arribar.',
    'PW_POLICY_TIP': '1. Almenys 8 caràcters.\n' +
      '2. Ha de contenir lletres minúscules.\n' +
      '3. Ha de contenir lletres majúscules.\n' +
      '4. Ha de contenir caràcters especials.',
    'You are already logged in as': 'Ja has iniciat sessió com a',
    'Sign out': 'Tanca la sessió',
    'Bad Response.': 'Resposta incorrecta.',
    'Email': 'Correu electrònic',
    'Password': 'Contrasenya',
    'Sign in': 'Inicia sessió',
    'Confirm': 'Confirma',
    'Don\'t have an account?': 'No tens compte?',
    'Sign up': 'Registra\'t',
    'or': 'o',
    'Forgot your password?': 'Has oblidat la contrasenya?',
    'Create account': 'Crea un compte',
    'Username': 'Nom d\'usuari',
    'Confirm Password': 'Confirma la contrasenya',
    'New Password': 'Nova contrasenya',
    'By signing up, you agree to our': 'En registrar-te, acceptes els nostres',
    'Terms of Service': 'Termes de servei',
    ' and ': ' i ',
    'Privacy Policy': 'Política de privadesa',
    'Already have an account?': 'Ja tens compte?',
    'Reset password': 'Restableix la contrasenya',
    'Enter the code sent to your email': 'Introdueix el codi enviat al teu correu electrònic',
    'Send code': 'Envia el codi',
    'Resend code': 'Torna a enviar el codi',
    'Back to login': 'Torna a l\'inici de sessió',
    'Enter your email': 'Introdueix el teu correu electrònic',
    'Invalid Password': 'Contrasenya no vàlida',
    'Passwords do not match.': 'Les contrasenyes no coincideixen.',
    'We have sent a numeric verification code to your email address at': 'Hem enviat un codi de verificació numèric a la teva adreça de correu electrònic:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Pas d\'inici de sessió no admès:',
    'AUTH_ERROR_GENERIC': 'L\'autenticació ha fallat. Torna-ho a intentar.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Correu electrònic o contrasenya incorrectes.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'El teu compte encara no s\'ha confirmat. Verifica\'l amb el codi que t\'hem enviat.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Aquest nom d\'usuari ja està en ús.',
    'AUTH_ERROR_USER_NOT_FOUND': 'No hem pogut trobar un compte per a aquesta adreça de correu electrònic.',
    'AUTH_ERROR_CODE_MISMATCH': 'El codi de verificació és incorrecte.',
    'AUTH_ERROR_CODE_EXPIRED': 'El codi de verificació ha caducat. Sol·licita\'n un de nou.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Massa sol·licituds. Espera un moment i torna-ho a intentar.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Massa intents fallits. Espera un moment i torna-ho a intentar.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'No hem pogut enviar el codi de verificació. Torna-ho a intentar més tard.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Ja has iniciat sessió.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Alguna informació no és vàlida. Comprova la teva entrada i torna-ho a intentar.'
  },
  'es': {
    'login': 'Iniciar sesión',
    'signup': 'Registrarse',
    'reset-password': 'Restablecer contraseña',
    'confirm-code': 'Confirmar código',
    'CODE_ON_THE_WAY_TIP': 'Tu código está en camino. Para iniciar sesión, ingresa el código que te enviamos. Puede tardar un minuto en llegar.',
    'PW_POLICY_TIP': '1. Al menos 8 caracteres.\n' +
      '2. Debe contener letras minúsculas.\n' +
      '3. Debe contener letras mayúsculas.\n' +
      '4. Debe contener caracteres especiales.',
    'You are already logged in as': 'Ya has iniciado sesión como',
    'Sign out': 'Cerrar sesión',
    'Bad Response.': 'Respuesta incorrecta.',
    'Email': 'Correo electrónico',
    'Password': 'Contraseña',
    'Sign in': 'Iniciar sesión',
    'Confirm': 'Confirmar',
    'Don\'t have an account?': '¿No tienes cuenta?',
    'Sign up': 'Registrarse',
    'or': 'o',
    'Forgot your password?': '¿Olvidaste tu contraseña?',
    'Create account': 'Crear cuenta',
    'Username': 'Nombre de usuario',
    'Confirm Password': 'Confirmar contraseña',
    'New Password': 'Nueva contraseña',
    'By signing up, you agree to our': 'Al registrarte, aceptas nuestros',
    'Terms of Service': 'Términos de servicio',
    ' and ': ' y ',
    'Privacy Policy': 'Política de privacidad',
    'Already have an account?': '¿Ya tienes cuenta?',
    'Reset password': 'Restablecer contraseña',
    'Enter the code sent to your email': 'Ingresa el código enviado a tu correo electrónico',
    'Send code': 'Enviar código',
    'Resend code': 'Reenviar código',
    'Back to login': 'Volver al inicio de sesión',
    'Enter your email': 'Ingresa tu correo electrónico',
    'Invalid Password': 'Contraseña no válida',
    'Passwords do not match.': 'Las contraseñas no coinciden.',
    'We have sent a numeric verification code to your email address at': 'Hemos enviado un código de verificación numérico a tu dirección de correo electrónico:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Paso de inicio de sesión no compatible:',
    'AUTH_ERROR_GENERIC': 'La autenticación falló. Por favor, inténtalo de nuevo.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Correo electrónico o contraseña incorrectos.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Tu cuenta no está confirmada aún. Verifícala con el código que te enviamos.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Este nombre de usuario ya está en uso.',
    'AUTH_ERROR_USER_NOT_FOUND': 'No pudimos encontrar una cuenta para esa dirección de correo electrónico.',
    'AUTH_ERROR_CODE_MISMATCH': 'El código de verificación es incorrecto.',
    'AUTH_ERROR_CODE_EXPIRED': 'El código de verificación ha expirado. Por favor, solicita uno nuevo.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Demasiadas solicitudes. Por favor, espera un momento e inténtalo de nuevo.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Demasiados intentos fallidos. Por favor, espera un momento e inténtalo de nuevo.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'No pudimos enviar el código de verificación. Por favor, inténtalo más tarde.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Ya has iniciado sesión.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Alguna información no es válida. Por favor, revisa tu entrada e inténtalo de nuevo.'
  },
  'nb-NO': {
    'login': 'Logg inn',
    'signup': 'Registrer deg',
    'reset-password': 'Tilbakestill passord',
    'confirm-code': 'Bekreft kode',
    'CODE_ON_THE_WAY_TIP': 'Koden din er på vei. For å logge inn, skriv inn koden vi sendte deg. Det kan ta ett minutt å komme frem.',
    'PW_POLICY_TIP': '1. Minst 8 tegn.\n' +
      '2. Må inneholde små bokstaver.\n' +
      '3. Må inneholde store bokstaver.\n' +
      '4. Må inneholde symboler.',
    'You are already logged in as': 'Du er allerede logget inn som',
    'Sign out': 'Logg ut',
    'Bad Response.': 'Dårlig svar.',
    'Email': 'E-post',
    'Password': 'Passord',
    'Sign in': 'Logg inn',
    'Confirm': 'Bekreft',
    'Don\'t have an account?': 'Har du ikke en konto?',
    'Sign up': 'Registrer deg',
    'or': 'eller',
    'Forgot your password?': 'Glemt passordet?',
    'Create account': 'Opprett konto',
    'Username': 'Brukernavn',
    'Confirm Password': 'Bekreft passord',
    'New Password': 'Nytt passord',
    'By signing up, you agree to our': 'Ved å registrere deg godtar du våre',
    'Terms of Service': 'Vilkår for bruk',
    ' and ': ' og ',
    'Privacy Policy': 'Personvernregler',
    'Already have an account?': 'Har du allerede en konto?',
    'Reset password': 'Tilbakestill passord',
    'Enter the code sent to your email': 'Skriv inn koden som ble sendt til e-posten din',
    'Send code': 'Send kode',
    'Resend code': 'Send kode på nytt',
    'Back to login': 'Tilbake til innlogging',
    'Enter your email': 'Skriv inn e-postadressen din',
    'Invalid Password': 'Ugyldig passord',
    'Passwords do not match.': 'Passordene stemmer ikke overens.',
    'We have sent a numeric verification code to your email address at': 'Vi har sendt en numerisk bekreftelseskode til e-postadressen din:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Ikke-støttet innloggingstrinn:',
    'AUTH_ERROR_GENERIC': 'Autentisering mislyktes. Prøv igjen.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Feil e-post eller passord.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Kontoen din er ikke bekreftet ennå. Bekreft den med koden vi sendte.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Dette brukernavnet er allerede tatt.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Vi fant ingen konto for den e-postadressen.',
    'AUTH_ERROR_CODE_MISMATCH': 'Bekreftelseskoden er feil.',
    'AUTH_ERROR_CODE_EXPIRED': 'Bekreftelseskoden er utløpt. Be om en ny.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'For mange forespørsler. Vent litt og prøv igjen.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'For mange mislykkede forsøk. Vent litt og prøv igjen.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Vi kunne ikke sende bekreftelseskoden. Prøv igjen senere.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Du er allerede logget inn.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Noe informasjon er ugyldig. Sjekk inndataene dine og prøv igjen.'
  },
  'pt-BR': {
    'login': 'Entrar',
    'signup': 'Cadastrar',
    'reset-password': 'Redefinir senha',
    'confirm-code': 'Confirmar código',
    'CODE_ON_THE_WAY_TIP': 'Seu código está a caminho. Para fazer login, insira o código que enviamos para você. Pode levar um minuto para chegar.',
    'PW_POLICY_TIP': '1. Pelo menos 8 caracteres.\n' +
      '2. Deve conter letras minúsculas.\n' +
      '3. Deve conter letras maiúsculas.\n' +
      '4. Deve conter caracteres especiais.',
    'You are already logged in as': 'Você já está conectado como',
    'Sign out': 'Sair',
    'Bad Response.': 'Resposta inválida.',
    'Email': 'E-mail',
    'Password': 'Senha',
    'Sign in': 'Entrar',
    'Confirm': 'Confirmar',
    'Don\'t have an account?': 'Não tem uma conta?',
    'Sign up': 'Cadastrar',
    'or': 'ou',
    'Forgot your password?': 'Esqueceu sua senha?',
    'Create account': 'Criar conta',
    'Username': 'Nome de usuário',
    'Confirm Password': 'Confirmar senha',
    'New Password': 'Nova senha',
    'By signing up, you agree to our': 'Ao se cadastrar, você concorda com nossos',
    'Terms of Service': 'Termos de serviço',
    ' and ': ' e ',
    'Privacy Policy': 'Política de privacidade',
    'Already have an account?': 'Já tem uma conta?',
    'Reset password': 'Redefinir senha',
    'Enter the code sent to your email': 'Insira o código enviado para seu e-mail',
    'Send code': 'Enviar código',
    'Resend code': 'Reenviar código',
    'Back to login': 'Voltar ao login',
    'Enter your email': 'Insira seu e-mail',
    'Invalid Password': 'Senha inválida',
    'Passwords do not match.': 'As senhas não correspondem.',
    'We have sent a numeric verification code to your email address at': 'Enviamos um código de verificação numérico para seu endereço de e-mail:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Etapa de login não suportada:',
    'AUTH_ERROR_GENERIC': 'Falha na autenticação. Por favor, tente novamente.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'E-mail ou senha incorretos.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Sua conta ainda não foi confirmada. Por favor, verifique-a com o código que enviamos.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Este nome de usuário já está em uso.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Não encontramos uma conta para esse endereço de e-mail.',
    'AUTH_ERROR_CODE_MISMATCH': 'O código de verificação está incorreto.',
    'AUTH_ERROR_CODE_EXPIRED': 'O código de verificação expirou. Por favor, solicite um novo.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Muitas solicitações. Por favor, aguarde um momento e tente novamente.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Muitas tentativas malsucedidas. Por favor, aguarde um momento e tente novamente.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Não conseguimos enviar o código de verificação. Por favor, tente novamente mais tarde.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Você já está conectado.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Algumas informações são inválidas. Por favor, verifique sua entrada e tente novamente.'
  },
  'pt-PT': {
    'login': 'Iniciar sessão',
    'signup': 'Registar',
    'reset-password': 'Repor palavra-passe',
    'confirm-code': 'Confirmar código',
    'CODE_ON_THE_WAY_TIP': 'O seu código está a caminho. Para iniciar sessão, introduza o código que lhe enviámos. Pode demorar um minuto a chegar.',
    'PW_POLICY_TIP': '1. Pelo menos 8 caracteres.\n' +
      '2. Deve conter letras minúsculas.\n' +
      '3. Deve conter letras maiúsculas.\n' +
      '4. Deve conter caracteres especiais.',
    'You are already logged in as': 'Já iniciou sessão como',
    'Sign out': 'Terminar sessão',
    'Bad Response.': 'Resposta inválida.',
    'Email': 'E-mail',
    'Password': 'Palavra-passe',
    'Sign in': 'Iniciar sessão',
    'Confirm': 'Confirmar',
    'Don\'t have an account?': 'Não tem conta?',
    'Sign up': 'Registar',
    'or': 'ou',
    'Forgot your password?': 'Esqueceu a palavra-passe?',
    'Create account': 'Criar conta',
    'Username': 'Nome de utilizador',
    'Confirm Password': 'Confirmar palavra-passe',
    'New Password': 'Nova palavra-passe',
    'By signing up, you agree to our': 'Ao registar-se, concorda com os nossos',
    'Terms of Service': 'Termos de serviço',
    ' and ': ' e ',
    'Privacy Policy': 'Política de privacidade',
    'Already have an account?': 'Já tem conta?',
    'Reset password': 'Repor palavra-passe',
    'Enter the code sent to your email': 'Introduza o código enviado para o seu e-mail',
    'Send code': 'Enviar código',
    'Resend code': 'Reenviar código',
    'Back to login': 'Voltar ao início de sessão',
    'Enter your email': 'Introduza o seu e-mail',
    'Invalid Password': 'Palavra-passe inválida',
    'Passwords do not match.': 'As palavras-passe não coincidem.',
    'We have sent a numeric verification code to your email address at': 'Enviámos um código de verificação numérico para o seu endereço de e-mail:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Passo de início de sessão não suportado:',
    'AUTH_ERROR_GENERIC': 'Falha na autenticação. Por favor, tente novamente.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'E-mail ou palavra-passe incorretos.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'A sua conta ainda não foi confirmada. Por favor, verifique-a com o código que enviámos.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Este nome de utilizador já está em uso.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Não encontrámos nenhuma conta para esse endereço de e-mail.',
    'AUTH_ERROR_CODE_MISMATCH': 'O código de verificação está incorreto.',
    'AUTH_ERROR_CODE_EXPIRED': 'O código de verificação expirou. Por favor, solicite um novo.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Demasiadas solicitações. Por favor, aguarde um momento e tente novamente.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Demasiadas tentativas falhadas. Por favor, aguarde um momento e tente novamente.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Não conseguimos enviar o código de verificação. Por favor, tente novamente mais tarde.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Já tem sessão iniciada.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Algumas informações são inválidas. Por favor, verifique a sua entrada e tente novamente.'
  },
  'ru': {
    'login': 'Войти',
    'signup': 'Зарегистрироваться',
    'reset-password': 'Сбросить пароль',
    'confirm-code': 'Подтвердить код',
    'CODE_ON_THE_WAY_TIP': 'Ваш код в пути. Чтобы войти, введите код, который мы вам отправили. Это может занять минуту.',
    'PW_POLICY_TIP': '1. Не менее 8 символов.\n' +
      '2. Должен содержать строчные буквы.\n' +
      '3. Должен содержать заглавные буквы.\n' +
      '4. Должен содержать специальные символы.',
    'You are already logged in as': 'Вы уже вошли как',
    'Sign out': 'Выйти',
    'Bad Response.': 'Некорректный ответ.',
    'Email': 'Эл. почта',
    'Password': 'Пароль',
    'Sign in': 'Войти',
    'Confirm': 'Подтвердить',
    'Don\'t have an account?': 'Нет аккаунта?',
    'Sign up': 'Зарегистрироваться',
    'or': 'или',
    'Forgot your password?': 'Забыли пароль?',
    'Create account': 'Создать аккаунт',
    'Username': 'Имя пользователя',
    'Confirm Password': 'Подтвердить пароль',
    'New Password': 'Новый пароль',
    'By signing up, you agree to our': 'Регистрируясь, вы соглашаетесь с нашими',
    'Terms of Service': 'Условиями обслуживания',
    ' and ': ' и ',
    'Privacy Policy': 'Политикой конфиденциальности',
    'Already have an account?': 'Уже есть аккаунт?',
    'Reset password': 'Сбросить пароль',
    'Enter the code sent to your email': 'Введите код, отправленный на вашу почту',
    'Send code': 'Отправить код',
    'Resend code': 'Отправить код повторно',
    'Back to login': 'Вернуться к входу',
    'Enter your email': 'Введите адрес эл. почты',
    'Invalid Password': 'Неверный пароль',
    'Passwords do not match.': 'Пароли не совпадают.',
    'We have sent a numeric verification code to your email address at': 'Мы отправили числовой код подтверждения на ваш адрес эл. почты:',
    'COUNTDOWN_SUFFIX': 'с',
    'Unsupported sign-in step:': 'Неподдерживаемый шаг входа:',
    'AUTH_ERROR_GENERIC': 'Ошибка аутентификации. Пожалуйста, попробуйте снова.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Неверный адрес эл. почты или пароль.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Ваш аккаунт ещё не подтверждён. Пожалуйста, подтвердите его с помощью кода, который мы отправили.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Это имя пользователя уже занято.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Нам не удалось найти аккаунт с таким адресом эл. почты.',
    'AUTH_ERROR_CODE_MISMATCH': 'Код подтверждения неверен.',
    'AUTH_ERROR_CODE_EXPIRED': 'Срок действия кода подтверждения истёк. Пожалуйста, запросите новый.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Слишком много запросов. Пожалуйста, подождите немного и попробуйте снова.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Слишком много неудачных попыток. Пожалуйста, подождите немного и попробуйте снова.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Нам не удалось отправить код подтверждения. Пожалуйста, попробуйте позже.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Вы уже вошли в систему.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Некоторые данные неверны. Пожалуйста, проверьте введённые данные и попробуйте снова.'
  },
  'it': {
    'login': 'Accedi',
    'signup': 'Registrati',
    'reset-password': 'Reimposta la password',
    'confirm-code': 'Conferma il codice',
    'CODE_ON_THE_WAY_TIP': 'Il tuo codice è in arrivo. Per accedere, inserisci il codice che ti abbiamo inviato. Potrebbe impiegare un minuto ad arrivare.',
    'PW_POLICY_TIP': '1. Almeno 8 caratteri.\n' +
      '2. Deve contenere lettere minuscole.\n' +
      '3. Deve contenere lettere maiuscole.\n' +
      '4. Deve contenere caratteri speciali.',
    'You are already logged in as': 'Sei già connesso come',
    'Sign out': 'Disconnetti',
    'Bad Response.': 'Risposta errata.',
    'Email': 'E-mail',
    'Password': 'Password',
    'Sign in': 'Accedi',
    'Confirm': 'Conferma',
    'Don\'t have an account?': 'Non hai un account?',
    'Sign up': 'Registrati',
    'or': 'o',
    'Forgot your password?': 'Hai dimenticato la password?',
    'Create account': 'Crea account',
    'Username': 'Nome utente',
    'Confirm Password': 'Conferma password',
    'New Password': 'Nuova password',
    'By signing up, you agree to our': 'Registrandoti, accetti i nostri',
    'Terms of Service': 'Termini di servizio',
    ' and ': ' e ',
    'Privacy Policy': 'Informativa sulla privacy',
    'Already have an account?': 'Hai già un account?',
    'Reset password': 'Reimposta la password',
    'Enter the code sent to your email': 'Inserisci il codice inviato alla tua e-mail',
    'Send code': 'Invia codice',
    'Resend code': 'Invia di nuovo il codice',
    'Back to login': 'Torna al login',
    'Enter your email': 'Inserisci la tua e-mail',
    'Invalid Password': 'Password non valida',
    'Passwords do not match.': 'Le password non corrispondono.',
    'We have sent a numeric verification code to your email address at': 'Abbiamo inviato un codice di verifica numerico al tuo indirizzo e-mail:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Fase di accesso non supportata:',
    'AUTH_ERROR_GENERIC': 'Autenticazione non riuscita. Riprova.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'E-mail o password errati.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Il tuo account non è ancora confermato. Verificalo con il codice che abbiamo inviato.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Questo nome utente è già in uso.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Non abbiamo trovato un account per quell\'indirizzo e-mail.',
    'AUTH_ERROR_CODE_MISMATCH': 'Il codice di verifica non è corretto.',
    'AUTH_ERROR_CODE_EXPIRED': 'Il codice di verifica è scaduto. Richiedine uno nuovo.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Troppe richieste. Attendi un momento e riprova.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Troppi tentativi falliti. Attendi un momento e riprova.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Non siamo riusciti a inviare il codice di verifica. Riprova più tardi.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Hai già effettuato l\'accesso.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Alcune informazioni non sono valide. Controlla l\'inserimento e riprova.'
  },
  'tr': {
    'login': 'Giriş yap',
    'signup': 'Kayıt ol',
    'reset-password': 'Şifreyi sıfırla',
    'confirm-code': 'Kodu onayla',
    'CODE_ON_THE_WAY_TIP': 'Kodunuz yolda. Giriş yapmak için size gönderdiğimiz kodu girin. Gelmesi bir dakika sürebilir.',
    'PW_POLICY_TIP': '1. En az 8 karakter.\n' +
      '2. Küçük harf içermelidir.\n' +
      '3. Büyük harf içermelidir.\n' +
      '4. Sembol karakterleri içermelidir.',
    'You are already logged in as': 'Zaten şu kullanıcı olarak giriş yapıldı:',
    'Sign out': 'Çıkış yap',
    'Bad Response.': 'Hatalı yanıt.',
    'Email': 'E-posta',
    'Password': 'Şifre',
    'Sign in': 'Giriş yap',
    'Confirm': 'Onayla',
    'Don\'t have an account?': 'Hesabınız yok mu?',
    'Sign up': 'Kayıt ol',
    'or': 'veya',
    'Forgot your password?': 'Şifrenizi mi unuttunuz?',
    'Create account': 'Hesap oluştur',
    'Username': 'Kullanıcı adı',
    'Confirm Password': 'Şifreyi onayla',
    'New Password': 'Yeni şifre',
    'By signing up, you agree to our': 'Kayıt olarak',
    'Terms of Service': 'Kullanım Koşullarımızı',
    ' and ': ' ve ',
    'Privacy Policy': 'Gizlilik Politikamızı',
    'Already have an account?': 'Zaten bir hesabınız var mı?',
    'Reset password': 'Şifreyi sıfırla',
    'Enter the code sent to your email': 'E-postanıza gönderilen kodu girin',
    'Send code': 'Kodu gönder',
    'Resend code': 'Kodu yeniden gönder',
    'Back to login': 'Girişe geri dön',
    'Enter your email': 'E-posta adresinizi girin',
    'Invalid Password': 'Geçersiz şifre',
    'Passwords do not match.': 'Şifreler eşleşmiyor.',
    'We have sent a numeric verification code to your email address at': 'E-posta adresinize sayısal bir doğrulama kodu gönderdik:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Desteklenmeyen giriş adımı:',
    'AUTH_ERROR_GENERIC': 'Kimlik doğrulama başarısız oldu. Lütfen tekrar deneyin.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Yanlış e-posta veya şifre.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Hesabınız henüz onaylanmadı. Lütfen gönderdiğimiz kodla doğrulayın.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Bu kullanıcı adı zaten alınmış.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Bu e-posta adresi için bir hesap bulamadık.',
    'AUTH_ERROR_CODE_MISMATCH': 'Doğrulama kodu yanlış.',
    'AUTH_ERROR_CODE_EXPIRED': 'Doğrulama kodunun süresi doldu. Lütfen yeni bir tane isteyin.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Çok fazla istek. Lütfen bir süre bekleyin ve tekrar deneyin.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Çok fazla başarısız deneme. Lütfen bir süre bekleyin ve tekrar deneyin.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Doğrulama kodunu gönderemedik. Lütfen daha sonra tekrar deneyin.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Zaten giriş yapmış durumdasınız.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Bazı bilgiler geçersiz. Lütfen girdinizi kontrol edin ve tekrar deneyin.'
  },
  'ko': {
    'login': '로그인',
    'signup': '회원가입',
    'reset-password': '비밀번호 재설정',
    'confirm-code': '코드 확인',
    'CODE_ON_THE_WAY_TIP': '코드가 전송 중입니다. 로그인하려면 보내드린 코드를 입력하세요. 도착하는 데 약 1분이 걸릴 수 있습니다.',
    'PW_POLICY_TIP': '1. 최소 8자 이상.\n' +
      '2. 소문자를 포함해야 합니다.\n' +
      '3. 대문자를 포함해야 합니다.\n' +
      '4. 특수 문자를 포함해야 합니다.',
    'You are already logged in as': '현재 로그인된 계정:',
    'Sign out': '로그아웃',
    'Bad Response.': '잘못된 응답입니다.',
    'Email': '이메일',
    'Password': '비밀번호',
    'Sign in': '로그인',
    'Confirm': '확인',
    'Don\'t have an account?': '계정이 없으신가요?',
    'Sign up': '회원가입',
    'or': '또는',
    'Forgot your password?': '비밀번호를 잊으셨나요?',
    'Create account': '계정 만들기',
    'Username': '사용자 이름',
    'Confirm Password': '비밀번호 확인',
    'New Password': '새 비밀번호',
    'By signing up, you agree to our': '회원가입 시',
    'Terms of Service': '이용약관',
    ' and ': ' 및 ',
    'Privacy Policy': '개인정보 처리방침',
    'Already have an account?': '이미 계정이 있으신가요?',
    'Reset password': '비밀번호 재설정',
    'Enter the code sent to your email': '이메일로 전송된 코드를 입력하세요',
    'Send code': '코드 전송',
    'Resend code': '코드 재전송',
    'Back to login': '로그인으로 돌아가기',
    'Enter your email': '이메일 주소를 입력하세요',
    'Invalid Password': '유효하지 않은 비밀번호',
    'Passwords do not match.': '비밀번호가 일치하지 않습니다.',
    'We have sent a numeric verification code to your email address at': '다음 이메일 주소로 숫자 인증 코드를 전송했습니다:',
    'COUNTDOWN_SUFFIX': '초',
    'Unsupported sign-in step:': '지원되지 않는 로그인 단계:',
    'AUTH_ERROR_GENERIC': '인증에 실패했습니다. 다시 시도해 주세요.',
    'AUTH_ERROR_INVALID_CREDENTIALS': '이메일 또는 비밀번호가 올바르지 않습니다.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': '계정이 아직 확인되지 않았습니다. 전송된 코드로 확인해 주세요.',
    'AUTH_ERROR_USERNAME_EXISTS': '이미 사용 중인 사용자 이름입니다.',
    'AUTH_ERROR_USER_NOT_FOUND': '해당 이메일 주소에 대한 계정을 찾을 수 없습니다.',
    'AUTH_ERROR_CODE_MISMATCH': '인증 코드가 올바르지 않습니다.',
    'AUTH_ERROR_CODE_EXPIRED': '인증 코드가 만료되었습니다. 새로운 코드를 요청해 주세요.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': '요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': '실패한 시도가 너무 많습니다. 잠시 후 다시 시도해 주세요.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': '인증 코드를 전송하지 못했습니다. 나중에 다시 시도해 주세요.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': '이미 로그인되어 있습니다.',
    'AUTH_ERROR_INVALID_PARAMETER': '일부 정보가 올바르지 않습니다. 입력 내용을 확인하고 다시 시도해 주세요.'
  },
  'pl': {
    'login': 'Zaloguj się',
    'signup': 'Zarejestruj się',
    'reset-password': 'Zresetuj hasło',
    'confirm-code': 'Potwierdź kod',
    'CODE_ON_THE_WAY_TIP': 'Twój kod jest w drodze. Aby się zalogować, wpisz kod, który Ci wysłaliśmy. Może to zająć minutę.',
    'PW_POLICY_TIP': '1. Co najmniej 8 znaków.\n' +
      '2. Musi zawierać małe litery.\n' +
      '3. Musi zawierać duże litery.\n' +
      '4. Musi zawierać znaki specjalne.',
    'You are already logged in as': 'Jesteś już zalogowany jako',
    'Sign out': 'Wyloguj się',
    'Bad Response.': 'Nieprawidłowa odpowiedź.',
    'Email': 'E-mail',
    'Password': 'Hasło',
    'Sign in': 'Zaloguj się',
    'Confirm': 'Potwierdź',
    'Don\'t have an account?': 'Nie masz konta?',
    'Sign up': 'Zarejestruj się',
    'or': 'lub',
    'Forgot your password?': 'Nie pamiętasz hasła?',
    'Create account': 'Utwórz konto',
    'Username': 'Nazwa użytkownika',
    'Confirm Password': 'Potwierdź hasło',
    'New Password': 'Nowe hasło',
    'By signing up, you agree to our': 'Rejestrując się, zgadzasz się na nasze',
    'Terms of Service': 'Warunki korzystania',
    ' and ': ' i ',
    'Privacy Policy': 'Politykę prywatności',
    'Already have an account?': 'Masz już konto?',
    'Reset password': 'Zresetuj hasło',
    'Enter the code sent to your email': 'Wpisz kod wysłany na Twój adres e-mail',
    'Send code': 'Wyślij kod',
    'Resend code': 'Wyślij kod ponownie',
    'Back to login': 'Wróć do logowania',
    'Enter your email': 'Wpisz swój adres e-mail',
    'Invalid Password': 'Nieprawidłowe hasło',
    'Passwords do not match.': 'Hasła nie są identyczne.',
    'We have sent a numeric verification code to your email address at': 'Wysłaliśmy numeryczny kod weryfikacyjny na Twój adres e-mail:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Nieobsługiwany krok logowania:',
    'AUTH_ERROR_GENERIC': 'Uwierzytelnianie nie powiodło się. Spróbuj ponownie.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Nieprawidłowy adres e-mail lub hasło.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Twoje konto nie zostało jeszcze potwierdzone. Zweryfikuj je za pomocą kodu, który wysłaliśmy.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Ta nazwa użytkownika jest już zajęta.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Nie znaleźliśmy konta dla tego adresu e-mail.',
    'AUTH_ERROR_CODE_MISMATCH': 'Kod weryfikacyjny jest nieprawidłowy.',
    'AUTH_ERROR_CODE_EXPIRED': 'Kod weryfikacyjny wygasł. Poproś o nowy.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Zbyt wiele żądań. Poczekaj chwilę i spróbuj ponownie.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Zbyt wiele nieudanych prób. Poczekaj chwilę i spróbuj ponownie.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Nie mogliśmy wysłać kodu weryfikacyjnego. Spróbuj ponownie później.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Jesteś już zalogowany.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Niektóre informacje są nieprawidłowe. Sprawdź dane i spróbuj ponownie.'
  },
  'sk': {
    'login': 'Prihlásiť sa',
    'signup': 'Zaregistrovať sa',
    'reset-password': 'Obnoviť heslo',
    'confirm-code': 'Potvrdiť kód',
    'CODE_ON_THE_WAY_TIP': 'Váš kód je na ceste. Ak sa chcete prihlásiť, zadajte kód, ktorý sme vám poslali. Príchod môže trvať minútu.',
    'PW_POLICY_TIP': '1. Aspoň 8 znakov.\n' +
      '2. Musí obsahovať malé písmená.\n' +
      '3. Musí obsahovať veľké písmená.\n' +
      '4. Musí obsahovať špeciálne znaky.',
    'You are already logged in as': 'Ste už prihlásený ako',
    'Sign out': 'Odhlásiť sa',
    'Bad Response.': 'Neplatná odpoveď.',
    'Email': 'E-mail',
    'Password': 'Heslo',
    'Sign in': 'Prihlásiť sa',
    'Confirm': 'Potvrdiť',
    'Don\'t have an account?': 'Nemáte účet?',
    'Sign up': 'Zaregistrovať sa',
    'or': 'alebo',
    'Forgot your password?': 'Zabudli ste heslo?',
    'Create account': 'Vytvoriť účet',
    'Username': 'Meno používateľa',
    'Confirm Password': 'Potvrdiť heslo',
    'New Password': 'Nové heslo',
    'By signing up, you agree to our': 'Registráciou súhlasíte s našimi',
    'Terms of Service': 'Podmienkami služby',
    ' and ': ' a ',
    'Privacy Policy': 'Zásadami ochrany súkromia',
    'Already have an account?': 'Máte už účet?',
    'Reset password': 'Obnoviť heslo',
    'Enter the code sent to your email': 'Zadajte kód odoslaný na váš e-mail',
    'Send code': 'Odoslať kód',
    'Resend code': 'Znova odoslať kód',
    'Back to login': 'Späť na prihlásenie',
    'Enter your email': 'Zadajte svoju e-mailovú adresu',
    'Invalid Password': 'Neplatné heslo',
    'Passwords do not match.': 'Heslá sa nezhodujú.',
    'We have sent a numeric verification code to your email address at': 'Poslali sme číselný overovací kód na vašu e-mailovú adresu:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Nepodporovaný krok prihlásenia:',
    'AUTH_ERROR_GENERIC': 'Overenie zlyhalo. Skúste to prosím znova.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Nesprávny e-mail alebo heslo.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Váš účet ešte nebol potvrdený. Overte ho pomocou kódu, ktorý sme poslali.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Toto meno používateľa je už obsadené.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Pre túto e-mailovú adresu sme nenašli žiadny účet.',
    'AUTH_ERROR_CODE_MISMATCH': 'Overovací kód je nesprávny.',
    'AUTH_ERROR_CODE_EXPIRED': 'Platnosť overovacieho kódu vypršala. Požiadajte o nový.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Príliš veľa požiadaviek. Chvíľu počkajte a skúste to znova.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Príliš veľa neúspešných pokusov. Chvíľu počkajte a skúste to znova.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Overovací kód sa nám nepodarilo odoslať. Skúste to neskôr.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Ste už prihlásený.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Niektoré informácie sú neplatné. Skontrolujte zadané údaje a skúste to znova.'
  },
  'uk': {
    'login': 'Увійти',
    'signup': 'Зареєструватися',
    'reset-password': 'Скинути пароль',
    'confirm-code': 'Підтвердити код',
    'CODE_ON_THE_WAY_TIP': 'Ваш код вже в дорозі. Щоб увійти, введіть код, який ми вам надіслали. Це може зайняти хвилину.',
    'PW_POLICY_TIP': '1. Не менше 8 символів.\n' +
      '2. Повинен містити малі літери.\n' +
      '3. Повинен містити великі літери.\n' +
      '4. Повинен містити спеціальні символи.',
    'You are already logged in as': 'Ви вже увійшли як',
    'Sign out': 'Вийти',
    'Bad Response.': 'Некоректна відповідь.',
    'Email': 'Ел. пошта',
    'Password': 'Пароль',
    'Sign in': 'Увійти',
    'Confirm': 'Підтвердити',
    'Don\'t have an account?': 'Немає облікового запису?',
    'Sign up': 'Зареєструватися',
    'or': 'або',
    'Forgot your password?': 'Забули пароль?',
    'Create account': 'Створити обліковий запис',
    'Username': 'Ім\'я користувача',
    'Confirm Password': 'Підтвердити пароль',
    'New Password': 'Новий пароль',
    'By signing up, you agree to our': 'Реєструючись, ви погоджуєтесь із нашими',
    'Terms of Service': 'Умовами надання послуг',
    ' and ': ' та ',
    'Privacy Policy': 'Політикою конфіденційності',
    'Already have an account?': 'Вже є обліковий запис?',
    'Reset password': 'Скинути пароль',
    'Enter the code sent to your email': 'Введіть код, надісланий на вашу пошту',
    'Send code': 'Надіслати код',
    'Resend code': 'Надіслати код повторно',
    'Back to login': 'Повернутися до входу',
    'Enter your email': 'Введіть адресу ел. пошти',
    'Invalid Password': 'Недійсний пароль',
    'Passwords do not match.': 'Паролі не збігаються.',
    'We have sent a numeric verification code to your email address at': 'Ми надіслали числовий код підтвердження на вашу адресу ел. пошти:',
    'COUNTDOWN_SUFFIX': 'с',
    'Unsupported sign-in step:': 'Непідтримуваний крок входу:',
    'AUTH_ERROR_GENERIC': 'Помилка автентифікації. Будь ласка, спробуйте ще раз.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Неправильна адреса ел. пошти або пароль.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Ваш обліковий запис ще не підтверджено. Будь ласка, підтвердьте його за допомогою коду, який ми надіслали.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Це ім\'я користувача вже зайнято.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Нам не вдалося знайти обліковий запис для цієї адреси ел. пошти.',
    'AUTH_ERROR_CODE_MISMATCH': 'Код підтвердження невірний.',
    'AUTH_ERROR_CODE_EXPIRED': 'Термін дії коду підтвердження закінчився. Будь ласка, запросіть новий.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Забагато запитів. Будь ласка, зачекайте хвилину і спробуйте знову.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Забагато невдалих спроб. Будь ласка, зачекайте хвилину і спробуйте знову.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Нам не вдалося надіслати код підтвердження. Будь ласка, спробуйте пізніше.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Ви вже увійшли в систему.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Деяка інформація недійсна. Будь ласка, перевірте введені дані та спробуйте знову.'
  },
  'fa': {
    'login': 'ورود',
    'signup': 'ثبت‌نام',
    'reset-password': 'بازنشانی رمز عبور',
    'confirm-code': 'تأیید کد',
    'CODE_ON_THE_WAY_TIP': 'کد شما در راه است. برای ورود، کدی که برای شما ارسال کرده‌ایم را وارد کنید. ممکن است یک دقیقه طول بکشد تا برسد.',
    'PW_POLICY_TIP': '1. حداقل ۸ کاراکتر.\n' +
      '2. باید حروف کوچک داشته باشد.\n' +
      '3. باید حروف بزرگ داشته باشد.\n' +
      '4. باید نویسه‌های نمادی داشته باشد.',
    'You are already logged in as': 'شما در حال حاضر با این حساب وارد شده‌اید:',
    'Sign out': 'خروج',
    'Bad Response.': 'پاسخ نامعتبر.',
    'Email': 'ایمیل',
    'Password': 'رمز عبور',
    'Sign in': 'ورود',
    'Confirm': 'تأیید',
    'Don\'t have an account?': 'حساب کاربری ندارید؟',
    'Sign up': 'ثبت‌نام',
    'or': 'یا',
    'Forgot your password?': 'رمز عبورتان را فراموش کرده‌اید؟',
    'Create account': 'ایجاد حساب',
    'Username': 'نام کاربری',
    'Confirm Password': 'تأیید رمز عبور',
    'New Password': 'رمز عبور جدید',
    'By signing up, you agree to our': 'با ثبت‌نام، شما با',
    'Terms of Service': 'شرایط خدمات',
    ' and ': ' و ',
    'Privacy Policy': 'سیاست حریم خصوصی',
    'Already have an account?': 'حساب کاربری دارید؟',
    'Reset password': 'بازنشانی رمز عبور',
    'Enter the code sent to your email': 'کد ارسال‌شده به ایمیل خود را وارد کنید',
    'Send code': 'ارسال کد',
    'Resend code': 'ارسال مجدد کد',
    'Back to login': 'بازگشت به ورود',
    'Enter your email': 'آدرس ایمیل خود را وارد کنید',
    'Invalid Password': 'رمز عبور نامعتبر',
    'Passwords do not match.': 'رمزهای عبور مطابقت ندارند.',
    'We have sent a numeric verification code to your email address at': 'یک کد تأیید عددی به آدرس ایمیل شما ارسال کرده‌ایم:',
    'COUNTDOWN_SUFFIX': 'ث',
    'Unsupported sign-in step:': 'مرحله ورود پشتیبانی‌نشده:',
    'AUTH_ERROR_GENERIC': 'احراز هویت ناموفق بود. لطفاً دوباره امتحان کنید.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'ایمیل یا رمز عبور اشتباه است.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'حساب شما هنوز تأیید نشده است. لطفاً آن را با کدی که ارسال کرده‌ایم تأیید کنید.',
    'AUTH_ERROR_USERNAME_EXISTS': 'این نام کاربری قبلاً استفاده شده است.',
    'AUTH_ERROR_USER_NOT_FOUND': 'حسابی برای آن آدرس ایمیل پیدا نکردیم.',
    'AUTH_ERROR_CODE_MISMATCH': 'کد تأیید اشتباه است.',
    'AUTH_ERROR_CODE_EXPIRED': 'کد تأیید منقضی شده است. لطفاً یک کد جدید درخواست کنید.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'درخواست‌های بیش از حد. لطفاً کمی صبر کنید و دوباره امتحان کنید.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'تلاش‌های ناموفق زیاد. لطفاً کمی صبر کنید و دوباره امتحان کنید.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'نتوانستیم کد تأیید را ارسال کنیم. لطفاً بعداً دوباره امتحان کنید.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'شما قبلاً وارد شده‌اید.',
    'AUTH_ERROR_INVALID_PARAMETER': 'برخی اطلاعات نامعتبر است. لطفاً ورودی خود را بررسی کنید و دوباره امتحان کنید.'
  },
  'id': {
    'login': 'Masuk',
    'signup': 'Daftar',
    'reset-password': 'Atur ulang kata sandi',
    'confirm-code': 'Konfirmasi kode',
    'CODE_ON_THE_WAY_TIP': 'Kode Anda sedang dalam perjalanan. Untuk masuk, masukkan kode yang kami kirimkan. Mungkin perlu satu menit untuk tiba.',
    'PW_POLICY_TIP': '1. Minimal 8 karakter.\n' +
      '2. Harus mengandung huruf kecil.\n' +
      '3. Harus mengandung huruf besar.\n' +
      '4. Harus mengandung karakter simbol.',
    'You are already logged in as': 'Anda sudah masuk sebagai',
    'Sign out': 'Keluar',
    'Bad Response.': 'Respons buruk.',
    'Email': 'Email',
    'Password': 'Kata sandi',
    'Sign in': 'Masuk',
    'Confirm': 'Konfirmasi',
    'Don\'t have an account?': 'Belum punya akun?',
    'Sign up': 'Daftar',
    'or': 'atau',
    'Forgot your password?': 'Lupa kata sandi?',
    'Create account': 'Buat akun',
    'Username': 'Nama pengguna',
    'Confirm Password': 'Konfirmasi kata sandi',
    'New Password': 'Kata sandi baru',
    'By signing up, you agree to our': 'Dengan mendaftar, Anda menyetujui',
    'Terms of Service': 'Ketentuan Layanan',
    ' and ': ' dan ',
    'Privacy Policy': 'Kebijakan Privasi',
    'Already have an account?': 'Sudah punya akun?',
    'Reset password': 'Atur ulang kata sandi',
    'Enter the code sent to your email': 'Masukkan kode yang dikirim ke email Anda',
    'Send code': 'Kirim kode',
    'Resend code': 'Kirim ulang kode',
    'Back to login': 'Kembali ke halaman masuk',
    'Enter your email': 'Masukkan email Anda',
    'Invalid Password': 'Kata sandi tidak valid',
    'Passwords do not match.': 'Kata sandi tidak cocok.',
    'We have sent a numeric verification code to your email address at': 'Kami telah mengirimkan kode verifikasi numerik ke alamat email Anda:',
    'COUNTDOWN_SUFFIX': 'd',
    'Unsupported sign-in step:': 'Langkah masuk yang tidak didukung:',
    'AUTH_ERROR_GENERIC': 'Autentikasi gagal. Silakan coba lagi.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Email atau kata sandi salah.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Akun Anda belum dikonfirmasi. Silakan verifikasi dengan kode yang kami kirimkan.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Nama pengguna ini sudah digunakan.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Kami tidak dapat menemukan akun untuk alamat email tersebut.',
    'AUTH_ERROR_CODE_MISMATCH': 'Kode verifikasi salah.',
    'AUTH_ERROR_CODE_EXPIRED': 'Kode verifikasi telah kedaluwarsa. Silakan minta yang baru.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Terlalu banyak permintaan. Tunggu sebentar dan coba lagi.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Terlalu banyak upaya gagal. Tunggu sebentar dan coba lagi.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Kami tidak dapat mengirimkan kode verifikasi. Silakan coba lagi nanti.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Anda sudah masuk.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Beberapa informasi tidak valid. Periksa masukan Anda dan coba lagi.'
  },
  'cs': {
    'login': 'Přihlásit se',
    'signup': 'Zaregistrovat se',
    'reset-password': 'Obnovit heslo',
    'confirm-code': 'Potvrdit kód',
    'CODE_ON_THE_WAY_TIP': 'Váš kód je na cestě. Chcete-li se přihlásit, zadejte kód, který jsme vám poslali. Příchod může trvat minutu.',
    'PW_POLICY_TIP': '1. Alespoň 8 znaků.\n' +
      '2. Musí obsahovat malá písmena.\n' +
      '3. Musí obsahovat velká písmena.\n' +
      '4. Musí obsahovat speciální znaky.',
    'You are already logged in as': 'Jste již přihlášeni jako',
    'Sign out': 'Odhlásit se',
    'Bad Response.': 'Špatná odpověď.',
    'Email': 'E-mail',
    'Password': 'Heslo',
    'Sign in': 'Přihlásit se',
    'Confirm': 'Potvrdit',
    'Don\'t have an account?': 'Nemáte účet?',
    'Sign up': 'Zaregistrovat se',
    'or': 'nebo',
    'Forgot your password?': 'Zapomněli jste heslo?',
    'Create account': 'Vytvořit účet',
    'Username': 'Uživatelské jméno',
    'Confirm Password': 'Potvrdit heslo',
    'New Password': 'Nové heslo',
    'By signing up, you agree to our': 'Registrací souhlasíte s našimi',
    'Terms of Service': 'Podmínkami služby',
    ' and ': ' a ',
    'Privacy Policy': 'Zásadami ochrany osobních údajů',
    'Already have an account?': 'Již máte účet?',
    'Reset password': 'Obnovit heslo',
    'Enter the code sent to your email': 'Zadejte kód odeslaný na váš e-mail',
    'Send code': 'Odeslat kód',
    'Resend code': 'Znovu odeslat kód',
    'Back to login': 'Zpět na přihlášení',
    'Enter your email': 'Zadejte svůj e-mail',
    'Invalid Password': 'Neplatné heslo',
    'Passwords do not match.': 'Hesla se neshodují.',
    'We have sent a numeric verification code to your email address at': 'Zaslali jsme číselný ověřovací kód na vaši e-mailovou adresu:',
    'COUNTDOWN_SUFFIX': 's',
    'Unsupported sign-in step:': 'Nepodporovaný krok přihlášení:',
    'AUTH_ERROR_GENERIC': 'Ověření se nezdařilo. Zkuste to prosím znovu.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'Nesprávný e-mail nebo heslo.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'Váš účet ještě nebyl potvrzen. Ověřte ho prosím pomocí kódu, který jsme odeslali.',
    'AUTH_ERROR_USERNAME_EXISTS': 'Toto uživatelské jméno je již obsazeno.',
    'AUTH_ERROR_USER_NOT_FOUND': 'Nenašli jsme žádný účet pro tuto e-mailovou adresu.',
    'AUTH_ERROR_CODE_MISMATCH': 'Ověřovací kód je nesprávný.',
    'AUTH_ERROR_CODE_EXPIRED': 'Platnost ověřovacího kódu vypršela. Požádejte o nový.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'Příliš mnoho požadavků. Chvíli počkejte a zkuste to znovu.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'Příliš mnoho neúspěšných pokusů. Chvíli počkejte a zkuste to znovu.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'Nepodařilo se nám odeslat ověřovací kód. Zkuste to prosím later.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'Jste již přihlášeni.',
    'AUTH_ERROR_INVALID_PARAMETER': 'Některé informace jsou neplatné. Zkontrolujte svůj vstup a zkuste to znovu.'
  },
  'ar': {
    'login': 'تسجيل الدخول',
    'signup': 'إنشاء حساب',
    'reset-password': 'إعادة تعيين كلمة المرور',
    'confirm-code': 'تأكيد الرمز',
    'CODE_ON_THE_WAY_TIP': 'رمزك في الطريق. لتسجيل الدخول، أدخل الرمز الذي أرسلناه إليك. قد يستغرق الأمر دقيقة للوصول.',
    'PW_POLICY_TIP': '1. 8 أحرف على الأقل.\n' +
      '2. يجب أن يحتوي على أحرف صغيرة.\n' +
      '3. يجب أن يحتوي على أحرف كبيرة.\n' +
      '4. يجب أن يحتوي على رموز.',
    'You are already logged in as': 'أنت بالفعل مسجل دخولك بحساب:',
    'Sign out': 'تسجيل الخروج',
    'Bad Response.': 'استجابة غير صالحة.',
    'Email': 'البريد الإلكتروني',
    'Password': 'كلمة المرور',
    'Sign in': 'تسجيل الدخول',
    'Confirm': 'تأكيد',
    'Don\'t have an account?': 'ليس لديك حساب؟',
    'Sign up': 'إنشاء حساب',
    'or': 'أو',
    'Forgot your password?': 'هل نسيت كلمة المرور؟',
    'Create account': 'إنشاء حساب',
    'Username': 'اسم المستخدم',
    'Confirm Password': 'تأكيد كلمة المرور',
    'New Password': 'كلمة مرور جديدة',
    'By signing up, you agree to our': 'بالتسجيل، أنت توافق على',
    'Terms of Service': 'شروط الخدمة',
    ' and ': ' و',
    'Privacy Policy': 'سياسة الخصوصية',
    'Already have an account?': 'لديك حساب بالفعل؟',
    'Reset password': 'إعادة تعيين كلمة المرور',
    'Enter the code sent to your email': 'أدخل الرمز المرسل إلى بريدك الإلكتروني',
    'Send code': 'إرسال الرمز',
    'Resend code': 'إعادة إرسال الرمز',
    'Back to login': 'العودة إلى تسجيل الدخول',
    'Enter your email': 'أدخل بريدك الإلكتروني',
    'Invalid Password': 'كلمة مرور غير صالحة',
    'Passwords do not match.': 'كلمتا المرور غير متطابقتين.',
    'We have sent a numeric verification code to your email address at': 'لقد أرسلنا رمز تحقق رقمياً إلى عنوان بريدك الإلكتروني:',
    'COUNTDOWN_SUFFIX': 'ث',
    'Unsupported sign-in step:': 'خطوة تسجيل دخول غير مدعومة:',
    'AUTH_ERROR_GENERIC': 'فشل المصادقة. يرجى المحاولة مرة أخرى.',
    'AUTH_ERROR_INVALID_CREDENTIALS': 'بريد إلكتروني أو كلمة مرور غير صحيحة.',
    'AUTH_ERROR_USER_NOT_CONFIRMED': 'لم يتم تأكيد حسابك بعد. يرجى التحقق منه باستخدام الرمز الذي أرسلناه.',
    'AUTH_ERROR_USERNAME_EXISTS': 'اسم المستخدم هذا مأخوذ بالفعل.',
    'AUTH_ERROR_USER_NOT_FOUND': 'لم نتمكن من العثور على حساب لعنوان البريد الإلكتروني هذا.',
    'AUTH_ERROR_CODE_MISMATCH': 'رمز التحقق غير صحيح.',
    'AUTH_ERROR_CODE_EXPIRED': 'انتهت صلاحية رمز التحقق. يرجى طلب رمز جديد.',
    'AUTH_ERROR_TOO_MANY_REQUESTS': 'طلبات كثيرة جداً. يرجى الانتظار لحظة والمحاولة مرة أخرى.',
    'AUTH_ERROR_TOO_MANY_ATTEMPTS': 'محاولات فاشلة كثيرة جداً. يرجى الانتظار لحظة والمحاولة مرة أخرى.',
    'AUTH_ERROR_CODE_DELIVERY_FAILED': 'لم نتمكن من إرسال رمز التحقق. يرجى المحاولة مرة أخرى لاحقاً.',
    'AUTH_ERROR_ALREADY_AUTHENTICATED': 'أنت بالفعل مسجل دخولك.',
    'AUTH_ERROR_INVALID_PARAMETER': 'بعض المعلومات غير صالحة. يرجى التحقق من إدخالك والمحاولة مرة أخرى.'
  }
}
