# .github/release.yml

changelog:
  exclude:
    labels:
      - test
      - chore
      - ci
      - :type/dev
  categories:
    - title: Exciting New Features 🎉
      labels:
        - :type/feature-request
        - :type/feature
    - title: Bug Fixes 🐛
      labels:
        - :type/bug
        - :type/bug-fix
        - :type/regression
    - title: Enhancements 🔧
      labels:
        - :type/enhancement
        - :type/performance
    - title: Other Changes 🚧
      labels:
        - "*"
