import { chromium } from 'playwright';
const b = await chromium.launch();
const pg = await b.newPage();
pg.on('console', m => { if (m.type()==='error'||m.type()==='warning') console.log('LOG', m.type(), m.text().slice(0,200)); });
pg.on('pageerror', e => console.log('PAGEERROR', String(e).slice(0,300)));
const target = 'refclick-target-' + Date.now();
const host = 'refclick-host-' + Date.now();
await pg.goto('http://localhost:3002/');
await pg.waitForTimeout(2500);
// create target page via cmdk
await pg.keyboard.press('Meta+k');
await pg.waitForSelector('.ls-dialog-cmdk input, .cp__cmdk input');
await pg.keyboard.type(target, {delay: 20});
await pg.waitForTimeout(800);
await pg.locator(".search-results > div", {hasText: "Create page"}).first().click();
await pg.waitForSelector('.editor-wrapper textarea', {timeout: 10000});
// go to host page
await pg.keyboard.press('Meta+k');
await pg.waitForSelector('.ls-dialog-cmdk input');
await pg.keyboard.type(host, {delay: 20});
await pg.waitForTimeout(800);
await pg.locator(".search-results > div", {hasText: "Create page"}).first().click();
await pg.waitForSelector('.editor-wrapper textarea', {timeout: 10000});
await pg.keyboard.type('[[' + target + ']]');
await pg.keyboard.press('Escape');
await pg.waitForTimeout(800);
const ref = pg.locator('.page-reference .page-ref', {hasText: target});
console.log('ref count', await ref.count());
await ref.first().click();
await pg.waitForTimeout(1500);
console.log('hash', await pg.evaluate(() => location.hash));
console.log('title', await pg.evaluate(() => document.querySelector('.page-title, [data-testid="page title"], .ls-page-title')?.textContent));
await b.close();
