(ns frontend.modules.shortcut.dicts.de
  "Provides dictionary entries for shortcuts in DE")

(def dict
  {:command.auto-complete/complete         "Automatische Vervollständigung: Ausgewähltes Element auswählen"
   :command.auto-complete/next             "Automatische Vervollständigung: Nächstes Element auswählen"
   :command.auto-complete/open-link        "Automatische Vervollständigung: Ausgewähltes Element im Browser öffnen"
   :command.auto-complete/prev             "Automatische Vervollständigung: Vorheriges Element auswählen"
   :command.auto-complete/shift-complete   "Automatische Vervollständigung: Ausgewähltes Element in der Seitenleiste öffnen"
   :command.cards/forgotten                "Karten: Vergessen"
   :command.cards/next-card                "Karten: Nächste Karte"
   :command.cards/recall                   "Karten: Nehmen Sie sich eine Weile Zeit, um sich zu erinnern"
   :command.cards/remembered               "Karten: Gemerkt"
   :command.cards/toggle-answers           "Karten: Antworten/Lücken ein-/ausblenden"
   :command.command/run                    "Git-Befehl ausführen"
   :command.command/toggle-favorite        "Zu Favoriten hinzufügen/entfernen"
   :command.command-palette/toggle         "Befehlspalette umschalten"
   :command.date-picker/complete           "Datumsauswahl: Den gewünschten Tag wählen"
   :command.date-picker/next-day           "Datumsauswahl: Den nächsten Tag wählen"
   :command.date-picker/next-week          "Datumsauswahl: Die nächste Woche wählen"
   :command.date-picker/prev-day           "Datumsauswahl: Den vorherigen Tag wählen"
   :command.date-picker/prev-week          "Datumsauswahl: Die vorherige Woche wählen"
   :command.dev/show-block-ast             "(Dev) Block-AST anzeigen"
   :command.dev/show-block-data            "(Dev) Blockdaten anzeigen"
   :command.dev/show-page-ast              "(Dev) Seiten-AST anzeigen"
   :command.dev/show-page-data             "(Dev) Seitendaten anzeigen"
   :command.editor/backspace               "Backspace / Rückwärts löschen"
   :command.editor/backward-kill-word      "Ein Wort rückwärts löschen"
   :command.editor/backward-word           "Cursor ein Wort zurückbewegen"
   :command.editor/beginning-of-block      "Cursor an den Anfang eines Blocks bewegen"
   :command.editor/bold                    "Fett"
   :command.editor/clear-block             "Gesamten Blockinhalt löschen"
   :command.editor/collapse-block-children "Zusammenklappen"
   :command.editor/copy                    "Kopieren (kopiert entweder die Auswahl oder die Blockreferenz)"
   :command.editor/copy-current-file       "Aktuelle Datei kopieren"
   :command.editor/copy-embed              "Kopieren einer Blockeinbettung, die auf den aktuellen Block verweist"
   :command.editor/copy-page-url           "Seiten-URL kopieren"
   :command.editor/copy-text               "Auswahl als Text kopieren"
   :command.editor/cut                     "Ausschneiden"
   :command.editor/cycle-todo              "Den TODO-Status des aktuellen Eintrags ändern"
   :command.editor/delete                  "Löschen / Vorwärts löschen"
   :command.editor/delete-selection        "Ausgewählte Blöcke löschen"
   :command.editor/down                    "Cursor nach unten bewegen / Nach unten auswählen"
   :command.editor/end-of-block            "Cursor an das Ende eines Blocks bewegen"
   :command.editor/escape-editing          "Bearbeitung abschließen"
   :command.editor/expand-block-children   "Erweitern"
   :command.editor/follow-link             "Link unter dem Cursor folgen"
   :command.editor/forward-kill-word       "Ein Wort vorwärts löschen"
   :command.editor/forward-word            "Cursor ein Wort vorwärts bewegen"
   :command.editor/highlight               "Hervorheben"
   :command.editor/indent                  "Block einrücken"
   :command.editor/insert-link             "HTML Link"
   :command.editor/insert-youtube-timestamp "YouTube-Zeitstempel einfügen"
   :command.editor/italics                 "Kursiv"
   :command.editor/kill-line-after         "Zeile nach der Cursorposition löschen"
   :command.editor/kill-line-before        "Zeile vor der Cursorposition löschen"
   :command.editor/left                    "Cursor nach links bewegen / Ausgewählten Block am Anfang öffnen"
   :command.editor/move-block-up           "Block nach oben verschieben"
   :command.editor/move-block-down         "Block nach unten verschieben"
   :command.editor/new-block               "Neuen Block erstellen"
   :command.editor/new-line                "Neue Zeile innerhalb des Blocks erstellen"
   :command.editor/new-whiteboard          "Neues Whiteboard"
   :command.editor/open-edit               "Ausgewählten Block bearbeiten"
   :command.editor/open-file-in-default-app "Datei in Standard-Anwendung öffnen"
   :command.editor/open-file-in-directory  "Datei im übergeordneten Verzeichnis öffnen"
   :command.editor/open-link-in-sidebar    "Link in Seitenleiste öffnen"
   :command.editor/outdent                 "Block ausrücken"
   :command.editor/paste-text-in-one-block-at-point "Text in einen Block an Stelle einfügen"
   :command.editor/redo                    "Wiederholen"
   :command.editor/replace-block-reference-at-point "Blockreferenz durch ihren Inhalt an Stelle ersetzen"
   :command.editor/right                   "Cursor nach rechts bewegen / Ausgewählten Block am Ende öffnen"
   :command.editor/select-all-blocks       "Alle Blöcke auswählen"
   :command.editor/select-block-down       "Block unterhalb auswählen"
   :command.editor/select-block-up         "Block oberhalb auswählen"
   :command.editor/select-down             "Inhalt unten auswählen"
   :command.editor/select-parent           "Übergeordneten Block auswählen"
   :command.editor/select-up               "Inhalt oben auswählen"
   :command.editor/strike-through          "Durchgestrichen"
   :command.editor/toggle-open-blocks      "Öffnen von Blöcken umschalten (alle Blöcke ein- oder ausklappen)"
   :command.editor/toggle-undo-redo-mode   "Rückgängig / Wiederherstellen umschalten (global oder nur die Seite)"
   :command.editor/undo                    "Rückgängig"
   :command.editor/up                      "Cursor nach oben bewegen / Nach oben auswählen"
   :command.editor/zoom-in                 "Heranzoomen"
   :command.editor/zoom-out                "Herauszoomen"
   :command.git/commit                     "Git Commit-Nachricht"
   :command.go/all-graphs                  "Zu allen Graphen springen"
   :command.go/all-pages                   "Zu allen Seiten springen"
   :command.go/backward                    "Zurück"
   :command.go/electron-find-in-page       "Text in Seite finden"
   :command.go/electron-jump-to-the-next   "Zum nächsten Treffer in der Suchleiste springen"
   :command.go/electron-jump-to-the-previous "Zum vorherigen Treffer in der Suchleiste springen"
   :command.go/flashcards                  "Karteikarten umdrehen"
   :command.go/forward                     "Vorwärts"
   :command.go/graph-view                  "Zur Graph-Ansicht springen"
   :command.go/home                        "Zur Startseite springen"
   :command.go/journals                    "Zu Journalen springen"
   :command.go/keyboard-shortcuts          "Zu Tastaturkürzeln springen"
   :command.go/next-journal                "Zum nächsten Journal springen"
   :command.go/prev-journal                "Zum vorherigen Journal springen"
   :command.go/search                      "Volltextsuche"
   :command.go/search-in-page              "Blöcke auf der aktuellen Seite suchen"
   :command.go/tomorrow                    "Zu morgen springen"
   :command.go/whiteboards                 "Zu Whiteboards springen"
   :command.graph/add                      "Einen Graph hinzufügen"
   :command.graph/export-as-html           "Öffentliche Graphseite als HTML exportieren"
   :command.graph/open                     "Graph zum Öffnen auswählen"
   :command.graph/re-index                 "Aktuellen Graph neu indizieren"
   :command.graph/remove                   "Einen Graph entfernen"
   :command.graph/save                     "Aktuellen Graph auf Festplatte speichern"
   :command.misc/copy                      "mod+c"
   :command.pdf/close                      "PDF: Aktuelles PDF-Dokument schließen"
   :command.pdf/find                       "PDF: Text des aktuellen PDF-Dokuments durchsuchen"
   :command.pdf/next-page                  "PDF: Nächste Seite des aktuellen PDF-Dokuments"
   :command.pdf/previous-page              "PDF: Vorherige Seite des aktuellen PDF-Dokuments"
   :command.search/re-index                "Suchindex neu erstellen"
   :command.sidebar/clear                  "Alles in der rechten Seitenleiste entfernen"
   :command.sidebar/close-top              "Schließt das oberste Element in der rechten Seitenleiste"
   :command.sidebar/open-today-page        "Seite des heutigen Tages in der rechten Seitenleiste öffnen"
   :command.ui/clear-all-notifications     "Alle Benachrichtigungen entfernen"
   :command.ui/goto-plugins                "Zum Plugin-Dashboard springen"
   :command.ui/install-plugins-from-file   "Plugins aus plugins.edn installieren"
   :command.ui/select-theme-color          "Verfügbare Themenfarben auswählen"
   :command.ui/toggle-brackets             "Umschalten, ob Klammern angezeigt werden sollen"
   :command.ui/toggle-cards                "Karten umschalten"
   :command.ui/toggle-contents             "Inhalt in Seitenleiste umschalten"
   :command.ui/toggle-document-mode        "Dokumentenmodus umschalten"
   :command.ui/toggle-help                 "Hilfe aktivieren"
   :command.ui/toggle-right-sidebar        "Rechte Seitenleiste umschalten"
   :command.ui/toggle-left-sidebar         "Linke Seitenleiste umschalten"
   :command.ui/toggle-settings             "Einstellungen umschalten"
   :command.ui/toggle-wide-mode            "Breitbildmodus umschalten"
   :command.ui/toggle-theme                "Umschalten zwischen dunklem/hellem Theme"
   :shortcut.category/basics               "Grundlagen"
   :shortcut.category/block-command-editing "Blockbefehl bearbeiten"
   :shortcut.category/block-editing        "Blockbearbeitung allgemein"
   :shortcut.category/block-selection      "Blockauswahl (Esc drücken, um die Auswahl zu beenden)"
   :shortcut.category/formatting           "Formatierung"
   :shortcut.category/navigating           "Navigation"
   :shortcut.category/others               "Sonstiges"
   :shortcut.category/toggle               "Umschalten"})
