(ns frontend.modules.shortcut.dicts.es
  "Provides dictionary entries for shortcuts in ES")

(def dict
  {:shortcut.category/formatting                      "Formato"
   :shortcut.category/basics                          "Básico"
   :shortcut.category/navigating                      "Navegación"
   :shortcut.category/block-editing                   "Edición de bloque general"
   :shortcut.category/block-command-editing           "Comandos edición de bloque"
   :shortcut.category/block-selection                 "Selección de bloques (pulsar Esc para salir)"
   :shortcut.category/toggle                          "Alternar"
   :shortcut.category/others                          "Otros"
   :command.editor/indent                             "Aumentar sangría"
   :command.editor/outdent                            "Disminuir sangría"
   :command.editor/move-block-up                      "Mover bloque arriba"
   :command.editor/move-block-down                    "Mover bloque abajo"
   :command.editor/new-block                          "Crear bloque nuevo"
   :command.editor/new-line                           "Nueva linea en bloque"
   :command.editor/zoom-in                            "Acercar / Adelante"
   :command.editor/zoom-out                           "Alejar / Atrás"
   :command.editor/follow-link                        "Seguir enlace bajo el cursor"
   :command.editor/open-link-in-sidebar               "Abrir enlace en barra lateral"
   :command.editor/expand-block-children              "Expandir"
   :command.editor/collapse-block-children            "Colapsar"
   :command.editor/select-block-up                    "Seleccionar bloque de arriba"
   :command.editor/select-block-down                  "Seleccionar bloque de abajo"
   :command.editor/select-all-blocks                  "Seleccionar todos los bloques"
   :command.ui/toggle-help                            "Alternar ayuda"
   :command.git/commit                                "Confirmar"
   :command.go/search                                 "Buscar en el grafo"
   :command.go/search-in-page                         "Buscar en la página actual"
   :command.ui/toggle-document-mode                   "Alternar modo documento"
   :command.ui/toggle-contents                        "Alternar Contenido en barra lateral"
   :command.ui/toggle-theme                           "Alternar entre tema claro/oscuro"
   :command.ui/toggle-right-sidebar                   "Alternar barra lateral"
   :command.ui/toggle-settings                        "Alternar Opciones"
   :command.go/journals                               "Ir a los diarios"
   :command.ui/toggle-wide-mode                       "Alternar modo ancho"
   :command.ui/toggle-brackets                        "Alternar corchetes"
   :command.search/re-index                           "Reconstruir índice de búsqueda"
   :command.editor/bold                               "Negrita"
   :command.editor/italics                            "Cursiva"
   :command.editor/insert-link                        "Enlace html"
   :command.editor/highlight                          "Resaltado"
   :command.editor/undo                               "Deshacer"
   :command.editor/redo                               "Rehacer"
   :command.editor/copy                               "Copiar"
   :command.editor/cut                                "Pegar"
   :command.editor/up                                 "Mover cursor arriba / Seleccionar arriba"
   :command.editor/down                               "Mover cursor abajo / Seleccionar abajo"
   :command.editor/left                               "Mover cursor a la izquierda / Abrir bloque seleccionado al inicio"
   :command.editor/right                              "Mover cursor a la derecha / Abrir bloque seleccionado al final"
   :command.editor/backspace                          "Retroceso / Eliminar hacia atrás"
   :command.editor/delete                             "Suprimir / Eliminar hacia delante"
   :command.editor/cycle-todo                         "Rotar estado TODO del elemento"
   :command.editor/clear-block                        "Borrar contenido del bloque"
   :command.editor/kill-line-before                   "Borrar linea antes del cursor"
   :command.editor/kill-line-after                    "Borrar linea despues del cursor"
   :command.editor/beginning-of-block                 "Mover cursor al inicio del bloque"
   :command.editor/end-of-block                       "Mover cursor al final del bloque"
   :command.editor/forward-word                       "Mover cursor una palabra adelante"
   :command.editor/backward-word                      "Mover cursor una palabra atrás"
   :command.editor/forward-kill-word                  "Borrar palabra posterior"
   :command.editor/backward-kill-word                 "Borrar palabra anterior"
   :command.editor/open-edit                          "Editar bloque seleccionado"
   :command.editor/delete-selection                   "Eliminar bloques seleccionados"
   :command.editor/toggle-open-blocks                 "Alternar bloques abiertos, (colapsar o expandir todos)"
   :command.auto-complete/complete                    "Auto-completar: Escoger elementos seleccionados"
   :command.auto-complete/next                        "Auto-completar: Seleccionar elemento siguiente"
   :command.auto-complete/open-link                   "Auto-completar: Abrir elemento seleccionado en navegador"
   :command.auto-complete/prev                        "Auto-completar: Seleccionar elemento anterior"
   :command.auto-complete/shift-complete              "Auto-completar: Abrir elemento seleccionado en barra lateral"
   :command.cards/forgotten                           "Tarjetas: olvidadas "
   :command.cards/next-card                           "Tarjetas: tarjeta siguiente"
   :command.cards/recall                              "Tarjetas: tomar un momento para recordar"
   :command.cards/remembered                          "Tarjetas: recordadas"
   :command.cards/toggle-answers                      "Tarjetas: mostrar/ocultar respuestas/prueba de completar oraciones "
   :command.command/run                               "Ejecutar comando git"
   :command.command/toggle-favorite                   "Agregar a/eliminar de favoritos"
   :command.command-palette/toggle                    "Alternar paleta de comandos"
   :command.date-picker/complete                      "Selector de fechas: Escoger día seleccionado"
   :command.date-picker/next-day                      "Selector de fechas: Seleccionar día siguiente"
   :command.date-picker/next-week                     "Selector de fechas: Seleccionar siguiente semana"
   :command.date-picker/prev-day                      "Selector de fechas: Seleccionar día anterior"
   :command.date-picker/prev-week                     "Selector de fechas: Seleccionar semana anterior"
   :command.dev/show-block-ast                        "(Dev) Mostrar AST de bloque"
   :command.dev/show-block-data                       "(Dev) Mostrar datos de bloque"
   :command.dev/show-page-ast                         "(Dev) Mostrar AST de página"
   :command.dev/show-page-data                        "(Dev) Mostrar datos de página"
   :command.editor/copy-current-file                  "Copiar el archivo actual"
   :command.editor/copy-embed                         "Copiar una incrustación de bloque apuntando al bloque actual"
   :command.editor/copy-page-url                      "Copiar url de página"
   :command.editor/copy-text                          "Copiar selección como texto"
   :command.editor/escape-editing                     "Escapar de edición"
   :command.editor/insert-youtube-timestamp           "Insertar marca de tiempo de YouTube"
   :command.editor/new-whiteboard                     "Nueva pizarra"
   :command.editor/open-file-in-default-app           "Abrir archivo en aplicación por defecto"
   :command.editor/open-file-in-directory             "Abrir archivo en carpeta padre"
   :command.editor/paste-text-in-one-block-at-point   "Pegar texto en un bloque en el punto"
   :command.editor/replace-block-reference-at-point   "Reemplazar referencia de bloque con su contenido en el punto"
   :command.editor/select-down                        "Seleccionar el contenido a continuación"
   :command.editor/select-parent                      "Seleccionar bloque padre"
   :command.editor/select-up                          "Seleccionar contenido anterior"
   :command.editor/strike-through                     "Tachado"
   :command.editor/toggle-undo-redo-mode              "Alternar modo deshacer rehacer (global o solo en página)"
   :command.go/all-graphs                             "Ir a todos los grafos"
   :command.go/all-pages                              "Ir a todas las páginas"
   :command.go/backward                               "Hacia atrás"
   :command.go/electron-find-in-page                  "Encontrar texto en página"
   :command.go/electron-jump-to-the-next              "Saltar a la siguiente coincidencia de tu búsqueda en la barra Find"
   :command.go/electron-jump-to-the-previous          "Saltar a la coincidencia anterior de tu búsqueda en la barra Find..."
   :command.go/flashcards                             "Alternar tarjetas de memorización"
   :command.go/forward                                "Hacia adelante"
   :command.go/graph-view                             "Ir a vista de grafos"
   :command.go/home                                   "Ir a página de inicio"
   :command.go/keyboard-shortcuts                     "Ir a atajos de teclado"
   :command.go/next-journal                           "Ir al siguiente diario"
   :command.go/prev-journal                           "Ir al diario anterior"
   :command.go/tomorrow                               "Ir a mañana"
   :command.go/whiteboards                            "Ir a pizarras"
   :command.graph/add                                 "Agregar un grafo"
   :command.graph/export-as-html                      "Exportar grafo público como html "
   :command.graph/open                                "Seleccionar grafo a abrir"
   :command.graph/re-index                            "Reindexar grafo actual"
   :command.graph/remove                              "Eliminar un grafo"
   :command.graph/save                                "Guardar grafo actual al disco"
   :command.misc/copy                                 "mod + c"
   :command.pdf/close                                 "Pdf: Cerrar documento pdf actual"
   :command.pdf/find                                  "Pdf: Buscar texto del documento pdf actual"
   :command.pdf/next-page                             "Pdf: Página siguiente del documento pdf actual"
   :command.pdf/previous-page                         "Pdf: Página previa del documento pdf actual"
   :command.sidebar/clear                             "Cerrar todo en la barra lateral derecha"
   :command.sidebar/close-top                         "Cierra el elemento superior en la barra lateral derecha"
   :command.sidebar/open-today-page                   "Abrir la página de hoy en barra lateral derecha"
   :command.ui/clear-all-notifications                "Borrar todas las notificaciones"
   :command.ui/goto-plugins                           "Ir al panel de extensiones"
   :command.ui/install-plugins-from-file              "Instalar extensiones de plugins.edn"
   :command.ui/select-theme-color                     "Seleccionar temas de colores disponibles"
   :command.ui/toggle-cards                           "Alternar tarjetas"
   :command.ui/toggle-left-sidebar                    "Alternar barra lateral izquierda"})
