(ns frontend.modules.shortcut.dicts.fr
  "Provides dictionary entries for shortcuts in FR")

(def dict
  {:shortcut.category/formatting           "Formats"
   :command.editor/indent                  "Indenter un Bloc vers la droite"
   :command.editor/outdent                 "Indenter un Bloc vers la gauche"
   :command.editor/move-block-up           "Déplacer un bloc au dessus"
   :command.editor/move-block-down         "Déplacer un bloc en dessous"
   :command.editor/new-block               "Créer un nouveau bloc"
   :command.editor/new-line                "Aller à la ligne dans un bloc"
   :command.editor/zoom-in                 "Zoomer"
   :command.editor/zoom-out                "Dézoomer"
   :command.editor/follow-link             "Suivre le lien sous le curseur"
   :command.editor/open-link-in-sidebar    "Ouvrir le lien dans la barre latérale"
   :command.editor/expand-block-children   "Etendre"
   :command.editor/collapse-block-children "Réduire"
   :command.editor/select-block-up         "Sélectionner le bloc au dessus"
   :command.editor/select-block-down       "Sélectionner le bloc en dessous"
   :command.editor/select-all-blocks       "Sélectionner tous les blocs"
   :command.ui/toggle-help                 "Afficher l'aide"
   :command.git/commit                     "Message de commit Git"
   :command.go/search                      "Recherche globale dans le texte"
   :command.ui/toggle-document-mode        "Intervertir le mode document"
   :command.ui/toggle-theme                "Intervertir le thème foncé/clair"
   :command.ui/toggle-right-sidebar        "Afficher/cacher la barre latérale"
   :command.go/journals                    "Aller au Journal"
   :command.auto-complete/complete  "Auto-complétion : Choisir l'élémnent sélectionné"
   :command.auto-complete/next  "Auto-complétion : Sélection l'élément suivant"
   :command.auto-complete/open-link  "Auto-complétion : Ouvrir l'élément sélectionné dans le navigateur"
   :command.auto-complete/prev  "Auto-complétion : Sélectionner l'élément précédent"
   :command.auto-complete/shift-complete  "Auto-complétion : Ouvrir l'élément sélectionné dans la barre latérale"
   :command.cards/forgotten  "Cartes : oubliées"
   :command.cards/next-card  "Cartes : carte suivante"
   :command.cards/recall  "Cartes : ayant pris du temps à se souvenir"
   :command.cards/remembered  "Cartes : souvenues"
   :command.cards/toggle-answers  "Cartes : montrer/masquer les réponses/clozes"
   :command.command/run  "Lancer une commande git"
   :command.command/toggle-favorite  "Ajouter/retirer des favoris"
   :command.command-palette/toggle  "Basculer la palette de commandes"
   :command.date-picker/complete  "Sélecteur de date : Choisir le jour sélectionné"
   :command.date-picker/next-day  "Sélecteur de date : Sélectionner le jour suivant"
   :command.date-picker/next-week  "Sélecteur de date : Sélectionner la semaine suivante "
   :command.date-picker/prev-day  "Sélecteur de date : Sélectionner le jour précédent"
   :command.date-picker/prev-week  "Sélecteur de date : Sélectionner la semaine précédente"
   :command.editor/backspace  "Retour arrière / Effacer en arrière"
   :command.editor/backward-kill-word  "Supprimer un mot en arrière"
   :command.editor/backward-word  "Déplacer le curseur avant un mot"
   :command.editor/beginning-of-block  "Déplacer le curseur au début du bloc"
   :command.editor/bold  "Gras"
   :command.editor/clear-block  "Supprimer tout le contenu d'un bloc"
   :command.editor/copy  "Copier (copie soit une sélection, ou une référence de bloc)..."
   :command.editor/copy-current-file  "Copier le fichier en cours"
   :command.editor/copy-embed  "Copier une intégration de ce bloc"
   :command.editor/copy-text  "Copier le texte de la sélection"
   :command.editor/cut  "Couper"
   :command.editor/cycle-todo  "Basculer l'état du TODO de l'élément"
   :command.editor/delete  "Supprimer / Efface en avant"
   :command.editor/delete-selection  "Supprimer les blocs sélectionnés"
   :command.editor/down  "Déplacer le curseur vers le bas / Sélectionner vers le bas"
   :command.editor/end-of-block  "Déplacer le curseur à la fin du bloc"
   :command.editor/escape-editing  "Quitter l'édition"
   :command.editor/forward-kill-word  "Supprimer un mot en avant"
   :command.editor/forward-word  "Déplacer le curseur d'un mot en avant"
   :command.editor/highlight  "Surlignage"
   :command.editor/insert-link  "Lien HTML"
   :command.editor/insert-youtube-timestamp  "Insérer un horodatage YouTube"
   :command.editor/italics  "Italique"
   :command.editor/kill-line-after  "Effacer la ligne après position du curseur"
   :command.editor/kill-line-before  "Effacer la ligne avant la position du curseur"
   :command.editor/left  "Déplacer le curseur à gauche / Ouvrir au début du bloc sélectionné"
   :command.editor/new-whiteboard  "Nouveau tableau blanc"
   :command.editor/open-edit  "Modifier le bloc sélectionné"
   :command.editor/open-file-in-default-app  "Ouvrir le fichier dans l'application par défaut"
   :command.editor/open-file-in-directory  "Montrer le fichier dans son dossier parent"
   :command.editor/paste-text-in-one-block-at-point  "Coller le texte dans un bloc"
   :command.editor/redo  "Refaire"
   :command.editor/replace-block-reference-at-point  "Remplacer la référence d'un bloc par son contenu"
   :command.editor/right  "Déplacer le curseur à droite / Ouvrir à la fin du bloc sélectionné"
   :command.editor/select-down  "Sélectionner le contenu en dessous"
   :command.editor/select-up  "Sélectionner le contenu au dessus"
   :command.editor/strike-through  "Barrer"
   :command.editor/toggle-open-blocks  "Basculer l'ouverture des blocs (réduit ou ouvre tous les blocs)"
   :command.editor/undo  "Annuler"
   :command.editor/up  "Déplacer le curseur vers le haut / Sélectionner au dessus"
   :command.go/all-graphs  "Aller vers tous les graphes"
   :command.go/all-pages  "Aller vers toutes les pages"
   :command.go/backward  "En arrière"
   :command.go/electron-find-in-page  "Chercher du texte dans une page"
   :command.go/electron-jump-to-the-next  "Aller vers le résultat de recherche suivant"
   :command.go/electron-jump-to-the-previous  "Aller vers le résultat de recherche précédent"
   :command.go/flashcards  "Basculer les cartes-mémoire"
   :command.go/forward  "En avant"
   :command.go/graph-view  "Aller vers la vue en graphe"
   :command.go/home  "Aller vers l'accueil"
   :command.go/keyboard-shortcuts  "Aller vers les raccourcis clavier"
   :command.go/next-journal  "Aller au journal suivant"
   :command.go/prev-journal  "Aller au journal précédent"
   :command.go/search-in-page  "Rechercher des blocs dans la page"
   :command.go/tomorrow  "Aller vers demain"
   :command.go/whiteboards  "Aller vers les tableaux blancs"
   :command.graph/add  "Ajouter un graphe"
   :command.graph/export-as-html  "Exporter les pages publiques du graphe en HTML"
   :command.graph/open  "Sélectionner un graphe à ouvrir"
   :command.graph/re-index  "Réindexer le graph actuel"
   :command.graph/remove  "Retirer un graphe"
   :command.graph/save  "Enregistrer le graphe sur le disque"
   :command.misc/copy  "mod+c"
   :command.pdf/close  "PDF: Fermer le document PDF"
   :command.pdf/find  "PDF: Rechercher du texte dans le document"
   :command.pdf/next-page  "PDF: Page suivante du document en cours"
   :command.pdf/previous-page  "PDF: Page précédente du document en cours"
   :command.search/re-index  "Reconstruire l'index de recherche"
   :command.sidebar/clear  "Vider intégralement la barre latérale droite"
   :command.sidebar/open-today-page  "Ouvrir la page du jour dans la barre latérale droite"
   :command.ui/goto-plugins  "Aller vers le panneau des extensions"
   :command.ui/install-plugins-from-file  "Installer les extensions depuis plugins.edn"
   :command.ui/select-theme-color  "Sélectionner les couleurs disponibles du thème"
   :command.ui/toggle-brackets  "Basculer l'affichage des crochets"
   :command.ui/toggle-cards  "Basculer l'affichage des cartes"
   :command.ui/toggle-contents  "Basculer l'affichage du contenu dans la barre latérale"
   :command.ui/toggle-left-sidebar  "Basculer la barre latérale gauche"
   :command.ui/toggle-settings  "Basculer l'affichage des réglages"
   :command.ui/toggle-wide-mode  "Basculer le vue en pleine largeur"
   :shortcut.category/basics  "Bases"
   :shortcut.category/block-command-editing  "Édition de commande de bloc"
   :shortcut.category/block-editing  "Édition de bloc en générale"
   :shortcut.category/block-selection  "Sélection de bloc (appuyer sur Esc pour quitter la sélection)"
   :shortcut.category/navigating  "Navigation"
   :shortcut.category/others  "Autres"
   :shortcut.category/toggle  "Basculer"
   :command.editor/select-parent "Sélectionnez le bloc parent"
   :command.sidebar/close-top "Ferme l'élément supérieur dans la barre latérale droite"})
