(ns frontend.modules.shortcut.dicts.it
  "Provides dictionary entries for shortcuts in IT")

(def dict
  {:command.date-picker/complete         "Selettore data: scegli il giorno selezionato"
   :command.date-picker/prev-day         "Selettore data: Seleziona il giorno precedente"
   :command.date-picker/next-day         "Selettore data: Seleziona il giorno successivo"
   :command.date-picker/prev-week        "Selettore data: Seleziona la settimana precedente"
   :command.date-picker/next-week        "Selettore data: Seleziona la settimana successiva"
   :command.pdf/previous-page            "Pagina precedente del pdf corrente"
   :command.pdf/next-page                "Pagina successiva del pdf corrente"
   :command.auto-complete/complete       "Auto completamento: Scegli l'oggetto selezionato"
   :command.auto-complete/prev           "Auto completamento: Seleziona l'oggetto precedente"
   :command.auto-complete/next           "Auto completamento: Seleziona l'oggetto successivo"
   :command.auto-complete/shift-complete "Auto completamento: Apri l'oggetto selezionato nella barra laterale"
   :command.auto-complete/open-link      "Auto completamento: Apri l'oggetto selezionato nel browser"
   :command.cards/toggle-answers         "Carte: mostra/nascondi risposte/chiusure"
   :command.cards/next-card              "Carte: prossima carta"
   :command.cards/forgotten              "Carte: dimenticato"
   :command.cards/remembered             "Carte: ricordato"
   :command.cards/recall                 "Carte: ci ho messo un pò a ricordarlo"
   :command.editor/escape-editing        "Esci dalla modifica"
   :command.editor/backspace             "Tasto Backspace / Cancella all'indietro"
   :command.editor/delete                "Tasto Delete / Cancella avanti"
   :command.editor/new-block             "Crea un nuovo blocco"
   :command.editor/new-line              "Nuova riga accapo nel blocco attuale"
   :command.editor/follow-link           "Segui il link sotto al cursore"
   :command.editor/open-link-in-sidebar  "Apri il link nella barra laterale"
   :command.editor/bold                  "Grassetto"
   :command.editor/italics               "Corsivo"
   :command.editor/highlight             "Evidenzia"
   :command.editor/strike-through        "Barrato"
   :command.editor/clear-block           "Elimina l'intero contenuto del blocco"
   :command.editor/kill-line-before      "Cancella la riga prima della posizione del cursore"
   :command.editor/kill-line-after       "Cancella la riga dopo la posizione del cursore"
   :command.editor/beginning-of-block    "Muovi il cursore all'inizio di un blocco"
   :command.editor/end-of-block          "Muovi il cursore alla fine di un blocco"
   :command.editor/forward-word          "Muovi il cursore in avanti di una parola"
   :command.editor/backward-word         "Muovi il cursore all'indietro di una parola"
   :command.editor/forward-kill-word     "Elimina una parola in avanti"
   :command.editor/backward-kill-word    "Elimina una parola all'indietro"
   :command.editor/replace-block-reference-at-point "Sostituisci il riferimento di blocco con il suo contenuto al punto"
   :command.editor/paste-text-in-one-block-at-point "Incolla testo in un blocco al punto"
   :command.editor/insert-youtube-timestamp         "Inserisci marca temporale di youtube"
   :command.editor/cycle-todo              "Cicla lo stato TODO dell'elemento corrente"
   :command.editor/up                      "Muovi il cursore sopra / Seleziona sopra"
   :command.editor/down                    "Muovi il cursore sotto / Seleziona sotto"
   :command.editor/left                    "Muovi il cursore a sinistra / Apri il blocco selezionato all'inizio"
   :command.editor/right                   "Muovi il cursore a destra / Apri il blocco selezionato all'inizio"
   :command.editor/select-up               "Seleziona il contenuto sopra"
   :command.editor/select-down             "Seleziona il contenuto sotto"
   :command.editor/move-block-up           "Muovi il blocco sopra"
   :command.editor/move-block-down         "Muovi il blocco sotto"
   :command.editor/open-edit               "Modifica il blocco selezionato"
   :command.editor/select-block-up         "Seleziona blocco sopra"
   :command.editor/select-block-down       "Seleziona blocco sotto"
   :command.editor/delete-selection        "Elimina i blocchi selezionati"
   :command.editor/expand-block-children   "Espandi"
   :command.editor/collapse-block-children "Collassa"
   :command.editor/indent                  "Rientra blocco"
   :command.editor/outdent                 "Annulla il rientro blocco"
   :command.editor/copy                    "Copia (copia una selezione o un riferimento di blocco)"
   :command.editor/cut                     "Taglia"
   :command.editor/undo                    "Annulla"
   :command.editor/redo                    "Rifai"
   :command.editor/insert-link             "Link HTML"
   :command.editor/select-all-blocks       "Seleziona tutti i blocchi"
   :command.editor/zoom-in                 "Ingrandisci blocco di modifica / Avanti altrimenti"
   :command.editor/zoom-out                "Rimpicciolisci il blocco di modifica / Indietro altrimenti"
   :command.ui/toggle-brackets             "Selezionare se visualizzare le parentesi"
   :command.go/search-in-page              "Cerca nella pagina attuale"
   :command.go/search                      "Ricerca testo completo"
   :command.go/journals                    "Vai ai diari"
   :command.go/backward                    "Indietro"
   :command.go/forward                     "Avanti"
   :command.search/re-index                "Ricostruisci indice di ricerca"
   :command.sidebar/open-today-page        "Apri la pagina di oggi nella barra laterale destra"
   :command.sidebar/clear                  "Pulisci tutto nella barra laterale destra"
   :command.misc/copy                      "mod+c"
   :command.command-palette/toggle         "Attiva/disattiva tavolozza comandi"
   :command.graph/open                     "Seleziona il diagramma da aprire"
   :command.graph/remove                   "Rimuovi un diagramma"
   :command.graph/add                      "Aggiungi un diagramma"
   :command.graph/save                     "Salva il diagramma corrente su disco"
   :command.command/run                    "Esegui comando git"
   :command.go/home                        "Vai all'inizio"
   :command.go/all-pages                   "Vai a tutte le pagine"
   :command.go/graph-view                  "Vai alla visualizzazione diagramma"
   :command.go/keyboard-shortcuts          "Vai alle scorciatoie da tastiera"
   :command.go/tomorrow                    "Vai a domani"
   :command.go/next-journal                "Vai al prossimo diario"
   :command.go/prev-journal                "Vai al diario precedente"
   :command.go/flashcards                  "Attiva/disattiva carte flash"
   :command.ui/toggle-document-mode        "Attiva/disattiva modalità documento"
   :command.ui/toggle-settings             "Attiva/disattiva impostazioni"
   :command.ui/toggle-right-sidebar        "Attiva/disattiva barra laterale destra"
   :command.ui/toggle-left-sidebar         "Attiva/disattiva barra laterale sinistra"
   :command.ui/toggle-help                 "Attiva/disattiva aiuto"
   :command.ui/toggle-theme                "Passa dal tema scuro a quello chiaro"
   :command.ui/toggle-contents             "Attiva/disattiva i contenuti nella barra laterale"
             ;;  :command.ui/open-new-window             "Apri un'altra finestra"
   :command.command/toggle-favorite        "Aggiungi a/rimuovi dai preferiti"
   :command.editor/open-file-in-default-app "Apri file nell'app predefinita"
   :command.editor/open-file-in-directory   "Apri file nella directory principale"
   :command.editor/copy-current-file        "Copia file corrente"
   :command.ui/toggle-wide-mode             "Attiva/disattiva modalità ampia"
   :command.ui/select-theme-color           "Seleziona i colori del tema disponibili"
   :command.ui/goto-plugins                 "Vai alla dashboard dei plugin"
   :command.editor/toggle-open-blocks       "Attiva/disattiva i blocchi aperti (comprimi o espandi tutti i blocchi)"
   :command.ui/toggle-cards                 "Attiva/disattiva le carte"
   :command.git/commit                      "Git messaggio di commit"
   :shortcut.category/basics                "Nozioni di base"
   :shortcut.category/formatting            "Formattazione"
   :shortcut.category/navigating            "Navigazione"
   :shortcut.category/block-editing         "Modiifica blocco generale"
   :shortcut.category/block-command-editing "Modifica comandi blocco"
   :shortcut.category/block-selection       "Selezione blocco (premi Esc per uscire dalla selezione)"
   :shortcut.category/toggle                "Attiva/disattiva"
   :shortcut.category/others                "Altri"
   :command.editor/copy-embed               "Copia un incorporamento di blocco che punta al blocco corrente"
   :command.editor/copy-text                "Copia le selezioni come testo"
   :command.pdf/close                       "Chiudi anteprima PDF"})
