(ns frontend.modules.shortcut.dicts.ja
  "Provides dictionary entries for shortcuts in JA")

(def dict
  {:shortcut.category/formatting            "フォーマット"
   :shortcut.category/basics                "基本操作"
   :shortcut.category/navigating            "ナビゲーション"
   :shortcut.category/block-editing         "ブロック単位の編集"
   :shortcut.category/block-command-editing "ブロック内の編集"
   :shortcut.category/block-selection       "ブロック選択"
   :shortcut.category/toggle                "トグル"
   :shortcut.category/others                "その他"
   :command.editor/indent                   "インデント"
   :command.editor/outdent                  "アウトデント"
   :command.editor/move-block-up            "ブロックを上へ移動"
   :command.editor/move-block-down          "ブロックを下へ移動"
   :command.editor/new-block                "新しいブロック"
   :command.editor/new-line                 "新しい行"
   :command.editor/new-whiteboard           "新しいホワイトボード"
   :command.editor/zoom-in                  "ズームイン"
   :command.editor/zoom-out                 "ズームアウト"
   :command.editor/follow-link              "リンクを開く"
   :command.editor/open-link-in-sidebar     "サイドバーでリンクを開く"
   :command.editor/expand-block-children    "子ブロックを展開"
   :command.editor/collapse-block-children  "子ブロックを折り畳み"
   :command.editor/select-block-up          "上のブロックを選択"
   :command.editor/select-block-down        "下のブロックを選択"
   :command.editor/select-all-blocks        "全てのブロックを選択"
   :command.editor/replace-block-reference-at-point        "この場所でブロック参照をそのコンテンツで置き換え"
   :command.editor/paste-text-in-one-block-at-point        "カーソル位置へ文字列として貼り付け"
   :command.ui/toggle-help                  "ヘルプのトグル"
   :command.git/commit                      "Git コミットする"
   :command.go/search                       "検索"
   :command.go/backward                     "戻る"
   :command.go/forward                      "前へ"
   :command.go/flashcards                   "フラッシュカードのトグル"
   :command.go/home                         "ホームへ移動"
   :command.go/all-graphs                   "全グラフへ移動"
   :command.go/whiteboards                  "ホワイトボードへ移動"
   :command.go/all-pages                    "全ページへ移動"
   :command.go/graph-view                   "グラフビューへ移動"
   :command.go/tomorrow                     "明日へ移動"
   :command.go/next-journal                 "次の日誌へ移動"
   :command.go/prev-journal                 "前の日誌へ移動"
   :command.go/keyboard-shortcuts           "キーボードショートカットへ移動"
             ;;  :command.ui/open-new-window              "別のウィンドウを開く"
   :command.go/search-in-page               "ページ内を検索"
   :command.go/electron-find-in-page        "ページ内で文字列検索"
   :command.go/electron-jump-to-the-next   "文字列検索で次を検索"
   :command.go/electron-jump-to-the-previous "文字列検索で前を検索"
   :command.ui/toggle-document-mode         "ドキュメントモードのトグル"
   :command.ui/toggle-contents              "目次のトグル"
   :command.ui/toggle-theme                 "テーマのトグル"
   :command.ui/toggle-right-sidebar         "右サイドバーのトグル"
   :command.ui/toggle-settings              "トグル設定"
   :command.go/journals                     "日誌"
   :command.ui/toggle-wide-mode             "ワイドモードのトグル"
   :command.ui/toggle-brackets              "ブラケット表示On/Offのトグル"
   :command.search/re-index                 "インデックス再構築"
   :command.editor/bold                     "太字"
   :command.editor/italics                  "斜体"
   :command.editor/insert-link              "リンク挿入"
   :command.editor/highlight                "ハイライト"
   :command.editor/undo                     "元に戻す"
   :command.editor/redo                     "やり直し"
   :command.editor/copy                     "コピー"
   :command.editor/copy-text                "選択範囲を文字列としてコピー"
   :command.editor/cut                      "切り取り"
   :command.editor/up                       "カーソル上移動 / 上を選択"
   :command.editor/down                     "カーソル下移動 / 下を選択"
   :command.editor/left                     "カーソル左移動 / 左を選択"
   :command.editor/right                    "カーソル右移動 / 右を選択"
   :command.editor/select-up                "上のコンテンツを選ぶ"
   :command.editor/select-down              "下のコンテンツを選ぶ"
   :command.editor/backspace                "前の文字を削除"
   :command.editor/delete                   "次の文字を削除"
   :command.editor/cycle-todo               "現在の項目の TODO 状態をローテートさせる"
   :command.editor/clear-block              "ブロックをクリア"
   :command.editor/kill-line-before         "行中のカーソル位置から前を削除"
   :command.editor/copy-embed               "現在のブロックを指すブロック埋め込みをコピーする"
   :command.editor/kill-line-after          "行中のカーソル位置から先を削除"
   :command.editor/beginning-of-block       "カーソルをブロックのはじめへ移動"
   :command.editor/end-of-block             "カーソルをブロックの最後へ移動"
   :command.editor/forward-word             "カーソルを次の単語へ移動"
   :command.editor/backward-word            "カーソルを前の単語へ移動"
   :command.editor/forward-kill-word        "次の単語を削除"
   :command.editor/backward-kill-word       "前の単語を削除"
   :command.editor/open-edit                "選択したブロックを編集"
   :command.editor/delete-selection         "選択したブロックを削除"
   :command.editor/toggle-open-blocks       "ブロック展開のトグル（全てのブロックを折りたたみ／展開）"
   :command.ui/toggle-cards                 "フラッシュカードのトグル"
   :command.ui/toggle-left-sidebar          "左サイドバーのトグル"
   :command.pdf/next-page                   "PDF: 現在のPDF文書で次のページへ"
   :command.pdf/previous-page               "PDF: 現在のPDF文書で前のページへ"
   :command.pdf/close                       "PDF: 現在のPDF文書を閉じる"
   :command.pdf/find                        "PDF: 現在のPDF文書を検索"
   :command.command/run                             "Git コマンドを実行"
   :command.command-palette/toggle                  "コマンドパレットのトグル"
   :command.graph/export-as-html           "公開グラフのページをHTMLとしてエクスポート"
   :command.graph/open                              "グラフを選択して開く"
   :command.graph/remove                            "グラフを削除"
   :command.graph/add                               "グラフを追加"
   :command.graph/save                              "現在のグラフをディスクへ保存"
   :command.graph/re-index                 "現在のグラフを再構築"
   :command.sidebar/clear                           "右サイドバーの内容を全てクリア"
   :command.sidebar/open-today-page                 "今日の日誌を右サイドバーで開く"
   :command.sidebar/close-top              "右サイドバーの一番上の項目を閉じる"
   :command.editor/insert-youtube-timestamp         "YouTubeのタイプスタンプを挿入"
   :command.auto-complete/complete                  "自動補完：項目を選択"
   :command.auto-complete/prev                      "自動補完：前の項目を選択"
   :command.auto-complete/next                      "自動補完：次の項目を選択"
   :command.auto-complete/shift-complete            "自動補完：選択した項目をサイドバーで開く"
   :command.auto-complete/open-link                 "自動補完：選択したアイテムをブラウザで開く"
   :command.date-picker/complete                    "日付選択：選択した日で決定"
   :command.date-picker/prev-day                    "日付選択：前の日を選ぶ"
   :command.date-picker/next-day                    "日付選択：次の日を選ぶ"
   :command.date-picker/prev-week                   "日付選択：前の週を選ぶ"
   :command.date-picker/next-week                   "日付選択：次の週を選ぶ"
   :command.cards/forgotten                         "カード：忘れられた"
   :command.cards/next-card                         "カード：次のカード"
   :command.cards/recall                            "カード：思い出すのに時間がかかる"
   :command.cards/remembered                        "カード：覚えている"
   :command.cards/toggle-answers                    "カード：答えや穴埋めの表示／隠すのトグル"
   :command.command/toggle-favorite                 "お気に入りへの追加／削除のトグル"
   :command.editor/copy-current-file                "現在のファイルをコピー"
   :command.editor/escape-editing                   "編集をやめる"
   :command.editor/open-file-in-default-app         "ファイルを規定のアプリで開く"
   :command.editor/open-file-in-directory           "ファイルをディレクトリで開く"
   :command.editor/strike-through                   "打ち消し線"
   :command.misc/copy                               "コピー"
   :command.ui/goto-plugins                         "プラグインへ"
   :command.ui/select-theme-color                   "利用可能なテーマ色を選択"})
