(ns frontend.modules.shortcut.dicts.ko
  "Provides dictionary entries for shortcuts in KO")

(def dict
  {:shortcut.category/formatting             "포맷"
   :shortcut.category/basics                "기본 동작"
   :shortcut.category/navigating            "내비게이션"
   :shortcut.category/block-editing         "블록 편집"
   :shortcut.category/block-command-editing "블록 내부 편집"
   :shortcut.category/block-selection       "블록 선택"
   :shortcut.category/toggle                "토글"
   :shortcut.category/others                "기타"
   :command.editor/indent                   "들여쓰기"
   :command.editor/outdent                  "내어쓰기"
   :command.editor/move-block-up            "위로 블록 이동"
   :command.editor/move-block-down          "아래로 블록 이동"
   :command.editor/new-block                "새 블록"
   :command.editor/new-line                 "새 줄"
   :command.editor/zoom-in                  "확대"
   :command.editor/zoom-out                 "축소"
   :command.editor/follow-link              "링크 열기"
   :command.editor/open-link-in-sidebar     "사이드바에서 링크 열기"
   :command.editor/expand-block-children    "하위 블록 열기"
   :command.editor/collapse-block-children  "하위 블록 닫기"
   :command.editor/select-block-up          "위 블록 선택"
   :command.editor/select-block-down        "아래 블록 선택"
   :command.editor/select-all-blocks        "모든 블록 선택"
   :command.editor/replace-block-reference-at-point        "블록 참조를 해당 콘텐츠로 변경"
   :command.editor/paste-text-in-one-block-at-point        "현재 위치에 텍스트를 붙여넣기"
   :command.ui/toggle-help                  "도움말 토글"
   :command.git/commit                      "커밋"
   :command.go/search                       "검색으로 이동"
   :command.go/backward                     "뒤로 이동"
   :command.go/forward                      "앞으로 이동"
   :command.go/flashcards                   "플래시 카드로 이동"
   :command.go/home                         "홈으로 이동"
   :command.go/all-pages                    "모든 페이지로 이동"
   :command.go/graph-view                   "그래프 뷰로 이동"
   :command.go/tomorrow                     "내일로 이동"
   :command.go/next-journal                 "다음 일지로 이동"
   :command.go/prev-journal                 "이전 일지로 이동"
   :command.go/keyboard-shortcuts           "키보드 단축키로 이동"
             ;;  :command.ui/open-new-window              "새 창 열기"
   :command.go/search-in-page               "페이지 안에서 검색"
   :command.ui/toggle-document-mode         "문서 모드 토글"
   :command.ui/toggle-contents              "목차 토글"
   :command.ui/toggle-theme                 "테마 토글"
   :command.ui/toggle-right-sidebar         "오른쪽 사이드바 토글"
   :command.ui/toggle-settings              "설정 토글"
   :command.go/journals                     "일지로 이동"
   :command.ui/toggle-wide-mode             "와이드 모드 토글"
   :command.ui/toggle-brackets              "대괄호 토글"
   :command.search/re-index                 "다시 인덱스하기"
   :command.editor/bold                     "볼드체"
   :command.editor/italics                  "이탤릭체"
   :command.editor/insert-link              "링크 삽입"
   :command.editor/highlight                "하이라이트"
   :command.editor/undo                     "실행 취소"
   :command.editor/redo                     "다시 실행"
   :command.editor/copy                     "복사"
   :command.editor/cut                      "잘라내기"
   :command.editor/up                       "위로 이동"
   :command.editor/down                     "아래로 이동"
   :command.editor/left                     "왼쪽으로 이동"
   :command.editor/right                    "오른쪽으로 이동"
   :command.editor/select-up                "위 콘텐츠 선택"
   :command.editor/select-down              "아래 콘텐츠 선택"
   :command.editor/backspace                "이전 문자 삭제"
   :command.editor/delete                   "다음 문자 삭제"
   :command.editor/cycle-todo               "할 일 돌아보기"
   :command.editor/clear-block              "블록 클리어"
   :command.editor/kill-line-before         "이전 줄 삭제"
   :command.editor/kill-line-after          "다음 줄 삭제"
   :command.editor/beginning-of-block       "블록 시작으로 이동"
   :command.editor/end-of-block             "블록 끝으로 이동"
   :command.editor/forward-word             "다음 단어로 이동"
   :command.editor/backward-word            "이전 단어로 이동"
   :command.editor/forward-kill-word        "다음 단어 삭제"
   :command.editor/backward-kill-word       "이전 단어 삭제"
   :command.editor/open-edit                "선택한 블록 편집"
   :command.editor/delete-selection         "선택한 블록 삭제"
   :command.editor/toggle-open-blocks       "열린 블록 토글"
   :command.ui/toggle-cards                 "플래시 카드 토글"
   :command.ui/toggle-left-sidebar          "왼쪽 사이드바 토글"
   :command.pdf/next-page                   "다음 페이지"
   :command.pdf/previous-page               "이전 페이지"
   :command.command/run                             "Git 명령 실행"
   :command.command-palette/toggle                  "명령 팔레트 토글"
   :command.graph/open                              "그래프 열기"
   :command.graph/remove                            "그래프 제거"
   :command.graph/add                               "그래프 추가"
   :command.graph/save                              "그래프 저장"
   :command.sidebar/clear                           "사이드바 클리어"
   :command.sidebar/open-today-page                 "오늘의 일지를 사이드바에서 열기"
   :command.editor/insert-youtube-timestamp         "YouTube 타임스탬프 삽입"
   :command.auto-complete/complete                  "항목 선택"
   :command.auto-complete/prev                      "이전 항목 선택"
   :command.auto-complete/next                      "다음 항목 선택"
   :command.auto-complete/shift-complete            "선택 항목 열기"
   :command.auto-complete/open-link                 "링크 열기"
   :command.date-picker/complete                    "선택한 날짜로 이동"
   :command.date-picker/prev-day                    "이전 날짜로 이동"
   :command.date-picker/next-day                    "다음 날짜로 이동"
   :command.date-picker/prev-week                   "이전 주로 이동"
   :command.date-picker/next-week                   "다음 주로 이동"
   :command.cards/forgotten                         "잊은 카드"
   :command.cards/next-card                         "다음 카드"
   :command.cards/recall                            "기억이 잘 안 난 카드"
   :command.cards/remembered                        "기억한 카드"
   :command.cards/toggle-answers                    "정답 토글"
   :command.command/toggle-favorite                 "즐겨찾기 토글"
   :command.editor/copy-current-file                "현재 파일 복사"
   :command.editor/escape-editing                   "편집 나가기"
   :command.editor/open-file-in-default-app         "기본 앱으로 파일 열기"
   :command.editor/open-file-in-directory           "파일 위치 열기"
   :command.editor/strike-through                   "취소선"
   :command.misc/copy                               "복사"
   :command.ui/goto-plugins                         "플러그인 페이지로 이동"
   :command.ui/select-theme-color                   "테마 색상 선택"
   :command.editor/copy-text                        "선택한 영역을 텍스트로 복사"
   :command.pdf/close                               "PDF 닫기"
   :command.dev/show-block-ast                      "(개발자) 블록 AST 보기"
   :command.dev/show-block-data                     "(개발자) 블록 데이터 보기"
   :command.dev/show-page-ast                       "(개발자) 페이지 AST 보기"
   :command.dev/show-page-data                      "(개발자) 페이지 데이터 보기"
   :command.editor/copy-embed                       "현재 블록의 블록 임베드 복사"
   :command.editor/new-whiteboard                   "새 화이트보드"
   :command.editor/select-parent                    "부모 블록 선택"
   :command.go/all-graphs                           "모든 그래프로 이동"
   :command.go/electron-find-in-page                "페이지에서 검색"
   :command.go/electron-jump-to-the-next            "다음 검색 항목으로 디오"
   :command.go/electron-jump-to-the-previous        "이전 검색 항목으로 이동"
   :command.go/whiteboards                          "화이트보드로 이동"
   :command.graph/export-as-html                    "그래프를 html로 내보내기"
   :command.graph/re-index                          "현재 그래프 인덱스 재생성"
   :command.pdf/find                                "PDF: 현재 PDF 문서에서 검색"
   :command.sidebar/close-top                       "우축 사이드바의 최상단 항목 닫기"
   :command.ui/clear-all-notifications              "모든 알람 제거"
   :command.ui/install-plugins-from-file            "plugins.edn에서 플러그인 설치"})
