(ns frontend.modules.shortcut.dicts.nl
  "Provides dictionary entries for shortcuts in NL")

(def dict
  {:command.auto-complete/complete         "Automatisch aanvullen: Kies geselecteerd item"
   :command.auto-complete/next             "Automatisch aanvullen: Selecteer volgend item"
   :command.auto-complete/open-link        "Automatisch aanvullen: Open geselecteerd item in browser"
   :command.auto-complete/prev             "Automatisch aanvullen: Selecteer vorig item"
   :command.auto-complete/shift-complete   "Automatisch aanvullen: Open geselecteerd item in zijbalk"
   :command.cards/forgotten                "Kaarten: vergeten"
   :command.cards/next-card                "Kaarten: volgende kaart"
   :command.cards/recall                   "Kaarten: het duurt even om terug te roepen"
   :command.cards/remembered               "Kaarten: herinnerd"
   :command.cards/toggle-answers           "Kaarten: toon/verberg antwoorden/clozes"
   :command.command/run                    "Voer git commando uit"
   :command.command/toggle-favorite        "Toevoegen aan/verwijderen uit favorieten"
   :command.command-palette/toggle         "Schakel commando lijn"
   :command.date-picker/complete           "Datumkiezer: Kies de geselecteerde dag"
   :command.date-picker/next-day           "Datumkiezer: Volgende dag kiezen"
   :command.date-picker/next-week          "Datumkiezer: Volgende week kiezen"
   :command.date-picker/prev-day           "Datumkiezer: Vorige dag kiezen"
   :command.date-picker/prev-week          "Datumkiezer: Vorige week kiezen"
   :command.editor/backspace               "Backspace / Achteruit wissen"
   :command.editor/backward-kill-word      "Een woord achterwaarts wissen"
   :command.editor/backward-word           "Verplaats de cursor een woord achteruit"
   :command.editor/beginning-of-block      "Verplaats de cursor naar het begin van een blok"
   :command.editor/bold                    "Vet"
   :command.editor/clear-block             "Wis volledige blokinhoud"
   :command.editor/collapse-block-children "Samenvouwen"
   :command.editor/copy                    "Kopiëren (kopieert een selectie of een blokverwijzing)"
   :command.editor/copy-current-file       "Kopieer huidig bestand"
   :command.editor/copy-embed              "Kopieer een blok embed dat wijst naar het huidige blok"
   :command.editor/copy-text               "Kopieer selecties als tekst"
   :command.editor/cut                     "Knip"
   :command.editor/cycle-todo              "Draai de TODO status van het huidige item"
   :command.editor/delete                  "Verwijderen / verwijderen vooruit"
   :command.editor/delete-selection        "Verwijder geselecteerde blokken"
   :command.editor/down                    "Verplaats cursor omlaag / Selecteer omlaag"
   :command.editor/end-of-block            "Verplaats cursor naar het einde van een blok"
   :command.editor/escape-editing          "Klaar met bewerken"
   :command.editor/expand-block-children   "Openvouwen"
   :command.editor/follow-link             "Volg de link onder de cursor"
   :command.editor/forward-kill-word       "Een woord vooruit verwijderen"
   :command.editor/forward-word            "Verplaats de cursor een woord vooruit"
   :command.editor/highlight               "Markeer"
   :command.editor/indent                  "Blok inspringen"
   :command.editor/insert-link             "HTML Link"
   :command.editor/insert-youtube-timestamp "Voeg youtube tijdstempel toe"
   :command.editor/italics                 "Cursief"
   :command.editor/kill-line-after         "Verwijder regel na cursorpositie"
   :command.editor/kill-line-before        "Verwijder regel voor cursorpositie"
   :command.editor/left                    "Verplaats cursor naar links / Open geselecteerd blok bij het begin"
   :command.editor/move-block-down         "Verplaats blok omlaag"
   :command.editor/move-block-up           "Verplaats blok omhoog"
   :command.editor/new-block               "Maak nieuw blok"
   :command.editor/new-line                "Nieuwe regel in huidig blok"
   :command.editor/open-edit               "Bewerk geselecteerde blok"
   :command.editor/open-file-in-default-app "Open bestand in standaard app"
   :command.editor/open-file-in-directory  "Open bestand in bovenliggende map"
   :command.editor/open-link-in-sidebar    "Open link in zijbalk"
   :command.editor/outdent                 "Verminder blok inspringing"
   :command.editor/paste-text-in-one-block-at-point "Plak tekst in een blok op punt"
   :command.editor/redo                    "Herhaal"
   :command.editor/replace-block-reference-at-point "Vervang de blokverwijzing door de inhoud op punt"
   :command.editor/right                   "Beweeg cursor naar rechts / Open geselecteerd blok aan einde"
   :command.editor/select-all-blocks       "Selecteer alle blokken"
   :command.editor/select-block-down       "Selecteer blok hieronder"
   :command.editor/select-block-up         "Selecteer blok hierboven"
   :command.editor/select-down             "Selecteer inhoud hieronder"
   :command.editor/select-up               "Selecteer inhoud hierboven"
   :command.editor/strike-through          "Doorstrepen"
   :command.editor/toggle-open-blocks      "Toggle open blocks (open of dichtklappen van alle blokken)"
   :command.editor/undo                    "Ongedaan maken"
   :command.editor/up                      "Verplaats cursor omhoog / Selecteer omhoog"
   :command.editor/zoom-in                 "Zoom in bewerkingsblok / Vooruit anders"
   :command.editor/zoom-out                "Zoom uit bewerkingsblok / Achteruit anders"
   :command.git/commit                     "Maak git commit met bericht"
   :command.go/all-pages                   "Ga naar alle pagina's"
   :command.go/backward                    "Achteruit"
   :command.go/flashcards                  "Flashcards Toggle"
   :command.go/forward                     "Vooruit"
   :command.go/graph-view                  "Ga naar grafiekweergave"
   :command.go/home                        "Ga naar home"
   :command.go/journals                    "Ga naar journaals"
   :command.go/keyboard-shortcuts          "Ga naar sneltoetsen"
   :command.go/next-journal                "Ga naar volgende journaal"
   :command.go/prev-journal                "Ga naar vorige journaal"
   :command.go/search                      "Zoeken in volledige tekst"
   :command.go/search-in-page              "Zoeken in de huidige pagina"
   :command.go/tomorrow                    "Ga naar morgen"
   :command.graph/add                      "Voeg een grafiek toe"
   :command.graph/open                     "Selecteer grafiek om te openen"
   :command.graph/re-index                 "Huidige grafiek opnieuw indexeren"
   :command.graph/remove                   "Verwijder een grafiek"
   :command.graph/save                     "Huidige grafiek opslaan op schijf"
   :command.misc/copy                      "Kopieer"
   :command.pdf/close                      "Huidige pdf-viewer sluiten"
   :command.pdf/next-page                  "Volgende pagina van huidige pdf doc"
   :command.pdf/previous-page              "Vorige pagina van huidige pdf doc"
   :command.search/re-index                "Bouw zoekindex opnieuw op"
   :command.sidebar/clear                  "Wis alles in de rechter zijbalk"
   :command.sidebar/open-today-page        "Open de pagina van vandaag in de rechter zijbalk"
   :command.ui/goto-plugins                "Ga naar plugins dashboard"
   :command.ui/select-theme-color          "Selecteer beschikbare themakleuren"
   :command.ui/toggle-brackets             "Toggle tussen het weergeven van beugels"
   :command.ui/toggle-cards                "Toggle kaarten"
   :command.ui/toggle-contents             "Toggle inhoud in zijbalk"
   :command.ui/toggle-document-mode        "Schakel tussen documentmodus"
   :command.ui/toggle-help                 "Toggle help"
   :command.ui/toggle-left-sidebar         "Toggle linker zijbalk"
   :command.ui/toggle-right-sidebar        "Toggle rechter zijbalk"
   :command.ui/toggle-settings             "Toggle settings"
   :command.ui/toggle-theme                "Toggle tussen donker/licht thema"
   :command.ui/toggle-wide-mode            "Toggle brede modus"
   :shortcut.category/basics               "Basis"
   :shortcut.category/block-command-editing "Blokcommando's bewerken"
   :shortcut.category/block-editing        "Blokbewerking algemeen"
   :shortcut.category/block-selection      "Blokselectie (druk op Esc om selectie te beëindigen)"
   :shortcut.category/formatting           "Formatteren"
   :shortcut.category/navigating           "Navigatie"
   :shortcut.category/others               "Anderen"
   :shortcut.category/toggle               "Toggle"})
