(ns frontend.modules.shortcut.dicts.sk
  "Provides dictionary entries for shortcuts in SK")

(def dict
  {:shortcut.category/formatting                             "Formátovanie"
   :shortcut.category/basics                                 "Základy"
   :shortcut.category/navigating                             "Navigácia"
   :shortcut.category/block-editing                          "Úprava bloku (všeobecné)"
   :shortcut.category/block-command-editing                  "Príkazy na úpravu bloku"
   :shortcut.category/block-selection                        "Výber bloku (výber ukončíte stlačením klávesy Esc)"
   :shortcut.category/toggle                                 "Prepínače"
   :shortcut.category/others                                 "Ostatné"

   :command.date-picker/complete                             "Výber dátumu: podvrďte vybraný deň"
   :command.date-picker/next-day                             "Výber dátumu: vyberte nasledujúci deň"
   :command.date-picker/next-week                            "Výber dátumu: vyberte nasledujúci týždeň"
   :command.date-picker/prev-day                             "Výber dátumu: vyberte predchádzajúci deň"
   :command.date-picker/prev-week                            "Výber dátumu: vyberte predchádzajúci týždeň"
   :command.pdf/previous-page                                "PDF: Predchádzajúca strana aktuálneho PDF dokumentu"
   :command.pdf/next-page                                    "PDF: Nasledujúca strana aktuálneho PDF dokumentu"
   :command.pdf/close                                        "PDF: Zatvoriť aktuálny PDF dokument"
   :command.pdf/find                                         "PDF: Vyhľadať text v aktuálnom pdf dokumente"
   :command.auto-complete/complete                           "Automatické dokončovanie: Potvrdiť vybranú položku"
   :command.auto-complete/prev                               "Automatické dokončovanie: Vybrať predchádzajúcu položku"
   :command.auto-complete/next                               "Automatické dokončovanie: Vybrať ďalšiu položku"
   :command.auto-complete/shift-complete                     "Automatické dokončovanie: Otvoriť vybranú položku na bočnom paneli"
   :command.auto-complete/open-link                          "Automatické dokončovanie: Otvoriť vybranú položku v prehliadači"
   :command.cards/toggle-answers                             "Karty: Zobraziť/Skryť odpovede"
   :command.cards/next-card                                  "Karty: Ďalšia karta"
   :command.cards/forgotten                                  "Karty: Zabudnuté"
   :command.cards/remembered                                 "Karty: Zapamätané"
   :command.cards/recall                                     "Karty: take a while to recall"
   :command.editor/escape-editing                            "Zrušiť editovanie"
   :command.editor/backspace                                 "Zmazať dozadu"
   :command.editor/delete                                    "Zmazať dopredu"
   :command.editor/new-block                                 "Vytvoriť nový blok"
   :command.editor/new-line                                  "Nový riadok v aktuálnom bloku"
   :command.editor/new-whiteboard                            "Nová tabuľa"
   :command.editor/follow-link                               "Prejsť na odkaz pod kurzorom"
   :command.editor/open-link-in-sidebar                      "Otvoriť odkaz v bočnom paneli"
   :command.editor/bold                                      "Tučné"
   :command.editor/italics                                   "Kurzíva"
   :command.editor/highlight                                 "Zvýrazniť"
   :command.editor/strike-through                            "Prečiarknuté"
   :command.editor/clear-block                               "Odstrániť celý obsah bloku"
   :command.editor/kill-line-before                          "Odstrániť riadok pred pozíciou kurzora"
   :command.editor/copy-embed                                "Kopírovať vložený blok ukazujúci na aktuálny blok"
   :command.editor/kill-line-after                           "Odstrániť riadok za pozíciou kurzora"
   :command.editor/beginning-of-block                        "Presunúť kurzor na začiatok bloku"
   :command.editor/end-of-block                              "Presunúť kurzor na koniec bloku"
   :command.editor/forward-word                              "Posunúť kurzor o slovo dopredu"
   :command.editor/backward-word                             "Presunúť kurzor o slovo dozadu"
   :command.editor/forward-kill-word                         "Vymazať slovo dopredu"
   :command.editor/backward-kill-word                        "Vymazať slovo dozadu"
   :command.editor/replace-block-reference-at-point          "Nahradiť referenciu bloku jeho obsahom v bode"
   :command.editor/paste-text-in-one-block-at-point          "Prilepiť text do jedného bloku v bode"
   :command.editor/insert-youtube-timestamp                  "Vložiť YouTube časovú značku"
   :command.editor/cycle-todo                                "Zmeniť stav TODO aktuálnej položky"
   :command.editor/up                                        "Posunúť kurzor nahor/Vybrať nahor"
   :command.editor/down                                      "Posunúť kurzor nadol/Vybrať nadol"
   :command.editor/left                                      "Posunúť kurzor doľava/Otvoriť vybraný blok na začiatku"
   :command.editor/right                                     "Posunúť kurzor doprava/Otvoriť vybraný blok na konci"
   :command.editor/select-up                                 "Vybrať obsah vyššie"
   :command.editor/select-down                               "Vybrať obsah nižšie"
   :command.editor/move-block-up                             "Posunúť blok nahor"
   :command.editor/move-block-down                           "Posunúť blok nadol"
   :command.editor/open-edit                                 "Upraviť vybraný blok"
   :command.editor/select-block-up                           "Vybrať blok vyššie"
   :command.editor/select-block-down                         "Vybrať blok nižšie"
   :command.editor/delete-selection                          "Odstrániť vybrané bloky"
   :command.editor/expand-block-children                     "Rozbaliť"
   :command.editor/collapse-block-children                   "Zbaliť"
   :command.editor/indent                                    "Odsadiť blok"
   :command.editor/outdent                                   "Zrusiť odsadenie bloku"
   :command.editor/copy                                      "Kopírovať (skopíruje buď výber alebo referenciu na blok)"
   :command.editor/copy-text                                 "Kopírovať výber ako text"
   :command.editor/cut                                       "Vystrihnúť"
   :command.editor/undo                                      "Zrusiť zmenu"
   :command.editor/redo                                      "Znova"
   :command.editor/insert-link                               "HTML odkaz"
   :command.editor/select-all-blocks                         "Vybrať všetky bloky"
   :command.editor/select-parent                             "Vybrať rodičovský blok"
   :command.editor/zoom-in                                   "Priblížiť upravovaný blok/Inak vpred"
   :command.editor/zoom-out                                  "Oddialiť upravaný blok/Inak dozadu"
   :command.ui/toggle-brackets                               "Prepnúť, či sa majú zobraziť hranaté zátvorky"
   :command.go/search-in-page                                "Hľadať bloky na aktuálnej stránke"
   :command.go/electron-find-in-page                         "Nájsť text na stránke"
   :command.go/electron-jump-to-the-next                     "Preskočiť na ďalšiu zhodu s vyhľadávaním v Paneli hľadania"
   :command.go/electron-jump-to-the-previous                 "Preskočiť na predchádzajúcu zhodu s vyhľadávaním v Paneli hľadania"
   :command.go/search                                        "Hľadať stránky a bloky"
   :command.go/journals                                      "Choď do denníkov"
   :command.go/backward                                      "Späť"
   :command.go/forward                                       "Vpred"
   :command.search/re-index                                  "Obnoviť index vyhľadávania"
   :command.sidebar/open-today-page                          "Otvoriť dnešnú stránku v pravom bočnom paneli"
   :command.sidebar/close-top                                "Zavri hornú položku na pravom bočnom paneli"
   :command.sidebar/clear                                    "Vymazať všetko na pravom bočnom paneli"
   :command.misc/copy                                        "Kopírovať"
   :command.command-palette/toggle                           "Zobraziť/Skryť zoznam príkazov"
   :command.graph/export-as-html                             "Exportovať verejné stránky grafu ako HTML"
   :command.graph/open                                       "Vybrať graf na otvorenie"
   :command.graph/remove                                     "Odstrániť graf"
   :command.graph/add                                        "Pridať graf"
   :command.graph/save                                       "Uložiť aktuálny graf na disk"
   :command.graph/re-index                                   "Preindexovať aktuálny graf"
   :command.command/run                                      "Spustiť príkaz GIT"
   :command.go/home                                          "Prejsť na hlavnú stránku"
   :command.go/all-graphs                                    "Prejsť na všetky grafy"
   :command.go/whiteboards                                   "Prejsť na tabule"
   :command.go/all-pages                                     "Prejsť na všetky stránky"
   :command.go/graph-view                                    "Prejsť na zobrazenie grafu"
   :command.go/keyboard-shortcuts                            "Prejsť na klávesové skratky"
   :command.go/tomorrow                                      "Prejsť na zajtrajší denník"
   :command.go/next-journal                                  "Prejsť na ďalší denník"
   :command.go/prev-journal                                  "Prejsť na predchádzajúci denník"
   :command.go/flashcards                                    "Zobraziť/Skryť kartičky"
   :command.ui/toggle-document-mode                          "Zobraziť/Skryť režim dokumentu"
   :command.ui/toggle-settings                               "Prepnúť nastavenia"
   :command.ui/toggle-right-sidebar                          "Zobraziť/Skryť pravý bočný panel"
   :command.ui/toggle-left-sidebar                           "Zobraziť/Skryť ľavý bočný panel"
   :command.ui/toggle-help                                   "Zobraziť/Skryť pomocníka"
   :command.ui/toggle-theme                                  "Prepínať medzi tmavým/svetlým motívom"
   :command.ui/toggle-contents                               "Zobraziť/Skryť obsah na bočnom paneli"
   :command.command/toggle-favorite                          "Pridať/Odstrániť z obľúbených"
   :command.editor/open-file-in-default-app                  "Otvoriť súbor v predvolenej aplikácii"
   :command.editor/open-file-in-directory                    "Otvoriť súbor v nadradenom adresári"
   :command.editor/copy-current-file                         "Skopírovať aktuálny súbor"
   :command.ui/toggle-wide-mode                              "Prepnúť širokouhlý režim"
   :command.ui/select-theme-color                            "Vyberte dostupné farby motívu"
   :command.ui/goto-plugins                                  "Prejsť na zoznam doplnkov"
   :command.ui/install-plugins-from-file                     "Inštalovať doplnky z plugins.edn"
   :command.editor/toggle-open-blocks                        "Prepnúť otvorené bloky (zbaliť alebo rozbaliť všetky bloky)"
   :command.ui/toggle-cards                                  "Zobraziť/Skryť karty"
   :command.git/commit                                       "Spusiť príkaz git commit so správou"})
