(ns frontend.modules.shortcut.dicts.tr
  "Provides dictionary entries for shortcuts in TR")

(def dict
  {:shortcut.category/basics "Temel bilgiler"
   :shortcut.category/formatting "Biçimlendirme"
   :shortcut.category/navigating "Gezinme"
   :shortcut.category/block-editing "Genel blok düzenleme"
   :shortcut.category/block-command-editing "Blok düzenleme komutuları"
   :shortcut.category/block-selection "Blok seçimi (seçimden çıkmak için Esc tuşuna basın)"
   :shortcut.category/toggle "Aç/Kapat"
   :shortcut.category/whiteboard "Beyaz tahta"
   :shortcut.category/others "Diğer"
   :command.date-picker/complete         "Tarih seçici: Seçilen günü seç"
   :command.date-picker/prev-day         "Tarih seçici: Önceki günü seç"
   :command.date-picker/next-day         "Tarih seçici: Sonraki günü seç"
   :command.date-picker/prev-week        "Tarih seçici: Önceki haftayı seç"
   :command.date-picker/next-week        "Tarih seçici: Sonraki haftayı seç"
   :command.pdf/previous-page            "Pdf: Geçerli pdf belgesinin önceki sayfası"
   :command.pdf/next-page                "Pdf: Geçerli pdf belgesinin sonraki sayfası"
   :command.pdf/close                    "Pdf: Geçerli pdf görüntüleyiciyi kapat"
   :command.pdf/find                     "Pdf: Geçerli pdf belgesinde aranacak metin"
   :command.auto-complete/complete       "Otomatik tamamlama: Seçili öğeyi seç"
   :command.auto-complete/prev           "Otomatik tamamlama: Önceki öğeyi seç"
   :command.auto-complete/next           "Otomatik tamamlama: Sonraki öğeyi seç"
   :command.auto-complete/shift-complete "Otomatik tamamlama: Seçili öğeyi kenar çubuğunda aç"
   :command.auto-complete/open-link      "Otomatik tamamlama: Seçili öğeyi tarayıcıda aç"
   :command.cards/toggle-answers         "Kartlar: cevapları ve cümle tamamlamayı göster/gizle"
   :command.cards/next-card              "Kartlar: sonraki kart"
   :command.cards/forgotten              "Kartlar: unutuldu"
   :command.cards/remembered             "Kartlar: hatırlandı"
   :command.cards/recall                 "Kartlar: hatırlamak biraz zaman aldı"
   :command.editor/escape-editing        "Düzenlemeden çık"
   :command.editor/backspace             "Geri tuşu (Backspace) / Geriye doğru sil"
   :command.editor/delete                "Silme tuşu (Delete) / İleriye doğru sil"
   :command.editor/new-block             "Yeni blok oluştur"
   :command.editor/new-line              "Geçerli blokta yeni satır"
   :command.editor/new-whiteboard        "Yeni beyaz tahta"
   :command.editor/follow-link           "İmlecin altındaki bağlantıyı takip et"
   :command.editor/open-link-in-sidebar  "Bağlantıyı kenar çubuğunda aç"
   :command.editor/bold                  "Kalın"
   :command.editor/italics               "İtalik"
   :command.editor/highlight             "Vurgulu"
   :command.editor/strike-through        "Üstü çizili"
   :command.editor/clear-block           "Tüm blok içeriğini sil"
   :command.editor/kill-line-before      "İmleç konumundan önceki satırı sil"
   :command.editor/copy-embed            "Geçerli bloğu işaret eden bir blok eklemesi kopyala"
   :command.editor/kill-line-after       "İmleç konumundan sonraki satırı sil"
   :command.editor/beginning-of-block    "İmleci bir bloğun başına taşı"
   :command.editor/end-of-block          "İmleci bir bloğun sonuna taşı"
   :command.editor/forward-word          "İmleci bir kelime ileri götür"
   :command.editor/backward-word         "İmleci bir kelime geri götür"
   :command.editor/forward-kill-word     "İleriye doğru bir kelimeyi sil"
   :command.editor/backward-kill-word    "Geriye doğru bir kelimeyi sil"
   :command.editor/replace-block-reference-at-point "Blok referansını bu konumdaki içeriğiyle değiştirin"
   :command.editor/paste-text-in-one-block-at-point "İmleç konumunda metin olarak yapıştırın"
   :command.editor/insert-youtube-timestamp         "Youtube zaman damgası ekle"
   :command.editor/cycle-todo              "Geçerli öğenin TODO durumunu değiştir"
   :command.editor/up                      "İmleci yukarı taşı / Yukarıyı seç"
   :command.editor/down                    "İmleci aşağı taşı / Aşağı seç"
   :command.editor/left                    "İmleci sola hareket ettir / Seçili bloğu aç ve başına git"
   :command.editor/right                   "İmleci sağa hareket ettir / Seçili bloğu aç ve sonuna git"
   :command.editor/select-up               "Yukarıdaki içeriği seçin"
   :command.editor/select-down             "Aşağıdaki içeriği seçin"
   :command.editor/move-block-up           "Bloğu yukarı taşı"
   :command.editor/move-block-down         "Bloğu aşağı taşı"
   :command.editor/open-edit               "Seçili bloğu düzenle"
   :command.editor/select-block-up         "Yukarıdaki bloğu seçin"
   :command.editor/select-block-down       "Aşağıdaki bloğu seçin"
   :command.editor/delete-selection        "Seçili blokları sil"
   :command.editor/expand-block-children   "Genişlet"
   :command.editor/collapse-block-children "Daralt"
   :command.editor/indent                  "Bloğu girintile"
   :command.editor/outdent                 "Blok girintisini azalt"
   :command.editor/copy                    "Kopyala (seçimi veya blok referansını kopyalar)"
   :command.editor/copy-text               "Seçimleri metin olarak kopyala"
   :command.editor/cut                     "Kes"
   :command.editor/undo                    "Geri al"
   :command.editor/redo                    "Tinele"
   :command.editor/insert-link             "HTML Bağlantısı"
   :command.editor/select-all-blocks       "Tüm blokları seç"
   :command.editor/zoom-in                 "Düzenlenen bloğu yakınlaştır / Aksi takdirde ileri git"
   :command.editor/zoom-out                "Düzenlenen bloğu uzaklaştır / Aksi takdirde geri git"
   :command.editor/toggle-undo-redo-mode   "Geri alma / yineleme modunu değiştir (yalnızca sayfa veya genel)"
   :command.editor/toggle-number-list      "Numaralı liste olarak değiştir"
   :command.whiteboard/select              "Seçim aracı"
   :command.whiteboard/pan                 "Kaydırma aracı"
   :command.whiteboard/portal              "Portal aracı"
   :command.whiteboard/pencil              "Kalem aracı"
   :command.whiteboard/highlighter         "Vurgulayıcı aracı"
   :command.whiteboard/eraser              "Silgi aracı"
   :command.whiteboard/connector           "Bağlayıcı aracı"
   :command.whiteboard/text                "Metin aracı"
   :command.whiteboard/rectangle           "Dikdörtgen aracı"
   :command.whiteboard/ellipse             "Elips aracı"
   :command.whiteboard/reset-zoom          "Yakınlaştırmayı sıfırla"
   :command.whiteboard/zoom-to-fit         "Çizimi yakınlaştır"
   :command.whiteboard/zoom-to-selection   "Seçimi sığacak kadar yakınlaştır"
   :command.whiteboard/zoom-out            "Uzaklaştır"
   :command.whiteboard/zoom-in             "Yakınlaştır"
   :command.whiteboard/send-backward       "Geriye git"
   :command.whiteboard/send-to-back        "Geriye taşı"
   :command.whiteboard/bring-forward       "İleriye git"
   :command.whiteboard/bring-to-front      "Öne taşı"
   :command.whiteboard/lock                "Seçimi kilitle"
   :command.whiteboard/unlock              "Seçimin Kilidini aç"
   :command.whiteboard/group               "Seçimi gruplandır"
   :command.whiteboard/ungroup             "Seçimi gruptan çıkar"
   :command.whiteboard/toggle-grid         "Tuval ızgarasını değiştir"
   :command.ui/toggle-brackets             "Köşeli ayraçların görüntülenip görüntülenmeyeceğini değiştir"
   :command.go/search-in-page              "Geçerli sayfada ara"
   :command.go/electron-find-in-page       "Sayfada bul"
   :command.go/electron-jump-to-the-next   "Aramanız için bir sonraki eşleşmeye atlayın"
   :command.go/electron-jump-to-the-previous "Aramanız için bir önceki eşleşmeye atlayın"
   :command.go/search                      "Tam metin araması"
   :command.go/journals                    "Günlüğe git"
   :command.go/backward                    "Geriye git"
   :command.go/forward                     "İleriye git"
   :command.search/re-index                "Arama dizinini yeniden oluştur"
   :command.sidebar/open-today-page        "Sağ kenar çubuğunda bugünün sayfasını açın"
   :command.sidebar/close-top              "Sağ kenar çubuğunun en üst öğesini kapatır"
   :command.sidebar/clear                  "Sağ kenar çubuğundaki herşeyi temizle"
   :command.misc/copy                      "mod+c"
   :command.command-palette/toggle         "Komut paletini aç"
   :command.graph/export-as-html           "Herkese açık graf sayfalarını html olarak dışarı aktar"
   :command.graph/open                     "Açılacak grafı seçin"
   :command.graph/remove                   "Bir grafı kaldır"
   :command.graph/add                      "Graf ekle"
   :command.graph/save                     "Mevcut grafı diske kaydet"
   :command.graph/re-index                 "Mevcut grafı yeniden oluştur"
   :command.command/run                    "Git komutunu çalıştır"
   :command.go/home                        "Ana sayfaya git"
   :command.go/all-graphs                  "Bütün graflara git"
   :command.go/whiteboards                 "Beyaz tahtalara git"
   :command.go/all-pages                   "Bütün sayfalara git"
   :command.go/graph-view                  "Graf görünümüne git"
   :command.go/keyboard-shortcuts          "Klavye kısayollarına git"
   :command.go/tomorrow                    "Yarının günlüğüne git"
   :command.go/next-journal                "Sonraki günlüğe git"
   :command.go/prev-journal                "Önceki günlüğe git"
   :command.go/flashcards                  "Bilgi kartlarına git"
   :command.ui/toggle-document-mode        "Belge modunu aç/kapat"
   :command.ui/toggle-settings             "Ayarları aç/kapat"
   :command.ui/toggle-right-sidebar        "Sağ kenar çubuğunu aç/kapat"
   :command.ui/toggle-left-sidebar         "Sol kenar çubuğunu aç/kapat"
   :command.ui/toggle-help                 "Yardımı aç/kapat"
   :command.ui/toggle-theme                "Koyu ve açık tema arasında geçiş yap"
   :command.ui/toggle-contents             "Kenar çubuğundaki içeriği aç/kapat"
             ;;  :command.ui/open-new-window             "Başka bir pencere aç"
   :command.command/toggle-favorite        "Sık kullanılanlara ekle/çıkar"
   :command.editor/open-file-in-default-app "Dosyayı varsayılan uygulamada aç"
   :command.editor/open-file-in-directory   "Dosyayı üst dizinde aç"
   :command.editor/copy-current-file        "Geçerli dosyayı kopyala"
   :command.editor/copy-page-url           "Sayfa url'sini kopyala"
   :command.ui/toggle-wide-mode             "Geniş modu aç/kapat"
   :command.ui/select-theme-color           "Kullanılabilir tema renklerini seçin"
   :command.ui/goto-plugins                 "Eklentiler panosuna git"
   :command.ui/install-plugins-from-file    "Eklentileri plugins.edn dosyasından yükleyin"
   :command.editor/toggle-open-blocks       "Açık blokları kapat/aç (tüm blokları daralt veya genişlet)"
   :command.ui/toggle-cards                 "Kartları aç/kapat"
   :command.ui/clear-all-notifications      "Tüm bildirimleri temizle"
   :command.git/commit                      "Mesajlı git commit oluştur"
   :command.editor/select-parent            "Üst bloğu seçin"
   :command.dev/show-block-data             "(Dev) Blok verilerini göster"
   :command.dev/show-block-ast              "(Dev) Blok AST'sini göster"
   :command.dev/show-page-data              "(Dev) Sayfa verilerini göster"
   :command.dev/show-page-ast               "(Dev) Sayfa AST'sini göster"})
