(ns frontend.modules.shortcut.dicts.uk
  "Provides dictionary entries for shortcuts in UK")

(def dict
  {:shortcut.category/formatting                             "Форматування"
   :shortcut.category/basics                                 "Основи"
   :shortcut.category/navigating                             "Навігація"
   :shortcut.category/block-editing                          "Загальне редагування блоку"
   :shortcut.category/block-command-editing                  "Редагування команди блоку"
   :shortcut.category/block-selection                        "Вибір блоку (натисніть Esc щоб вийти із вибірки)"
   :shortcut.category/toggle                                 "Перемкнути"
   :shortcut.category/others                                 "Інші"

   :command.date-picker/complete                             "Вибір дати: підтвердити обраний день"
   :command.date-picker/next-day                             "Вибір дати: виберіть наступний день"
   :command.date-picker/next-week                            "Вибір дати: виберіть наступний тиждень"
   :command.date-picker/prev-day                             "Вибір дати: виберіть попередній день"
   :command.date-picker/prev-week                            "Вибір дати: виберіть попередній тиждень"
   :command.pdf/previous-page                                "PDF: Попередня сторінка поточного документа PDF"
   :command.pdf/next-page                                    "PDF: Наступна сторінка поточного документа PDF"
   :command.pdf/close                                        "PDF: Закрити поточний документ PDF"
   :command.pdf/find                                         "PDF: Пошук тексту в поточному pdf-документі"
   :command.auto-complete/complete                           "Автозаповнення: підтвердити вибраний елемент"
   :command.auto-complete/prev                               "Автозаповнення: попередній елемент"
   :command.auto-complete/next                               "Автозаповнення: наступний елемент"
   :command.auto-complete/shift-complete                     "Автозаповнення: відкрити вибраний елемент на бічній панелі"
   :command.auto-complete/open-link                          "Автозаповнення: відкрити вибраний елемент у браузері"
   :command.cards/toggle-answers                             "Вкладки: Показати/Сховати відповіді"
   :command.cards/next-card                                  "Карти: ще одна картка"
   :command.cards/forgotten                                  "Карти: забуті"
   :command.cards/remembered                                 "Карти: запам'ятовані"
   :command.cards/recall                                     "Карти: знадобиться деякий час, щоб згадати"
   :command.editor/escape-editing                            "Скасувати редагування"
   :command.editor/backspace                                 "Видалити в зворотному напрямку"
   :command.editor/delete                                    "Видалити"
   :command.editor/new-block                                 "Створити новоий блок"
   :command.editor/new-line                                  "Новий рядок у поточному блоці"
   :command.editor/new-whiteboard                            "Нова дошка"
   :command.editor/follow-link                               "Перейдіть за посиланням"
   :command.editor/open-link-in-sidebar                      "Відкрити посилання на бічній панелі"
   :command.editor/bold                                      "Жирний"
   :command.editor/italics                                   "Курсив"
   :command.editor/highlight                                 "Виділення"
   :command.editor/strike-through                            "Закреслений"
   :command.editor/clear-block                               "Видалити весь вміст блоку"
   :command.editor/kill-line-before                          "Видалити рядок перед позицією курсору"
   :command.editor/copy-embed                                "Скопіювати вставлений блок, вказуючи на поточний блок"
   :command.editor/kill-line-after                           "Видалити рядок після позиції курсора"
   :command.editor/beginning-of-block                        "Перемістіть курсор на початок блоку"
   :command.editor/end-of-block                              "Перемістіть курсор у кінець блоку"
   :command.editor/forward-word                              "Перемістіть курсор на одне слово вперед"
   :command.editor/backward-word                             "Перемістіть курсор на одне слово назад"
   :command.editor/forward-kill-word                         "Видалити слово вперед"
   :command.editor/backward-kill-word                        "Видалити слово назад"
   :command.editor/replace-block-reference-at-point          "Замініть посилання на блок його вмістом у точці"
   :command.editor/paste-text-in-one-block-at-point          "Вставити текст в один блок за точкою"
   :command.editor/insert-youtube-timestamp                  "Вставити мітку часу YouTube"
   :command.editor/cycle-todo                                "Змінити статус TODO для поточного елемента"
   :command.editor/up                                        "Перемістити курсор вгору/Вибрати вгору"
   :command.editor/down                                      "Перемістіть курсор вниз/Виберіть вниз"
   :command.editor/left                                      "Перемістити курсор ліворуч/Відкрити виділений блок на початку"
   :command.editor/right                                     "Перемістити курсор вправо/Відкрити вибраний блок у кінці"
   :command.editor/select-up                                 "Вибрати вміст вище"
   :command.editor/select-down                               "Вибрати вміст нище"
   :command.editor/move-block-up                             "Перемістити блок нагору"
   :command.editor/move-block-down                           "Перемістити блок вниз"
   :command.editor/open-edit                                 "Редагувати виділений блок"
   :command.editor/select-block-up                           "Вибрати блок вище"
   :command.editor/select-block-down                         "Вибрати блок нище"
   :command.editor/delete-selection                          "Видалити вибрані блоки"
   :command.editor/expand-block-children                     "Розкрити"
   :command.editor/collapse-block-children                   "Сховати"
   :command.editor/indent                                    "Зсув блоку"
   :command.editor/outdent                                   "Скасувати зсув блоку"
   :command.editor/copy                                      "Копіювати (копіює виділення або посилання на блок)"
   :command.editor/copy-text                                 "Копіювати виділення як текст"
   :command.editor/cut                                       "Вирізати"
   :command.editor/undo                                      "Скасувати зміни"
   :command.editor/redo                                      "Повторити"
   :command.editor/insert-link                               "HTML посилання"
   :command.editor/select-all-blocks                         "Вибрати всі блоки"
   :command.editor/select-parent                             "Вибрати батьківський блок"
   :command.editor/zoom-in                                   "Збільшити"
   :command.editor/zoom-out                                  "Зменшити"
   :command.ui/toggle-brackets                               "Показати/Сховати квадратні дужки"
   :command.go/search-in-page                                "Пошук блоків на поточній сторінці"
   :command.go/electron-find-in-page                         "Знайти текст на сторінці"
   :command.go/electron-jump-to-the-next                     "Шукати далі"
   :command.go/electron-jump-to-the-previous                 "Шукати назад"
   :command.go/search                                        "Пошук сторінок і блоків"
   :command.go/journals                                      "Перейти до журналів"
   :command.go/backward                                      "Назад"
   :command.go/forward                                       "Вперед"
   :command.search/re-index                                  "Оновити індекс пошуку"
   :command.sidebar/open-today-page                          "Відкрити сторінку сьогоднішнього дня на правій бічній панелі"
   :command.sidebar/close-top                                "Закрити верхній елемент на правій бічній панелі"
   :command.sidebar/clear                                    "Очистити усе на правій бічній панелі"
   :command.misc/copy                                        "Копіювати"
   :command.command-palette/toggle                           "Показати/Сховати список команд"
   :command.graph/export-as-html                             "Експортувати загальнодоступні сторінки графіків у форматі HTML"
   :command.graph/open                                       "Виберіть графік, яку потрібно відкрити"
   :command.graph/remove                                     "Видалити графік"
   :command.graph/add                                        "Додати графік"
   :command.graph/save                                       "Зберегти поточний графік на диск"
   :command.graph/re-index                                   "Переіндексувати поточний графік"
   :command.command/run                                      "Виконати команду GIT"
   :command.go/home                                          "Перейти на головну сторінку"
   :command.go/all-graphs                                    "Перейти до всіх діаграм"
   :command.go/whiteboards                                   "Перейти до дошок"
   :command.go/all-pages                                     "Перейти на всі сторінки"
   :command.go/graph-view                                    "Перейти до перегляду графіка"
   :command.go/keyboard-shortcuts                            "Перейти до комбінацій клавіш"
   :command.go/tomorrow                                      "Перейти до завтрашнього щоденника"
   :command.go/next-journal                                  "Перейти до наступного журналу"
   :command.go/prev-journal                                  "Перейти до попереднього журналу"
   :command.go/flashcards                                    "Показати/Сховати картки"
   :command.ui/toggle-document-mode                          "Показати/Сховати режим документа"
   :command.ui/toggle-settings                               "Налаштування перемикача"
   :command.ui/toggle-right-sidebar                          "Показати/сховати праву бічну панель"
   :command.ui/toggle-left-sidebar                           "Показати/Сховати ліву бічну панель"
   :command.ui/toggle-help                                   "Показати/Сховати помічника"
   :command.ui/toggle-theme                                  "Перемикання між темною та світлою темою"
   :command.ui/toggle-contents                               "Показати/Приховати вміст бічної панелі"
   :command.command/toggle-favorite                          "Додати/Видалити з вибраного"
   :command.editor/open-file-in-default-app                  "Відкрити файл у програмі за замовчуванням"
   :command.editor/open-file-in-directory                    "Відкрити файл у папці"
   :command.editor/copy-current-file                         "Копіювати поточний файл"
   :command.ui/toggle-wide-mode                              "Перейти у ширококутний режим"
   :command.ui/select-theme-color                            "Вибрати доступні кольори теми"
   :command.ui/goto-plugins                                  "Перейти до списку плагінів"
   :command.ui/install-plugins-from-file                     "Встановити плагіни з plugins.edn"
   :command.editor/toggle-open-blocks                        "Згорнути/Розгорнути всі блоки"
   :command.ui/toggle-cards                                  "Показати/Сховати карти"
   :command.git/commit                                       "Виконати команду git commit із повідомленням"
   :command.ui/clear-all-notifications                       "Очистити всі сповіщення"
   :command.editor/copy-page-url                             "Копіювати URL-адресу сторінки"
   :command.dev/show-block-ast                               "(Dev) Показати блок AST"
   :command.dev/show-block-data                              "(Dev) Показати дані блоку"
   :command.dev/show-page-ast                                "(Dev) Показати сторінку AST"
   :command.dev/show-page-data                               "(Dev) Показати дані сторінки"})
