(ns frontend.modules.shortcut.dicts.zh-cn
  "Provides dictionary entries for shortcuts in zh-CN")

(def dict
  {:shortcut.category/formatting            "格式化"
   :shortcut.category/basics                "基础操作"
   :shortcut.category/navigating            "移动"
   :shortcut.category/block-editing         "块编辑基本"
   :shortcut.category/block-command-editing "块编辑文本操作"
   :shortcut.category/block-selection       "块选择操作"
   :shortcut.category/toggle                "切换"
   :shortcut.category/others                "其他"
   :command.auto-complete/complete          "自动完成：选择当前项"
   :command.auto-complete/next              "自动完成：选择下一项"
   :command.auto-complete/open-link         "自动完成：在浏览器中打开当前项"
   :command.auto-complete/prev              "自动完成：选择上一项"
   :command.auto-complete/shift-complete    "自动完成：在侧边栏打开"
   :command.cards/forgotten                 "卡片：忘记了"
   :command.cards/next-card                 "卡片：下一个"
   :command.cards/recall                    "卡片：需要一会儿才能记起"
   :command.cards/remembered                "卡片：记得"
   :command.cards/toggle-answers            "卡片：显示/隐藏 答案/填空"
   :command.command/run                     "运行 git 命令"
   :command.command/toggle-favorite         "切换收藏"
   :command.command-palette/toggle          "切换命令面板"
   :command.date-picker/complete            "日期选择：选择当前天"
   :command.date-picker/next-day            "日期选择：下一天"
   :command.date-picker/next-week           "日期选择：下一周"
   :command.date-picker/prev-day            "日期选择：上一天"
   :command.date-picker/prev-week           "日期选择：上一周"
   :command.editor/copy-current-file        "复制当前文件"
   :command.editor/copy-embed               "复制指向当前块的嵌入块"
   :command.editor/copy-text                "复制选中的文本"
   :command.editor/escape-editing           "转义编辑"
   :command.editor/insert-youtube-timestamp "插入 Youtube 时间戳"
   :command.editor/new-whiteboard           "新建白板"
   :command.editor/open-file-in-default-app "在默认应用中打开文件"
   :command.editor/open-file-in-directory   "在目录中打开文件"
   :command.editor/paste-text-in-one-block-at-point  "粘贴文本到块的点"
   :command.editor/replace-block-reference-at-point  "用内容替换块引用"
   :command.editor/select-down              "选择下面内容"
   :command.editor/select-up                "选择上面的内容"
   :command.editor/strike-through           "删除线"
   :command.go/all-graphs                   "所有图谱"
   :command.go/all-pages                    "全部页面"
   :command.go/electron-jump-to-the-next    "跳转到查找栏搜索的下一个匹配项"
   :command.go/electron-jump-to-the-previous "跳转到查找栏搜索的上一个匹配项"
   :command.go/flashcards                   "记忆卡片"
   :command.go/graph-view                   "记忆图谱"
   :command.go/home                         "首页"
   :command.go/keyboard-shortcuts           "快捷键"
   :command.go/next-journal                 "下一篇日记"
   :command.go/prev-journal                 "上一篇日记"
   :command.go/tomorrow                     "明天"
   :command.go/whiteboards                  "前往白板"
   :command.graph/add                       "添加图谱"
   :command.graph/export-as-html            "将公共图谱导出为 html"
   :command.graph/open                      "打开图谱"
   :command.graph/re-index                  "重建索引"
   :command.graph/remove                    "移除图谱"
   :command.graph/save                      "保存"
   :command.misc/copy                       "Ctrl/Command + c"
   :command.sidebar/clear                   "清除侧边栏"
   :command.sidebar/open-today-page         "在侧边栏打开今日"
   :command.ui/goto-plugins                 "插件"
   :command.ui/select-theme-color           "选择皮肤颜色"
   :command.ui/toggle-cards                 "切换卡片"
   :command.ui/toggle-left-sidebar          "切换左侧边栏"
   :command.editor/indent                   "缩进块标签"
   :command.editor/outdent                  "取消缩进块"
   :command.editor/move-block-up            "向上移动块"
   :command.editor/move-block-down          "向下移动块"
   :command.editor/new-block                "创建块"
   :command.editor/new-line                 "块中新建行"
   :command.editor/zoom-in                  "聚焦"
   :command.editor/zoom-out                 "退出聚焦"
   :command.editor/follow-link              "跟随光标下的链接"
   :command.editor/open-link-in-sidebar     "在侧边栏打开"
   :command.editor/expand-block-children    "展开"
   :command.editor/collapse-block-children  "折叠"
   :command.editor/select-block-up          "选择上方的块"
   :command.editor/select-block-down        "选择下方的块"
   :command.editor/select-all-blocks        "选择所有块"
   :command.pdf/find                        "Pdf: 查找当前 pdf 文档的文本"
   :command.pdf/previous-page               "上一页PDF文档"
   :command.pdf/next-page                   "下一页PDF文档"
   :command.pdf/close                       "关闭当前PDF文档"
   :command.ui/toggle-help                  "显示/关闭帮助"
   :command.git/commit                      "提交消息"
   :command.go/search                       "搜索页面和块"
   :command.go/backward                     "回退"
   :command.go/forward                      "前进"
   :command.go/search-in-page               "在当前页面搜索块"
   :command.go/electron-find-in-page        "在当前页面查找文本"
   :command.ui/toggle-document-mode         "切换文档模式"
   :command.ui/toggle-contents              "打开/关闭目录"
   :command.ui/toggle-theme                 "在暗色/亮色主题之间切换"
   :command.ui/toggle-right-sidebar         "启用/关闭右侧栏"
   :command.ui/toggle-settings              "显示/关闭设置"
   :command.go/journals                     "跳转到日记"
   :command.ui/toggle-wide-mode             "切换宽屏模式"
   :command.ui/toggle-brackets              "切换是否显示括号"
   :command.search/re-index                 "重新建立搜索索引"
   :command.editor/bold                     "粗体"
   :command.editor/italics                  "斜体"
   :command.editor/insert-link              "Html 链接"
   :command.editor/highlight                "高亮"
   :command.editor/undo                     "撤销"
   :command.editor/redo                     "重做"
   :command.editor/copy                     "复制"
   :command.editor/cut                      "剪切"
   :command.editor/up                       "向上移动光标 / 向上选择"
   :command.editor/down                     "向下移动光标 / 向下选择"
   :command.editor/left                     "向左移动光标 / 向左选择"
   :command.editor/right                    "向右移动光标 / 向右选择"
   :command.editor/backspace                "向左删除"
   :command.editor/delete                   "向右删除"
   :command.editor/cycle-todo               "切换TODO状态"
   :command.editor/clear-block              "清除块内容"
   :command.editor/kill-line-before         "删除光标右侧行"
   :command.editor/kill-line-after          "删除光标左侧行"
   :command.editor/beginning-of-block       "移动光标到块开始位置"
   :command.editor/end-of-block             "移动光标到块末尾"
   :command.editor/forward-word             "光标向后移动一个单词"
   :command.editor/backward-word            "光标向前移动一个单词"
   :command.editor/forward-kill-word        "向后删除一个单词"
   :command.editor/backward-kill-word       "向前删除一个单词"
   :command.editor/open-edit                "编辑选中块"
   :command.editor/delete-selection         "删除选中块"
   :command.editor/toggle-open-blocks       "切换折叠/展开所有块（非编辑状态）"})
