(lang dune 3.23)

(using melange 1.0)

(name logseq-cli)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(pin
 (url "git+https://github.com/logseq/melange-edn.git#main")
 (package (name melange-edn-core) (version 0.5.0)))
(pin
 (url "git+https://github.com/logseq/melange-edn.git#main")
 (package (name melange-edn-melange) (version 0.5.0)))
(pin
 (url "git+https://github.com/logseq/melange-transit.git#main")
 (package (name melange-transit-core) (version 0.1.2)))
(pin
 (url "git+https://github.com/logseq/melange-transit.git#main")
 (package (name melange-transit-melange) (version 0.1.2)))
(pin
 (url "git+https://github.com/rcmerci/humanize.git#main")
 (package (name humanize)))
(pin
 (url "git+https://github.com/logseq/rrbvec.git#main")
 (package (name rrbvec)))

(package
 (name logseq-cli)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
  (ocaml (>= 5.1.1))
  melange
  melange-fetch
  melange-transit-melange
  melange-edn-melange
  melange-fest
  rrbvec
  humanize)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
