name: Bug Report
description: Report a bug encountered while using Logseq
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce the Bug
      description: |
        Please tell us the steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        Please tell us what's the behavior you expect.
    validations:
      required: false
  - type: textarea
    id: Screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: desktop
    attributes:
      label: Desktop Platform Information
      description: |
        Would you mind to tell us the system information about your desktop platform?
      placeholder: |
        OS version, Browser or App, Logseq App version
        example: MacOS 12.2, App, v0.5.9
    validations:
      required: false
  - type: textarea
    id: mobile
    attributes:
      label: Mobile Platform Information
      description: |
        Would you mind to tell us the system information about your mobile platform?
      placeholder: |
        Device, OS version, Browser or App, Logseq App version
        example: iPhone6, iOS8.1, App, v0.5.9
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        If applicable, add additional context to help explain your problem.
    validations:
      required: false
