contact_links:
  - name: Database Version Issue
    url: https://github.com/logseq/db-test/issues
    about: For issues related to unreleased Database Version
  - name: Feature request
    url: https://discuss.logseq.com/new-topic?category=feature-requests
    about: Suggest an idea for Logseq
  - name: Questions & Help
    url: https://discuss.logseq.com/new-topic?category=questions-and-help
    about: Ask a question about Logseq
  - name: Feedback
    url: https://discuss.logseq.com/new-topic?category=feedback
    about: Discuss where Logseq can be improved

