(ns capacitor.ionic
  (:require ["@capacitor/camera" :as ionicCamera]
            ["@ionic/react" :as ionicReact]
            [logseq.shui.icon.v2 :as shui-icon]
            [logseq.shui.util :as shui-util]))

;(def define-custom-component ionicLoader/defineCustomElements)
(def ^js ionic-react ionicReact)
(def ^js ionic-camera (.-Camera ionicCamera))
(def ^js ionic-camera-result-type (.-CameraResultType ionicCamera))

(def tabler-icon shui-icon/root)

(defonce ion-app (shui-util/react->rum (.-IonApp ionic-react) true))
(defonce ion-page (shui-util/react->rum (.-IonPage ionic-react) true))
(defonce ion-nav (shui-util/react->rum (.-IonNav ionic-react) true))
(defonce ion-nav-link (shui-util/react->rum (.-IonNavLink ionic-react) true))
(defonce ion-content (shui-util/react->rum (.-IonContent ionic-react) true))
(defonce ion-header (shui-util/react->rum (.-IonHeader ionic-react) true))
(defonce ion-back-button (shui-util/react->rum (.-IonBackButton ionic-react) false))
(defonce ion-buttons (shui-util/react->rum (.-IonButtons ionic-react) true))
(defonce ion-toolbar (shui-util/react->rum (.-IonToolbar ionic-react) true))
(defonce ion-loading (shui-util/react->rum (.-IonLoading ionic-react) true))
(defonce ion-title (shui-util/react->rum (.-IonTitle ionic-react) true))
(defonce ion-button (shui-util/react->rum (.-IonButton ionic-react) true))
(defonce ion-alert (shui-util/react->rum (.-IonAlert ionic-react) true))
(defonce ion-input (shui-util/react->rum (.-IonInput ionic-react) true))
(defonce ion-textarea (shui-util/react->rum (.-IonTextarea ionic-react) true))
(defonce ion-icon (shui-util/react->rum (.-IonIcon ionic-react) true))
(defonce ion-badge (shui-util/react->rum (.-IonBadge ionic-react) true))
(defonce ion-tabs (shui-util/react->rum (.-IonTabs ionic-react) false))
(defonce ion-tab (shui-util/react->rum (.-IonTab ionic-react) false))
(defonce ion-tab-bar (shui-util/react->rum (.-IonTabBar ionic-react) false))
(defonce ion-tab-button (shui-util/react->rum (.-IonTabButton ionic-react) false))
(defonce ion-modal (shui-util/react->rum (.-IonModal ionic-react) false))
(defonce ion-label (shui-util/react->rum (.-IonLabel ionic-react) false))
(defonce ion-list (shui-util/react->rum (.-IonList ionic-react) false))
(defonce ion-item (shui-util/react->rum (.-IonItem ionic-react) false))
(defonce ion-datetime (shui-util/react->rum (.-IonDatetime ionic-react) false))
(defonce ion-datetime-button (shui-util/react->rum (.-IonDatetimeButton ionic-react) false))
(defonce ion-refresher (shui-util/react->rum (.-IonRefresher ionic-react) false))
(defonce ion-refresher-content (shui-util/react->rum (.-IonRefresherContent ionic-react) false))
(defonce ion-menu (shui-util/react->rum (.-IonMenu ionic-react) false))
(defonce ion-menu-button (shui-util/react->rum (.-IonMenuButton ionic-react) false))
(defonce ion-action-sheet (shui-util/react->rum (.-IonActionSheet ionic-react) false))
