(ns frontend.tools.tongue
  (:require [tongue.core :as tongue]
            [frontend.state :as state]
            [clojure.string :as string]))


;; TODO
;; - [ ] Localizing Number Formats
;; - [ ] Localizing Dates

(def dicts
  {:en {:on-boarding/title "Hi, welcome to Logseq!"
        :on-boarding/sharing "sharing"
        :on-boarding/is-a " is a "
        :on-boarding/local-first "local-first"
        :on-boarding/non-linear "non-linear"
        :on-boarding/outliner "outliner"
        :on-boarding/notebook-for-organizing-and " notebook for organizing and "
        :on-boarding/your-personal-knowledge-base " your personal knowledge base."
        :on-boarding/notice "Notice that this project is in its early days and under quick development, files might be corrupted."
        :on-boarding/features-desc "Use it to organize your todo list, to write your journals, or to record your unique life."
        :on-boarding/privacy "The server will never store or analyze your private notes. Your data are plain text files, we support both Markdown and Emacs Org mode for the time being. Even if the website is down or can't be maintained, your data is always yours."
        :on-boarding/inspired-by " is hugely inspired by "
        :on-boarding/where-are-my-notes-saved "Where are my notes saved?"
        :on-boarding/storage "Your notes will be stored in the local browser storage using "
        :on-boarding/how-do-i-use-it "How do I use it?"
        :on-boarding/use-1 "1. Sync between multiple devices"
        :on-boarding/use-1-desc "Currently, we only support syncing through Github, more options (Self-host git, WebDAV, Google Drive, etc.) will be added soon."
        :on-boarding/use-1-video "Check out this awesome video by "
        :on-boarding/use-2 "2. Use it locally (no need to login)"
        :on-boarding/use-2-desc "Remember to backup your notes periodically!"
        :on-boarding/features "Features"
        :on-boarding/features-backlinks "Backlinks between [[Page]]s"
        :on-boarding/features-block-embed "Block embed"
        :on-boarding/features-page-embed "Page embed"
        :on-boarding/features-graph-vis "Graph visualization"
        :on-boarding/features-heading-properties "Heading properties"
        :on-boarding/features-datalog "Datalog queries, the notes db is powered by "
        :on-boarding/features-custom-view-component "Custom view component"
        :on-boarding/integration " integration"
        :on-boarding/slide-support " slide support"
        :on-boarding/built-in-supports "Document built-in supports:"
        :on-boarding/supports-code-highlights "Code highlights"
        :on-boarding/supports-katex-latex "Katex latex"
        :on-boarding/raw "Raw "
        :on-boarding/raw-html "Raw html"
        :on-boarding/learn-more "Learn more"
        :on-boarding/discord-desc " where the community ask questions and share tips"
        :on-boarding/github-desc " everyone is encouraged to report issues!"
        :on-boarding/our-blog "Our blog: "
        :on-boarding/credits-to "Credits to"
        :on-boarding/clojure-desc " - A dynamic, functional, general-purpose programming language"
        :on-boarding/datascript-desc " - Immutable database and Datalog query engine for Clojure, ClojureScript and JS"
        :on-boarding/angstrom-desc-1 ", the document "
        :on-boarding/angstrom-desc-2 "parser"
        :on-boarding/angstrom-desc-3 " is built on Angstrom."
        :on-boarding/cuekeeper-desc " - Browser-based GTD (TODO list) system."
        :on-boarding/sci-desc " - Small Clojure Interpreter"
        :on-boarding/isomorphic-git-desc " - A pure JavaScript implementation of git for node and browsers!"
        :right-side-bar/help "Help"
        :right-side-bar/switch-theme "Switch to {1} theme"
        :right-side-bar/theme "{1} theme"
        :right-side-bar/page "Page graph"
        :right-side-bar/recent "Recent"
        :right-side-bar/contents "Contents"
        :right-side-bar/graph-ref "Graph of "
        :right-side-bar/block-ref "Block reference"
        :git/set-access-token "Set Github personal access token"
        :git/token-is-encrypted "The token will be encrypted and stored in the browser local storage"
        :git/token-server "The server will never store it"
        :git/create-personal-access-token "How to create a Github personal access token?"
        :git/push "Push now"
        :git/local-changes-synced "All local changes are synced!"
        :git/pull "Pull now"
        :git/last-pull "Last pulled at"
        :git/version "Version"
        :git/import-notes "Import your notes"
        :git/import-notes-helper "You can import your notes from a repo on Github."
        :git/add-another-repo "Add another repo"
        :git/re-index "Clone again and re-index the db"
        :git/message "Your commit message"
        :git/commit-and-push "Commit and push!"
        :git/use-remote "Use remote"
        :git/keep-local "Keep local"
        :git/edit "Edit"
        :git/title "Diff"
        :git/no-diffs "No diffs"
        :git/commit-message "Commit message (optional)"
        :git/pushing "Pushing"
        :git/force-push "Commit and force pushing"
        :git/a-force-push "A force push"
        :git/add-repo-prompt "Install Logseq on your repo"
        :git/add-repo-prompt-confirm "Add and install"
        :format/preferred-mode "What's your preferred mode?"
        :format/markdown "Markdown"
        :format/org-mode "Org Mode"
        :reference/linked "Linked Reference"
        :reference/unlinked-ref "Unlinked References"
        :project/setup "Setup a public project on Logseq"
        :project/location "All published pages will be located under"
        :project/sync-settings "Sync project settings"
        :page/presentation-mode "Presentation mode (Powered by Reveal.js)"
        :page/delete-success "Page {1} was deleted successfully!"
        :page/delete-confirmation "Are you sure you want to delete this page?"
        :page/rename-to "Rename {1}\" to:\""
        :page/priority "Priority {1}\"\""
        :page/re-index "Re-index this page"
        :page/copy-to-json "Copi the whole page as JSON"
        :page/rename "Rename page"
        :page/delete "Delete page (will delete the file too)"
        :page/publish "Publish this page on Logseq"
        :page/publish-as-slide "Publish this page as a slide on Logseq"
        :page/unpublish "Un-publish this page on Logseq"
        :page/add-to-contents "Add to Contents"
        :page/show-journals "Show Journals"
        :page/show-name "Show page name"
        :page/hide-name "Hide page name"
        :page/name "Page name"
        :page/last-modified "Last modified at"
        :page/new-title "What's your new page title?"
        :journal/multiple-files-with-different-formats "It seems that you have multiple journal files (with different formats) for the same month, please only keep one journal file for each month."
        :journal/go-to "Go to files"
        :file/name "File name"
        :file/file "File: "
        :file/last-modified-at "Last modified at"
        :file/no-data "No data"
        :file/format-not-supported "Format .{1} is not supported."
        :editor/block-search "Search for a block"
        :editor/image-uploading "Uploading"
        :draw/invalid-file "Could not load this invalid excalidraw file"
        :draw/specify-title "Please specify a title first!"
        :draw/rename-success "File was renamed successfully!"
        :draw/rename-failure "Rename file failed, reason: "
        :draw/title-placeholder "Untitled"
        :draw/save "Save"
        :draw/save-changes "Save changes"
        :draw/new-file "New file"
        :draw/list-files "List files"
        :draw/delete "Delete"
        :draw/more-options "More options"
        :draw/back-to-logseq "Back to logseq"
        :content/copy "Copy"
        :content/cut "Cut"
        :content/make-todos "Make {1}s"
        :content/copy-block-ref "Copy block ref"
        :content/focus-on-block "Focus on block"
        :content/open-in-sidebar "Open in sidebar"
        :content/copy-as-json "Copy as JSON"
        :content/click-to-edit "Click to edit"
        :settings-page/edit-config-edn "Edit config.edn (for current repo)"
        :settings-page/preferred-file-format "Preferred file format"
        :settings-page/preferred-workflow "Preferred workflow"
        :settings-page/dont-use-other-peoples-proxy-servers "Don't use other people's proxy servers. It's very dangerous, which could make your token and notes stolen. Logseq will not be responsible for this loss if you use other people's proxy servers. You can deploy it yourself, check "
        :settings-page/custom-cors-proxy-server "Custom CORS proxy server"
        :settings-page/developer-mode "Developer mode"
        :settings-page/enable-developer-mode "Enable developer mode"
        :settings-page/disable-developer-mode "Disable developer mode"
        :settings-page/developer-mode-desc "Developer mode helps contributors and extension developers test their integration with Logseq more efficient."
        :logseq "Logseq"
        :dot-mode "Dot mode"
        :on "ON"
        :more-options "More options"
        :to "to"
        :yes "Yes"
        :submit "Submit"
        :cancel "Cancel"
        :re-index "Re-index"
        :export-json "Export as JSON"
        :unlink "unlink"
        :search "Search"
        :new-page "New page"
        :graph "Graph"
        :all-repos "All repos"
        :all-pages "All pages"
        :all-files "All files"
        :settings "Settings"
        :import "Import"
        :join-community "Join the community"
        :discord-title "Our discord group!"
        :sign-out "Sign out"
        :help-shortcut-title "Click to check shortcuts and other tips"
        :loading "Loading"
        :cloning "Cloning"
        :parsing-files "Parsing files"
        :loading-files "Loading files"
        :login-github "Login with Github"
        :excalidraw-title "Draw with Excalidraw"
        :go-to "Go to "
        :or "or"
        :download "Download"
        :language "Language"
        :white "White"
        :dark "Black"}

   :zh-CN {:on-boarding/title "你好，欢迎使用 Logseq！"
           :on-boarding/notice "请注意，本项目正在快速开发中，存在文件损坏的风险。"
           :right-side-bar/help "帮助"
           :right-side-bar/switch-theme "切换到{1}主题"
           :right-side-bar/theme "{1}主题"
           :right-side-bar/page "页面图谱"
           :right-side-bar/recent "最近"
           :right-side-bar/contents "目录"
           :right-side-bar/graph-ref "图谱："
           :right-side-bar/block-ref "块引用"
           :git/set-access-token "设定 Github 个人访问令牌"
           :git/token-is-encrypted "令牌将被加密并存储在浏览器本地存储"
           :git/token-server "服务器将永远不会存储它"
           :git/create-personal-access-token "如何创建 Github 个人访问令牌？"
           :git/push "现在 push"
           :git/local-changes-synced "所有本地更改已同步！"
           :git/pull "现在 pull"
           :git/last-pull "最后 pull 时间 "
           :git/version "版本"
           :git/import-notes "导入笔记"
           :git/import-notes-helper "你可以从 Github 的库中导入笔记"
           :git/add-another-repo "添加一个库"
           :git/re-index "重新 clone 然后重新建立索引"
           :git/message "你的 commit 信息"
           :git/commit-and-push "commit 并 push"
           :git/use-remote "使用云端版本"
           :git/keep-local "使用本地版本"
           :git/edit "编辑"
           :git/title "文件冲突"
           :git/no-diffs "没有文件冲突"
           :git/commit-message "commit 消息（可选）"
           :git/pushing "Pushing"
           :git/force-push "Commit 并强制 push"
           :git/a-force-push "强制 push"
           :git/add-repo-prompt "在你的库上安装 Logseq"
           :git/add-repo-prompt-confirm "添加并安装"
           :format/preferred-mode "请选择偏好格式"
           :format/markdown "Markdown"
           :format/org-mode "Org Mode"
           :reference/linked "已链接的引用"
           :reference/unlinked-ref "未链接的引用"
           :project/setup "在 Logseq 上发布新的项目"
           :project/location "一切发布的页面将会被放到 "
           :project/sync-settings "同步项目设置"
           :page/presentation-mode "演讲模式 (由 Reveal.js 驱动)"
           :page/delete-success "页面 {1} 删除成功！"
           :page/delete-confirmation "你确定要删除此页面吗？"
           :page/rename-to "重命名{1}\" 至：\""
           :page/priority "优先级 {1}\"\""
           :page/re-index "对此页面重新建立索引"
           :page/copy-to-json "将整页以 JSON 格式复制"
           :page/rename "重命名本页"
           :page/delete "删除本页（并删除文件）"
           :page/publish "将本页发布至 Logseq"
           :page/publish-as-slide "将本页作为幻灯片发布至 Logseq"
           :page/unpublish "取消将本页发布至 Logseq"
           :page/add-to-contents "将本页添加到目录"
           :page/show-journals "显示日志"
           :page/show-name "显示页面名"
           :page/hide-name "隐藏页面名"
           :page/name "页面名"
           :page/last-modified "最后更改于"
           :page/new-title "请输入新页面的名字:"
           :journal/multiple-files-with-different-formats "你似乎在同一个月有多个日记文件(格式不同)，请每个月只保留一个日记文件。"
           :journal/go-to "转到所有文件"
           :file/name "文件名"
           :file/file "文件："
           :file/last-modified-at "最后更改于"
           :file/no-data "没有数据"
           :file/format-not-supported "格式 .{1} 目前不支持."
           :editor/block-search "搜索块"
           :editor/image-uploading "上传中"
           :draw/invalid-file "无法加载此无效的 excalidraw 文件"
           :draw/specify-title "请先指定标题!"
           :draw/rename-success "文件重命名成功!"
           :draw/rename-failure "文件重命名失败，原因是："
           :draw/title-placeholder "未命名"
           :draw/save "保存"
           :draw/save-changes "保存更改"
           :draw/new-file "新文件"
           :draw/list-files "所有文件"
           :draw/delete "删除"
           :draw/more-options "更多选项"
           :draw/back-to-logseq "返回 logseq"
           :content/copy "复制"
           :content/cut "剪切"
           :content/make-todos "格式化为 {1}"
           :content/copy-block-ref "复制块引用"
           :content/focus-on-block "聚焦在此块"
           :content/open-in-sidebar "在侧边栏打开"
           :content/copy-as-json "复制为 JSON"
           :content/click-to-edit "点击以编辑"
           :settings-page/edit-config-edn "编辑 config.edn (当前库)"
           :settings-page/preferred-file-format "首选文件格式"
           :settings-page/preferred-workflow "首选工作流"
           :settings-page/dont-use-other-peoples-proxy-servers "不要使用其他人的代理服务器。这非常危险，可能会使您的令牌和笔记被盗。 如果您使用其他人的代理服务器，Logseq 将不会对此损失负责。您可以自己部署它，请查阅 "
           :settings-page/custom-cors-proxy-server "自定义 CORS 代理服务器"
           :settings-page/developer-mode "开发者模式"
           :settings-page/enable-developer-mode "启用开发者模式"
           :settings-page/disable-developer-mode "禁用开发者模式"
           :settings-page/developer-mode-desc "开发者模式帮助贡献者和扩展开发者更有效地测试他们与 Logseq 的集成。"
           :logseq "Logseq"
           :dot-mode "点模式"
           :on "已打开"
           :more-options "更多选项"
           :to "至"
           :yes "是"
           :submit "提交"
           :cancel "取消"
           :re-index "重新建立索引"
           :export-json "以 JSON 格式导出"
           :unlink "解除绑定"
           :search "搜索"
           :new-page "新页面"
           :graph "图谱"
           :all-repos "所有库"
           :all-pages "所有页面"
           :all-files "所有文件"
           :settings "设置"
           :import "导入"
           :join-community "加入社区"
           :discord-title "我们的 Discord 社群!"
           :sign-out "登出"
           :help-shortcut-title "点此查看快捷方式和更多游泳帮助"
           :loading "加载中"
           :cloning "Clone 中"
           :parsing-files "正在解析文件"
           :loading-files "正在加载文件"
           :login-github "用 Github 登陆"
           :excalidraw-title "用 Excalidraw 画图"
           :go-to "转到"
           :or "或"
           :download "下载"
           :language "语言"
           :white "白色"
           :dark "黑色"}

  :tongue/fallback :en})

(def languages [{:label "English" :value :en}
                {:label "简体中文" :value :zh-CN}])

(def translate
  (tongue/build-translate dicts))
