(ns frontend.modules.shortcut.dict
  (:require [frontend.modules.shortcut.data-helper :as dh])
  (:require-macros [frontend.modules.shortcut.macro :refer [shortcut-dict]]))

(def dict
  (shortcut-dict
   (dh/desc-helper)
   (dh/category-helper)
   {:zh-CN
    {:shortcut.category/formatting            "格式化"
     :shortcut.editor/indent                  "缩进块标签"
     :shortcut.editor/outdent                 "取消缩进块"
     :shortcut.editor/move-block-up           "向上移动块"
     :shortcut.editor/move-block-down         "向下移动块"
     :shortcut.editor/new-block               "创建块"
     :shortcut.editor/new-line                "块中新建行"
     :shortcut.editor/zoom-in                 "聚焦"
     :shortcut.editor/zoom-out                "退出聚焦"
     :shortcut.editor/follow-link             "跟随光标下的链接"
     :shortcut.editor/open-link-in-sidebar    "在侧边栏打开"
     :shortcut.editor/expand-block-children   "展开"
     :shortcut.editor/collapse-block-children "折叠"
     :shortcut.editor/select-block-up         "选择上方的块"
     :shortcut.editor/select-block-down       "选择下方的块"
     :shortcut.editor/select-all-blocks       "选择所有块"
     :shortcut.ui/toggle-help                 "显示/关闭帮助"
     :shortcut.git/commit                     "提交消息"
     :shortcut.go/search                      "全文搜索"
     :shortcut.go/search-in-page              "在当前页面搜索"
     :shortcut.ui/toggle-document-mode        "切换文档模式"
     :shortcut.ui/toggle-contents             "打开/关闭目录"
     :shortcut.ui/toggle-theme                "在暗色/亮色主题之间切换"
     :shortcut.ui/toggle-right-sidebar        "启用/关闭右侧栏"
     :shortcut.ui/toggle-settings             "显示/关闭设置"
     :shortcut.ui/toggle-new-block            "切换 Enter/Shift+Enter 以插入新块"
     :shortcut.go/journals                    "跳转到日记"
     ;; TODO translate those in fr/de/etc..
     :shortcut.category/basics                "基础操作"
     :shortcut.category/navigating            "移动"
     :shortcut.category/block-editing         "块编辑基本"
     :shortcut.category/block-command-editing "块编辑文本操作"
     :shortcut.category/block-selection       "块选择操作"
     :shortcut.category/toggle                "切换"
     :shortcut.category/others                "其他"
     :shortcut.ui/toggle-wide-mode            "切换宽屏模式"
     :shortcut.ui/toggle-brackets             "切换是否显示括号"
     :shortcut.ui/fold                        "折叠块（非编辑状态）"
     :shortcut.ui/un-fold                     "展开块（非编辑状态）"
     :shortcut.search/re-index                "重新建立搜索索引"
     :shortcut.graph/re-index                 "重新建立图库索引"
     :shortcut.editor/bold                    "粗体"
     :shortcut.editor/italics                 "斜体"
     :shortcut.editor/insert-link             "Html 链接"
     :shortcut.editor/highlight               "高亮"
     :shortcut.editor/undo                    "撤销"
     :shortcut.editor/redo                    "重做"
     :shortcut.editor/copy                    "复制"
     :shortcut.editor/cut                     "剪切"
     :shortcut.editor/up                      "向上移动光标 / 向上选择"
     :shortcut.editor/down                    "向下移动光标 / 向下选择"
     :shortcut.editor/left                    "向左移动光标 / 向左选择"
     :shortcut.editor/right                   "向右移动光标 / 向右选择"
     :shortcut.editor/backspace               "向左删除"
     :shortcut.editor/delete                  "向右删除"
     :shortcut.editor/cycle-todo              "切换TODO状态"
     :shortcut.editor/clear-block             "清除块内容"
     :shortcut.editor/kill-line-before        "删除光标右侧行"
     :shortcut.editor/kill-line-after         "删除光标左侧行"
     :shortcut.editor/beginning-of-block      "移动光标到块开始位置"
     :shortcut.editor/end-of-block            "移动光标到块末尾"
     :shortcut.editor/forward-word            "光标向后移动一个单词"
     :shortcut.editor/backward-word           "光标向前移动一个单词"
     :shortcut.editor/forward-kill-word       "向后删除一个单词"
     :shortcut.editor/backward-kill-word      "向前删除一个单词"
     :shortcut.editor/open-edit               "编辑选中块"
     :shortcut.editor/delete-selection        "删除选中块"}
    :zh-Hant
    {:shortcut.editor/indent                  "縮進塊標簽"
     :shortcut.editor/outdent                 "取消縮進塊"
     :shortcut.editor/move-block-up           "向上移動塊"
     :shortcut.editor/move-block-down         "向下移動塊"
     :shortcut.editor/new-block               "創建塊"
     :shortcut.editor/new-line                "塊中新建行"
     :shortcut.editor/zoom-in                 "聚焦"
     :shortcut.editor/zoom-out                "推出聚焦"
     :shortcut.editor/follow-link             "跟隨光標下的鏈接"
     :shortcut.editor/open-link-in-sidebar    "在側邊欄打開"
     :shortcut.editor/expand-block-children   "展開"
     :shortcut.editor/collapse-block-children "折疊"
     :shortcut.editor/select-block-up         "選擇上方的塊"
     :shortcut.editor/select-block-down       "選擇下方的塊"
     :shortcut.editor/select-all-blocks       "選擇所有塊"
     :shortcut.ui/toggle-help                 "顯示/關閉幫助"
     :shortcut.git/commit                     "提交消息"
     :shortcut.go/search                      "全文搜索"
     :shortcut.ui/toggle-document-mode        "切換文檔模式"
     :shortcut.ui/toggle-theme                "“在暗色/亮色主題之間切換”"
     :shortcut.ui/toggle-right-sidebar        "啟用/關閉右側欄"
     :shortcut.ui/toggle-new-block            "切換 Enter/Shift+Enter 以插入新塊"
     :shortcut.go/journals                    "跳轉到日記"
     :shortcut.category/formatting            "格式化"}
    :de
    {:shortcut.editor/indent                  "Block einrücken"
     :shortcut.editor/outdent                 "Block ausrücken"
     :shortcut.editor/move-block-up           "Block nach oben verschieben"
     :shortcut.editor/move-block-down         "Block nach unten verschieben"
     :shortcut.editor/new-block               "Neuen Block erstellen"
     :shortcut.editor/new-line                "Neue Zeile innerhalb des Blocks erstellen"
     :shortcut.editor/zoom-in                 "Heranzoomen"
     :shortcut.editor/zoom-out                "Herauszoomen"
     :shortcut.editor/follow-link             "Link unter dem Cursor folgen"
     :shortcut.editor/open-link-in-sidebar    "Link in Seitenleiste öffnen"
     :shortcut.editor/expand-block-children   "Erweitern"
     :shortcut.editor/collapse-block-children "Zusammenklappen"
     :shortcut.editor/select-block-up         "Block oberhalb auswählen"
     :shortcut.ui/toggle-help                 "Hilfe aktivieren"
     :shortcut.go/search                      "Volltextsuche"
     :shortcut.ui/toggle-document-mode        "Dokumentenmodus umschalten"
     :shortcut.ui/toggle-theme                "Umschalten zwischen dunklem/hellem Thema"
     :shortcut.ui/toggle-right-sidebar        "Rechte Seitenleiste umschalten"
     :shortcut.ui/toggle-new-block            "Umschalten von Enter/Shift+Enter zum Einfügen eines neuen Blocks"
     :shortcut.go/journals                    "Zu Journalen springen"
     :shortcut.git/commit                     "Git Commit-Nachricht"
     :shortcut.editor/select-block-down       "Block unterhalb auswählen"
     :shortcut.editor/select-all-blocks       "Alle Blöcke auswählen"
     :shortcut.category/formatting            "Formatierung"}
    :fr
    {:shortcut.editor/indent                  "Indenter un Bloc vers la droite"
     :shortcut.editor/outdent                 "Indenter un Bloc vers la gauche"
     :shortcut.editor/move-block-up           "Déplacer un bloc au dessus"
     :shortcut.editor/move-block-down         "Déplacer un bloc en dessous"
     :shortcut.editor/new-block               "Créer un nouveau bloc"
     :shortcut.editor/new-line                "Aller à la ligne dans un bloc"
     :shortcut.editor/zoom-in                 "Zoomer"
     :shortcut.editor/zoom-out                "Dézoomer"
     :shortcut.editor/follow-link             "Suivre le lien sous le curseur"
     :shortcut.editor/open-link-in-sidebar    "Ouvrir le lien dans la barre latérale"
     :shortcut.editor/expand-block-children   "Etendre"
     :shortcut.editor/collapse-block-children "Réduire"
     :shortcut.editor/select-block-up         "Sélectionner le bloc au dessus"
     :shortcut.editor/select-block-down       "Sélectionner le bloc en dessous"
     :shortcut.editor/select-all-blocks       "Sélectionner tous les blocs"
     :shortcut.ui/toggle-help                 "Afficher l'aide"
     :shortcut.git/commit                     "Message de commit Git"
     :shortcut.go/search                      "Recherche globale dans le texte"
     :shortcut.ui/toggle-document-mode        "Intervertir le mode document"
     :shortcut.ui/toggle-theme                "Intervertir le thème foncé/clair"
     :shortcut.ui/toggle-right-sidebar        "Afficher/cacher la barre latérale"
     :shortcut.ui/toggle-new-block            "Activer Entreée ou Shift+Enter pour insérer un bloc"
     :shortcut.go/journals                    "Aller au Journal"
     :shortcut.category/formatting            "Formats"}
    :af
    {:shortcut.editor/indent                  "Ingekeepte blok oortjie"
     :shortcut.editor/outdent                 "Oningekeepte blok"
     :shortcut.editor/move-block-up           "Skuif Blok Boontoe"
     :shortcut.editor/move-block-down         "Skuif Blok Ondertoe"
     :shortcut.editor/new-block               "Skep 'n nuwe blok"
     :shortcut.editor/new-line                "Nuwe lyn in blok"
     :shortcut.editor/zoom-in                 "Zoem in"
     :shortcut.editor/zoom-out                "Zoem uit"
     :shortcut.editor/follow-link             "Volg die skakel onder die wyser"
     :shortcut.editor/open-link-in-sidebar    "Maak skakel in kantlys oop"
     :shortcut.editor/expand-block-children   "Brei uit"
     :shortcut.editor/collapse-block-children "Vou in"
     :shortcut.editor/select-block-up         "Kies blok bo"
     :shortcut.editor/select-block-down       "Kies blok onder"
     :shortcut.editor/select-all-blocks       "Kies alle blokke"
     :shortcut.ui/toggle-help                 "Wissel help"
     :shortcut.git/commit                     "Jou git stoor boodskap"
     :shortcut.go/search                      "Volteks soek"
     :shortcut.ui/toggle-document-mode        "Wissel dokument modus"
     :shortcut.go/journals                    "Spring na joernale"
     :shortcut.category/formatting            "Formatering"
     :shortcut.ui/toggle-theme                "Wissel tussen donker/lig temas"
     :shortcut.ui/toggle-right-sidebar        "Wissel regter sybalk"
     :shortcut.ui/toggle-new-block            "Wissel Enter/Shift+enter vir die byvoeging van nuwe blokke"}}))
