(ns frontend.modules.shortcut.dict
  (:require [frontend.modules.shortcut.data-helper :as dh]
            [frontend.modules.shortcut.macro :refer [shortcut-dict]]))

(def dict
  (shortcut-dict
   (dh/desc-helper)
   (dh/category-helper)
   {:zh-CN
    {:shortcut.category/formatting            "格式化"
     :shortcut.category/basics                "基础操作"
     :shortcut.category/navigating            "移动"
     :shortcut.category/block-editing         "块编辑基本"
     :shortcut.category/block-command-editing "块编辑文本操作"
     :shortcut.category/block-selection       "块选择操作"
     :shortcut.category/toggle                "切换"
     :shortcut.category/others                "其他"
     :command.editor/indent                  "缩进块标签"
     :command.editor/outdent                 "取消缩进块"
     :command.editor/move-block-up           "向上移动块"
     :command.editor/move-block-down         "向下移动块"
     :command.editor/new-block               "创建块"
     :command.editor/new-line                "块中新建行"
     :command.editor/zoom-in                 "聚焦"
     :command.editor/zoom-out                "退出聚焦"
     :command.editor/follow-link             "跟随光标下的链接"
     :command.editor/open-link-in-sidebar    "在侧边栏打开"
     :command.editor/expand-block-children   "展开"
     :command.editor/collapse-block-children "折叠"
     :command.editor/select-block-up         "选择上方的块"
     :command.editor/select-block-down       "选择下方的块"
     :command.editor/select-all-blocks       "选择所有块"
     :command.ui/toggle-help                 "显示/关闭帮助"
     :command.git/commit                     "提交消息"
     :command.go/search                      "全文搜索"
     :command.go/backward                    "回退"
     :command.go/forward                     "前进"
     :command.go/search-in-page              "在当前页面搜索"
     :command.ui/toggle-document-mode        "切换文档模式"
     :command.ui/toggle-contents             "打开/关闭目录"
     :command.ui/toggle-theme                "在暗色/亮色主题之间切换"
     :command.ui/toggle-right-sidebar        "启用/关闭右侧栏"
     :command.ui/toggle-settings             "显示/关闭设置"
     :command.ui/toggle-new-block            "切换 Enter/Shift+Enter 以插入新块"
     :command.go/journals                    "跳转到日记"
     :command.ui/toggle-wide-mode            "切换宽屏模式"
     :command.ui/toggle-brackets             "切换是否显示括号"
     :command.search/re-index                "重新建立搜索索引"
     :command.graph/re-index                 "重新建立图库索引"
     :command.editor/bold                    "粗体"
     :command.editor/italics                 "斜体"
     :command.editor/insert-link             "Html 链接"
     :command.editor/highlight               "高亮"
     :command.editor/undo                    "撤销"
     :command.editor/redo                    "重做"
     :command.editor/copy                    "复制"
     :command.editor/cut                     "剪切"
     :command.editor/up                      "向上移动光标 / 向上选择"
     :command.editor/down                    "向下移动光标 / 向下选择"
     :command.editor/left                    "向左移动光标 / 向左选择"
     :command.editor/right                   "向右移动光标 / 向右选择"
     :command.editor/backspace               "向左删除"
     :command.editor/delete                  "向右删除"
     :command.editor/cycle-todo              "切换TODO状态"
     :command.editor/clear-block             "清除块内容"
     :command.editor/kill-line-before        "删除光标右侧行"
     :command.editor/kill-line-after         "删除光标左侧行"
     :command.editor/beginning-of-block      "移动光标到块开始位置"
     :command.editor/end-of-block            "移动光标到块末尾"
     :command.editor/forward-word            "光标向后移动一个单词"
     :command.editor/backward-word           "光标向前移动一个单词"
     :command.editor/forward-kill-word       "向后删除一个单词"
     :command.editor/backward-kill-word      "向前删除一个单词"
     :command.editor/open-edit               "编辑选中块"
     :command.editor/delete-selection        "删除选中块"
     :command.editor/toggle-open-blocks      "切换折叠/展开所有块（非编辑状态）"}
    :zh-Hant
    {:command.editor/indent                  "縮進塊標簽"
     :command.editor/outdent                 "取消縮進塊"
     :command.editor/move-block-up           "向上移動塊"
     :command.editor/move-block-down         "向下移動塊"
     :command.editor/new-block               "創建塊"
     :command.editor/new-line                "塊中新建行"
     :command.editor/zoom-in                 "聚焦"
     :command.editor/zoom-out                "推出聚焦"
     :command.editor/follow-link             "跟隨光標下的鏈接"
     :command.editor/open-link-in-sidebar    "在側邊欄打開"
     :command.editor/expand-block-children   "展開"
     :command.editor/collapse-block-children "折疊"
     :command.editor/select-block-up         "選擇上方的塊"
     :command.editor/select-block-down       "選擇下方的塊"
     :command.editor/select-all-blocks       "選擇所有塊"
     :command.ui/toggle-help                 "顯示/關閉幫助"
     :command.git/commit                     "提交消息"
     :command.go/search                      "全文搜索"
     :command.ui/toggle-document-mode        "切換文檔模式"
     :command.ui/toggle-theme                "“在暗色/亮色主題之間切換”"
     :command.ui/toggle-right-sidebar        "啟用/關閉右側欄"
     :command.ui/toggle-new-block            "切換 Enter/Shift+Enter 以插入新塊"
     :command.go/journals                    "跳轉到日記"}
    :de
    {:shortcut.category/formatting            "Formatierung"
     :command.editor/indent                  "Block einrücken"
     :command.editor/outdent                 "Block ausrücken"
     :command.editor/move-block-up           "Block nach oben verschieben"
     :command.editor/move-block-down         "Block nach unten verschieben"
     :command.editor/new-block               "Neuen Block erstellen"
     :command.editor/new-line                "Neue Zeile innerhalb des Blocks erstellen"
     :command.editor/zoom-in                 "Heranzoomen"
     :command.editor/zoom-out                "Herauszoomen"
     :command.editor/follow-link             "Link unter dem Cursor folgen"
     :command.editor/open-link-in-sidebar    "Link in Seitenleiste öffnen"
     :command.editor/expand-block-children   "Erweitern"
     :command.editor/collapse-block-children "Zusammenklappen"
     :command.editor/select-block-up         "Block oberhalb auswählen"
     :command.ui/toggle-help                 "Hilfe aktivieren"
     :command.go/search                      "Volltextsuche"
     :command.ui/toggle-document-mode        "Dokumentenmodus umschalten"
     :command.ui/toggle-theme                "Umschalten zwischen dunklem/hellem Thema"
     :command.ui/toggle-right-sidebar        "Rechte Seitenleiste umschalten"
     :command.ui/toggle-new-block            "Umschalten von Enter/Shift+Enter zum Einfügen eines neuen Blocks"
     :command.go/journals                    "Zu Journalen springen"
     :command.git/commit                     "Git Commit-Nachricht"
     :command.editor/select-block-down       "Block unterhalb auswählen"
     :command.editor/select-all-blocks       "Alle Blöcke auswählen"}
    :fr
    {:shortcut.category/formatting            "Formats"
     :command.editor/indent                  "Indenter un Bloc vers la droite"
     :command.editor/outdent                 "Indenter un Bloc vers la gauche"
     :command.editor/move-block-up           "Déplacer un bloc au dessus"
     :command.editor/move-block-down         "Déplacer un bloc en dessous"
     :command.editor/new-block               "Créer un nouveau bloc"
     :command.editor/new-line                "Aller à la ligne dans un bloc"
     :command.editor/zoom-in                 "Zoomer"
     :command.editor/zoom-out                "Dézoomer"
     :command.editor/follow-link             "Suivre le lien sous le curseur"
     :command.editor/open-link-in-sidebar    "Ouvrir le lien dans la barre latérale"
     :command.editor/expand-block-children   "Etendre"
     :command.editor/collapse-block-children "Réduire"
     :command.editor/select-block-up         "Sélectionner le bloc au dessus"
     :command.editor/select-block-down       "Sélectionner le bloc en dessous"
     :command.editor/select-all-blocks       "Sélectionner tous les blocs"
     :command.ui/toggle-help                 "Afficher l'aide"
     :command.git/commit                     "Message de commit Git"
     :command.go/search                      "Recherche globale dans le texte"
     :command.ui/toggle-document-mode        "Intervertir le mode document"
     :command.ui/toggle-theme                "Intervertir le thème foncé/clair"
     :command.ui/toggle-right-sidebar        "Afficher/cacher la barre latérale"
     :command.ui/toggle-new-block            "Activer Entreée ou Shift+Enter pour insérer un bloc"
     :command.go/journals                    "Aller au Journal"}
    :af
    {:shortcut.category/formatting            "Formatering"
     :command.editor/indent                  "Ingekeepte blok oortjie"
     :command.editor/outdent                 "Oningekeepte blok"
     :command.editor/move-block-up           "Skuif Blok Boontoe"
     :command.editor/move-block-down         "Skuif Blok Ondertoe"
     :command.editor/new-block               "Skep 'n nuwe blok"
     :command.editor/new-line                "Nuwe lyn in blok"
     :command.editor/zoom-in                 "Zoem in"
     :command.editor/zoom-out                "Zoem uit"
     :command.editor/follow-link             "Volg die skakel onder die wyser"
     :command.editor/open-link-in-sidebar    "Maak skakel in kantlys oop"
     :command.editor/expand-block-children   "Brei uit"
     :command.editor/collapse-block-children "Vou in"
     :command.editor/select-block-up         "Kies blok bo"
     :command.editor/select-block-down       "Kies blok onder"
     :command.editor/select-all-blocks       "Kies alle blokke"
     :command.ui/toggle-help                 "Wissel help"
     :command.git/commit                     "Jou git stoor boodskap"
     :command.go/search                      "Volteks soek"
     :command.ui/toggle-document-mode        "Wissel dokument modus"
     :command.go/journals                    "Spring na joernale"
     :command.ui/toggle-theme                "Wissel tussen donker/lig temas"
     :command.ui/toggle-right-sidebar        "Wissel regter sybalk"
     :command.ui/toggle-new-block            "Wissel Enter/Shift+enter vir die byvoeging van nuwe blokke"}
    :es
    {:shortcut.category/formatting            "Formato"
     :shortcut.category/basics                "Básico"
     :shortcut.category/navigating            "Navegación"
     :shortcut.category/block-editing         "Edición de bloque general"
     :shortcut.category/block-command-editing "Comandos edición de bloque"
     :shortcut.category/block-selection       "Selección de bloques (pulsar Esc para salir)"
     :shortcut.category/toggle                "Alternar"
     :shortcut.category/others                "Otros"
     :command.editor/indent                  "Aumentar sangría"
     :command.editor/outdent                 "Disminuir sangría"
     :command.editor/move-block-up           "Mover bloque arriba"
     :command.editor/move-block-down         "Mover bloque abajo"
     :command.editor/new-block               "Crear bloque nuevo"
     :command.editor/new-line                "Nueva linea en bloque"
     :command.editor/zoom-in                 "Acercar / Adelante"
     :command.editor/zoom-out                "Alejar / Atrás"
     :command.editor/follow-link             "Seguir enlace bajo el cursor"
     :command.editor/open-link-in-sidebar    "Abrir enlace en barra lateral"
     :command.editor/expand-block-children   "Expandir"
     :command.editor/collapse-block-children "Colapsar"
     :command.editor/select-block-up         "Seleccionar bloque de arriba"
     :command.editor/select-block-down       "Seleccionar bloque de abajo"
     :command.editor/select-all-blocks       "Seleccionar todos los bloques"
     :command.ui/toggle-help                 "Alternar ayuda"
     :command.git/commit                     "Confirmar"
     :command.go/search                      "Buscar en el grafo"
     :command.go/search-in-page              "Buscar en la página actual"
     :command.ui/toggle-document-mode        "Alternar modo documento"
     :command.ui/toggle-contents             "Alternar Contenido en barra lateral"
     :command.ui/toggle-theme                "Alternar entre tema claro/oscuro"
     :command.ui/toggle-right-sidebar        "Alternar barra lateral"
     :command.ui/toggle-settings             "Alternar Opciones"
     :command.ui/toggle-new-block            "Alternar Enter/Shift+Enter para crear nuevas lineas"
     :command.go/journals                    "Ir a los diarios"
     :command.ui/toggle-wide-mode            "Alternar modo ancho"
     :command.ui/toggle-brackets             "Alternar corchetes"
     :command.search/re-index                "Reconstruir índice de búsqueda"
     :command.graph/re-index                 "Reindexar el grafo completo"
     :command.editor/bold                    "Negrita"
     :command.editor/italics                 "Cursiva"
     :command.editor/insert-link             "Enlace html"
     :command.editor/highlight               "Resaltado"
     :command.editor/undo                    "Deshacer"
     :command.editor/redo                    "Rehacer"
     :command.editor/copy                    "Copiar"
     :command.editor/cut                     "Pegar"
     :command.editor/up                      "Mover cursor arriba / Seleccionar arriba"
     :command.editor/down                    "Mover cursor abajo / Seleccionar abajo"
     :command.editor/left                    "Mover cursor a la izquierda / Abrir bloque seleccionado al inicio"
     :command.editor/right                   "Mover cursor a la derecha / Abrir bloque seleccionado al final"
     :command.editor/backspace               "Retroceso / Eliminar hacia atrás"
     :command.editor/delete                  "Suprimir / Eliminar hacia delante"
     :command.editor/cycle-todo              "Rotar estado TODO del elemento"
     :command.editor/clear-block             "Borrar contenido del bloque"
     :command.editor/kill-line-before        "Borrar linea antes del cursor"
     :command.editor/kill-line-after         "Borrar linea despues del cursor"
     :command.editor/beginning-of-block      "Mover cursor al inicio del bloque"
     :command.editor/end-of-block            "Mover cursor al final del bloque"
     :command.editor/forward-word            "Mover cursor una palabra adelante"
     :command.editor/backward-word           "Mover cursor una palabra atrás"
     :command.editor/forward-kill-word       "Borrar palabra posterior"
     :command.editor/backward-kill-word      "Borrar palabra anterior"
     :command.editor/open-edit               "Editar bloque seleccionado"
     :command.editor/delete-selection        "Eliminar bloques seleccionados"
     :command.editor/toggle-open-blocks      "Alternar bloques abieros, (colapsar o expandir todos)"}
    :nb-NO
    {:shortcut.category/formatting            "Formatering"
     :shortcut.category/basics                "Basis"
     :shortcut.category/navigating            "Navigasjon"
     :shortcut.category/block-editing         "Blokkredigering generelt"
     :shortcut.category/block-command-editing "Blokkredigering kommandoer"
     :shortcut.category/block-selection       "Blokkseleksjon (trykk ESC for å avslutte)"
     :shortcut.category/toggle                "Veksling"
     :shortcut.category/others                "Annet"
     :command.editor/indent                  "Innrykk inn"
     :command.editor/outdent                 "Innrykk ut"
     :command.editor/move-block-up           "Flytt blokk opp"
     :command.editor/move-block-down         "Flytt blokk ned"
     :command.editor/new-block               "Opprett ny blokk"
     :command.editor/new-line                "Ny linje i nåværende blokk"
     :command.editor/zoom-in                 "Zoom inn / Fremover"
     :command.editor/zoom-out                "Zoom ut / Tilbake"
     :command.editor/follow-link             "Følg lenke under markøren"
     :command.editor/open-link-in-sidebar    "Åpne lenke i sidestolpe"
     :command.editor/expand-block-children   "Utvid"
     :command.editor/collapse-block-children "Slå sammen"
     :command.editor/select-block-up         "Velg blokk over"
     :command.editor/select-block-down       "Velg blokk under"
     :command.editor/select-all-blocks       "Velg alle blokker"
     :command.ui/toggle-help                 "Vis hjelp"
     :command.git/commit                     "Git comitt beskjed"
     :command.go/search                      "Fulltekst søk"
     :command.go/search-in-page              "Søk på nåværende side"
     :command.ui/toggle-document-mode        "Aktiver dokumentmodus"
     :command.ui/toggle-contents             "Åpne favoritter i sidestolpen"
     :command.ui/toggle-theme                "Veksle mellom lyst og mørkt tema"
     :command.ui/toggle-right-sidebar        "Aktiver høyre sidestolpe"
     :command.ui/toggle-settings             "Åpne innstillinger"
     :command.ui/toggle-new-block            "Veksle mellom Enter og Shift+Enter for ny linje"
     :command.go/journals                    "Gå til dagbok"
     :command.ui/toggle-wide-mode            "Aktiver vid-modus"
     :command.ui/toggle-brackets             "Aktiver vising av klammer"
     :command.search/re-index                "Gjenoppbygg søkeindeks"
     :command.graph/re-index                 "Reindekser hele diagrammet"
     :command.editor/bold                    "Fet"
     :command.editor/italics                 "Kursiv"
     :command.editor/insert-link             "HTML lenke"
     :command.editor/highlight               "Markering"
     :command.editor/undo                    "Angre"
     :command.editor/redo                    "Gjør om"
     :command.editor/copy                    "Kopier"
     :command.editor/cut                     "Klipp ut"
     :command.editor/up                      "Flytt markøren opp / Velg opp"
     :command.editor/down                    "Flytt markøren ned / Velg ned"
     :command.editor/left                    "Flytt markøren til venstre / Åpne valgt blokk på begynnelsen"
     :command.editor/right                   "Flytt markøren til høyre / Åpne valgt blokk på slutten"
     :command.editor/backspace               "Backspace / Slett bakover"
     :command.editor/delete                  "Delete / Slett forover"
     :command.editor/cycle-todo              "Veksle TODO status for valg linje"
     :command.editor/clear-block             "Slett alt innhold i blokken"
     :command.editor/kill-line-before        "Slett linje foran markøren"
     :command.editor/kill-line-after         "Slett linsje etter markøren"
     :command.editor/beginning-of-block      "Flytt markøren til begynnelsen av blokken"
     :command.editor/end-of-block            "Flytt markøren til slutten av blokken"
     :command.editor/forward-word            "Flytt markøren frem ett ord"
     :command.editor/backward-word           "Flytt markøren bakover ett ord"
     :command.editor/forward-kill-word       "Slett ett ord forover"
     :command.editor/backward-kill-word      "Slett ett ord bakover"
     :command.editor/open-edit               "Rediger valgt blokk"
     :command.editor/delete-selection        "Slett valgte blokker"
     :command.editor/toggle-open-blocks      "Veksle åpne blokker (slå sammen eller utvid alle blokker)"}
     :pt-PT
    {:shortcut.category/formatting            "Formatação"
     :shortcut.category/basics                "Básico"
     :shortcut.category/navigating            "Navegação"
     :shortcut.category/block-editing         "Edição geral de blocos"
     :shortcut.category/block-command-editing "Comandos de edição de blocos"
     :shortcut.category/block-selection       "Seleção de blocos (premir Esc para sair)"
     :shortcut.category/toggle                "Alternar"
     :shortcut.category/others                "Outros"
     :command.editor/indent                  "Aumentar avanço de parágrafo"
     :command.editor/outdent                 "Diminuir avanço de parágrafo"
     :command.editor/move-block-up           "Mover bloco para cima"
     :command.editor/move-block-down         "Mover bloco para baixo"
     :command.editor/new-block               "Criar novo bloco"
     :command.editor/new-line                "Nova linha no bloco actual"
     :command.editor/zoom-in                 "Aproximar / Para a frente"
     :command.editor/zoom-out                "Afastar / Para trás"
     :command.editor/follow-link             "Seguir ligação sob o cursor"
     :command.editor/open-link-in-sidebar    "Abrir ligação na barra lateral"
     :command.editor/expand-block-children   "Expandir"
     :command.editor/collapse-block-children "Colapsar"
     :command.editor/select-block-up         "Selecionar bloco acima"
     :command.editor/select-block-down       "Selecionar bloco abaixo"
     :command.editor/select-all-blocks       "Selecionar todos os blocos"
     :command.ui/toggle-help                 "Alternar ajuda"
     :command.git/commit                     "Confirmar"
     :command.go/search                      "Pesquisar no grafo"
     :command.go/search-in-page              "Pesquisar na página atual"
     :command.ui/toggle-document-mode        "Alternar modo de documento"
     :command.ui/toggle-contents             "Alternar Conteúdo na barra lateral"
     :command.ui/toggle-theme                "Alternar entre tema claro/escuro"
     :command.ui/toggle-right-sidebar        "Alternar barra lateral"
     :command.ui/toggle-settings             "Alternar Opções"
     :command.ui/toggle-new-block            "Alternar Enter/Shift+Enter para criar novas linhas"
     :command.go/journals                    "Ir para diários"
     :command.ui/toggle-wide-mode            "Alternar modo de ecrã amplo"
     :command.ui/toggle-brackets             "Alternar parênteses rectos"
     :command.search/re-index                "Reconstruir índice de pesquisa"
     :command.graph/re-index                 "Reindexar o grafo completo"
     :command.editor/bold                    "Negrito"
     :command.editor/italics                 "Itálico"
     :command.editor/insert-link             "Inserir ligação html"
     :command.editor/highlight               "Realçado"
     :command.editor/undo                    "Desfazer"
     :command.editor/redo                    "Refazer"
     :command.editor/copy                    "Copiar"
     :command.editor/cut                     "Cortar"
     :command.editor/up                      "Mover cursor para cima / Selecionar para cima"
     :command.editor/down                    "Mover cursor para baixo / Selecionar para baixo"
     :command.editor/left                    "Mover cursor para a esquerda / Abrir bloco selecionado no início"
     :command.editor/right                   "Mover cursor para a direita / Abrir bloco selecionado no final"
     :command.editor/backspace               "Retroceder / Eliminar para atrás"
     :command.editor/delete                  "Apagar / Eliminar para a frente"
     :command.editor/cycle-todo              "Alternar estado TODO do elemento"
     :command.editor/clear-block             "Apagar conteúdo do bloco"
     :command.editor/kill-line-before        "Apagar linha antes do cursor"
     :command.editor/kill-line-after         "Apagar linha depois do cursor"
     :command.editor/beginning-of-block      "Mover o cursor para o início do bloco"
     :command.editor/end-of-block            "Mover o cursor para o fim do bloco"
     :command.editor/forward-word            "Mover o cursor para a próxima palavra"
     :command.editor/backward-word           "Mover o cursor para a palavra anterior"
     :command.editor/forward-kill-word       "Apagar a próxima palavra"
     :command.editor/backward-kill-word      "Apagar a palavra anterior"
     :command.editor/open-edit               "Editar bloco selecionado"
     :command.editor/delete-selection        "Eliminar blocos selecionados"
     :command.editor/toggle-open-blocks      "Alternar blocos abertos (colapsar ou expandir todos)"}}))
