(ns frontend.dicts.de
  "Provides translation to DE"
  #?(:cljs (:require [shadow.resource :as rc])))

(def dict
  {:all-files "Alle Dateien"
   :all-graphs "Alle Graphen"
   :all-journals "Alle Journale"
   :all-pages "Alle Seiten"
   :all-whiteboards "Alle Whiteboards"
   :auto-heading "Automatische Überschrift"
   :bold "Fett"
   :cancel "Abbrechen"
   :close "Schließen"
   :code "Quelltext"
   :delete "Löschen"
   :discourse-title "Unser Forum!"
   :download "Herunterladen"
   :export "Exportieren"
   :export-edn "Als EDN exportieren"
   :export-graph "Graph exportieren"
   :export-json "Als JSON exportieren"
   :export-markdown "Als Standard-Markdown exportieren (ohne Block-Eigenschaften)"
   :export-opml "Als OPML exportieren"
   :export-page "Seite exportieren"
   :export-public-pages "Öffentliche Seiten exportieren"
   :export-roam-json "Als Roam JSON exportieren"
   :graph "Graph"
   :graph-search "Graph durchsuchen"
   :heading "Überschrift {1}"
   :highlight "Hervorhebung"
   :host "Host"
   :import "Importieren"
   :importing "Importiere"
   :italics "Kursiv"
   :join-community "Treten Sie der Community bei"
   :language "Sprache"
   :loading "Laden"
   :loading-files "Dateien laden"
   :login "Einloggen"
   :logout "Ausloggen"
   :more "Mehr"
   :new-graph "Neuen Graphen hinzufügen"
   :new-page "Neue Seite"
   :new-whiteboard "Neues Whiteboard"
   :open-a-directory "Öffne ein lokales Verzeichnis"
   :open-new-window "Neues Fenster"
   :page-search "In der aktuellen Seite suchen"
   :parsing-files "Dateien analysieren"
   :plugins "Plugins"
   :port "Port"
   :re-index "Neu indizieren"
   :re-index-detail "Graph neu aufbauen"
   :re-index-discard-unsaved-changes-warning "Bei der Neuindizierung wird der aktuelle Graph verworfen, und alle Dateien werden wieder so verarbeitet, wie sie derzeit auf der Festplatte gespeichert sind. Dabei gehen nicht gespeicherte Änderungen verloren und es kann eine Weile dauern. Fortfahren?"
   :re-index-multiple-windows-warning "Sie müssen die anderen Fenster schließen, bevor Sie diesen Graphen erneut indizieren "
   :relaunch-confirm-to-work "Sie sollten die App neu starten, damit sie funktioniert. Möchten Sie sie jetzt neu starten?"
   :remove-background "Hintergrund entfernen"
   :remove-heading "Überschrift entfernen"
   :remove-orphaned-pages "Verweiste Seiten entfernen"
   :save "Speichern"
   :search "Suchen oder Seite erstellen"
   :settings "Einstellungen"
   :settings-of-plugins "Plugins"
   :strikethrough "Durchstreichung"
   :submit "Senden"
   :sync-from-local-changes-detected "Aktualisieren erkennt und verarbeitet Dateien, die auf Ihrer Festplatte geändert wurden und vom aktuellen Inhalt der Logseq-Seite abweichen. Fortfahren?"
   :sync-from-local-files "Aktualisieren"
   :sync-from-local-files-detail "Änderungen aus lokalen Dateien importieren"
   :themes "Themen"
   :type "Typ"
   :untitled "Ohne Titel"
   :yes "Ja"

   :accessibility/skip-to-main-content "Zum Hauptinhalt springen"

   :asset/confirm-delete "{1} wirklich löschen?"
   :asset/copy "Bild kopieren"
   :asset/delete "Bild löschen"
   :asset/maximize "Bild maximieren"
   :asset/open-in-browser "Bild im Browser öffnen"
   :asset/physical-delete "Datei ebenfalls entfernen (Achtung: die Datei kann nicht wiederhergestellt werden)"
   :asset/show-in-folder "Bild im Ordner anzeigen"

   :block/name "Seitenname"

   :color/gray "Grau"
   :color/red "Rot"
   :color/yellow "Gelb"
   :color/green "Grün"
   :color/blue "Blau"
   :color/purple "Violett"
   :color/pink "Rosa"

   :command-palette/prompt "Befehl eingeben"

   :content/click-to-edit "Klicken zum bearbeiten"
   :editor/copy "Kopieren"
   :editor/cut "Ausschneiden"
   :content/copy-block-emebed "Blockeinbettung kopieren"
   :content/copy-block-ref "Blockreferenz kopieren"
   :content/open-in-sidebar "In Seitenleiste öffnen"

   :editor/block-search "Nach einem Block suchen"

   :file-sync/graph-deleted "Der aktuelle Remote-Graph wurde gelöscht"
   :file-sync/other-user-graph "Aktueller lokaler Graph ist an den Remote-Graph des anderen Benutzers gebunden. Kann also nicht mit der Synchronisierung beginnen."

   :file/format-not-supported "Format .{1} wird nicht unterstützt."
   :file/last-modified-at "Zuletzt geändert am"
   :file/name "Dateinamen"
   :file/no-data "Keine Daten"
   :file/validate-existing-file-error "Seite existiert bereits mit einer anderen Datei: {1}, aktuelle Datei: {2}. Bitte behalten Sie nur eine davon und indizieren Sie Ihren Graphen neu."

   :file-rn/all-action "Alle Aktionen anwenden!"
   :file-rn/apply-rename "Anwenden des Vorgangs zur Datei-Umbenennung"
   :file-rn/close-panel "Das Panel schließen"
   :file-rn/confirm-proceed "Format aktualisieren!"
   :file-rn/filename-desc-1 "Diese Einstellung legt fest, wie eine Seite in einer Datei gespeichert wird. Logseq speichert eine Seite in einer Datei mit demselben Namen."
   :file-rn/filename-desc-2 "Einige Zeichen wie \"/\" oder \"?\" sind für einen Dateinamen ungültig."
   :file-rn/filename-desc-3 "Logseq ersetzt ungültige Zeichen durch ihr URL-kodiertes Äquivalent, um sie gültig zu machen (z. B. wird \"?\" zu \"%3F\")."
   :file-rn/filename-desc-4 "Auch das Namespace-Trennzeichen \"/\" wird aus ästhetischen Gründen durch \"___\" (dreifacher Unterstrich) ersetzt."
   :file-rn/format-deprecated "Sie verwenden derzeit ein veraltetes Format. Es wird dringend empfohlen, auf das neueste Format zu aktualisieren. Bitte sichern Sie vor dem Vorgang Ihre Daten und schließen Sie Logseq-Clients auf anderen Geräten."
   :file-rn/instruct-1 "Die Aktualisierung des Dateinamenformats erfolgt in zwei Schritten:"
   :file-rn/instruct-2 "1. Klicken "
   :file-rn/instruct-3 "2. Befolgen Sie die nachstehenden Anweisungen, um die Dateien in das neue Format umzubenennen:"
   :file-rn/legend "🟢 Optionale Umbenennungsaktionen; 🟡 Umbenennungsaktion erforderlich, um Titeländerung zu vermeiden; 🔴 Inkompatible Änderung."
   :file-rn/need-action "Es werden Aktionen zur Umbenennung von Dateien vorgeschlagen, damit sie dem neuen Format entsprechen. Eine erneute Indizierung ist auf allen Geräten erforderlich, wenn die umbenannten Dateien synchronisiert werden."
   :file-rn/no-action "Gut gemacht! Keine weiteren Maßnahmen erforderlich."
   :file-rn/optional-rename "Vorschlag: "
   :file-rn/or-select-actions " oder benennen Sie die folgenden Dateien einzeln um, dann "
   :file-rn/or-select-actions-2 ". Diese Aktionen stehen nicht mehr zur Verfügung, wenn Sie dieses Fenster schließen."
   :file-rn/otherwise-breaking "Oder der Titel wird zu"
   :file-rn/re-index "Es wird dringend empfohlen, die Indizierung nach der Umbenennung der Dateien und nach der Synchronisierung auf anderen Geräten zu wiederholen."
   :file-rn/rename "Datei \"{1}\" in \"{2}\" umbenennen"
   :file-rn/select-confirm-proceed "Dev: Format schreiben"
   :file-rn/select-format "(Entwicklermodus-Option, gefährlich!) Dateinamenformat auswählen"
   :file-rn/suggest-rename "Aktion erforderlich: "
   :file-rn/unreachable-title "Warnung! Der Seitenname wird unter dem aktuellen Dateinamenformat zu {1}, es sei denn, die Eigenschaft `title::` wird manuell gesetzt"

   :graph/all-graphs "Alle Graphen"
   :graph/local-graphs "Lokale Graphen"
   :graph/persist "Logseq synchronisiert gerade den internen Status, bitte warten Sie einige Sekunden."
   :graph/persist-error "Synchronisation des internen Status fehlgeschlagen."
   :graph/remote-graphs "Remote Graphen"
   :graph/save "Speichern..."
   :graph/save-error "Speichern fehlgeschlagen"
   :graph/save-success "Erfolgreich gespeichert"

   :help-shortcut-title "Hier klicken, um Tastenkombinationen und weitere Tipps zu sehen"
   :help/about "Über Logseq"
   :help/awesome-logseq "Awesome Logseq"
   :help/block-content-autocomplete "Blockinhalt (Quelltext, Zitate, Abfragen, etc.) Autovervollständigung"
   :help/block-reference "Blockverweis"
   :help/blog "Logseq Blog"
   :help/bug "Fehlerbericht"
   :help/changelog "Änderungsprotokoll"
   :help/context-menu "Kontextmenü"
   :help/docs "Dokumentation"
   :help/feature "Feature-Anfrage"
   :help/forum-community "Forum-Community"
   :help/markdown-syntax "Markdown-Syntax"
   :help/org-mode-syntax "Org-Mode-Syntax"
   :help/privacy "Datenschutzrichtlinie"
   :help/reference-autocomplete "Seitenverweis Autovervollständigung"
   :help/roadmap "Roadmap"
   :help/shortcut "Tastaturkürzel"
   :help/shortcut-page-title "Tastaturbefehl"
   :help/shortcuts "Tastaturkürzel"
   :help/shortcuts-triggers "Auslöser"
   :help/slash-autocomplete "/-Autovervollständigung"
   :help/start "Einstieg"
   :help/terms "Nutzungsbedingungen"
   :help/open-link-in-sidebar "Link in Seitenleiste öffnen"

   :left-side-bar/create "Erstellen"
   :left-side-bar/journals "Journale"
   :left-side-bar/nav-favorites "Favoriten"
   :left-side-bar/nav-recent-pages "Neuste"
   :left-side-bar/new-page "Neue Seite"
   :left-side-bar/new-whiteboard "Neues Whiteboard"

   :linked-references/filter-search "Suche in verknüpften Seiten"

   :notification/clear-all "Alles löschen"

   :on-boarding/add-graph "Graph hinzufügen"
   :on-boarding/demo-graph "Dies ist ein Demo-Graph. Änderungen werden nicht gespeichert, solange Sie kein lokales Verzeichnis öffnen."
   :on-boarding/new-graph-desc-1 "Logseq unterstützt sowohl Markdown als auch Org-mode. Sie können ein bestehendes Verzeichnis öffnen oder auf Ihrem Rechner ein neues Verzeichnis anlegen. Ein Verzeichnis wird auch als Ordner bezeichnet. Ihre Daten werden nur auf diesem Gerät gespeichert."
   :on-boarding/new-graph-desc-2 "Nachdem Sie ein Verzeichnis geöffnet haben, werden darin drei Ordner angelegt:"
   :on-boarding/new-graph-desc-3 "/journals - enthält Ihre Journal-Seiten"
   :on-boarding/new-graph-desc-4 "/pages - enthält die anderen Seiten"
   :on-boarding/new-graph-desc-5 "/logseq - enthält die Konfiguration, custom.css und Metadaten."
   :on-boarding/open-local-dir "Lokales Verzeichnis öffnen"
   :on-boarding/tour-whiteboard-home "{1} Zuhause für Ihre Whiteboards"
   :on-boarding/tour-whiteboard-home-description "Whiteboards haben einen eigenen Bereich in der App, in dem Sie sie auf einen Blick sehen, neue erstellen oder einfach löschen können."
   :on-boarding/tour-whiteboard-new "{1} Erstelle neues Whiteboard"
   :on-boarding/tour-whiteboard-new-description "Es gibt mehrere Möglichkeiten, ein neues Whiteboard zu erstellen. Eine davon ist immer direkt hier im Dashboard."
   :on-boarding/welcome-whiteboard-modal-title "Eine neue Leinwand für Ihre Gedanken."
   :on-boarding/welcome-whiteboard-modal-description "Whiteboards sind ein großartiges Werkzeug für Brainstorming und Organisation. Jetzt können Sie jeden Ihrer Gedanken aus der Wissensdatenbank oder neue Gedanken nebeneinander auf einer räumlichen Leinwand platzieren, um sie zu verbinden, zu assoziieren und auf neue Weise zu verstehen."
   :on-boarding/welcome-whiteboard-modal-skip "Überspringen"
   :on-boarding/welcome-whiteboard-modal-start "Whiteboarding beginnen"

   :page/add-to-favorites "Zu Favoriten hinzufügen"
   :page/backlinks "Backlinks"
   :page/copy-page-url "Seiten-URL kopieren"
   :page/created-at "Erstellt am"
   :page/delete "Seite löschen"
   :page/delete-confirmation "Diese Seite und die zugehörige Datei löschen?"
   :page/earlier "Früher"
   :page/make-private "Privat machen"
   :page/make-public "Beim Export in HTML veröffentlichen"
   :page/open-backup-directory "Verzeichnis für Seiten-Backups öffnen"
   :page/open-in-finder "Im Verzeichnis öffnen"
   :page/open-with-default-app "Mit Standard-Anwendung öffnen"
   :page/presentation-mode "Präsentationsmodus"
   :page/show-journals "Journal anzeigen"
   :page/show-whiteboards "Whiteboards anzeigen"
   :page/unfavorite "Seite aus Favoriten entfernen"
   :page/updated-at "Aktualisiert am"
   :page/version-history "Seitenverlauf anzeigen"

   :paginates/next "Weiter"
   :paginates/pages "Total {1} Seiten"
   :paginates/prev "Zurück"

   :pdf/copy-ref "Referenz kopieren"
   :pdf/copy-text "Text kopieren"
   :pdf/doc-metadata "Metadaten des Dokuments"
   :pdf/hl-block-colored "Farbige Beschriftung für Highlight-Block"
   :pdf/linked-ref "Verlinkte Referenzen"
   :pdf/toggle-dashed "Gestrichelter Stil für die Hervorhebung von Bereichen"

   :plugin/all "Alle"
   :plugin/check-all-updates "Alle Updates überprüfen"
   :plugin/check-update "Update überprüfen"
   :plugin/contribute "✨ Schreiben und veröffentlichen Sie ein neues Plugin"
   :plugin/custom-js-alert "Datei custom.js gefunden. Darf sie ausgeführt werden? (Wenn Sie den Inhalt dieser Datei nicht verstehen, wird empfohlen, die Ausführung nicht zuzulassen, da dies gewisse Sicherheitsrisiken birgt)."
   :plugin/delete-alert "Wollen Sie wirklich das Plugin [{1}] deinstallieren?"
   :plugin/disabled "Deaktiviert"
   :plugin/downloads "Downloads"
   :plugin/enabled "Aktiviert"
   :plugin/install "Installieren"
   :plugin/installed "Installiert"
   :plugin/installing "Installiere"
   :plugin/load-unpacked "Entpacktes Plugin laden"
   :plugin/marketplace "Marktplatz"
   :plugin/not-installed "Nicht installiert"
   :plugin/open-package "Paket öffnen"
   :plugin/open-settings "Einstellungen öffnen"
   :plugin/refresh-lists "Liste aktualisieren"
   :plugin/reload "Neu laden"
   :plugin/restart "App neu starten"
   :plugin/stars "Sterne"
   :plugin/title "Titel"
   :plugin/uninstall "Deinstallieren"
   :plugin/unpacked "Entpackt"
   :plugin/unpacked-tips "Plugin-Verzeichnis auswählen"
   :plugin/update "Aktualisierung"
   :plugin/update-available "Aktualisierung verfügbar"
   :plugin/updating "Aktualisiere"
   :plugin/up-to-date "Es ist auf dem neuesten Stand"

   :plugin.install-from-file/menu-title "Aus plugins.edn installieren"
   :plugin.install-from-file/title "Plugins aus plugins.edn installieren"
   :plugin.install-from-file/notice "Die folgenden Plugins werden Ihre Plugins ersetzen:"
   :plugin.install-from-file/success "Alle Plugins installiert!"

   :right-side-bar/all-pages "Alle Seiten"
   :right-side-bar/block-ref "Blockreferenz"
   :right-side-bar/contents "Inhalt"
   :right-side-bar/flashcards "Karteikarten"
   :right-side-bar/graph-view "Graph-Ansicht"
   :right-side-bar/help "Hilfe"
   :right-side-bar/new-page "Neue Seite"
   :right-side-bar/page-graph "Seiten-Graph"
   :right-side-bar/separator "Griff zur Größenänderung der rechten Seitenleiste"
   :right-side-bar/show-journals "Zeige Journale"
   :right-side-bar/switch-theme "Zu {1} Thema wechseln"
   :right-side-bar/whiteboards "Whiteboards"

   :search/items "Einträge"
   :search/page-names "In Seitennamen suchen"
   :search/publishing "Suchen"
   :search/result-for "Suchergebnisse für"

   :search-item/block "Block"
   :search-item/file "Datei"
   :search-item/page "Seite"
   :search-item/whiteboard "Whiteboard"

   :select/default-prompt "Wählen Sie einen"

   :select.graph/add-graph "Ja, weiteren Graphen hinzufügen"
   :select.graph/empty-placeholder-description "Keine übereinstimmenden Graphen. Möchten Sie einen weiteren hinzufügen?"
   :select.graph/prompt "Einen Graphen auswählen"

   :settings-page/alpha-features "Alpha-Funktionen"
   :settings-page/auto-updater "Automatisches Update"
   :settings-page/beta-features "Beta-Funktionen"
   :settings-page/clear "Löschen"
   :settings-page/clear-cache "Cache löschen"
   :settings-page/clear-cache-warning "Wenn Sie den Cache löschen, werden offene Graphen verworfen. Nicht gespeicherte Änderungen gehen dabei verloren."
   :settings-page/current-version "Aktuelle Version"
   :settings-page/custom-configuration "Individuelle Konfiguration"
   :settings-page/custom-date-format "Bevorzugtes Datumsformat"
   :settings-page/custom-date-format-warning "Neuindizierung erforderlich! Vorhandene Journal-Verweise würden nicht mehr funktionieren!"
   :settings-page/custom-global-configuration "Benutzerdefinierte globale Konfiguration"
   :settings-page/custom-theme "Individuelles Theme"
   :settings-page/customize-shortcuts "Tastaturbefehle"
   :settings-page/developer-mode "Entwicklermodus"
   :settings-page/developer-mode-desc "Der Entwicklermodus hilft Mitwirkenden und Entwicklern von Erweiterungen, ihre Integration mit Logseq effizienter zu testen."
   :settings-page/disable-sentry "Nutzungs- und Diagnostik-Daten an Logseq senden"
   :settings-page/disable-sentry-desc "Logseq wird niemals Ihre lokale Graphdatenbank sammeln oder Ihre Daten verkaufen."
   :settings-page/edit-config-edn "config.edn bearbeiten (im aktuellen Repository)"
   :settings-page/edit-custom-css "custom.css bearbeiten"
   :settings-page/edit-export-css "export.css bearbeiten"
   :settings-page/edit-global-config-edn "Globale config.edn bearbeiten"
   :settings-page/edit-setting "Bearbeiten"
   :settings-page/enable-all-pages-public "Alle Seiten bei Veröffentlichung öffentlich"
   :settings-page/enable-block-time "Zeitstempel für Blöcke aktivieren"
   :settings-page/enable-flashcards "Karteikarten"
   :settings-page/enable-journals "Journale einschalten"
   :settings-page/enable-shortcut-tooltip "Tooltips für Verknüpfungen aktivieren"
   :settings-page/enable-timetracking "Zeiterfassung einschalten"
   :settings-page/enable-tooltip "Tooltips"
   :settings-page/enable-whiteboards "Whiteboards"
   :settings-page/export-theme "Theme exportieren"
   :settings-page/filename-format "Dateinamen-Format"
   :settings-page/git-commit-delay "Anzahl Sekunden für Git Auto Commit"
   :settings-page/git-confirm "Sie müssen die App neu starten, nachdem Sie die Git-Einstellungen angepasst haben."
   :settings-page/git-switcher-label "Git Auto Commit aktivieren"
   :settings-page/home-default-page "Standard-Homepage einrichten"
   :settings-page/login-prompt "Um vor allen anderen auf neue Funktionen zugreifen zu können, müssen Sie ein Open Collective Sponsor oder Backer von Logseq sein und sich daher zuerst anmelden."
   :settings-page/network-proxy "Netzwerk-Proxy"
   :settings-page/plugin-system "Plugins"
   :settings-page/preferred-file-format "Bevorzugtes Datei-Format"
   :settings-page/preferred-outdenting "Logische Ausrückung"
   :settings-page/preferred-pasting-file "Einfügen der Datei bevorzugen"
   :settings-page/preferred-workflow "Bevorzugter Workflow"
   :settings-page/shortcut-settings "Verknüpfungen anpassen"
   :settings-page/show-brackets "Klammern anzeigen"
   :settings-page/show-full-blocks "Alle Zeilen einer Blockreferenz anzeigen"
   :settings-page/spell-checker "Rechtschreibprüfung"
   :settings-page/sync "Synchronisation"
   :settings-page/tab-advanced "Erweitert"
   :settings-page/tab-assets "Anlagen"
   :settings-page/tab-features "Funktionen"
   :settings-page/tab-editor "Editor"
   :settings-page/tab-general "Allgemein"
   :settings-page/tab-version-control "Versionskontrolle"

   :text/image "Bild"

   :tips/all-done "Alles erledigt"

   :tutorial/dummy-notes #?(:cljs (rc/inline "dummy-notes-en.md")
                            :default "dummy-notes-en.md")
   :tutorial/text #?(:cljs (rc/inline "tutorial-en.md")
                     :default "tutorial-en.md")

   :updater/new-version-install "Eine neue Version wurde heruntergeladen."
   :updater/quit-and-install "Neu starten, um zu installieren"

   :content/copy-block-url "Block-URL kopieren"
   :content/copy-export-as "Kopieren / Exportieren als.."
   :content/copy-ref "Diese Referenz kopieren"
   :content/delete-ref "Diese Referenz löschen"
   :content/replace-with-embed "Mit Verankerung ersetzen"
   :content/replace-with-text "Mit Text ersetzen"
   :context-menu/input-template-name "Wie lautet der Name der Vorlage?"
   :context-menu/make-a-flashcard "Eine Karteikarte erstellen"
   :context-menu/make-a-template "Eine Vorlage erstellen"
   :context-menu/preview-flashcard "Vorschau der Karteikarte"
   :context-menu/template-exists-warning "Vorlage existiert bereits!"
   :context-menu/template-include-parent-block "Einschließlich des übergeordneten Blocks in der Vorlage?"
   :dev/show-block-ast "(Dev) Block-AST anzeigen"
   :dev/show-block-data "(Dev) Block-Daten anzeigen"
   :dev/show-page-ast "(Dev) Seiten-AST anzeigen"
   :dev/show-page-data "(Dev) Seiten-Daten anzeigen"
   :editor/collapse-block-children "Alles einklappen"
   :editor/cycle-todo "Den TODO-Status des aktuellen Elements rotieren"
   :editor/delete-selection "Ausgewählte Blöcke entfernen"
   :editor/expand-block-children "Alles ausklappen"
   :page/logseq-is-having-a-problem "Logseq hat ein Problem festgestellt. Versuche zurückzukehren ..."
   :page/something-went-wrong "Es ist etwas schief gelaufen."
   :page/step "Schritt {1}"
   :page/try "Versuch"
   :plugin/found-n-updates "{1} Aktualisierungen gefunden"
   :plugin/found-updates "Aktualisierungen gefunden"
   :plugin/update-all-selected "Alle ausgewählten aktualisieren"
   :plugin/updates-downloading "Aktualisierungen werden heruntergeladen"
   :right-side-bar/history "(Dev) Verlauf rückgängig machen / wiederherstellen"
   :select/default-select-multiple "Ein oder mehrere auswählen"
   :settings-page/auto-expand-block-refs "Automatisch beim Heranzoomen Blockreferenzen erweitern..."

   :whiteboard/link-whiteboard-or-block "Whiteboard/Seite/Block verknüpfen"})
