(ns frontend.dicts.ja
  "Provides translation to JA"
  #?(:cljs (:require [shadow.resource :as rc])))

(def dict
  {:tutorial/text #?(:cljs (rc/inline "tutorial-ja.md")
                     :default "tutorial-ja.md")
   :tutorial/dummy-notes #?(:cljs (rc/inline "dummy-notes-ja.md")
                            :default "dummy-notes-ja.md")
   :on-boarding/demo-graph "これはデモ用のグラフなので変更内容は保存されません。保存するにはローカルフォルダを選んで新規グラフを追加してください。"
   :on-boarding/add-graph "新規グラフを追加"
   :on-boarding/open-local-dir "ここをクリックして、データ保存先のローカルフォルダを選んでください"
   :on-boarding/new-graph-desc-1 "LogseqはMarkdownとOrg-modeの両方をサポートしています。あなたのPC端末上の既存のフォルダ（ディレクトリ）を選ぶか新しいフォルダを作成してください。データはあなたのPC端末上にのみ保存されます。"
   :on-boarding/new-graph-desc-2 "フォルダを選ぶと、その中に3つのフォルダが作成されます："
   :on-boarding/new-graph-desc-3 "/journals - あなたの日誌が保存されます"
   :on-boarding/new-graph-desc-4 "/pages - その他のページが保存されます"
   :on-boarding/new-graph-desc-5 "/logseq - 設定ファイル、custom.css、その他のメタデータを保存します"
   :help/start "はじめに"
   :help/about "Logseqについて"
   :help/roadmap "ロードマップ"
   :help/bug "バグ報告"
   :help/feature "機能リクエスト"
   :help/changelog "更新履歴"
   :help/blog "Logseq ブログ"
   :help/docs "ドキュメント"
   :help/privacy "プライバシーポリシー"
   :help/terms "利用規約"
   :help/awesome-logseq "Awesome Logseq"
   :help/shortcuts "キーボードショートカット"
   :help/shortcuts-triggers "トリガー"
   :help/shortcut "ショートカット"
   :help/slash-autocomplete "スラッシュで自動補完"
   :help/block-content-autocomplete "ブロックコンテンツの自動補完"
   :help/reference-autocomplete "ページ参照の自動補完"
   :help/block-reference "ブロック参照"
   :help/open-link-in-sidebar "サイドバーでリンクを開く"
   :more "詳細"
   :search/result-for "Search result for "
   :search/items "items"
   :search/page-names "ページ名で検索"
   :help/context-menu "ブロックのコンテキストメニュー"
   :help/markdown-syntax "マークダウン文法"
   :help/org-mode-syntax "Org mode 文法"
   :bold "太字"
   :italics "斜体"
   :highlight "ハイライト"
   :strikethrough "取り消し線"
   :code "コード"
   :right-side-bar/help "ヘルプ"
   :right-side-bar/switch-theme "テーマ"
   :right-side-bar/contents "目次"
   :right-side-bar/page-graph "ページグラフ"
   :right-side-bar/block-ref "ブロック参照"
   :right-side-bar/graph-view "グラフビュー"
   :right-side-bar/all-pages "全ページ"
   :right-side-bar/flashcards "フラッシュカード"
   :right-side-bar/new-page "新規ページ"
   :left-side-bar/journals "日誌"
   :left-side-bar/new-page "新規ページ"
   :left-side-bar/nav-favorites "お気に入り"
   :left-side-bar/nav-recent-pages "最新"
   :page/presentation-mode "プレゼンテーション"
   :page/delete-confirmation "このページとページのファイルを削除してもよいですか？"
   :page/open-in-finder "ディレクトリで開く"
   :page/open-with-default-app "デフォルトのアプリで開く"
   :page/make-public "パブリッシュのため公開する"
   :page/version-history "ページ履歴の確認"
   :page/open-backup-directory "ページのバックアップディレクトリを開く"
   :page/make-private "非公開にする"
   :page/delete "ページ削除"
   :page/add-to-favorites "お気に入りへ追加"
   :page/unfavorite "お気に入りを解除"
   :page/show-journals "日誌を表示"
   :block/name "ページ名"
   :page/earlier "もっと前へ"
   :page/copy-page-url "ページの URL をコピー"
   :file/name "ファイル名"
   :file/last-modified-at "最終更新日時 "
   :file/no-data "データがありません"
   :file/format-not-supported ".{1} 形式はサポートされていません。"
   :page/created-at "作成日時 "
   :page/updated-at "更新日時 "
   :page/backlinks "バックリンク"
   :editor/block-search "ブロックを検索"
   :text/image "画像"
   :asset/confirm-delete "この {1} を削除してもよろしいですか？"
   :asset/physical-delete "ファイルも削除します（元に戻せないことにご注意ください）"
   :color/gray "グレー"
   :color/red "赤"
   :color/yellow "黄"
   :color/green "緑"
   :color/blue "青"
   :color/purple "紫"
   :color/pink "ピンク"
   :editor/copy "コピー"
   :editor/cut "カット"
   :content/copy-block-ref "ブロック参照をコピー"
   :content/copy-block-emebed "ブロック埋め込みをコピー"
   :content/open-in-sidebar "サイドバーで開く"
   :content/click-to-edit "クリックで編集"
   :settings-page/git-confirm "Git設定を更新するにはアプリを再起動する必要があります。"
   :settings-page/git-switcher-label "Gitの自動コミットを有効化"
   :settings-page/git-commit-delay "Gitの自動コミット間隔（秒）"
   :settings-page/edit-config-edn "config.ednを編集"
   :settings-page/edit-custom-css "custom.cssを編集"
   :settings-page/custom-configuration "カスタム設定"
   :settings-page/custom-theme "カスタムテーマ"
   :settings-page/show-brackets "ブラケットを表示"
   :settings-page/spell-checker "スペルチェッカー"
   :settings-page/auto-updater "自動更新"
   :settings-page/disable-sentry "使用状況データと診断内容をLogseqへ送信します。"
   :settings-page/preferred-outdenting "論理的なアウトデント"
   :settings-page/custom-date-format "日時の表示形式"
   :settings-page/preferred-file-format "ファイル形式"
   :settings-page/preferred-workflow "ワークフローの表示方法"
   :settings-page/enable-shortcut-tooltip "ショートカットのツールチップを表示"
   :settings-page/enable-timetracking "タイムトラッキング"
   :settings-page/enable-tooltip "ツールチップ"
   :settings-page/enable-journals "日誌"
   :settings-page/enable-all-pages-public "パブリッシュ時には全てのページを公開する"
   :settings-page/customize-shortcuts "キーボードショートカット"
   :settings-page/shortcut-settings "ショートカットをカスタマイズ"
   :settings-page/home-default-page "デフォルトのホームページを設定"
   :settings-page/enable-block-time "ブロックタイムスタンプ"
   :settings-page/clear-cache "キャッシュをクリア"
   :settings-page/clear "クリア"
   :settings-page/developer-mode "開発者モード"
   :settings-page/developer-mode-desc "開発者モードはコントリビューターと機能拡張の開発者がLogseqとの統合をより効率的にテストする助けになります。"
   :settings-page/current-version "現在のバージョン"
   :settings-page/tab-general "一般"
   :settings-page/tab-editor "エディタ"
   :settings-page/tab-version-control "バージョンコントロール"
   :settings-page/tab-advanced "高度な設定"
   :settings-page/plugin-system "プラグインシステム"
   :settings-page/network-proxy "ネットワークプロキシ"
   :yes "はい"
   :submit "投稿"
   :cancel "キャンセル"
   :close "閉じる"
   :delete "削除"
   :save "保存"
   :type "種別"
   :host "ホスト"
   :port "ポート"
   :re-index "インデックス再構築"
   :re-index-detail "グラフ再構築"
   :re-index-multiple-windows-warning "このグラフのインデックスを再構築する前に、Logseq で開いている他のウィンドウを閉じる必要があります。"
   :re-index-discard-unsaved-changes-warning "インデックスの再構築は現在のグラフをいったん破棄し、現在ディスク上にある全てのファイルから再構築します。未保存の内容は失われます。また、少し時間がかかります。実行してもよいですか？"
   :open-new-window "新規ウィンドウ"
   :sync-from-local-files "再表示"
   :sync-from-local-files-detail "ローカルファイルの変更点をインポート"
   :sync-from-local-changes-detected " 再表示は、ディスク上で変更されて Logseq 上のページと内容が変わってしまったファイルを検出し、読み込みます。実行してもよいですか？"
   :search/publishing "検索"
   :search "検索／新規ページ名"
   :page-search "現在のページを検索"
   :graph-search "グラフを検索"
   :new-page "新規ページ"
   :new-graph "新規グラフを追加"
   :graph "グラフ"
   :graph/persist "Logseq の内部状態を同期中です。少々お待ちください。"
   :graph/persist-error "内部状態の同期に失敗しました。"
   :graph/save "保存中..."
   :graph/save-success "保存に成功しました"
   :graph/save-error "保存に失敗しました"
   :graph/all-graphs "全グラフ"
   :graph/local-graphs "ローカルグラフ"
   :graph/remote-graphs "リモートグラフ"
   :export "エクスポート"
   :export-graph "グラフをエクスポート"
   :export-page "ページをエクスポート"
   :export-markdown "標準Markdownでエクスポート(blockプロパティなし)"
   :export-opml "OPML形式でエクスポート"
   :export-public-pages "公開ページのエクスポート"
   :export-json "JSON形式でエクスポート"
   :export-roam-json "Roam JSON形式でエクスポート"
   :export-edn "EDN形式でエクスポート"
   :all-graphs "全グラフ"
   :all-pages "全ページ"
   :all-files "全ファイル"
   :remove-orphaned-pages "孤立ページを削除"
   :all-journals "全日誌"
   :settings "設定"
   :settings-of-plugins "プラグイン設定"
   :plugins "プラグイン"
   :themes "テーマ"
   :relaunch-confirm-to-work "動作させるには再起動が必要です。いますぐ再起動しますか？"
   :import "インポート"
   :join-community "コミュニティへ参加"
   :help-shortcut-title "クリックしてショートカットと他のTipsを確認"
   :loading "ロード中"
   :parsing-files "ファイル解析中"
   :loading-files "ファイルロード中"
   :login "ログイン"
   :logout "ログアウト"
   :download "ダウンロード"
   :language "言語"
   :remove-background "背景を消去"
   :remove-heading "見出しを消去"
   :heading "見出し {1}"
   :auto-heading "自動見出し"
   :open-a-directory "ローカルディレクトリを開く"

   :help/shortcut-page-title "キーボードショートカット"

   :plugin/installed "インストール済"
   :plugin/not-installed "未インストール"
   :plugin/installing "インストール中"
   :plugin/install "インストール"
   :plugin/reload "リロード"
   :plugin/update "更新"
   :plugin/check-update "更新を確認"
   :plugin/check-all-updates "全ての更新を確認"
   :plugin/refresh-lists "リスト更新"
   :plugin/enabled "有効化"
   :plugin/disabled "無効化"
   :plugin/update-available "利用可能な更新を適用"
   :plugin/updating "更新中"
   :plugin/uninstall "アンインストール"
   :plugin/marketplace "マーケットプレース"
   :plugin/downloads "ダウンロード"
   :plugin/stars "スター"
   :plugin/title "タイトル"
   :plugin/all "全て"
   :plugin/unpacked "展開済"
   :plugin/delete-alert "プラグイン [{1}]　をアンインストールしてもよいですか？"
   :plugin/open-settings "設定を開く"
   :plugin/open-package "パッケージを開く"
   :plugin/load-unpacked "展開されたプラグインをロード"
   :plugin/restart "アプリを再起動"
   :plugin/unpacked-tips "プラグインディレクトリを選択"
   :plugin/contribute "✨ 新規プラグインの作成とサブミット"
   :plugin/up-to-date "最新の状態です"
   :plugin/custom-js-alert "custom.js ファイルを見つけました。実行を許可しますか？ （もしあなたがこのファイルの内容を理解していない場合、セキュリティのリスクがあるため許可しないことをお勧めします。）"

   :pdf/copy-ref "参照をコピー"
   :pdf/copy-text "テキストをコピー"
   :pdf/linked-ref "リンクありの参照元"
   :pdf/toggle-dashed "破線で Area highlight"

   :updater/new-version-install "新しいバージョンがダウンロードされました。"
   :updater/quit-and-install "インストールのためアプリを再起動してください。"

   :paginates/pages "全 {1} ページ"
   :paginates/prev "前"
   :paginates/next "次"

   :tips/all-done "All Done"

   :command-palette/prompt "コマンドを入力"
   :select/default-prompt "選択してください"
   :select.graph/prompt "グラフを選んでください"
   :select.graph/empty-placeholder-description "マッチするグラフがありません。新しいグラフを追加しますか？"
   :select.graph/add-graph "はい、新規グラフを追加します。"

   :file-sync/other-user-graph "現在のローカルグラフは他のユーザーのリモートグラフにバインドされています。同期を開始できません。"
   :file-sync/graph-deleted "現在のリモートグラフが削除されました"})
