(ns frontend.dicts.ko
  "Provides translation to KO"
  #?(:cljs (:require [shadow.resource :as rc])))

(def dict
  {:tutorial/text #?(:cljs (rc/inline "tutorial-ko.md")
                     :default "tutorial-ko.md")
   :tutorial/dummy-notes #?(:cljs (rc/inline "dummy-notes-ko.md")
                            :default "dummy-notes-ko.md")
   :on-boarding/demo-graph "이 그래프는 데모 그래프입니다. 로컬 폴더를 열기 전까지 변경 사항은 저장되지 않습니다."
   :on-boarding/add-graph "그래프 추가"
   :on-boarding/open-local-dir "로컬 폴더 열기"
   :on-boarding/new-graph-desc-1 "Logseq은 Markdown과 Org-Mode를 모두 지원합니다. 기기에서 존재하는 디렉토리(폴더)를 열거나 새 디렉토리를 만들 수 있습니다. 사용자의 데이터는 오직 이 기기에만 저장됩니다."
   :on-boarding/new-graph-desc-2 "디렉토리를 열면 Logseq은 3가지 폴더를 만들 것입니다:"
   :on-boarding/new-graph-desc-3 "/journals - 일지 페이지들을 저장합니다."
   :on-boarding/new-graph-desc-4 "/pages - 기타 페이지들을 저장합니다."
   :on-boarding/new-graph-desc-5 "/logseq - 사용자 설정과 custom.css, 그리고 몇 가지 메타데이터를 저장합니다."
   :help/start "시작"
   :help/about "Logseq에 대하여"
   :help/roadmap "로드맵"
   :help/bug "오류 제보"
   :help/feature "기능 제안"
   :help/changelog "변경 사항"
   :help/blog "Logseq 블로그"
   :help/docs "안내 문서"
   :help/privacy "개인정보 보호정책"
   :help/terms "약관"
   :help/awesome-logseq "Awesome Logseq"
   :help/shortcuts "키보드 단축키"
   :help/shortcuts-triggers "트리거"
   :help/shortcut "단축키"
   :help/slash-autocomplete "Slash 자동 완성"
   :help/block-content-autocomplete "블록 콘텐츠 자동 완성"
   :help/reference-autocomplete "페이지 레퍼런스 자동 완성"
   :help/block-reference "블록 레퍼런스"
   :help/open-link-in-sidebar "사이드바에서 링크 열기"
   :more "더 보기"
   :search/result-for "검색 결과: "
   :search/items "항목"
   :search/page-names "페이지 이름 검색"
   :help/context-menu "블록 컨텍스트 메뉴"
   :help/markdown-syntax "Markdown 문법"
   :help/org-mode-syntax "Org mode 문법"
   :bold "볼드체"
   :italics "이탤릭체"
   :highlight "하이라이트"
   :strikethrough "취소선"
   :code "코드"
   :right-side-bar/help "도움말"
   :right-side-bar/switch-theme "테마 모드"
   :right-side-bar/contents "콘텐츠"
   :right-side-bar/page-graph "페이지 그래프"
   :right-side-bar/block-ref "블록 레퍼런스"
   :right-side-bar/graph-view "그래프 뷰"
   :right-side-bar/all-pages "모든 페이지"
   :right-side-bar/flashcards "플래시 카드"
   :right-side-bar/new-page "새 페이지"
   :left-side-bar/journals "일지"
   :left-side-bar/new-page "새 페이지"
   :left-side-bar/nav-favorites "즐겨찾기"
   :left-side-bar/nav-recent-pages "최근 페이지"
   :page/presentation-mode "프레젠테이션 모드"
   :page/delete-confirmation "이 페이지와 페이지의 파일들을 삭제하시겠습니까?"
   :page/open-in-finder "디렉토리에서 열기"
   :page/open-with-default-app "기본 앱으로 열기"
   :page/make-public "출판 전 공개 상태로 만들기"
   :page/version-history "페이지 편집 기록 확인"
   :page/open-backup-directory "페이지 백업 디렉토리 열기"
   :page/make-private "비공개 상태로 만들기"
   :page/delete "페이지 삭제"
   :page/add-to-favorites "즐겨찾기에 추가"
   :page/unfavorite "즐겨찾기에서 삭제"
   :page/show-journals "일지 보기"
   :block/name "페이지 이름"
   :page/earlier "이전"
   :page/copy-page-url "페이지 URL 복사"
   :file/name "파일 이름"
   :file/last-modified-at "마지막 편집 시간:"
   :file/no-data "데이터 없음"
   :file/format-not-supported "확장자 .{1} 형태의 파일은 지원되지 않습니다."
   :page/created-at "생성 시간:"
   :page/updated-at "수정 시간:"
   :page/backlinks "역링크"
   :editor/block-search "블록 검색"
   :text/image "이미지"
   :asset/confirm-delete "정말 {1} 을/를 삭제하겠습니까?"
   :asset/physical-delete "파일 또한 삭제 (복구 불가능)"
   :editor/copy "복사"
   :editor/cut "잘라내기"
   :content/copy-block-ref "블록 주소 복사"
   :content/copy-block-emebed "블록 임베드 복사"
   :content/open-in-sidebar "사이드바에서 열기"
   :content/click-to-edit "클릭하여 수정"
   :settings-page/git-confirm "Git 설정을 변경한 뒤 앱을 재시작해야 합니다."
   :settings-page/git-switcher-label "Git 자동 커밋 설정"
   :settings-page/git-commit-delay "Git 자동 커밋 간격 (초)"
   :settings-page/edit-config-edn "config.edn 수정"
   :settings-page/edit-custom-css "custom.css 수정"
   :settings-page/edit-export-css "export.css 수정"
   :settings-page/custom-configuration "사용자 설정"
   :settings-page/custom-theme "사용자 테마"
   :settings-page/export-theme "웹 배포 테마"
   :settings-page/show-brackets "대괄호 표시"
   :settings-page/spell-checker "문법 검사"
   :settings-page/auto-updater "자동 업데이트"
   :settings-page/disable-sentry "사용 통계와 분석을 Logseq에 전송"
   :settings-page/preferred-outdenting "논리적 아웃덴팅"
   :settings-page/custom-date-format "선호하는 날짜 형식"
   :settings-page/preferred-file-format "선호하는 파일 형식"
   :settings-page/preferred-workflow "선호하는 워크플로우"
   :settings-page/enable-shortcut-tooltip "단축키 툴팁 활성화"
   :settings-page/enable-timetracking "시간 추적 활성화"
   :settings-page/enable-tooltip "툴팁 활성화"
   :settings-page/enable-journals "일지 활성화"
   :settings-page/enable-all-pages-public "출판할 때 모든 페이지 공개로 설정"
   :settings-page/customize-shortcuts "키보드 단축키"
   :settings-page/shortcut-settings "단축키 설정"
   :settings-page/home-default-page "기본 홈 페이지 설정"
   :settings-page/enable-block-time "블록 타임스탬프"
   :settings-page/clear-cache "캐시 지우기"
   :settings-page/clear "지우기"
   :settings-page/developer-mode "개발자 모드"
   :settings-page/developer-mode-desc "개발자 모드는 컨트리뷰터와 확장 프로그램 개발자들이 Logseq과의 연동을 더 쉽고 효율적으로 테스트할 수 있게 도와줍니다."
   :settings-page/current-version "현재 버전"
   :settings-page/tab-general "일반"
   :settings-page/tab-editor "에디터"
   :settings-page/tab-version-control "버전 컨트롤"
   :settings-page/tab-advanced "고급"
   :settings-page/plugin-system "플러그인 시스템"
   :settings-page/network-proxy "네트워크 프록시"
   :yes "예"
   :submit "제출"
   :cancel "취소"
   :close "닫기"
   :delete "삭제"
   :save "저장"
   :type "타입"
   :host "호스트"
   :port "포트"
   :re-index "인덱스 재생성"
   :re-index-detail "그래프 다시 빌드"
   :re-index-multiple-windows-warning "그래프를 다시 인덱싱 전 다른 윈도우를 모두 닫아야 합니다."
   :re-index-discard-unsaved-changes-warning "인덱싱을 다시 하게 되면 현재 나타나 있는 그래프가 사라지며, 하드 디스크에 저장된 파일대로 그래프를 재구성하게 됩니다. 저장되지 않은 변경사항들이 삭제되며 약간의 시간이 걸릴 수 있습니다. 계속하시겠습니까?"
   :open-new-window "새 창"
   :sync-from-local-files "새로고침"
   :sync-from-local-files-detail "로컬 파일로부터 변경 사항 불러오기"
   :sync-from-local-changes-detected "그래프를 새로 고치면 로컬 디스크에서 Logseq과는 다르게 변경된 파일들을 감지하고 처리합니다. 계속하시겠습니까?"

   :search/publishing "검색"
   :search "페이지를 검색하거나 생성"
   :page-search "현재 페이지에서 검색"
   :graph-search "그래프 검색"
   :new-page "새 페이지"
   :new-graph "새 그래프"
   :graph "그래프"
   :graph/persist "Logseq가 내부 상태를 동기화 중입니다. 잠시만 기다려주십시오."
   :graph/persist-error "내부 상태 동기화에 실패했습니다."
   :graph/save "저장 중..."
   :graph/save-success "저장 완료"
   :graph/save-error "저장 실패"
   :export "내보내기"
   :export-graph "그래프 내보내기"
   :export-page "페이지 내보내기"
   :export-markdown "표준 Markdown으로 내보내기 (블록 속성 미포함)"
   :export-opml "OPML으로 내보내기"
   :export-public-pages "공개 페이지 내보내기"
   :export-json "JSON으로 내보내기"
   :export-roam-json "Roam JSON으로 내보내기"
   :export-edn "EDN으로 내보내기"
   :all-graphs "모든 그래프"
   :all-pages "모든 페이지"
   :all-files "모든 파일"
   :remove-orphaned-pages "고립된 페이지 삭제"
   :all-journals "모든 일지"
   :settings "설정"
   :settings-of-plugins "플러그인 설정"
   :plugins "플러그인"
   :themes "테마"
   :relaunch-confirm-to-work "완료하려면 앱을 재시작해야 합니다. 지금 재시작하시겠습니까?"
   :import "불러오기"
   :join-community "커뮤니티에 참여"
   :help-shortcut-title "다른 단축키와 도움말 확인하기"
   :loading "로딩 중"
   :parsing-files "파일 파싱 중"
   :loading-files "파일 로딩 중"
   :login "로그인"
   :logout "로그아웃"
   :download "다운로드"
   :language "언어"
   :remove-background "배경 제거"
   :open-a-directory "로컬 디렉토리 열기"

   :help/shortcut-page-title "키보드 단축키"

   :plugin/installed "설치됨"
   :plugin/not-installed "설치되지 않음"
   :plugin/installing "설치 중"
   :plugin/install "설치"
   :plugin/reload "다시 불러오기"
   :plugin/update "업데이트"
   :plugin/check-update "업데이트 확인"
   :plugin/check-all-updates "모든 업데이트 확인"
   :plugin/refresh-lists "리스트 새로고침"
   :plugin/enabled "활성화됨"
   :plugin/disabled "비활성화됨"
   :plugin/update-available "업데이트 가능"
   :plugin/updating "업데이트 중"
   :plugin/uninstall "설지 제거"
   :plugin/marketplace "마켓플레이스"
   :plugin/downloads "다운로드"
   :plugin/stars "스타"
   :plugin/title "제목"
   :plugin/all "전체"
   :plugin/unpacked "압축 해제됨"
   :plugin/delete-alert "다음 [{1}] 플러그인을 삭제하시겠습니까?"
   :plugin/open-settings "설정 열기"
   :plugin/open-package "패키지 열기"
   :plugin/load-unpacked "압축 해제된 플러그인 불러오기"
   :plugin/restart "앱 다시 시작"
   :plugin/unpacked-tips "플러그인 디렉토리 열기"
   :plugin/contribute "✨ 새 플러그인을 만들고 기여하기"
   :plugin/up-to-date "최신 상태입니다."
   :plugin/custom-js-alert "custom.js 파일을 감지했습니다. 실행을 허용하겠습니까? (파일의 내용을 이해하지 못한다면 보안과 안전 상의 이유로 실행하지 않는 것이 권장됩니다."

   :pdf/copy-ref "레퍼런스 복사하기"
   :pdf/copy-text "텍스트 복사하기"
   :pdf/linked-ref "링크된 레퍼런스"
   :pdf/toggle-dashed "영역 하이라이트를 위해 Dashed style 사용"

   :updater/new-version-install "새 버전이 다운로드되었습니다."
   :updater/quit-and-install "다시 시작하여 설치하십시오."

   :paginates/pages "총 {1} 페이지"
   :paginates/prev "이전"
   :paginates/next "다음"

   :tips/all-done "모두 완료"

   :command-palette/prompt "커맨드를 입력하십시오"
   :select/default-prompt "하나를 선택하십시오"
   :select.graph/prompt "그래프를 선택하십시오."
   :select.graph/empty-placeholder-description "일치하는 그래프가 없습니다. 새로 추가하시겠습니까?"
   :select.graph/add-graph "네, 새 그래프를 추가합니다"

   :file-sync/other-user-graph "현재 로컬 그래프가 다른 유저의 리모트 그래프와 충돌합니다. 동기화를 시작할 수 없습니다."
   :file-sync/graph-deleted "현재 리모트 그래프를 삭제했습니다."

   :all-whiteboards "모든 화이트보드"
   :auto-heading "자동 헤딩"
   :discourse-title "포럼!"
   :heading "헤딩 {1}"
   :importing "불러오는 중"
   :new-whiteboard "새 화이트보드"
   :remove-heading "헤딩 제거"
   :untitled "제목 없음"
   :accessibility/skip-to-main-content "메인 컨텐츠로 건너뛰기"
   :asset/copy "이미지 복사"
   :asset/delete "이미지 삭제"
   :asset/maximize "이미지 최대화"
   :asset/open-in-browser "이미지 브라우저에서 열기"
   :asset/show-in-folder "이미지 폴더에서 열기"
   :color/blue "파란색"
   :color/gray "회색"
   :color/green "초록색"
   :color/pink "분홍색"
   :color/purple "보라색"
   :color/red "빨간색"
   :color/yellow "노란색"
   :on-boarding/tour-whiteboard-home "{1} 홈 화이트보드"
   :on-boarding/tour-whiteboard-home-description "화이트보드는 각각 섹션이 존재합니다. 섹션에서 화이트보드를 한눈에 보고, 생성하거나 삭제할 수 있습니다."
   :on-boarding/tour-whiteboard-new "{1} 새 화이트보드 생성"
   :on-boarding/tour-whiteboard-new-description "새 화이트보드를 만드는 데에는 여러 방법이 존재합니다. 그 중 하나는 이 대시보드에서 만드는 것입니다."
   :on-boarding/welcome-whiteboard-modal-description "화이트보드는 브레인스토밍을 하거나 데이터를 정리하는 강력한 도구입니다. 어떠한 것도 좋습니다. 캔버스에 놓고, 연결시키고, 새롭게 이해해보십시오."
   :on-boarding/welcome-whiteboard-modal-skip "건너뛰기"
   :on-boarding/welcome-whiteboard-modal-start "화이트보드 시작하기"
   :on-boarding/welcome-whiteboard-modal-title "새 캔버스"
   :file/validate-existing-file-error "페이지가 이미 존재합니다: {1}, 현재 파일: {2}. 하나만 남겨놓은 뒤 그래프의 인덱스를 재생성하십시오."
   :file-rn/all-action "모든 작업 적용!"
   :file-rn/apply-rename "파일명 변경"
   :file-rn/close-panel "패널 닫기"
   :file-rn/confirm-proceed "포맷 업데이트!"
   :file-rn/filename-desc-1 "이 설정은 페이지가 어떻게 파일로 저장되는지 구성합니다. 기본적으로 Logseq는 페이지를 같은 이름의 파일에 저장합니다."
   :file-rn/filename-desc-2 "\"/\", \"?\"과 같은 몇몇의 문자들은 파일명으로 사용할 수 없습니다."
   :file-rn/filename-desc-3 "Logseq는 적절하지 않은 문자들을 인코딩하여 저장합니다. 예) \"?\"를 \"%3F\"로."
   :file-rn/filename-desc-4 "네임스페이스 구분자 \"/\" 또한 \"___\" (세 개의 언더스코어)로 대체됩니다."
   :file-rn/format-deprecated "현재 오래된 파일명 포맷을 사용하고 있습니다. 최신 포맷으로 업데이트하는 것을 권장합니다. Logseq 데이터를 백업하고, 다른 Logseq 클라이언트를 종료한 뒤 진행해주십시오."
   :file-rn/instruct-1 "파일명 포맷을 업데이트하기 위한 과정:"
   :file-rn/instruct-2 "1. 클릭: "
   :file-rn/instruct-3 "2. 다음의 과정 따르기:"
   :file-rn/need-action "새로운 포맷에 맞춰 파일명 변경 작업이 필요합니다. 동기화가 진행된 이후, 모든 장치의 인덱스를 재생성하십시오."
   :file-rn/no-action "좋습니다! 별다른 작업이 필요하지 않습니다."
   :file-rn/optional-rename "제안:"
   :file-rn/or-select-actions " 혹은, 아래의 파일들을 직접 변경하십시오. "
   :file-rn/or-select-actions-2 ". 이 작업들은 본 패널을 닫은 이후에는 유효하지 않습니다."
   :file-rn/re-index "파일명이 변경된 이후, 인덱스 재생성이 필요합니다."
   :file-rn/rename "{1}을(를) {2}(으)로 이름 변경"
   :file-rn/select-confirm-proceed "(개발자) 포맷 변경"
   :file-rn/select-format "(개발자, 위험!) 파일명 포맷 선택"
   :file-rn/suggest-rename "작업 필요: "
   :file-rn/unreachable-title "경고! 이 페이지는 `title::` 속성이 설정되어 있지 않는 한, 현재 파일명 포맷에 따라 {1}(으)로 변경될 것입니다."
   :graph/all-graphs "모든 그래프"
   :graph/local-graphs "로컬 그래프"
   :graph/remote-graphs "원격 그래프"
   :help/forum-community "포럼 커뮤니티"
   :left-side-bar/create "생성"
   :left-side-bar/new-whiteboard "새 화이트보드"
   :linked-references/filter-search "링크된 페이지에서 검색"
   :notification/clear-all "모두 제거"
   :page/logseq-is-having-a-problem "Logseq에 문제가 발생하였습니다. 작업 환경으로 돌아가기 위해서는 다음 지시를 따라주십시오."
   :page/show-whiteboards "화이트보드"
   :page/something-went-wrong "문제가 발생하였습니다."
   :page/step "스텝 {1}"
   :page/try "시도"
   :pdf/doc-metadata "메타데이터"
   :plugin.install-from-file/title "plugins.edn에서 설치"
   :plugin.install-from-file/notice "다음의 플러그인들이 교체될 것입니다:"
   :plugin.install-from-file/success "플러그인 설치 성공!"
   :plugin.install-from-file/menu-title "plugins.edn에서 설치"
   :right-side-bar/show-journals "일지 보기"
   :right-side-bar/whiteboards "화이트보드"
   :search-item/block "블록"
   :search-item/file "파일"
   :search-item/page "페이지"
   :search-item/whiteboard "화이트보드"
   :settings-page/alpha-features "알파 기능"
   :settings-page/beta-features "베타 기능"
   :settings-page/clear-cache-warning "캐시 삭제로, 현재 작업 내용을 잃을 수 있습니다."
   :settings-page/custom-date-format-warning "인덱스 재생성이 필요합니다. 일지 레퍼런스가 잘못될 수 있습니다."
   :settings-page/custom-global-configuration "전역 사용자 설정"
   :settings-page/disable-sentry-desc "Logseq는 사용자의 로컬 그래프 데이터베이스 정보를 수집하지 않습니다."
   :settings-page/edit-global-config-edn "전역 config.edn 수정"
   :settings-page/edit-setting "수정"
   :settings-page/enable-flashcards "플래시 카드 활성화"
   :settings-page/enable-whiteboards "화이트보드 활성화"
   :settings-page/filename-format "파일명 포맷"
   :settings-page/login-prompt "Logseq의 새로운 기능을 먼저 체험하기 위해서는, Open Collective Sponsor가 되거나 Logseq의 Backer가 되어야 합니다. 먼저, 로그인 하십시오."
   :settings-page/preferred-pasting-file "텍스트 복사 선호"
   :settings-page/show-full-blocks "블록 레퍼런스의 모든 줄 표시"
   :settings-page/sync "동기화"
   :settings-page/tab-assets "에셋"
   :settings-page/tab-features "기능"
   :whiteboard/link-whiteboard-or-block "화이트보드/페이지/블록 연결"})
