(ns frontend.dicts.nl
  "Provides translation to NL"
  #?(:cljs (:require [shadow.resource :as rc])))

(def dict
  {:all-files "Alle bestanden"
   :all-graphs "Alle grafieken"
   :all-journals "Alle Journalen"
   :all-pages "Alle pagina's"
   :bold "Vet"
   :cancel "Annuleren"
   :close "Sluiten"
   :code "Code"
   :delete "Verwijderen"
   :discourse-title "Ons forum!"
   :download "Downloaden"
   :export "Exporteren"
   :export-edn "Exporteren als EDN"
   :export-graph "Grafiek exporteren"
   :export-json "Exporteren als JSON"
   :export-markdown "Exporteren als standaard Markdown (geen blok eigenschappen)"
   :export-opml "Exporteren als OPML"
   :export-page "Exporteer pagina"
   :export-public-pages "Exporteer openbare pagina's"
   :export-roam-json "Exporteer als Roam JSON"
   :graph "Grafiek"
   :graph-search "Zoek grafiek"
   :help-shortcut-title "Klik om sneltoetsen en andere tips te bekijken"
   :highlight "Markeer"
   :host "Host"
   :import "Importeren"
   :italics "Cursief"
   :join-community "Sluit u aan bij de gemeenschap"
   :language "Taal"
   :loading-files "Bestanden laden"
   :loading "Laden"
   :login "Inloggen"
   :logout "Uitloggen"
   :more "Meer"
   :new-graph "Nieuwe grafiek toevoegen"
   :new-page "Nieuwe pagina"
   :open-a-directory "Open een lokale map"
   :open-new-window "Nieuwe venster"
   :page-search "Zoek in de huidige pagina"
   :parsing-files "Bestanden analyseren"
   :plugins "Plugins"
   :port "Poort"
   :re-index "Herindexeren"
   :re-index-detail "Grafiek herbouwen"
   :re-index-discard-unsaved-changes-warning "Herindexeren zal de huidige grafiek weggooien, en vervolgens alle bestanden opnieuw verwerken zoals ze momenteel op schijf zijn opgeslagen. U verliest niet-opgeslagen wijzigingen en het kan even duren. Verder?"
   :re-index-multiple-windows-warning "U moet de andere vensters sluiten voordat u deze grafiek opnieuw indexeert."
   :relaunch-confirm-to-work "U moet de app opnieuw opstarten om het te laten werken. Wil u het nu opnieuw opstarten?"
   :remove-background "Verwijder achtergrond"
   :remove-orphaned-pages "Verwijder gelinkte pagina's"
   :save "Opslaan"
   :search "Zoek of maak pagina"
   :settings "Instellingen"
   :settings-of-plugins "Plugin instellingen"
   :strikethrough "Doorgestreept"
   :submit "Verzenden"
   :sync-from-local-changes-detected "ReBijwerkenfresh detecteert en verwerkt bestanden die op uw schijf zijn gewijzigd en die afwijken van de eigenlijke inhoud van de Logseq pagina. Verder?"
   :sync-from-local-files "Bijwerken"
   :sync-from-local-files-detail "Importeer veranderingen uit lokale bestanden"
   :themes "Thema's"
   :type "Type"
   :yes "Ja"

   :asset/confirm-delete "Weet u zeker dat u dit wilt verwijderen {1}?"
   :asset/physical-delete "Verwijder het bestand ook (let op dat het niet hersteld kan worden)"

   :block/name "Pagina naam"

   :command-palette/prompt "Type een commando"

   :content/click-to-edit "Klik om te bewerken"
   :editor/copy "Kopieer"
   :editor/cut "Knip"
   :content/copy-block-emebed "Kopieer blok embed"
   :content/copy-block-ref "Kopieer blok ref"
   :content/open-in-sidebar "Open in zijbalk"

   :editor/block-search "Zoek voor een blok"
   :file/format-not-supported "Formaat .{1} wordt niet ondersteund."
   :file/last-modified-at "Laatst aangepast op"
   :file/name "Bestandsnaam"
   :file/no-data "Geen gegevens"

   :file-sync/graph-deleted "Het huidige remote grafiek is verwijderd"
   :file-sync/other-user-graph "De huidige lokale grafiek is gebonden aan de remote grafiek van de andere gebruiker. Dus kan de synchronisatie niet starten."

   :graph/persist "Logseq is de interne status aan het synchroniseren, wacht alstublieft enkele seconden."
   :graph/persist-error "Interne status sync mislukt."
   :graph/save "Opslaan..."
   :graph/save-error "Opslaan mislukt"
   :graph/save-success "Opslaan succesvol"

   :help/about "Over Logseq"
   :help/awesome-logseq "Awesome Logseq"
   :help/block-content-autocomplete "Blokinhoud (brontekst, citaten, zoekopdrachten, enz.) autocomplete"
   :help/block-reference "Blok referentie"
   :help/blog "Logseq blog"
   :help/bug "Rapporteer een fout"
   :help/changelog "Verander logboek"
   :help/context-menu "Blok context menu"
   :help/docs "Documentatie"
   :help/feature "Functie verzoek"
   :help/forum-community "Forum gemeenschap"
   :help/markdown-syntax "Markdown-syntax"
   :help/org-mode-syntax "Org-mode-syntax"
   :help/privacy "Privacybeleid"
   :help/reference-autocomplete "Automatisch aanvullen van paginareferenties"
   :help/roadmap "Roadmap"
   :help/shortcut "Snelkoppeling"
   :help/shortcut-page-title "Toetsenbord snelkoppelingen"
   :help/shortcuts "Toetsenbord snelkoppelingen"
   :help/shortcuts-triggers "Triggers"
   :help/slash-autocomplete "Slash-Autocomplete"
   :help/start "Aan de slag"
   :help/terms "Voorwaarden"
   :help/open-link-in-sidebar "Open link in zijbalk"

   :left-side-bar/journals "Journalen"
   :left-side-bar/nav-favorites "Favorieten"
   :left-side-bar/nav-recent-pages "Recent"
   :left-side-bar/new-page "Nieuwe pagina"

   :linked-references/filter-search "Zoeken in gelinkte pagina's"

   :on-boarding/add-graph "Grafiek toevoegen"
   :on-boarding/demo-graph "Dit is een demo grafiek, wijzigingen worden niet opgeslagen totdat u een lokale map opent."
   :on-boarding/new-graph-desc-1 "Logseq ondersteunt zowel Markdown als Org-mode. U kunt een bestaande map openen of een nieuwe aanmaken op uw apparaat, een map is ook gewoon bekend als een folder. Uw gegevens worden alleen op dit apparaat opgeslagen."
   :on-boarding/new-graph-desc-2 "Nadat u map hebt geopend, worden er drie mappen in die map aangemaakt:"
   :on-boarding/new-graph-desc-3 "/journals - bewaart de Journaal pagina's"
   :on-boarding/new-graph-desc-4 "/pages - bewaart de andere pagina's"
   :on-boarding/new-graph-desc-5 "/logseq - bewaart configuratie, custom.css, en wat metadata."
   :on-boarding/open-local-dir "Open een lokale map"

   :page/add-to-favorites "Voeg aan favorieten toe"
   :page/backlinks "Back-Links"
   :page/copy-page-url "Kopieer pagina URL"
   :page/created-at "Aangemaakt op"
   :page/delete "Verwijder pagina"
   :page/delete-confirmation "Weet u zeker dat u deze pagina wilt verwijderen..."
   :page/earlier "Eerder"
   :page/make-private "Maak prive"
   :page/make-public "Maak publiek"
   :page/open-backup-directory "Open backups map pagina"
   :page/open-in-finder "Open in map"
   :page/open-with-default-app "Open met standaard app"
   :page/presentation-mode "Presentatiemodus"
   :page/show-journals "Toon Journaals"
   :page/unfavorite "Pagina uit favorieten verwijderen"
   :page/updated-at "Bijgewerkt op"
   :page/version-history "Controleer pagina geschiedenis"

   :paginates/next "Volgende"
   :paginates/pages "Totaal {1} pagina's"
   :paginates/prev "Vorige"

   :pdf/copy-ref "Kopieer ref"
   :pdf/copy-text "Kopieer tekst"
   :pdf/linked-ref "Gekoppelde referenties"
   :pdf/toggle-dashed "Gestippelde stijl voor gebiedsmarkering"

   :plugin/all "Alle"
   :plugin/check-all-updates "Check alle updates"
   :plugin/check-update "Check update"
   :plugin/contribute "✨ Schrijf en dien nieuwe plugin in"
   :plugin/custom-js-alert "custom.js bestand gevonden, mag deze uitgevoerd worden? (Als je niet begrijpt wat dit bestand inhoud is het aangeraden om het uivoeren hiervan niet toe te staan, dit is in verband met beveiligings risico's.)" ;; TODO
   :plugin/delete-alert "Weet je zeker dat je plugin [{1}] wilt verwijderen?"
   :plugin/disabled "Uitgeschakeld"
   :plugin/downloads "Downloads"
   :plugin/enabled "Ingeschakeld"
   :plugin/install "Installeren"
   :plugin/installed "Geïnstalleerd"
   :plugin/installing "Installeren"
   :plugin/load-unpacked "Laad uitgepakte plugin"
   :plugin/marketplace "Marketplace"
   :plugin/not-installed "Niet geïnstalleerd"
   :plugin/open-package "Open pakket"
   :plugin/open-settings "Open instellingen"
   :plugin/refresh-lists "Vernieuw lijsten"
   :plugin/reload "Herlaad"
   :plugin/restart "Herstart app"
   :plugin/stars "Sterren"
   :plugin/title "Titel"
   :plugin/uninstall "Verwijder"
   :plugin/unpacked "Uitgepakt"
   :plugin/unpacked-tips "Selecteer de plugin map"
   :plugin/up-to-date "Het is up to date"
   :plugin/update "Update"
   :plugin/update-available "Update beschikbaar"
   :plugin/updating "Bijwerken"

   :right-side-bar/all-pages "Alle pagina's"
   :right-side-bar/block-ref "Blok verwijzingen"
   :right-side-bar/contents "Inhoud"
   :right-side-bar/flashcards "Flashcards"
   :right-side-bar/graph-view "Grafiekweergave"
   :right-side-bar/help "Help"
   :right-side-bar/new-page "Nieuwe pagina"
   :right-side-bar/page-graph "Pagina grafiek"
   :right-side-bar/show-journals "Toon Journaals"
   :right-side-bar/switch-theme "Thema modes"

   :search/items "items"
   :search/page-names "Zoek paginanamen"
   :search/publishing "Zoek"
   :search/result-for "Zoekresultaat voor "
   :select/default-prompt "Kies één"
   :select.graph/add-graph "Ja, voeg nog een grafiek toe"
   :select.graph/empty-placeholder-description "Geen overeenkomende grafieken. Wilt u er een toevoegen?"
   :select.graph/prompt "Selecteer een grafiek"

   :settings-page/auto-updater "Auto updater"
   :settings-page/clear "Verwijder"
   :settings-page/clear-cache "Cache wissen"
   :settings-page/current-version "Huidige versie"
   :settings-page/custom-configuration "Aangepaste configuratie"
   :settings-page/custom-date-format "Gewenst datumformaat"
   :settings-page/custom-theme "Aangepast thema"
   :settings-page/customize-shortcuts "Toetsenbord snelkoppelingen"
   :settings-page/developer-mode "Ontwikkelaar modus"
   :settings-page/developer-mode-desc "De ontwikkelaarsmodus helpt bijdragers en extensie-ontwikkelaars om hun integratie met Logseq efficiënter te testen."
   :settings-page/disable-sentry "Gebruiksgegevens en diagnostiek naar Logseq sturen"
   :settings-page/edit-config-edn "Bewerk config.edn"
   :settings-page/edit-custom-css "Bewerk custom.css"
   :settings-page/edit-export-css "Bewerk export.css"
   :settings-page/enable-all-pages-public "Alle pagina's openbaar bij publiceren"
   :settings-page/enable-block-time "Tijdstempel voor blokken inschakelen"

   :settings-page/enable-flashcards "Flashcards"
   :settings-page/enable-journals "Journaals"
   :settings-page/enable-shortcut-tooltip "Snelkoppeling tooltip inschakelen"
   :settings-page/enable-timetracking "Tijdregistratie inschakelen"
   :settings-page/enable-tooltip "Tooltips inschakelen"
   :settings-page/export-theme "Exporteer thema"
   :settings-page/git-commit-delay "Git auto commit seconden"
   :settings-page/git-confirm "Je moet de app opnieuw opstarten nadat je de Git instellingen hebt aangepast."
   :settings-page/git-switcher-label "Git auto commit inschakelen"
   :settings-page/home-default-page "De standaard startpagina instellen"
   :settings-page/network-proxy "Netwerk proxy"
   :settings-page/plugin-system "Plugin systeem"
   :settings-page/preferred-file-format "Gewenst bestandsformaat"
   :settings-page/preferred-outdenting "Logische uitdenting"
   :settings-page/preferred-workflow "Voorkeur voor workflow"
   :settings-page/shortcut-settings "Snelkoppelingen aanpassen"
   :settings-page/show-brackets "Toon beugels"
   :settings-page/spell-checker "Spellingcontrole"
   :settings-page/tab-advanced "Geavanceerd"
   :settings-page/tab-editor "Editor"
   :settings-page/tab-general "Algemeen"
   :settings-page/tab-version-control "Versiebeheer"

   :text/image "Afbeelding"

   :tips/all-done "Alles klaar"

   :tutorial/dummy-notes #?(:cljs (rc/inline "dummy-notes-en.md")
                            :default "dummy-notes-en.md")
   :tutorial/text #?(:cljs (rc/inline "tutorial-en.md")
                     :default "tutorial-en.md")

   :updater/new-version-install "Een nieuwe versie is gedownload."
   :updater/quit-and-install "Herstart om te installeren"})
