(ns frontend.dicts.pl
  "Provides translation to PL"
  #?(:cljs (:require [shadow.resource :as rc])))

(def dict
  {:tutorial/text #?(:cljs (rc/inline "tutorial-pl.md")
                     :default "tutorial-pl.md")
   :tutorial/dummy-notes #?(:cljs (rc/inline "dummy-notes-pl.md")
                            :default "dummy-notes-pl.md")
   :on-boarding/demo-graph "To jest przykładowy graf, zmiany nie zostaną zapisane dopóki nie otworzysz lokalnego katalogu."
   :on-boarding/add-graph "Dodaj graf"
   :on-boarding/open-local-dir "Otwórz lokalny katalog"
   :on-boarding/new-graph-desc-1 "Logseq wspiera zarówno składnię Markdown jak i Org-mode. Możesz otworzyć istniejący już folder lub utworzyć nowy katalog na swoim urządzeniu. Wszystkie dane będą przechowywane tylko na tym urządzeniu."
   :on-boarding/new-graph-desc-2 "Po otwarciu wybranego katalogu zostaną w nim utworzone trzy dodatkowe katalogi:"
   :on-boarding/new-graph-desc-3 "/journals - przechowuje wszystkie strony twojego dziennika"
   :on-boarding/new-graph-desc-4 "/pages - przechowuje wszystkie pozostałe, utworzone przez Ciebie strony"
   :on-boarding/new-graph-desc-5 "/logseq - przechowuje konfigurację, custom.css oraz niektóre meta dane."
   :help/start "Rozpocznij swoją przygodę z Logseq"
   :help/about "O Logseq"
   :help/roadmap "Roadmapa"
   :help/bug "Zgłoś błąd"
   :help/feature "Zgłoś zapotrzebowanie na funkcjonalność"
   :help/changelog "Log zmian"
   :help/blog "Blog Logseq"
   :help/docs "Dokumentacja"
   :help/privacy "Polityka prywatności"
   :help/terms "Warunki użytkowania"
   :help/forum-community "Forum dyskusyjne"
   :help/awesome-logseq "Awesome Logseq"
   :help/shortcuts "Skróty klawiszowe"
   :help/shortcuts-triggers "Akcja"
   :help/shortcut "Skrót"
   :help/slash-autocomplete "Autouzupełnianie poleceń /"
   :help/block-content-autocomplete "Autouzupełnianie treści bloku"
   :help/reference-autocomplete "Autouzupełnianie referencji bloku"
   :help/block-reference "Referencja bloku"
   :help/open-link-in-sidebar "Otwórz link w panelu bocznym"
   :more "Więcej"
   :search/result-for "Wyniki wyszukiwania dla"
   :search/items "elementów"
   :search/page-names "Przeszukaj nazwy stron"
   :help/context-menu "Menu kontekstowe bloku"
   :help/markdown-syntax "Składnia Markdown"
   :help/org-mode-syntax "Składnia Org mode"
   :bold "Pogrubienie"
   :italics "Pochylenie"
   :highlight "Wyróżnij"
   :strikethrough "Przekreśl"
   :code "Kod"
   :right-side-bar/help "Pomoc"
   :right-side-bar/switch-theme "Zmień motyw"
   :right-side-bar/contents "Treść"
   :right-side-bar/page-graph "Graf strony"
   :right-side-bar/block-ref "Ref bloku"
   :right-side-bar/graph-view "Widok grafu"
   :right-side-bar/all-pages "Wszystkie strony"
   :right-side-bar/flashcards "Fiszki"
   :right-side-bar/new-page "Nowa strona"
   :right-side-bar/show-journals "Pokaż dzienniki"
   :left-side-bar/journals "Dzienniki"
   :left-side-bar/new-page "Nowa strona"
   :left-side-bar/nav-favorites "Ulubione"
   :left-side-bar/nav-recent-pages "Ostatnio odwiedzane"
   :page/presentation-mode "Tryb prezentacji"
   :page/delete-confirmation "Czy jesteś pewien że chcesz usunąć tę stronę i jej plik?"
   :page/open-in-finder "Otwórz w przeglądarce plików"
   :page/open-with-default-app "Otwórz w domyślnej aplikacji"
   :page/make-public "Oznacz jako publiczną"
   :page/version-history "Sprawdź historię zmian"
   :page/open-backup-directory "Otwórz katalog z kopiami bezpieczeństwa"
   :page/make-private "Oznacz jako prywatną"
   :page/delete "Usuń stronę"
   :page/add-to-favorites "Dodaj do ulubionych"
   :page/unfavorite "Usuń z ulubionych"
   :page/show-journals "Pokaż dzienniki"
   :block/name "Nazwa strony"
   :page/earlier "Wcześniej"
   :page/copy-page-url "Kopiuj adres URL strony"
   :file/name "Nazwa pliku"
   :file/last-modified-at "Ostatnio zmodyfikowany"
   :file/no-data "Brak danych"
   :file/format-not-supported "Format .{1} nie jest wspierany."
   :page/created-at "Utworzony"
   :page/updated-at "Zaktualizowany"
   :page/backlinks "Backlinki"
   :linked-references/filter-search "Szukaj w powiązanych stronach"
   :editor/block-search "Szukaj bloku"
   :text/image "Obrazek"
   :asset/confirm-delete "Jesteś pewien, że chcesz usunąć ten {1}?"
   :asset/physical-delete "Usuń ten plik z dysku (operacja nie może zostać cofnięta)"
   :editor/copy "Kopiuj"
   :editor/cut "Wytnij"
   :content/copy-block-ref "Kopiuj ref bloku"
   :content/copy-block-emebed "Kopiuj blok jako embed"
   :content/open-in-sidebar "Otwórz w panelu bocznym"
   :content/click-to-edit "Kliknij, aby edytować"
   :settings-page/git-confirm "Musisz uruchomić ponownie aplikację żeby zastosować zmiany w ustawieniach Gita."
   :settings-page/git-switcher-label "Włącz opcję autocommit w Git"
   :settings-page/git-commit-delay "Wykonaj commit co każde [s.]"
   :settings-page/edit-config-edn "Edytuj config.edn"
   :settings-page/edit-custom-css "Edytuj custom.css"
   :settings-page/edit-export-css "Edytuj export.css"
   :settings-page/custom-configuration "Niestandardowa konfiguracja"
   :settings-page/custom-theme "Niestandardowy motyw graficzny"
   :settings-page/export-theme "Eksportuj motyw graficzny"
   :settings-page/show-brackets "Pokaż kwadratowe nawiasy"
   :settings-page/spell-checker "Sprawdzanie pisowni"
   :settings-page/auto-updater "Automatyczne aktualizacje"
   :settings-page/disable-sentry "Wyślij statystyki użycia aplikacji do Logseq"
   :settings-page/preferred-outdenting "Logiczne zmniejszanie wcięć"
   :settings-page/custom-date-format "Preferowany format daty"
   :settings-page/preferred-file-format "Preferowany format pliku"
   :settings-page/preferred-workflow "Preferowany flow TODOsów"
   :settings-page/enable-shortcut-tooltip "Włącz podpowiedzi skrótu klawiszowego"
   :settings-page/enable-timetracking "Mierzenie czasu"
   :settings-page/enable-tooltip "Podpowiedzi"
   :settings-page/enable-journals "Dzienniki"
   :settings-page/enable-all-pages-public "Publikuj wszystkie strony"
   :settings-page/customize-shortcuts "Skróty klawiszowe"
   :settings-page/shortcut-settings "Zmień skróty"
   :settings-page/home-default-page "Ustaw domyślną stronę startową"
   :settings-page/enable-block-time "Włącz czas dla bloków"
   :settings-page/clear-cache "Wyczyść cache"
   :settings-page/clear "Wyczyść"
   :settings-page/developer-mode "Tryb programisty"
   :settings-page/developer-mode-desc "Tryb programisty pomaga kontrybutorom i programistom rozszerzeń lepiej przetestować ich integracje w Logseq."
   :settings-page/current-version "Aktualna wersja"
   :settings-page/tab-general "Ogólne"
   :settings-page/tab-editor "Edytor"
   :settings-page/tab-version-control "Kontrola wersji"
   :settings-page/tab-advanced "Zaawansowane"
   :settings-page/plugin-system "System pluginów"
   :settings-page/enable-flashcards "Fiszki"
   :settings-page/network-proxy "Ustawienia proxy"
   :yes "Tak"
   :submit "Wyślij"
   :cancel "Anuluj"
   :close "Zamknij"
   :delete "Usuń"
   :save "Zapisz"
   :type "Typ"
   :re-index "Indeksuj ponownie"
   :re-index-detail "Przebuduj graf od nowa"
   :re-index-multiple-windows-warning "Musisz zamknąć inne okna, zanim rozpoczniesz proces ponownej indeksacji"
   :re-index-discard-unsaved-changes-warning "Ponowna indeksacja odrzuci zmiany w obecnym grafie, a następnie przejdzie po wszystkich plikach zapisanych na dysku. Utracisz wszystkie niezapisane zmiany, a sam proces może trochę potrwać. Kontynuować?"
   :open-new-window "Nowe okno"
   :sync-from-local-files "Odśwież"
   :sync-from-local-files-detail "Importuj zmiany z lokalnych plików"
   :sync-from-local-changes-detected "Funkcja Odśwież wykrywa i procesuje pliki zmienione na dysku. Wszystkie pliki różniące się od tych w Logseq zostaną ponownie wczytane. Kontynuować?"

   :search/publishing "Szukaj"
   :search "Wyszukaj lub stwórz stronę"
   :page-search "Wyszukaj na stronie"
   :graph-search "Przeszukaj graf"
   :new-page "Nowa strona"
   :new-graph "Dodaj nowy graf"
   :graph "Graf"
   :graph/persist "Logseq synchronizuje lokalny stan. Proszę poczekać kilka sekund."
   :graph/persist-error "Nieudana synchronizacja lokalnego stanu"
   :graph/save "Zapisuję..."
   :graph/save-success "Zmiany zostały zapisane"
   :graph/save-error "Zapisywanie zakończone niepowodzeniem"
   :host "Host"
   :port "Port"
   :import "Importuj"
   :export "Eksport"
   :export-graph "Eksportuj graf"
   :export-page "Eksportuj stronę"
   :export-markdown "Eksportuj jako Markdown (brak właściwości bloków)"
   :export-opml "Eksportuj jako OPML"
   :export-public-pages "Eksportuj publiczne strony"
   :export-json "Eksportuj jako JSON"
   :export-roam-json "Eksportuj jako Roam JSON"
   :export-edn "Eksportuj jako EDN"
   :all-graphs "Wszystkie grafy"
   :all-pages "Wszystkie strony"
   :all-files "Wszystkie pliki"
   :remove-orphaned-pages "Usuń strony bez powiązań"
   :all-journals "Wszystkie dzienniki"
   :settings "Ustawienia"
   :settings-of-plugins "Ustawienia pluginu"
   :plugins "Pluginy"
   :themes "Motywy graficzne"
   :relaunch-confirm-to-work "Aby wprowadzić zmiany, aplikacja musi zostać uruchomiona ponownie. Zrobić to teraz?"
   :join-community "Dołącz do społeczności"
   :discourse-title "Nasze forum!"
   :help-shortcut-title "Kliknij, aby sprawdzić skróty klawiszowe oraz inne porady"
   :loading "Ładuję"
   :parsing-files "Parsuję pliki"
   :loading-files "Ładuję pliki"
   :login "Zaloguj"
   :logout "Wyloguj"
   :download "Ściągnij"
   :language "Język"
   :remove-background "Usuń tło"
   :open-a-directory "Otwórz lokalny katalog"
   :help/shortcut-page-title "Skróty klawiszowe"
   :plugin/installed "Zainstalowany"
   :plugin/not-installed "Nie zainstalowany"
   :plugin/installing "Instaluję"
   :plugin/install "Zainstaluj"
   :plugin/reload "Przeładuj"
   :plugin/update "Zaktualizuj"
   :plugin/check-update "Sprawdź aktualizację"
   :plugin/check-all-updates "Sprawdź wszystkie aktualizacje"
   :plugin/refresh-lists "Odśwież listy"
   :plugin/enabled "Włączony"
   :plugin/disabled "Wyłączony"
   :plugin/update-available "Aktualizacja dostępna"
   :plugin/updating "Aktualizuję"
   :plugin/uninstall "Odinstaluj"
   :plugin/downloads "Ściągnięte"
   :plugin/stars "Gwiazdki"
   :plugin/title "Tytuł"
   :plugin/all "Wszystkie"
   :plugin/unpacked "Rozpakowany"
   :plugin/marketplace "Marketplace"
   :plugin/delete-alert "Czy na pewno chcesz usunąć plugin [{1}]?"
   :plugin/open-settings "Otwórz ustawienia"
   :plugin/open-package "Otwórz paczkę"
   :plugin/load-unpacked "Załaduj rozpakowany plugin"
   :plugin/restart "Uruchom ponownie"
   :plugin/unpacked-tips "Wybierz katalog z pluginem"
   :plugin/contribute "✨ Napisz i prześlij nowy plugin"
   :plugin/up-to-date "Wszystko jest aktualne"
   :plugin/custom-js-alert "Wykryto plik custom.js, czy chcesz go wykonać? Ze względów bezpieczeństwa, nie rekomendujemy wykonywania tego pliku, jeżeli nie znasz jego zawartości."

   :pdf/copy-ref "Kopiuj ref"
   :pdf/copy-text "Kopiuj tekst"
   :pdf/linked-ref "Połączone odwołania"
   :pdf/toggle-dashed "Styl kreskowany dla podświetlenia obszaru"

   :updater/new-version-install "Nowa wersja została ściągnięta."
   :updater/quit-and-install "Uruchom ponownie, aby zainstalować"

   :paginates/pages "{1} wszystkich stron"
   :paginates/prev "← Poprzednia"
   :paginates/next "Następna →"

   :tips/all-done "Wszystko zrobione"

   :command-palette/prompt "Wprowadź komendę"
   :select/default-prompt "Wybierz jeden"
   :select.graph/prompt "Wybierz graf"
   :select.graph/empty-placeholder-description "Brak pasujących grafów. Chcesz dodać nowy?"
   :select.graph/add-graph "Tak, dodaj nowy graf"

   :file-sync/other-user-graph "Obecny lokalny graf jest przypisany do zdalnego grafu innego użytkownika. Nie można rozpocząć synchronizacji."
   :file-sync/graph-deleted "Obecny zdalny graf został usunięty"})
