(ns frontend.dicts.tr
  "Provides translation to TR"
  #?(:cljs (:require [shadow.resource :as rc])))

(def dict
  {:accessibility/skip-to-main-content "Ana içeriğe geç"
   :tutorial/text #?(:cljs (rc/inline "tutorial-tr.md")
                     :default "tutorial-tr.md")
   :tutorial/dummy-notes #?(:cljs (rc/inline "dummy-notes-tr.md")
                            :default "dummy-notes-tr.md")
   :on-boarding/demo-graph "Bu bir demo graftır, yerel bir klasör açana kadar değişiklikler kaydedilmeyecektir."
   :on-boarding/add-graph "Bir graf ekle"
   :on-boarding/open-local-dir "Yerel bir dizin açın"
   :on-boarding/new-graph-desc-1 "Logseq, hem Markdown hem de Org modunu destekler. Cihazınızda var olan bir dizini (klasörü) açabilir veya yeni bir tane oluşturabilirsiniz. Verileriniz yalnızca bu cihazda saklanacaktır."
   :on-boarding/new-graph-desc-2 "Dizininizi açtıktan sonra, o dizinde üç klasör oluşturacaktır:"
   :on-boarding/new-graph-desc-3 "/journals - günlük sayfalarınız saklanır"
   :on-boarding/new-graph-desc-4 "/pages - diğer sayfalarınız saklanır"
   :on-boarding/new-graph-desc-5 "/logseq - yapılandırma, custom.css ve bazı meta veriler saklanır."
   :on-boarding/welcome-whiteboard-modal-title "Düşünceleriniz için yeni bir tuval."
   :on-boarding/welcome-whiteboard-modal-description "Beyaz tahtalar, fikir üretme ve düzenleme için harika bir araçtır. Şimdi bilgi tabanınızdaki düşüncelerinizi ya da yenilerini birbirleriyle yan yana getirerek, bağlantı kurabilir, ilişkilendirebilir ve yeni yöntemlerle anlayabilirsiniz."
   :on-boarding/welcome-whiteboard-modal-skip "Atla"
   :on-boarding/welcome-whiteboard-modal-start "Beyaz tahtaya başla"
   :on-boarding/tour-whiteboard-home "{1} Beyaz tahtalarınız için giriş sayfasıdır"
   :on-boarding/tour-whiteboard-home-description "Beyaz tahtalar uygulamada kendi bölümlerine sahiptir ve onları bir bakışta görebilir, kolayca yenilerini oluşturabilir veya silebilirsiniz."
   :on-boarding/tour-whiteboard-new "{1} Yeni beyaz tahta oluştur"
   :on-boarding/tour-whiteboard-new-description "Yeni bir beyaz tahta oluşturmanın birçok yolu vardır. Bunlardan biri her zaman tam burada bu panodadır."
   :help/start "Başlarken"
   :help/about "Logseq hakkında"
   :help/roadmap "Yol haritası"
   :help/bug "Hata raporu"
   :help/feature "Özellik talebi"
   :help/changelog "Değişiklik günlüğü"
   :help/blog "Logseq blogu"
   :help/docs "Belgeler"
   :help/privacy "Gizlilik ilkesi"
   :help/terms "Koşullar"
   :help/forum-community "Forum topluluğu"
   :help/awesome-logseq "Awesome Logseq"
   :help/shortcuts "Klavye kısayolları"
   :help/shortcuts-triggers "Tetikleyiciler"
   :help/shortcut "Kısayol"
   :help/slash-autocomplete "Eğik çizgi otomatik tamamlama"
   :help/block-content-autocomplete "Blok içeriği otomatik tamamlama"
   :help/reference-autocomplete "Sayfa referansı otomatik tamamlama"
   :help/block-reference "Blok referansı"
   :help/open-link-in-sidebar "Bağlantıyı kenar çubuğunda aç"
   :more "Daha fazla"
   :search/result-for "Arama sonucu: "
   :search/items "öğe"
   :search/page-names "Sayfa adlarında ara"
   :search-item/whiteboard "Beyaz tahta"
   :search-item/page "Sayfa"
   :search-item/file "Dosya"
   :search-item/block "Blok"
   :help/context-menu "Blok kısayol menüsü"
   :help/markdown-syntax "Markdown sözdizimi"
   :help/org-mode-syntax "Org modu sözdizimi"
   :bold "Kalın"
   :italics "İtalik"
   :highlight "Vurgulu"
   :strikethrough "Üstü çizili"
   :code "Kod"
   :untitled "Adsız"
   :right-side-bar/help "Yardım"
   :right-side-bar/switch-theme "Tema modları"
   :right-side-bar/contents "İçindekiler"
   :right-side-bar/page-graph "Sayfa grafı"
   :right-side-bar/history "(Dev) Geri Al / Yinele geçmişi"
   :right-side-bar/block-ref "Blok referansı"
   :right-side-bar/graph-view "Graf görünümü"
   :right-side-bar/all-pages "Bütün sayfalar"
   :right-side-bar/whiteboards "Beyaz tahtalar"
   :right-side-bar/flashcards "Bilgi kartları"
   :right-side-bar/new-page "Yeni sayfa"
   :right-side-bar/show-journals "Günlükleri Göster"
   :right-side-bar/separator "Sağ kenar çubuğu yeniden boyutlandırma işleyicisi"
   :left-side-bar/journals "Günlük"
   :left-side-bar/create "Oluştur"
   :left-side-bar/new-page "Yeni sayfa"
   :left-side-bar/new-whiteboard "Yeni beyaz tahta"
   :left-side-bar/nav-favorites "Sık kullanılanlar"
   :left-side-bar/nav-recent-pages "En son"
   :page/something-went-wrong "Bir sorun oluştu"
   :page/logseq-is-having-a-problem "Logseq'te bir sorun var. Tekrar çalışır duruma getirmek için lütfen aşağıdaki güvenli adımları sırayla deneyin:"
   :page/step "{1}. Adım"
   :page/try "Deneyin"
   :page/presentation-mode "Sunu"
   :page/delete-confirmation "Bu sayfayı ve dosyasını silmek istediğinizden emin misiniz?"
   :page/open-in-finder "Dizini aç"
   :page/open-with-default-app "Varsayılan uygulamayla aç"
   :page/make-public "Yayımlamak için herkese açık hale getir"
   :page/version-history "Sayfa geçmişini görüntüle"
   :page/open-backup-directory "Sayfa yedekleme dizinini aç"
   :page/make-private "Özel yap"
   :page/delete "Sayfayı sil"
   :page/add-to-favorites "Sık kullanılanlara ekle"
   :page/unfavorite "Sayfayı sık kullanılanlardan kaldır"
   :page/show-journals "Günlükleri göster"
   :page/show-whiteboards "Beyaz tahtaları göster"
   :block/name "Sayfa adı"
   :page/earlier "Daha önce"
   :page/copy-page-url "Sayfa URL adresini kopyala"
   :file/name "Dosya adı"
   :file/last-modified-at "Son değiştirilme tarihi"
   :file/no-data "Veri yok"
   :file/format-not-supported ".{1} biçimi desteklenmiyor."
   :file/validate-existing-file-error "Sayfa, başka bir dosyayla zaten var: {1}, geçerli dosya: {2}. Lütfen bunlardan yalnızca birini saklayın ve grafınız için yeniden dizin oluşturun."
   :file-rn/re-index "Dosyalar yeniden adlandırıldıktan ve diğer cihazlarla eşitledikten sonra yeniden dizin oluşturma önerilir."
   :file-rn/need-action "Yeni biçime uyması için dosya yeniden adlandırma eylemleri önerilir. Yeniden adlandırılan dosyalar eşitlendiğinde tüm cihazlarda yeniden dizin oluşturma gerekir."
   :file-rn/or-select-actions " veya aşağıdaki dosyaları tek tek yeniden adlandırın, ardından "
   :file-rn/or-select-actions-2 ". Bu paneli kapattığınızda bu eylemler kullanılamaz."
   :file-rn/legend "🟢 İsteğe bağlı yeniden adlandırma eylemleri; 🟡 Başlık değişikliğini önlemek için gereken yeniden adlandırma eylemi; 🔴 Hataya neden olan değişiklik."
   :file-rn/close-panel "Paneli Kapat"
   :file-rn/all-action "Tüm Eylemleri Uygula!"
   :file-rn/select-format "(Geliştirici Modu Seçeneği, Tehlikeli!) Dosya adı biçimini seçin"
   :file-rn/rename "\"{1}\" dosyasını \"{2}\" olarak yeniden adlandır"
   :file-rn/apply-rename "Dosya yeniden adlandırma işlemini uygula"
   :file-rn/suggest-rename "Eylem gereklidir: "
   :file-rn/otherwise-breaking "Veya başlık şöyle olacaktır:"
   :file-rn/no-action "Tebrikler! Gereken başka işlem yok."
   :file-rn/confirm-proceed "Biçimi güncelle!"
   :file-rn/select-confirm-proceed "Geliştirici: biçimi yaz"
   :file-rn/unreachable-title "Uyarı! `title::` özelliği el ile ayarlanmadıkça, sayfa adı geçerli dosya adı biçiminde {1} olur."
   :file-rn/optional-rename "Öneri: "
   :file-rn/format-deprecated "Şu anda güncel olmayan bir biçim kullanıyorsunuz. En son biçime güncellemeniz kesinlikle önerilir. Lütfen işlemden önce verilerinizi yedekleyin ve Logseq istemcilerini diğer cihazlarda kapatın."
   :file-rn/filename-desc-1 "Bu ayar, bir sayfanın bir dosyaya nasıl saklanacağını yapılandırır. Logseq, aynı ada sahip bir dosyaya bir sayfa depolar."
   :file-rn/filename-desc-2 "\"/\" vaya \"?\" gibi bazı karakterler bir dosya adı için geçersizdir."
   :file-rn/filename-desc-3 "Logseq, geçersiz karakterleri URL kodlu eşdeğerleriyle değiştirir (ör. \"?\", \"%3F\" olur)."
   :file-rn/filename-desc-4 "Ad boşluğu ayırıcısı \"/\", estetik değerlendirme için \"___\" (üçlü altçizgi) ile değiştirilir."
   :file-rn/instruct-1 "Dosya adı biçimini güncellemek 2 adımlı bir işlemdir:"
   :file-rn/instruct-2 "1. Tıklayın "
   :file-rn/instruct-3 "2. Dosyaları yeni biçimde yeniden adlandırmak için aşağıdaki talimatları izleyin:"
   :page/created-at "Oluşturulma Zamanı"
   :page/updated-at "Güncellenme Zamanı"
   :page/backlinks "Geri Bağlantılar"
   :linked-references/filter-search "Bağlantılı sayfalarda ara"
   :editor/block-search "Blok ara"
   :text/image "Resim"
   :asset/show-in-folder "Resmi klasörde göster"
   :asset/open-in-browser "Resmi tarayıcıda aç"
   :asset/delete "Resmi sil"
   :asset/copy "Resmi kopyala"
   :asset/maximize "Resim ekranı kaplasın"
   :asset/confirm-delete "Bu resmi silmek istediğinizden emin misiniz?"
   :asset/physical-delete "Dosyayı da kaldırın (geri getirilemeyeceğine dikkat edin)"
   :color/gray "Gri"
   :color/red "Kırmızı"
   :color/yellow "Sarı"
   :color/green "Yeşil"
   :color/blue "Mavi"
   :color/purple "Mor"
   :color/pink "Pembe"
   :editor/copy "Kopyala"
   :editor/cut "Kes"
   :editor/expand-block-children "Tümünü genişlet"
   :editor/collapse-block-children "Tümünü daralt"
   :editor/delete-selection "Seçili blokları sil"
   :editor/cycle-todo "Geçerli öğenin TODO durumunu döndür"
   :dev/show-page-data "(Dev) Sayfa verisini göster"
   :dev/show-block-data "(Dev) Blok verisini göster"
   :dev/show-block-ast "(Dev) Blok AST'sini göster"
   :dev/show-page-ast "(Dev) Sayfa AST'sini göster"
   :content/copy-export-as "Kopyala / Dışarı aktar.."
   :content/copy-block-url "Block URL'sini kopyala"
   :content/copy-block-ref "Blok referansını kopyala"
   :content/copy-block-emebed "Blok eklemesini kopyala"
   :content/copy-ref "Bu referansı kopyala"
   :content/delete-ref "Bu referansı sil"
   :content/replace-with-text "Metin ile değiştir"
   :content/replace-with-embed "Ekleme ile değiştir"
   :content/open-in-sidebar "Kenar çubuğunda aç"
   :content/click-to-edit "Düzenlemek için tıklayın"
   :context-menu/make-a-flashcard "Bilgi Kartı Oluştur"
   :context-menu/toggle-number-list "Numaralı liste olarak değiştir"
   :context-menu/preview-flashcard "Bilgi Kartını Önizle"
   :context-menu/make-a-template "Bir Şablon Oluştur"
   :context-menu/input-template-name "Şablonun adı nedir?"
   :context-menu/template-include-parent-block "Üst blok şablona dahil mi?"
   :context-menu/template-exists-warning "Şablon zaten var!"
   :settings-page/git-confirm "Git ayarlarını güncelledikten sonra uygulamayı yeniden başlatmanız gerekiyor."
   :settings-page/git-switcher-label "Otomatik git commit'i etkinleştir"
   :settings-page/git-commit-delay "Otomatik git commit saniyesi"
   :settings-page/edit-config-edn "config.edn dosyasını düzenle"
   :settings-page/edit-global-config-edn "Genel config.edn dosyasını düzenle"
   :settings-page/edit-custom-css "custom.css dosyasını düzenle"
   :settings-page/edit-export-css "export.css dosyasını düzenle"
   :settings-page/edit-setting "Düzenle"
   :settings-page/custom-configuration "Özel yapılandırma"
   :settings-page/custom-global-configuration "Özel genel yapılandırma"
   :settings-page/custom-theme "Özel tema"
   :settings-page/export-theme "Temayı dışarı aktar"
   :settings-page/show-brackets "Köşeli ayraçları göster"
   :settings-page/spell-checker "Yazım denetleyici"
   :settings-page/auto-updater "Otomatik güncelleme"
   :settings-page/disable-sentry "Kullanım verilerini ve tanılamayı Logseq'e gönderin"
   :settings-page/disable-sentry-desc "Logseq asla yerel graf veritabanınızı toplamayacak veya verilerinizi satmayacaktır."
   :settings-page/preferred-outdenting "Mantıksal girinti"
   :settings-page/show-full-blocks "Blok referansındaki tüm satırları göster"
   :settings-page/auto-expand-block-refs "Yakınlaştırdığınızda blok referanslarını otomatik olarak genişletin"
   :settings-page/custom-date-format "Tercih edilen tarih biçimi"
   :settings-page/custom-date-format-warning "Yeniden dizin oluşturma gerekli! Mevcut günlük referansları bozulabilir!"
   :settings-page/preferred-file-format "Tercih edilen dosya biçimi"
   :settings-page/preferred-workflow "Tercih edilen iş akışı"
   :settings-page/preferred-pasting-file "Dosya yapıştırmayı tercih et"
   :settings-page/enable-shortcut-tooltip "Kısayol araç ipuçlarını etkinleştir"
   :settings-page/enable-timetracking "Zaman takibi"
   :settings-page/enable-tooltip "Araç ipuçları"
   :settings-page/enable-journals "Günlük"
   :settings-page/enable-all-pages-public "Yayımlanan tüm sayfaları herkese açık yap"
   :settings-page/customize-shortcuts "Klavye kısayolları"
   :settings-page/shortcut-settings "Kısayolları özelleştir"
   :settings-page/home-default-page "Varsayılan ana sayfayı ayarla"
   :settings-page/enable-block-time "Blok zaman damgaları"
   :settings-page/clear-cache "Önbelleği temizle"
   :settings-page/clear "Temizle"
   :settings-page/clear-cache-warning "Önbelleği temizlemek açık grafları atacaktır. Kaydedilmemiş değişiklikleri kaybedersiniz."
   :settings-page/developer-mode "Geliştirici modu"
   :settings-page/developer-mode-desc "Geliştirici modu, katkıda bulunanların ve eklenti geliştiricilerinin Logseq ile entegrasyonlarını daha verimli bir şekilde test etmesine yardımcı olur."
   :settings-page/current-version "Geçerli sürüm"
   :settings-page/tab-general "Genel"
   :settings-page/tab-editor "Düzenleyici"
   :settings-page/tab-version-control "Sürüm denetimi"
   :settings-page/tab-advanced "Gelişmiş"
   :settings-page/tab-assets "Varlıklar"
   :settings-page/tab-features "Özellikler"
   :settings-page/plugin-system "Eklentiler"
   :settings-page/enable-flashcards "Bilgi kartları"
   :settings-page/network-proxy "Ağ ara sunucusu"
   :settings-page/filename-format "Dosya adı biçimi"
   :settings-page/alpha-features "Alpha özellikleri"
   :settings-page/beta-features "Beta özellikleri"
   :settings-page/login-prompt "Yeni özelliklere herkesten önce erişmek için bir Open Collective Sponsoru veya Logseq'in Destekçisi olmanız ve oturum açmanız gerekir."
   :settings-page/sync "Eşitle"
   :settings-page/enable-whiteboards "Beyaz tahtalar"
   :yes "Evet"
   :submit "Onayla"
   :cancel "İptal"
   :close "Kapat"
   :delete "Sil"
   :save "Kaydet"
   :type "Tür"
   :host "Ana Bilgisayar"
   :port "Bağlantı Noktası"
   :re-index "Yeniden dizin oluştur"
   :re-index-detail "Grafiği yeniden oluştur"
   :re-index-multiple-windows-warning "Bu graf için yeniden dizin oluşturmadan önce diğer pencereleri kapatmanız gerekiyor."
   :re-index-discard-unsaved-changes-warning "Yeniden dizin oluşturmak mevcut grafiği siler ve ardından tüm dosyaları o anda diskte depolandıkları şekilde yeniden işler. Kaydedilmemiş değişiklikleri kaybedeceksiniz ve bu biraz zaman alabilir. Devam edilsin mi?"
   :open-new-window "Yeni pencere"
   :sync-from-local-files "Yenile"
   :sync-from-local-files-detail "Yerel dosyalardan değişiklikleri içeri aktarın"
   :sync-from-local-changes-detected "Yenile, diskinizde değiştirilen ve gerçek Logseq sayfa içeriğinden ayrılan dosyaları algılar ve işler. Devam edilsin mi?"

   :search/publishing "Ara"
   :search "Ara veya sayfa oluştur"
   :whiteboard/link-whiteboard-or-block "Beyaz tahta/sayfa/blok bağlantısı"
   :page-search "Geçerli sayfada ara"
   :graph-search "Grafta ara"
   :new-page "Yeni sayfa"
   :new-whiteboard "Yeni beyaz tahta"
   :new-graph "Yeni graf ekle"
   :graph "Graf"
   :graph/persist "Logseq dahili durumu senkronize ediyor, lütfen birkaç saniye bekleyin."
   :graph/persist-error "Dahili durum senkronize edilemedi."
   :graph/save "Kaydediliyor..."
   :graph/save-success "Başarıyla Kaydedildi"
   :graph/save-error "Kaydedilemedi"
   :graph/all-graphs "Tüm graflar"
   :graph/local-graphs "Yerel graflar"
   :graph/remote-graphs "Uzak graflar"
   :export "Dışarı aktar"
   :export-graph "Grafı dışarı aktar"
   :export-page "Sayfayı dışarı aktar"
   :export-markdown "Standart Markdown olarak dışarı aktar (blok özelliği yok)"
   :export-opml "OPML olarak dışarı aktar"
   :export-public-pages "Herkese açık sayfaları dışarı aktar"
   :export-json "JSON olarak dışarı aktar"
   :export-roam-json "Roam JSON olarak dışarı aktar"
   :export-edn "EDN olarak dışarı aktar"
   :all-graphs "Tüm graflar"
   :all-pages "Tüm sayfalar"
   :all-whiteboards "Tüm beyaz tahtalar"
   :all-files "Tüm dosyalar"
   :remove-orphaned-pages "Yalnız bırakılmış sayfaları kaldır"
   :all-journals "Bütün günlükler"
   :settings "Ayarlar"
   :settings-of-plugins "Eklenti ayarları"
   :plugins "Eklentiler"
   :themes "Temalar"
   :relaunch-confirm-to-work "Çalışması için uygulama yeniden başlatılmalı. Şimdi yeniden başlatmak istiyor musunuz?"
   :import "İçeri aktar"
   :importing "İçeri aktarılıyor"
   :join-community "Topluluğa katıl"
   :discourse-title "Forum sayfamız!"
   :help-shortcut-title "Kısayolları ve diğer ipuçlarını kontrol etmek için tıklayın"
   :loading "Yükleniyor"
   :parsing-files "Dosyalar ayrıştırılıyor"
   :loading-files "Dosyalar yükleniyor"
   :login "Oturum aç"
   :logout "Oturumu kapat"
   :download "İndir"
   :language "Dil"
   :remove-background "Arka planı kaldır"
   :remove-heading "Başlığı kaldır"
   :heading "Başlık {1}"
   :auto-heading "Otomatik başlık"
   :open-a-directory "Yerel bir dizin aç"

   :help/shortcut-page-title "Klavye kısayolları"

   :plugin/installed "Yüklü"
   :plugin/not-installed "Yüklü olmayan"
   :plugin/installing "Yükleniyor"
   :plugin/install "Yükle"
   :plugin/reload "Yeniden yükle"
   :plugin/update "Güncelle"
   :plugin/check-update "Güncellemeyi denetle"
   :plugin/check-all-updates "Tüm güncellemeleri denetle"
   :plugin/found-updates "Yeni güncellemeler"
   :plugin/found-n-updates "{1} güncelleme bulundu"
   :plugin/update-all-selected "Seçilenlerin hepsini güncelle"
   :plugin/updates-downloading "Güncellemeler indiriliyor"
   :plugin/refresh-lists "Listeleri yenile"
   :plugin/enabled "Etkin"
   :plugin/disabled "Devre dışı"
   :plugin/update-available "Güncelleme var"
   :plugin/updating "Güncelleniyor"
   :plugin/uninstall "Kaldır"
   :plugin/marketplace "Market"
   :plugin/downloads "İndirilme"
   :plugin/stars "Yıldızlar"
   :plugin/title "Başlık"
   :plugin/all "Tümü"
   :plugin/unpacked "Çıkarılmamış"
   :plugin/delete-alert "[{1}] eklentisini kaldırmak istediğinizden emin misiniz?"
   :plugin/open-settings "Ayarları aç"
   :plugin/open-package "Eklentinin içeriğini aç"
   :plugin/load-unpacked "Çıkarılmamış eklentiyi yükle"
   :plugin/restart "Uygulamayı Yeniden Başlat"
   :plugin/unpacked-tips "Eklenti dizinini seçin"
   :plugin/contribute "✨ Yeni eklenti yaz ve gönder"
   :plugin/up-to-date "Güncel"
   :plugin/custom-js-alert "custom.js dosyası bulundu, çalıştırılmasına izin veriliyor mu? (Bu dosyanın içeriğini anlamadıysanız, belirli güvenlik riskleri olduğu için çalıştırmaya izin vermemeniz önerilir.)"
   :plugin.install-from-file/menu-title "plugins.edn dosyasından yükle"
   :plugin.install-from-file/title "Eklentileri plugins.edn dosyasından yükle"
   :plugin.install-from-file/notice "Aşağıdaki eklentiler yüklü olan eklentilerinizin yerini alacak:"
   :plugin.install-from-file/success "Tüm eklentiler yüklendi!"

   :pdf/copy-ref "Referansı kopyala"
   :pdf/copy-text "Metni kopyala"
   :pdf/linked-ref "Bağlantılı referans"
   :pdf/toggle-dashed "Alan vurgusu için çizgili stil"
   :pdf/hl-block-colored "Vurgulu blok için renkli etiket"
   :pdf/doc-metadata "Belge meta verileri"

   :updater/new-version-install "Yeni bir sürüm indirildi."
   :updater/quit-and-install "Yüklemek için yeniden başlatın"

   :paginates/pages "Toplam {1} sayfa"
   :paginates/prev "Önceki"
   :paginates/next "Sonraki"

   :tips/all-done "Tamamlandı"

   :command-palette/prompt "Bir komut yazın"
   :select/default-prompt "Birini seçin"
   :select/default-select-multiple "Bir veya daha fazla seçin"
   :select.graph/prompt "Bir graf seçin"
   :select.graph/empty-placeholder-description "Eşleşen graf yok. Bir tane daha eklemek ister misin?"
   :select.graph/add-graph "Evet, başka bir graf ekle"

   :file-sync/other-user-graph "Geçerli yerel graf, diğer kullanıcının uzak grafına bağlıdır. Bu yüzden senkronizasyon başlatılamıyor."
   :file-sync/graph-deleted "Geçerli uzak graf silindi"

   :notification/clear-all "Tümünü temizle"})
