(ns frontend.dicts
  (:require [tongue.core :as tongue]
            [frontend.config :as config]))

;; TODO
;; - [ ] Localizing Number Formats
;; - [ ] Localizing Dates


(def dicts
  {:en {:tutorial/text "---
title: $today
---

## Hi, welcome to Logseq!
:PROPERTIES:
:heading: true
:END:
## Logseq is a _privacy-first_, _open-source_ platform for _knowledge_ sharing and management.
## This is a 3 minutes tutorial on how to use Logseq. Let's get started!
## Here are some tips might be useful.
#+BEGIN_TIP
Click to edit any block.
Type `Enter` to create a new block.
Type `Shift+Enter` to create a new line.
Type `/` to show all the commands.
#+END_TIP
## 1. Let's create a page called [[How to take dummy notes?]]. You can click it to go to that page, or you can `Shift+Click` to open it in the right sidebar! Now you should see both _Linked References_ and _Unlinked References_.
## 2. Let's reference some blocks on [[How to take dummy notes?]], you can `Shift+Click` any block reference to open it in the right sidebar. Try making
some changes on the right sidebar, those referenced blocks will be changed too!
### ((5f713e91-8a3c-4b04-a33a-c39482428e2d)) : This is a block reference.
### ((5f713ea8-8cba-403d-ac00-9964b1ec7190)) : This is another block reference.
## 3. Do you support tags?
### Of course, this is a #dummy tag.
## 4. Do you support tasks like todo/doing/done and priorities?
### Yes, type `/` and pick your favorite todo keyword or priority (A/B/C).
### NOW [#A] A dummy tutorial on \"How to take dummy notes?\"
### LATER [#A] Check out this awesome video by [:a {:href \"https://twitter.com/EdTravelling\" :target \"_blank\"} \"@EdTravelling\"], which shows how to use logseq to open your local directory.

[:div.video-wrapper.mb-4
        [:iframe
         {:allowFullScreen \"allowfullscreen\"
          :allow
          \"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\"
        :frameBorder \"0\"
        :src \"https://www.youtube.com/embed/Afmqowr0qEQ\"
        :height \"367\"
        :width \"653\"}]]
### DONE Create a page
### CANCELED [#C] Write a page with more than 1000 blocks
## That's it! You can create more bullets or open a local directory to import some notes now!
##
"
        :tutorial/dummy-notes "---
title: How to take dummy notes?
---

## Hello, I'm a block!
:PROPERTIES:
:id: 5f713e91-8a3c-4b04-a33a-c39482428e2d
:END:
### I'm a child block!
### I'm another child block!
## Hey, I'm another block!
:PROPERTIES:
:id: 5f713ea8-8cba-403d-ac00-9964b1ec7190
:END:
"
        :on-boarding/title "Hi, welcome to Logseq!"
        :on-boarding/sharing "sharing"
        :on-boarding/is-a " is a "
        :on-boarding/vision "A privacy-first, open-source platform for knowledge sharing and management."
        :on-boarding/local-first "local-first"
        :on-boarding/non-linear "non-linear"
        :on-boarding/outliner "outliner"
        :on-boarding/notebook-for-organizing-and " notebook for organizing and "
        :on-boarding/your-personal-knowledge-base " your personal knowledge base."
        :on-boarding/notice "Notice that this project is in its alpha testing and under quick development, files might be corrupted."
        :on-boarding/features-desc "Use it to organize your todo list, to write your journals, or to record your unique life."
        :on-boarding/privacy "The server will never store or analyze your private notes. Your data are plain text files, we support both Markdown and Emacs Org mode for the time being. Even if the website is down or can't be maintained, your data is always yours."
        :on-boarding/inspired-by " is hugely inspired by "
        :on-boarding/where-are-my-notes-saved "Where are my notes saved?"
        :on-boarding/storage "Your notes will be stored in the local browser storage using "
        :on-boarding/how-do-i-use-it "How do I use it?"
        :on-boarding/use-1 "1. Sync between multiple devices"
        :on-boarding/use-1-desc "Currently, we only support syncing through Github, more options (Self-host git, WebDAV, Google Drive, etc.) will be added soon."
        :on-boarding/use-1-video "Check out this awesome video by "
        :on-boarding/use-2 "2. Use it locally (no need to login)"
        :on-boarding/features "Features"
        :on-boarding/features-backlinks "Backlinks between [[Page]]s"
        :on-boarding/features-block-embed "Block embed"
        :on-boarding/features-page-embed "Page embed"
        :on-boarding/features-graph-vis "Graph visualization"
        :on-boarding/features-heading-properties "Heading properties"
        :on-boarding/features-datalog "Datalog queries, the notes db is powered by "
        :on-boarding/features-custom-view-component "Custom view component"
        :on-boarding/integration " integration"
        :on-boarding/slide-support " slide support"
        :on-boarding/built-in-supports "Document built-in supports:"
        :on-boarding/supports-code-highlights "Code highlights"
        :on-boarding/supports-katex-latex "Katex latex"
        :on-boarding/raw "Raw "
        :on-boarding/raw-html "Raw html"
        :on-boarding/learn-more "Learn more"
        :on-boarding/discord-desc " where the community ask questions and share tips"
        :on-boarding/github-desc " everyone is encouraged to report issues!"
        :on-boarding/our-blog "Our blog: "
        :on-boarding/credits-to "Credits to"
        :on-boarding/clojure-desc " - A dynamic, functional, general-purpose programming language"
        :on-boarding/datascript-desc " - Immutable database and Datalog query engine for Clojure, ClojureScript and JS"
        :on-boarding/angstrom-desc-1 ", the document "
        :on-boarding/angstrom-desc-2 "parser"
        :on-boarding/angstrom-desc-3 " is built on Angstrom."
        :on-boarding/cuekeeper-desc " - Browser-based GTD (TODO list) system."
        :on-boarding/sci-desc " - Small Clojure Interpreter"
        :on-boarding/isomorphic-git-desc " - A pure JavaScript implementation of git for node and browsers!"
        :help/about "About Logseq"
        :help/bug "Bug report"
        :help/feature "Feature request"
        :help/changelog "Changelog"
        :help/blog "Logseq Blog"
        :help/docs "Documentation"
        :help/privacy "Privacy policy"
        :help/terms "Terms"
        :help/community "Discord community"
        :help/shortcuts "Keyboard Shortcuts"
        :help/shortcuts-triggers "Triggers"
        :help/shortcut "Shortcut"
        :help/slash-autocomplete "Slash Autocomplete"
        :help/block-content-autocomplete "Block content (Src, Quote, Query, etc) Autocomplete"
        :help/reference-autocomplete "Page reference Autocomplete"
        :help/block-reference "Block Reference"
        :help/key-commands "Key Commands"
        :help/working-with-lists " (working with lists)"
        :help/indent-block-tab "Indent Block Tab"
        :help/unindent-block "Unindent Block"
        :help/move-block-up "Move Block Up"
        :help/move-block-down "Move Block Down"
        :help/create-new-block "Create New Block"
        :help/new-line-in-block "New Line in Block"
        :help/select-nfs-browser "Please use another browser (like latest chrome) which support NFS features to open local directory."
        :undo "Undo"
        :redo "Redo"
        :help/zoom-in "Zoom In"
        :help/zoom-out "Zoom out"
        :help/follow-link-under-cursor "Follow link under cursor"
        :help/open-link-in-sidebar "Open link in Sidebar"
        :expand "Expand"
        :collapse "Collapse"
        :select-block-above "Select Block Above"
        :select-block-below "Select Block Below"
        :select-all-blocks "Select All Blocks"
        :general "General"
        :help/toggle "Toggle help"
        :help/git-commit-message "Git commit message"
        :help/full-text-search "Full Text Search"
        :help/context-menu "Context Menu"
        :help/fold-unfold "Fold/Unfold blocks (when not in edit mode)"
        :help/toggle-doc-mode "Toggle document mode"
        :help/toggle-theme "Toggle between dark/light theme"
        :help/toggle-right-sidebar "Toggle right sidebar"
        :help/toggle-insert-new-block "Toggle Enter/Alt+Enter for inserting new block"
        :help/jump-to-journals "Jump to Journals"
        :formatting "Formatting"
        :help/markdown-syntax "Markdown syntax"
        :help/org-mode-syntax "Org mode syntax"
        :bold "Bold"
        :italics "Italics"
        :html-link "Html Link"
        :highlight "Highlight"
        :strikethrough "Strikethrough"
        :code "Code"
        :right-side-bar/help "Help"
        :right-side-bar/switch-theme "Switch to {1} theme"
        :right-side-bar/theme "{1} theme"
        :right-side-bar/page "Page graph"
        :right-side-bar/recent "Recent"
        :right-side-bar/contents "Contents"
        :right-side-bar/graph-ref "Graph of "
        :right-side-bar/block-ref "Block reference"
        :git/set-access-token "Set Github personal access token"
        :git/token-is-encrypted "The token will be encrypted and stored in the browser local storage"
        :git/token-server "The server will never store it"
        :git/create-personal-access-token "How to create a Github personal access token?"
        :git/push "Push now"
        :git/push-failed "Push failed!"
        :git/local-changes-synced "All local changes are synced!"
        :git/pull "Pull now"
        :git/last-pull "Last pulled at"
        :git/version "Version"
        :git/import-notes "Import your notes"
        :git/import-notes-helper "You can import your notes from a repo on Github."
        :git/add-another-repo "Add another repo"
        :git/re-index "Clone again and re-index the db"
        :git/message "Your commit message"
        :git/commit-and-push "Commit and push!"
        :git/use-remote "Use remote"
        :git/keep-local "Keep local"
        :git/edit "Edit"
        :git/title "Diff"
        :git/no-diffs "No diffs"
        :git/commit-message "Commit message (optional)"
        :git/pushing "Pushing"
        :git/force-push "Commit and force pushing"
        :git/a-force-push "A force push"
        :git/add-repo-prompt "Install Logseq on your repo"
        :git/add-repo-prompt-confirm "Add and install"
        :format/preferred-mode "What's your preferred mode?"
        :format/markdown "Markdown"
        :format/org-mode "Org Mode"
        :reference/linked "Linked Reference"
        :reference/unlinked-ref "Unlinked References"
        :project/setup "Setup a public project on Logseq"
        :project/location "All published pages will be located under"
        :project/sync-settings "Sync project settings"
        :page/presentation-mode "Presentation mode (Powered by Reveal.js)"
        :page/edit-properties-placeholder "Click here to edit this page's properties"
        :page/delete-success "Page {1} was deleted successfully!"
        :page/delete-confirmation "Are you sure you want to delete this page and its file?"
        :page/rename-to "Rename \"{1}\" to:"
        :page/priority "Priority \"{1}\""
        :page/re-index "Re-index this page"
        :page/copy-to-json "Copy the whole page as JSON"
        :page/rename "Rename page"
        :page/open-in-finder "Open in directory"
        :page/open-with-default-app "Open with default app"
        :page/action-publish "Publish"
        :page/make-public "Publish it when exporting to an html file"
        :page/make-private "Make it private"
        :page/delete "Delete page"
        :page/publish "Publish this page on Logseq"
        :page/cancel-publishing "Cancel publishing on Logseq"
        :page/publish-as-slide "Publish this page as a slide on Logseq"
        :page/unpublish "Un-publish this page on Logseq"
        :page/add-to-contents "Add to Contents"
        :page/show-journals "Show Journals"
        :page/show-name "Show page name"
        :page/hide-name "Hide page name"
        :page/name "Page name"
        :page/last-modified "Last modified at"
        :page/new-title "What's your new page title?"
        :publishing/pages "Pages"
        :publishing/page-name "Page name"
        :publishing/current-project "Current Project"
        :publishing/delete-from-logseq "Delete From Logseq Server"
        :publishing/edit "Edit"
        :publishing/save "Save"
        :publishing/cancel "Cancel"
        :publishing/delete "Delete"
        :journal/multiple-files-with-different-formats "It seems that you have multiple journal files (with different formats) for the same month, please only keep one journal file for each month."
        :journal/go-to "Go to files"
        :file/name "File name"
        :file/file "File: "
        :file/last-modified-at "Last modified at"
        :file/no-data "No data"
        :file/format-not-supported "Format .{1} is not supported."
        :editor/block-search "Search for a block"
        :editor/image-uploading "Uploading"
        :draw/invalid-file "Could not load this invalid excalidraw file"
        :draw/specify-title "Please specify a title first!"
        :draw/rename-success "File was renamed successfully!"
        :draw/rename-failure "Rename file failed, reason: "
        :draw/title-placeholder "Untitled"
        :draw/save "Save"
        :draw/save-changes "Save changes"
        :draw/new-file "New file"
        :draw/list-files "List files"
        :draw/delete "Delete"
        :draw/more-options "More options"
        :draw/back-to-logseq "Back to logseq"
        :text/image "Image"
        :asset/confirm-delete "Are you sure you want to delete this {1}?"
        :asset/physical-delete "Remove the file too (notice it can't be restored)"
        :content/copy "Copy"
        :content/cut "Cut"
        :content/make-todos "Make {1}s"
        :content/copy-block-ref "Copy block ref"
        :content/focus-on-block "Focus on block"
        :content/open-in-sidebar "Open in sidebar"
        :content/copy-as-json "Copy as JSON"
        :content/click-to-edit "Click to edit"
        :settings-page/edit-config-edn "Edit config.edn (for current repo)"
        :settings-page/show-brackets "Show brackets"
        :settings-page/preferred-file-format "Preferred file format"
        :settings-page/preferred-workflow "Preferred workflow"
        :settings-page/enable-timetracking "Enable timetracking"
        :settings-page/enable-journals "Enable journals"
        :settings-page/home-default-page "Set the default home page"
        :settings-page/enable-block-time "Enable block timestamps"
        :settings-page/dont-use-other-peoples-proxy-servers "Don't use other people's proxy servers. It's very dangerous, which could make your token and notes stolen. Logseq will not be responsible for this loss if you use other people's proxy servers. You can deploy it yourself, check "
        :settings-page/custom-cors-proxy-server "Custom CORS proxy server"
        :settings-page/developer-mode "Developer mode"
        :settings-page/enable-developer-mode "Enable developer mode"
        :settings-page/disable-developer-mode "Disable developer mode"
        :settings-page/developer-mode-desc "Developer mode helps contributors and extension developers test their integration with Logseq more efficient."
        :settings-page/current-version "Current version"
        :logseq "Logseq"
        :dot-mode "Dot mode"
        :on "ON"
        :more-options "More options"
        :to "to"
        :yes "Yes"
        :submit "Submit"
        :cancel "Cancel"
        :re-index "Re-index"
        :export-json "Export as JSON"
        :unlink "unlink"
        :search (if config/publishing?
                  "Search"
                  "Search or Create Page")
        :new-page "New page"
        :new-file "New file"
        :graph "Graph"
        :publishing "Publishing"
        :export "Export public pages"
        :all-graphs "All graphs"
        :all-pages "All pages"
        :all-files "All files"
        :all-journals "All journals"
        :my-publishing "My publishing"
        :settings "Settings"
        :import "Import"
        :join-community "Join the community"
        :sponsor-us "Sponsor Us"
        :discord-title "Our discord group!"
        :sign-out "Sign out"
        :help-shortcut-title "Click to check shortcuts and other tips"
        :loading "Loading"
        :cloning "Cloning"
        :parsing-files "Parsing files"
        :loading-files "Loading files"
        :login-github "Login with Github"
        :login-google "Login with Google"
        :login "Login"
        :go-to "Go to "
        :or "or"
        :download "Download"
        :repo/download-zip "Download all files as a zip"
        :language "Language"
        :white "Light"
        :dark "Dark"
        :remove-background "Remove background"
        :open "Open"
        :open-a-directory "Open a local directory"}

   :fr {:help/about "A propos de Logseq"
        :help/bug "Signaler une anomalie"
        :help/feature "Demander une fonctionnalité"
        :help/changelog "Journal des modifications"
        :help/blog "Blog de Logseq"
        :help/docs "Documentation"
        :help/privacy "Politique de confidentialité"
        :help/terms "Conditions d'utilisation"
        :help/community "Communauté Discord"
        :help/shortcuts "Raccourcis clavier"
        :help/shortcuts-triggers "Actions déclenchées"
        :help/shortcut "Raccourcis"
        :help/slash-autocomplete "Slash Autocomplétion"
        :help/block-content-autocomplete "Autocomplétion du contenu du Bloc (Src, Quote, Query, etc)"
        :help/reference-autocomplete "Autocomplétion des références à une Page"
        :help/block-reference "Référence à un Bloc"
        :help/key-commands "Key Commands"
        :help/working-with-lists " (working with lists)"
        :help/indent-block-tab "Indenter un Bloc vers la droite"
        :help/unindent-block "Indenter un Bloc vers la gauche"
        :help/move-block-up "Déplacer un bloc au dessus"
        :help/move-block-down "Déplacer un bloc en dessous"
        :help/create-new-block "Créer un nouveau bloc"
        :help/new-line-in-block "Aller à la ligne dans un bloc"
        :help/select-nfs-browser "Please use another browser (like latest chrome) which support NFS features to open local directory."
        :undo "Annuler"
        :redo "Redo"
        :help/zoom-in "Zoomer"
        :help/zoom-out "Dézoomer"
        :help/follow-link-under-cursor "Suivre le lien sous le curseur"
        :help/open-link-in-sidebar "Ouvrir le lien dans la barre latérale"
        :expand "Etendre"
        :collapse "Réduire"
        :select-block-above "Sélectionner le bloc au dessus"
        :select-block-below "Sélectionner le bloc en dessous"
        :select-all-blocks "Sélectionner tous les blocs"
        :general "Général"
        :help/toggle "Afficher l'aide"
        :help/git-commit-message "Message de commit Git"
        :help/full-text-search "Recherche globale dans le texte"
        :help/context-menu "Menu contextuel"
        :help/fold-unfold "Plier/Déplier les blocs (hors mode édition)"
        :help/toggle-doc-mode "Intervertir le mode document"
        :help/toggle-theme "Intervertir le thème foncé/clair"
        :help/toggle-right-sidebar "Afficher/cacher la barre latérale"
        :help/toggle-insert-new-block "Activer Entreée ou Alt+Enter pour insérer un bloc"
        :help/jump-to-journals "Aller au Journal"
        :formatting "Formats"
        :help/markdown-syntax "Syntaxe Markdown"
        :help/org-mode-syntax "Syntaxe Org mode"
        :bold "Gras"
        :italics "Italique"
        :html-link "Lien HTML"
        :highlight "Surligner"
        :strikethrough "Barré"
        :code "Code"
        :right-side-bar/help "Aide"
        :right-side-bar/switch-theme "Basculer sur le thème {1}"
        :right-side-bar/theme "Thème {1}"
        :right-side-bar/page "Graphe de la page"
        :right-side-bar/recent "Récents"
        :right-side-bar/contents "Contenus"
        :right-side-bar/graph-ref "Graphe de "
        :right-side-bar/block-ref "Référence des blocs"
        :git/set-access-token "Définir un jeton d'accès personnel GitHub"
        :git/token-is-encrypted "Le jeton sera chiffré et gardé dans le stockage local du navigateur (local storage)"
        :git/token-server "Le serveur ne le stockera jamais"
        :git/create-personal-access-token "Comment générer un jeton d'accès GitHub ?"
        :git/push "Pousser maintenant (push)"
        :git/push-failed "L'envoi des données a échoué !"
        :git/local-changes-synced "Tous les changements locaux sont synchronisés !"
        :git/pull "Récupérer maintenant (pull)"
        :git/last-pull "Dernière récupération à"
        :git/version "Version"
        :git/import-notes "Importer mes notes"
        :git/import-notes-helper "Vous pouvez importer vos notes depuis un répertoire sur GitHub."
        :git/add-another-repo "Ajouter un autre répertoire GitHub"
        :git/re-index "Cloner à nouveau et indexer la base de données"
        :git/message "Votre message de commit"
        :git/commit-and-push "Commiter et pousser !"
        :git/use-remote "Utiliser les modifications distantes"
        :git/keep-local "Garder mes modifications locales"
        :git/edit "Editer"
        :git/title "Différences"
        :git/no-diffs "Pas de différences"
        :git/commit-message "Message de commit (facultatif)"
        :git/pushing "Envoi en cours"
        :git/force-push "Commiter et forcer l'envoi"
        :git/a-force-push "Un envoi forcé"
        :git/add-repo-prompt "Installer Logseq dans votre répertoire"
        :git/add-repo-prompt-confirm "Ajouter et installer"
        :format/preferred-mode "Quel est votre format préféré ?"
        :format/markdown "Markdown"
        :format/org-mode "Org Mode"
        :reference/linked "Références liées"
        :reference/unlinked-ref "Références non liées"
        :project/setup "Paramétrer un projet public sur Logseq"
        :project/location "Toutes les pages publiées seront joignables sous"
        :project/sync-settings "Synchroniser les paramètres du projet"
        :page/presentation-mode "Mode présentation (avec Reveal.js)"
        :page/delete-success "Page {1} supprimée !"
        :page/delete-confirmation "Etes-vous sûr de vouloir supprimer la page ?"
        :page/rename-to "Renommer \"{1}\" en:"
        :page/priority "Priorité \"{1}\""
        :page/re-index "Indexer à nouveau cette page"
        :page/copy-to-json "Copier la page au format JSON"
        :page/rename "Renommer la page"
        :page/make-public "Rendre la page publique"
        :page/make-private "Rendre la page privée"
        :page/delete "Supprimer la page (supprime le fichier)"
        :page/publish "Publier cette page sur Logseq"
        :page/cancel-publishing "Cancel publishing on Logseq"
        :page/publish-as-slide "Publier cette page en présentation sur Logseq"
        :page/unpublish "Dépublier cette page de Logseq"
        :page/add-to-contents "Ajouter au Contenu"
        :page/show-journals "Afficher le Journal"
        :page/show-name "Afficher le nom de la page"
        :page/hide-name "Cacher le nom de la page"
        :page/name "Nom de la page"
        :page/last-modified "Dernières modifications à"
        :page/new-title "Quel est le nouveau titre de la page ?"
        :publishing/pages "Pages"
        :publishing/page-name "Page name"
        :publishing/current-project "Current Project"
        :publishing/delete-from-logseq "Delete From Logseq Server"
        :publishing/edit "Edit"
        :publishing/save "Save"
        :publishing/cancel "Cancel"
        :publishing/delete "Delete"
        :journal/multiple-files-with-different-formats "Il semble que vous avez plusieurs fichier de journal (sous différents formats) pour le même mois, veuillez ne conserver qu'un fichier par mois."
        :journal/go-to "Voir les fichiers"
        :file/name "Nom de fichier"
        :file/file "Fichier: "
        :file/last-modified-at "Dernières modifications à"
        :file/no-data "Aucune donnée"
        :file/format-not-supported "Le format .{1} n'est pas supporté."
        :editor/block-search "Rechercher un bloc"
        :editor/image-uploading "Envoi en cours"
        :draw/invalid-file "Impossible de charger ce fichier excalidraw"
        :draw/specify-title "Veuillez préciser un titre"
        :draw/rename-success "Le fichier a été renommé !"
        :draw/rename-failure "Le fichier n'a pas pu être renommé : "
        :draw/title-placeholder "Sans titre"
        :draw/save "Enregistrer"
        :draw/save-changes "Enregistrer les modifications"
        :draw/new-file "Nouveau fichier"
        :draw/list-files "Liste des fichiers"
        :draw/delete "Supprimer"
        :draw/more-options "Plus d'options"
        :draw/back-to-logseq "Retourner sur logseq"
        :content/copy "Copier"
        :content/cut "Couper"
        :content/make-todos "Faire {1}s"
        :content/copy-block-ref "Copier la référence du bloc"
        :content/focus-on-block "Focus sur le bloc"
        :content/open-in-sidebar "Ouvrir dans la barre latérale"
        :content/copy-as-json "Copier au format JSON"
        :content/click-to-edit "Cliquer pour éditer"
        :settings-page/edit-config-edn "Editer config.edn (pour le repo actuel)"
        :settings-page/preferred-file-format "Format de fichier préféré"
        :settings-page/preferred-workflow "Workflow préféré"
        :settings-page/enable-timetracking "Activer le suivi de temps des tâches"
        :settings-page/dont-use-other-peoples-proxy-servers "N'utilisez pas de serveurs proxy que vous ne maîtrisez pas. Cela est très dangereux, vous pourriez vous faire voler vos jetons d'accès et vos notes. Logseq ne pourra être tenu responsable pour toute perte ou vol de données si vous utilisez des serveurs proxy. Vous pouvez également déployer Logseq vous-même, regardez "
        :settings-page/custom-cors-proxy-server "CORS personnalisé pour Serveur Proxy"
        :settings-page/developer-mode "Developer mode"
        :settings-page/enable-developer-mode "Activer le mode développeur"
        :settings-page/disable-developer-mode "Désactiver le mode développeur"
        :settings-page/developer-mode-desc "Le mode développeur aide les contributeurs et les développeurs d'extension à tester leur intégration avec Logseq."
        :logseq "Logseq"
        :dot-mode "Dot mode"
        :on "ON"
        :more-options "Plus d'options"
        :to "à"
        :yes "Oui"
        :submit "Envoyer"
        :cancel "Annuler"
        :re-index "Ré-indexer"
        :export-json "Exporter au format JSON"
        :unlink "délier"
        :search (if config/publishing?
                  "Rechercher"
                  "Rechercher ou Créer la Page")
        :new-page "Nouvelle page"
        :new-file "Nouveau fichier"
        :graph "Graphe"
        :publishing "Publication"
        :all-pages "Toutes les pages"
        :all-files "Tous les fichiers"
        :all-journals "Tous les journaux"
        :my-publishing "My publishing"
        :settings "Préférences"
        :import "Importer"
        :join-community "Rejoindre la communauté"
        :discord-title "Notre groupe Discord !"
        :sign-out "Se déconnecter"
        :help-shortcut-title "Click to check shortcuts and other tips"
        :loading "Chargement en cours"
        :cloning "Clonage en cours"
        :parsing-files "Analyse des fichiers"
        :loading-files "Chargement des fichiers"
        :login-github "S'authentifier avec Github"
        :login-google "S'authentifier avec Google"
        :go-to "Aller à "
        :or "ou"
        :download "Télécharger"
        :language "Langage"
        :white "Clair"
        :dark "Foncé"
        :remove-background "Retirer le fond"}

   :zh-CN {:on-boarding/title "你好，欢迎使用 Logseq！"
           :on-boarding/sharing "分享"
           :on-boarding/is-a " 是一个 "
           :on-boarding/local-first "本地优先"
           :on-boarding/non-linear "非线性"
           :on-boarding/outliner "大纲"
           :on-boarding/notebook-for-organizing-and " 笔记本， 用来整理和"
           :on-boarding/your-personal-knowledge-base "你的个人知识库。"
           :on-boarding/notice "请注意， 本项目正在快速开发中， 存在文件损坏的风险。"
           :on-boarding/features-desc "使用它来组织您的待办事项列表、 写日志或记录您的独特生活。"
           :on-boarding/privacy "服务器将永远不会存储或分析您的私人笔记。 您的数据是纯文本文件，我们暂时支持 Markdown 和 Emacs Org 模式。 即使网站已经关闭或无法维护，您的数据也永远属于您。"
           :on-boarding/inspired-by " 受到这些产品启发："
           :on-boarding/where-are-my-notes-saved "我的笔记存储在哪里？"
           :on-boarding/storage "你的笔记会被存储在本地浏览器中，使用 "
           :on-boarding/how-do-i-use-it "我该如何使用它？"
           :on-boarding/use-1 "1. 在多设备间同步"
           :on-boarding/use-1-desc "目前，我们只支持通过 Github 进行同步，将很快添加更多选项 (Self-host git、WebDAV、Google Drive等)。"
           :on-boarding/use-1-video "看看这个很棒的视频，创作者 "
           :on-boarding/use-2 "2. 在本地使用 (无需登录)"
           :on-boarding/features "功能"
           :on-boarding/features-backlinks "[[页面]] 之间的双向链接"
           :on-boarding/features-block-embed "块嵌入"
           :on-boarding/features-page-embed "页面嵌入"
           :on-boarding/features-graph-vis "图表可视化"
           :on-boarding/features-heading-properties "块属性"
           :on-boarding/features-datalog "Datalog 自定义查询——笔记数据库使用 "
           :on-boarding/features-custom-view-component "自定义视图组件"
           :on-boarding/integration " 集成"
           :on-boarding/slide-support " 幻灯片支持"
           :on-boarding/built-in-supports "文档内置支持："
           :on-boarding/supports-code-highlights "代码高亮显示"
           :on-boarding/supports-katex-latex "Katex latex"
           :on-boarding/raw "原始 "
           :on-boarding/raw-html "原始 html"
           :on-boarding/learn-more "了解更多"
           :on-boarding/discord-desc " 社区在此处提问和分享提示"
           :on-boarding/github-desc " 欢迎所有人报告问题！"
           :on-boarding/our-blog "我们的博客："
           :on-boarding/credits-to "鸣谢"
           :on-boarding/clojure-desc " - 一种动态的、函数式、通用的编程语言"
           :on-boarding/datascript-desc " - Clojure, ClojureScript 和 JS 的不可变数据库和 Datalog 查询引擎"
           :on-boarding/angstrom-desc-1 ", 文档"
           :on-boarding/angstrom-desc-2 "解析器"
           :on-boarding/angstrom-desc-3 "建立在 Angstrom 之上。"
           :on-boarding/cuekeeper-desc " - 基于浏览器的 GTD (待办清单) 系统。"
           :on-boarding/sci-desc " - 小型 Clojure 解析器"
           :on-boarding/isomorphic-git-desc " - 用于 Node 和浏览器的纯 JavaScript Git 实现！"
           :help/about "关于 Logseq"
           :help/bug "Bug 反馈"
           :help/feature "功能建议"
           :help/changelog "更新日志"
           :help/blog "Logseq 博客"
           :help/docs "文档"
           :help/privacy "隐私声明"
           :help/terms "服务条款"
           :help/community "Discord 社区"
           :help/shortcuts "快捷键"
           :help/shortcuts-triggers "触发"
           :help/shortcut "快捷键"
           :help/slash-autocomplete "Slash 自动提示"
           :help/block-content-autocomplete "块内容 (Src, Quote, Query 等) 自动完成"
           :help/reference-autocomplete "页面引用自动补全"
           :help/block-reference "块引用"
           :help/key-commands "关键命令"
           :help/working-with-lists " (与列表相关)"
           :help/indent-block-tab "缩进块标签"
           :help/unindent-block "取消缩进块"
           :help/move-block-up "向上移动块"
           :help/move-block-down "向下移动块"
           :help/create-new-block "创建块"
           :help/new-line-in-block "块中新建行"
           :help/select-nfs-browser "请选择支持nfs的浏览来使用logseq本地文件夹功能, 如最新的Chrome浏览器."
           :text/image "图片"
           :asset/confirm-delete "确定要删除{1}吗?"
           :asset/physical-delete "同时删除本地文件（目前不可撤销）"
           :undo "撤销"
           :redo "重做"
           :help/zoom-in "聚焦"
           :help/zoom-out "推出聚焦"
           :help/follow-link-under-cursor "跟随光标下的链接"
           :help/open-link-in-sidebar "在侧边栏打开"
           :expand "展开"
           :collapse "折叠"
           :select-block-above "选择上方的块"
           :select-block-below "选择下方的块"
           :select-all-blocks "选择所有块"
           :general "常规​​​​​"
           :help/toggle "显示/关闭帮助"
           :help/git-commit-message "提交消息"
           :help/full-text-search "全文搜索"
           :help/context-menu "右键菜单"
           :help/fold-unfold "折叠/展开方块(不在编辑模式中)"
           :help/toggle-doc-mode "切换文档模式"
           :help/toggle-theme "“在暗色/亮色主题之间切换”"
           :help/toggle-right-sidebar "启用/关闭右侧栏"
           :help/toggle-insert-new-block "切换 Enter/Alt+Enter 以插入新块"
           :help/jump-to-journals "跳转到日记"
           :formatting "格式化"
           :help/markdown-syntax "Markdown 语法"
           :help/org-mode-syntax "Org Mode 语法"
           :bold "粗体"
           :italics "斜体"
           :html-link "Html 链接"
           :highlight "高亮"
           :strikethrough "删除线"
           :code "代码"
           :right-side-bar/help "帮助"
           :right-side-bar/switch-theme "切换到 {1} 主题"
           :right-side-bar/theme "{1}主题"
           :right-side-bar/page "页面图谱"
           :right-side-bar/recent "最近"
           :right-side-bar/contents "目录"
           :right-side-bar/graph-ref "图谱："
           :right-side-bar/block-ref "块引用"
           :git/set-access-token "设定 Github 个人访问令牌"
           :git/token-is-encrypted "令牌将被加密并存储在浏览器本地存储"
           :git/token-server "服务器将永远不会存储它"
           :git/create-personal-access-token "如何创建 Github 个人访问令牌？"
           :git/push "现在 push"
           :git/push-failed "Push 失败!"
           :git/local-changes-synced "所有本地更改已同步！"
           :git/pull "现在 pull"
           :git/last-pull "最后 pull 时间 "
           :git/version "版本"
           :git/import-notes "导入笔记"
           :git/import-notes-helper "你可以从 Github 的库中导入笔记"
           :git/add-another-repo "添加一个库"
           :git/re-index "重新 clone 然后重新建立索引"
           :git/message "你的 commit 信息"
           :git/commit-and-push "commit 并 push"
           :git/use-remote "使用云端版本"
           :git/keep-local "使用本地版本"
           :git/edit "编辑"
           :git/title "文件冲突"
           :git/no-diffs "没有文件冲突"
           :git/commit-message "commit 消息（可选）"
           :git/pushing "Pushing"
           :git/force-push "Commit 并强制 push"
           :git/a-force-push "强制 push"
           :git/add-repo-prompt "在你的库上安装 Logseq"
           :git/add-repo-prompt-confirm "添加并安装"
           :format/preferred-mode "请选择偏好格式"
           :format/markdown "Markdown"
           :format/org-mode "Org Mode"
           :reference/linked "已链接的引用"
           :reference/unlinked-ref "未链接的引用"
           :project/setup "在 Logseq 上发布新的项目"
           :project/location "一切发布的页面将会被放到 "
           :project/sync-settings "同步项目设置"
           :page/edit-properties-placeholder "点击这里编辑当前页面的属性 (标签，别名等)"
           :page/presentation-mode "演讲模式 (由 Reveal.js 驱动)"
           :page/delete-success "页面 {1} 删除成功！"
           :page/delete-confirmation "您确定要删除此页面和文件吗？"
           :page/rename-to "重命名 \"{1}\" 至："
           :page/priority "优先级 \"{1}\""
           :page/re-index "对此页面重新建立索引"
           :page/copy-to-json "将整页以 JSON 格式复制"
           :page/rename "重命名本页"
           :page/open-in-finder "打开文件对应目录"
           :page/open-with-default-app "用默认应用打开文件"
           :page/action-publish "发布"
           :page/make-public "导出 HTML 时发布本页面"
           :page/make-private "导出 HTML 时取消发布本页面"
           :page/delete "删除本页"
           :page/publish "将本页发布至 Logseq"
           :page/cancel-publishing "撤回本页在 Logseq 上的发布"
           :page/publish-as-slide "将本页作为幻灯片发布至 Logseq"
           :page/unpublish "取消将本页发布至 Logseq"
           :page/add-to-contents "将本页添加到目录"
           :page/show-journals "显示日志"
           :page/show-name "显示页面名"
           :page/hide-name "隐藏页面名"
           :page/name "页面名称"
           :page/last-modified "最后更改于"
           :page/new-title "请输入新页面的名字:"
           :publishing/pages "页面"
           :publishing/page-name "页面名"
           :publishing/current-project "当前项目"
           :publishing/delete-from-logseq "从Logseq服务器删除"
           :publishing/edit "修改"
           :publishing/save "保存"
           :publishing/cancel "取消"
           :publishing/delete "删除"
           :journal/multiple-files-with-different-formats "你似乎在同一个月有多个日记文件(格式不同)，请每个月只保留一个日记文件。"
           :journal/go-to "前往所有文件"
           :file/name "文件名"
           :file/file "文件："
           :file/last-modified-at "最后更改于"
           :file/no-data "没有数据"
           :file/format-not-supported "格式 .{1} 目前不支持."
           :editor/block-search "搜索块"
           :editor/image-uploading "上传中"
           :draw/invalid-file "无法加载此无效的 excalidraw 文件"
           :draw/specify-title "请先指定标题!"
           :draw/rename-success "文件重命名成功!"
           :draw/rename-failure "文件重命名失败，原因是："
           :draw/title-placeholder "未命名"
           :draw/save "保存"
           :draw/save-changes "保存更改"
           :draw/new-file "新文件"
           :draw/list-files "所有文件"
           :draw/delete "删除"
           :draw/more-options "更多选项"
           :draw/back-to-logseq "返回 logseq"
           :content/copy "复制"
           :content/cut "剪切"
           :content/make-todos "格式化为 {1}"
           :content/copy-block-ref "复制块引用"
           :content/focus-on-block "聚焦在此块"
           :content/open-in-sidebar "在侧边栏打开"
           :content/copy-as-json "复制为 JSON"
           :content/click-to-edit "点击以编辑"
           :settings-page/edit-config-edn "编辑 config.edn (当前库)"
           :settings-page/show-brackets "显示括号 [[]]"
           :settings-page/preferred-file-format "首选文件格式"
           :settings-page/preferred-workflow "首选工作流"
           :settings-page/enable-timetracking "开启 timetracking"
           :settings-page/enable-journals "开启日记"
           :settings-page/home-default-page "设置首页默认页面"
           :settings-page/enable-block-time "记录 block 创建/修改时间"
           :settings-page/dont-use-other-peoples-proxy-servers "不要使用其他人的代理服务器。这非常危险，可能会使您的令牌和笔记被盗。 如果您使用其他人的代理服务器，Logseq 将不会对此损失负责。您可以自己部署它，请查阅 "
           :settings-page/custom-cors-proxy-server "自定义 CORS 代理服务器"
           :settings-page/developer-mode "开发者模式"
           :settings-page/enable-developer-mode "启用开发者模式"
           :settings-page/disable-developer-mode "禁用开发者模式"
           :settings-page/developer-mode-desc "开发者模式帮助贡献者和扩展开发者更有效地测试他们与 Logseq 的集成。"
           :settings-page/current-version "当前版本"
           :logseq "Logseq"
           :dot-mode "点模式"
           :on "已打开"
           :more-options "更多选项"
           :to "至"
           :yes "是"
           :submit "提交"
           :cancel "取消"
           :re-index "重新建立索引"
           :export-json "以 JSON 格式导出"
           :unlink "解除绑定"
           :search (if config/publishing?
                     "搜索"
                     "搜索或者创建新页面")
           :new-page "新页面"
           :new-file "新文件"
           :graph "图谱"
           :publishing "发布"
           :export "导出公开页面"
           :all-graphs "所有库"
           :all-pages "所有页面"
           :all-files "所有文件"
           :my-publishing "我的发布"
           :settings "设置"
           :import "导入"
           :join-community "加入社区"
           :sponsor-us "赞助我们!"
           :discord-title "我们的 Discord 社群!"
           :sign-out "登出"
           :help-shortcut-title "点此查看快捷方式和更多有用帮助"
           :loading "加载中"
           :cloning "Clone 中"
           :parsing-files "正在解析文件"
           :loading-files "正在加载文件"
           :login-github "用 Github 登录"
           :login-google "用 Google 登录"
           :login "登录"
           :go-to "转到"
           :or "或"
           :download "下载"
           :repo/download-zip "下载所有文件"
           :language "语言"
           :white "亮色"
           :dark "暗黑"
           :remove-background "去除背景"
           :open "打开"
           :open-a-directory "打开本地文件夹"}

   :zh-Hant {:on-boarding/title "你好，歡迎使用 Logseq！"
             :on-boarding/sharing "分享"
             :on-boarding/is-a " 是一個 "
             :on-boarding/local-first "本地優先"
             :on-boarding/non-linear "非線性"
             :on-boarding/outliner "大綱"
             :on-boarding/notebook-for-organizing-and " 筆記本， 用來整理和"
             :on-boarding/your-personal-knowledge-base "你的個人知識庫。"
             :on-boarding/notice "請注意， 本項目正在快速開發中， 存在文件損壞的風險。"
             :on-boarding/features-desc "使用它來組織您的待辦事項列表、 寫日志或記錄您的獨特生活。"
             :on-boarding/privacy "服務器將永遠不會存儲或分析您的私人筆記。 您的數據是純文本文件，我們暫時支持 Markdown 和 Emacs Org 模式。 即使網站已經關閉或無法維護，您的數據也永遠屬於您。"
             :on-boarding/inspired-by " 受到這些產品啟發："
             :on-boarding/where-are-my-notes-saved "我的筆記存儲在哪裡？"
             :on-boarding/storage "你的筆記會被存儲在本地瀏覽器中，使用 "
             :on-boarding/how-do-i-use-it "我該如何使用它？"
             :on-boarding/use-1 "1. 在多設備間同步"
             :on-boarding/use-1-desc "目前，我們只支持通過 Github 進行同步，將很快添加更多選項 (Self-host git、WebDAV、Google Drive等)。"
             :on-boarding/use-1-video "看看這個很棒的視頻，創作者 "
             :on-boarding/use-2 "2. 在本地使用 (無需登錄)"
             :on-boarding/features "功能"
             :on-boarding/features-backlinks "[[頁面]] 之間的雙向鏈接"
             :on-boarding/features-block-embed "塊嵌入"
             :on-boarding/features-page-embed "頁面嵌入"
             :on-boarding/features-graph-vis "圖表可視化"
             :on-boarding/features-heading-properties "塊屬性"
             :on-boarding/features-datalog "Datalog 自定義查詢——筆記數據庫使用 "
             :on-boarding/features-custom-view-component "自定義視圖組件"
             :on-boarding/integration " 集成"
             :on-boarding/slide-support " 幻燈片支持"
             :on-boarding/built-in-supports "文檔內置支持："
             :on-boarding/supports-code-highlights "代碼高亮顯示"
             :on-boarding/supports-katex-latex "Katex latex"
             :on-boarding/raw "原始 "
             :on-boarding/raw-html "原始 html"
             :on-boarding/learn-more "了解更多"
             :on-boarding/discord-desc " 社區在此處提問和分享提示"
             :on-boarding/github-desc " 歡迎所有人報告問題！"
             :on-boarding/our-blog "我們的博客："
             :on-boarding/credits-to "鳴謝"
             :on-boarding/clojure-desc " - 一種動態的、函數式、通用的編程語言"
             :on-boarding/datascript-desc " - Clojure, ClojureScript 和 JS 的不可變數據庫和 Datalog 查詢引擎"
             :on-boarding/angstrom-desc-1 ", 文檔"
             :on-boarding/angstrom-desc-2 "解析器"
             :on-boarding/angstrom-desc-3 "建立在 Angstrom 之上。"
             :on-boarding/cuekeeper-desc " - 基於瀏覽器的 GTD (待辦清單) 系統。"
             :on-boarding/sci-desc " - 小型 Clojure 解析器"
             :on-boarding/isomorphic-git-desc " - 用於 Node 和瀏覽器的純 JavaScript Git 實現！"
             :help/about "關於 Logseq"
             :help/bug "Bug 反饋"
             :help/feature "功能建議"
             :help/changelog "更新日志"
             :help/blog "Logseq 博客"
             :help/privacy "隱私聲明"
             :help/terms "服務條款"
             :help/community "Discord 社區"
             :help/shortcuts "快捷鍵"
             :help/shortcuts-triggers "觸發"
             :help/shortcut "快捷鍵"
             :help/slash-autocomplete "Slash 自動提示"
             :help/block-content-autocomplete "塊內容 (Src, Quote, Query 等) 自動完成"
             :help/reference-autocomplete "頁面引用自動補全"
             :help/block-reference "塊引用"
             :help/key-commands "關鍵命令"
             :help/working-with-lists " (與列表相關)"
             :help/indent-block-tab "縮進塊標簽"
             :help/unindent-block "取消縮進塊"
             :help/move-block-up "向上移動塊"
             :help/move-block-down "向下移動塊"
             :help/create-new-block "創建塊"
             :help/new-line-in-block "塊中新建行"
             :help/select-nfs-browser "Please use another browser (like latest chrome) which support NFS features to open local directory."
             :undo "撤銷"
             :redo "重做"
             :help/zoom-in "聚焦"
             :help/zoom-out "推出聚焦"
             :help/follow-link-under-cursor "跟隨光標下的鏈接"
             :help/open-link-in-sidebar "在側邊欄打開"
             :expand "展開"
             :collapse "折疊"
             :select-block-above "選擇上方的塊"
             :select-block-below "選擇下方的塊"
             :select-all-blocks "選擇所有塊"
             :general "常規​​​​​"
             :help/toggle "顯示/關閉幫助"
             :help/git-commit-message "提交消息"
             :help/full-text-search "全文搜索"
             :help/context-menu "右鍵菜單"
             :help/fold-unfold "折疊/展開方塊(不在編輯模式中)"
             :help/toggle-doc-mode "切換文檔模式"
             :help/toggle-theme "“在暗色/亮色主題之間切換”"
             :help/toggle-right-sidebar "啟用/關閉右側欄"
             :help/toggle-insert-new-block "切換 Enter/Alt+Enter 以插入新塊"
             :help/jump-to-journals "跳轉到日記"
             :formatting "格式化"
             :help/markdown-syntax "Markdown 語法"
             :help/org-mode-syntax "Org Mode 語法"
             :bold "粗體"
             :italics "斜體"
             :html-link "Html 鏈接"
             :highlight "高亮"
             :strikethrough "刪除線"
             :code "代碼"
             :right-side-bar/help "幫助"
             :right-side-bar/switch-theme "切換到 {1} 主題"
             :right-side-bar/theme "{1}主題"
             :right-side-bar/page "頁面圖譜"
             :right-side-bar/recent "最近"
             :right-side-bar/contents "目錄"
             :right-side-bar/graph-ref "圖譜："
             :right-side-bar/block-ref "塊引用"
             :git/set-access-token "設定 Github 個人訪問令牌"
             :git/token-is-encrypted "令牌將被加密並存儲在瀏覽器本地存儲"
             :git/token-server "服務器將永遠不會存儲它"
             :git/create-personal-access-token "如何創建 Github 個人訪問令牌？"
             :git/push "現在 push"
             :git/local-changes-synced "所有本地更改已同步！"
             :git/pull "現在 pull"
             :git/last-pull "最後 pull 時間 "
             :git/version "版本"
             :git/import-notes "導入筆記"
             :git/import-notes-helper "你可以從 Github 的庫中導入筆記"
             :git/add-another-repo "添加一個庫"
             :git/re-index "重新 clone 然後重新建立索引"
             :git/message "你的 commit 信息"
             :git/commit-and-push "commit 並 push"
             :git/use-remote "使用雲端版本"
             :git/keep-local "使用本地版本"
             :git/edit "編輯"
             :git/title "文件衝突"
             :git/no-diffs "沒有文件衝突"
             :git/commit-message "commit 消息（可選）"
             :git/pushing "Pushing"
             :git/force-push "Commit 並強制 push"
             :git/a-force-push "強制 push"
             :git/add-repo-prompt "在你的庫上安裝 Logseq"
             :git/add-repo-prompt-confirm "添加並安裝"
             :format/preferred-mode "請選擇偏好格式"
             :format/markdown "Markdown"
             :format/org-mode "Org Mode"
             :reference/linked "已鏈接的引用"
             :reference/unlinked-ref "未鏈接的引用"
             :project/setup "在 Logseq 上發布新的項目"
             :project/location "一切發布的頁面將會被放到 "
             :project/sync-settings "同步項目設置"
             :page/presentation-mode "演講模式 (由 Reveal.js 驅動)"
             :page/delete-success "頁面 {1} 刪除成功！"
             :page/delete-confirmation "您確定要刪除此頁面嗎？"
             :page/rename-to "重命名 \"{1}\" 至："
             :page/priority "優先級 \"{1}\""
             :page/re-index "對此頁面重新建立索引"
             :page/copy-to-json "將整頁以 JSON 格式復制"
             :page/rename "重命名本頁"
             :page/make-public "導出 HTML 時發布本頁面"
             :page/make-private "導出 HTML 時取消發布本頁面"
             :page/delete "刪除本頁（並刪除文件）"
             :page/publish "將本頁發布至 Logseq"
             :page/cancel-publishing "Cancel publishing on Logseq"
             :page/publish-as-slide "將本頁作為幻燈片發布至 Logseq"
             :page/unpublish "取消將本頁發布至 Logseq"
             :page/add-to-contents "將本頁添加到目錄"
             :page/show-journals "顯示日志"
             :page/show-name "顯示頁面名"
             :page/hide-name "隱藏頁面名"
             :page/name "頁面名稱："
             :page/last-modified "最後更改於"
             :page/new-title "請輸入新頁面的名字:"
             :publishing/pages "頁面"
             :publishing/page-name "頁面名稱"
             :publishing/current-project "當前項目"
             :publishing/delete-from-logseq "從Logseq服務器刪除"
             :publishing/edit "修改"
             :publishing/save "保存"
             :publishing/cancel "取消"
             :publishing/delete "删除"
             :journal/multiple-files-with-different-formats "你似乎在同一個月有多個日記文件(格式不同)，請每個月只保留一個日記文件。"
             :journal/go-to "前往所有文件"
             :file/name "文件名"
             :file/file "文件："
             :file/last-modified-at "最後更改於"
             :file/no-data "沒有數據"
             :file/format-not-supported "格式 .{1} 目前不支持."
             :editor/block-search "搜索塊"
             :editor/image-uploading "上傳中"
             :draw/invalid-file "無法加載此無效的 excalidraw 文件"
             :draw/specify-title "請先指定標題!"
             :draw/rename-success "文件重命名成功!"
             :draw/rename-failure "文件重命名失敗，原因是："
             :draw/title-placeholder "未命名"
             :draw/save "保存"
             :draw/save-changes "保存更改"
             :draw/new-file "新文件"
             :draw/list-files "所有文件"
             :draw/delete "刪除"
             :draw/more-options "更多選項"
             :draw/back-to-logseq "返回 logseq"
             :content/copy "復制"
             :content/cut "剪切"
             :content/make-todos "格式化為 {1}"
             :content/copy-block-ref "復制塊引用"
             :content/focus-on-block "聚焦在此塊"
             :content/open-in-sidebar "在側邊欄打開"
             :content/copy-as-json "復制為 JSON"
             :content/click-to-edit "點擊以編輯"
             :settings-page/edit-config-edn "編輯 config.edn (當前庫)"
             :settings-page/preferred-file-format "首選文件格式"
             :settings-page/preferred-workflow "首選工作流"
             :settings-page/dont-use-other-peoples-proxy-servers "不要使用其他人的代理服務器。這非常危險，可能會使您的令牌和筆記被盜。 如果您使用其他人的代理服務器，Logseq 將不會對此損失負責。您可以自己部署它，請查閱 "
             :settings-page/custom-cors-proxy-server "自定義 CORS 代理服務器"
             :settings-page/developer-mode "開發者模式"
             :settings-page/enable-developer-mode "啟用開發者模式"
             :settings-page/disable-developer-mode "禁用開發者模式"
             :settings-page/developer-mode-desc "開發者模式幫助貢獻者和擴展開發者更有效地測試他們與 Logseq 的集成。"
             :logseq "Logseq"
             :dot-mode "點模式"
             :on "已打開"
             :more-options "更多選項"
             :to "至"
             :yes "是"
             :submit "提交"
             :cancel "取消"
             :re-index "重新建立索引"
             :export-json "以 JSON 格式導出"
             :unlink "解除綁定"
             :search (if config/publishing?
                       "搜索"
                       "搜索或者創建新頁面")
             :new-page "新頁面"
             :graph "圖譜"
             :publishing "發布/下載 HTML 文件"
             :all-pages "所有頁面"
             :all-files "所有文件"
             :my-publishing "My publishing"
             :settings "設置"
             :import "導入"
             :join-community "加入社區"
             :discord-title "我們的 Discord 社群!"
             :sign-out "登出"
             :help-shortcut-title "點此查看快捷方式和更多有用幫助"
             :loading "加載中"
             :cloning "Clone 中"
             :parsing-files "正在解析文件"
             :loading-files "正在加載文件"
             :login-github "用 Github 登錄"
             :login-google "用 Google 登錄"
             :go-to "轉到"
             :or "或"
             :download "下載"
             :language "語言"
             :white "亮色"
             :dark "暗黑"
             :remove-background "去除背景"}

   :af {:on-boarding/title "Hi, welcome to Logseq!"
        :on-boarding/sharing "meedeling"
        :on-boarding/is-a " is 'n "
        :on-boarding/local-first "plaaslike-eerste"
        :on-boarding/non-linear "nie-lineêre"
        :on-boarding/outliner "buitelyn"
        :on-boarding/notebook-for-organizing-and " notaboek vir organisasie en "
        :on-boarding/your-personal-knowledge-base "  jou persoonlike kennis basis."
        :on-boarding/notice "Wees asseblief bewus daarvan dat die projek nog in die begin fase is, en jou leers kan korrupteer word."
        :on-boarding/features-desc "Gebruik dit om jou lyste vir aksie te organiseer, joernale te skryf, en jou unieke lewe op te neem."
        :on-boarding/privacy "The server will never store or analyze your private notes. Your data are plain text files, we support both Markdown and Emacs Org mode for the time being. Even if the website is down or can't be maintained, your data is always yours."
        :on-boarding/inspired-by " is geweldig geïnspireer deur "
        :on-boarding/where-are-my-notes-saved "Waar word my notas gestoor?"
        :on-boarding/storage "Jou notas word in the plaaslike webblaaier stoorkamer gestoor deur "
        :on-boarding/how-do-i-use-it "Hoe gebruik ek dit?"
        :on-boarding/use-1 "1. Sinkroniseer tussen onderskeie toestelle"
        :on-boarding/use-1-desc "Tans, ondersteun ons sinkronisering met Github, meer opsies (eie bediener git, WebDAV, Google Drive ensovoorts) sal binnekort bygevoeg word. "
        :on-boarding/use-1-video "Gaan loer gerus na hierdie lekker video by "
        :on-boarding/use-2 "2. Gebruik dit plaaslik (geen aantekening benodig)"
        :on-boarding/features "Kenmerke"
        :on-boarding/features-backlinks "Terugskakels tussen [[Blaaie]]"
        :on-boarding/features-block-embed "Blok insluiting"
        :on-boarding/features-page-embed "Blad insluiting"
        :on-boarding/features-graph-vis "Grafiese visualisering"
        :on-boarding/features-heading-properties "Opskrif eienskappe"
        :on-boarding/features-datalog "Datalog navrae, die notas db word aangedryf deur "
        :on-boarding/features-custom-view-component "Persoonlike aansig komponent"
        :on-boarding/integration " integrasie"
        :on-boarding/slide-support " skyfie ondersteuning"
        :on-boarding/built-in-supports "Ingeboude dokument ondersteuning:"
        :on-boarding/supports-code-highlights "Kode hoogtepunte"
        :on-boarding/supports-katex-latex "Katex latex"
        :on-boarding/raw "Rou "
        :on-boarding/raw-html "Rou html"
        :on-boarding/learn-more "Kom meer te wete"
        :on-boarding/discord-desc " waar die gemeenskap vrae vra en wenke deel"
        :on-boarding/github-desc " almal word angemoedig om kwessies aan te meld!"
        :on-boarding/our-blog "Ons blog: "
        :on-boarding/credits-to "Erkennings"
        :on-boarding/clojure-desc " - 'n Dinamiese, funksionele, algemene alle gebruiks programmertaal"
        :on-boarding/datascript-desc "Onveranderlike databasis en Datalog-navraag enjin vir Clojure, ClojureScript en JS"
        :on-boarding/angstrom-desc-1 ", die dokument "
        :on-boarding/angstrom-desc-2 "ontleder"
        :on-boarding/angstrom-desc-3 " is gebou op Angstrom."
        :on-boarding/cuekeeper-desc " - Webblaaier gebaseerde GTD (TODO lys) stelsel."
        :on-boarding/sci-desc " - 'n Klein Clojure interpreteerder"
        :on-boarding/isomorphic-git-desc "- 'n Suiwer JavaScript implementasie van git vir node en webblaaiers!"
        :help/about "Oor Logseq"
        :help/bug "Fout verslag"
        :help/feature "Funksie versoek"
        :help/changelog "Verandering-dagboek"
        :help/blog "Logseq blog"
        :help/privacy "Privaatheidsbeleid"
        :help/terms "Terme"
        :help/community "Discord gemeenskap"
        :help/shortcuts "Sleutelbord kortpaaie"
        :help/shortcuts-triggers "Snellers"
        :help/shortcut "Kortpad"
        :help/slash-autocomplete "Slash outovoltooi"
        :help/block-content-autocomplete "Blokkeer inhoud (Oorsprong, kwotasie, navrae ens.) Voltooi outomaties"
        :help/reference-autocomplete "Blad verwysing Outovoltooi"
        :help/block-reference "Blok verwysing"
        :help/key-commands "Sleutel instruksies"
        :help/working-with-lists " (werk met lyste)"
        :help/indent-block-tab "Ingekeepte blok oortjie"
        :help/unindent-block "Oningekeepte blok"
        :help/move-block-up "Skuif Blok Boontoe"
        :help/move-block-down "Skuif Blok Ondertoe"
        :help/create-new-block "Skep 'n nuwe blok"
        :help/new-line-in-block "Nuwe lyn in blok"
        :help/select-nfs-browser "Please use another browser (like latest chrome) which support NFS features to open local directory."
        :undo "Ontdoen"
        :redo "Herdoen"
        :help/zoom-in "Zoem in"
        :help/zoom-out "Zoem uit"
        :help/follow-link-under-cursor "Volg die skakel onder die wyser"
        :help/open-link-in-sidebar "Maak skakel in kantlys oop"
        :expand "Brei uit"
        :collapse "Vou in"
        :select-block-above "Kies blok bo"
        :select-block-below "Kies blok onder"
        :select-all-blocks "Kies alle blokke"
        :general "Algemeen"
        :help/toggle "Wissel help"
        :help/git-commit-message "Jou git stoor boodskap"
        :help/full-text-search "Volteks soek"
        :help/context-menu "Konteks kaart"
        :help/fold-unfold "Vou/ontvou blokke (wanneer nie in wysigings modus)"
        :help/toggle-doc-mode "Wissel dokument modus"
        :help/toggle-theme "Wissel tussen donker/lig temas"
        :help/toggle-right-sidebar "Wissel regter sybalk"
        :help/toggle-insert-new-block "Wissel Enter/Alt+enter vir die byvoeging van nuwe blokke"
        :help/jump-to-journals "Spring na joernale"
        :formatting "Formatering"
        :help/markdown-syntax "Markdown sintaksis"
        :help/org-mode-syntax "Org mode sintaksis"
        :bold "Vetdruk"
        :italics "Skuinsdruk"
        :html-link "Html Skakel"
        :highlight "Beklemtoon"
        :strikethrough "Deurstreep"
        :code "Kode"
        :right-side-bar/help "Hulp"
        :right-side-bar/switch-theme "Skakel oor na die {1} tema"
        :right-side-bar/theme "{1} tema"
        :right-side-bar/page "Grafiek bladsy"
        :right-side-bar/recent "Onlangs"
        :right-side-bar/contents "Inhoud"
        :right-side-bar/graph-ref "Grafiek van "
        :right-side-bar/block-ref "Blok verwysing"
        :git/set-access-token "Set Github personal access token"
        :git/token-is-encrypted "The token will be encrypted and stored in the browser local storage"
        :git/token-server "The server will never store it"
        :git/create-personal-access-token "How to create a Github personal access token?"
        :git/push "Stoor nou"
        :git/local-changes-synced "Alle veranderinge is gesinkroniseer!"
        :git/pull "Laai af"
        :git/last-pull "Laas afgelaai op"
        :git/version "Weergawe"
        :git/import-notes "Voer jou notas in"
        :git/import-notes-helper "Jy kan jou notas van 'n Github stoorplek laai."
        :git/add-another-repo "Voeg nog 'n stoorplek by"
        :git/re-index "Clone again and re-index the db"
        :git/message "Jou stoor boodskap"
        :git/commit-and-push "Stoor en sinkroniseer!"
        :git/use-remote "Gebruik afgeleë stoor"
        :git/keep-local "Hou plaaslik"
        :git/edit "Wysig"
        :git/title "Vergelyk"
        :git/no-diffs "Geen verskille"
        :git/commit-message "Veranderings nota (opsioneel)"
        :git/pushing "Stoor"
        :git/force-push "Stoor en laai op"
        :git/a-force-push "'n Gevorseerde stoor"
        :git/add-repo-prompt "Installeer Logseq op jou stoorplek"
        :git/add-repo-prompt-confirm "Voeg by en installeer"
        :format/preferred-mode "Wat is jou voorkeur model?"
        :format/markdown "Markdown"
        :format/org-mode "Org Mode"
        :reference/linked "Gekoppelde Verwysing"
        :reference/unlinked-ref "Ongekoppelde Verwysing"
        :project/setup "Stel 'n publieke projek op by Logseq"
        :project/location "Alle gepubliseerde blaai sal voorkom onder"
        :project/sync-settings "Sinkroniseer projek instellings"
        :page/presentation-mode "Aanbiedings modus (gedryf deur Reveal.js)"
        :page/delete-success "Bladsy {1} is suksesvol uitgevee!"
        :page/delete-confirmation "Is jy seker jy wil die bladsy uitvee?"
        :page/rename-to "Hernoem \"{1}\" na:"
        :page/priority "Prioriteit \"{1}\""
        :page/re-index "Re-index this page"
        :page/copy-to-json "Kopieer die hele bladsy as JSON"
        :page/rename "Hernoem die bladsy"
        :page/delete "Delete page (will delete the file too)"
        :page/publish "Publiseer hierdie blad op Logseq"
        :page/cancel-publishing "Cancel publishing on Logseq"
        :page/publish-as-slide "Publiseer hierdie blad as 'n skyfie op Logseq"
        :page/unpublish "Verwyder blad publikasie op Logseq"
        :page/add-to-contents "Voeg by inhoud"
        :page/show-journals "Wys joernale"
        :page/show-name "Wys blad naam"
        :page/hide-name "Steek bladnaam weg"
        :page/name "Page name"
        :page/last-modified "Laaste verander op"
        :page/new-title "Wat is die nuwe blad se titel?"
        :publishing/pages "Pages"
        :publishing/page-name "Page name"
        :publishing/current-project "Current Project"
        :publishing/delete-from-logseq "Delete From Logseq Server"
        :publishing/edit "Edit"
        :publishing/save "Save"
        :publishing/cancel "Cancel"
        :publishing/delete "Delete"
        :journal/multiple-files-with-different-formats "Dit wil voorkom asof jy verskeie journaal (met verskeie formate) vir dieselfde maand het, onderhou asb need een journaal lêer vir elke maand."
        :journal/go-to "Go to files"
        :file/name "Lêer naam"
        :file/file "Lêer: "
        :file/last-modified-at "Laas verander op"
        :file/no-data "Geen data"
        :file/format-not-supported "Formaat .{1} word nie ondersteun nie."
        :editor/block-search "Soek vir 'n blok"
        :editor/image-uploading "Laai tans op"
        :draw/invalid-file "Kon nie die ongeldige excalidraw lêer laai nie"
        :draw/specify-title "Spesifiseer asseblief eers a titel!"
        :draw/rename-success "Lêer is suksesvol verwyder!"
        :draw/rename-failure "Die lêer kon nie hernoem word nie, rede: "
        :draw/title-placeholder "Naamloos"
        :draw/save "Stoor"
        :draw/save-changes "Bewaar veranderinge"
        :draw/new-file "Nuwe lêer"
        :draw/list-files "Lys lêers"
        :draw/delete "Vee uit"
        :draw/more-options "Meer opsies"
        :draw/back-to-logseq "Terug na logseq"
        :content/copy "Kopieer"
        :content/cut "Sny"
        :content/make-todos "Maak {1}"
        :content/copy-block-ref "Kopieer blok verwysing"
        :content/focus-on-block "Fokus op blok"
        :content/open-in-sidebar "Maak in kantlys oop"
        :content/copy-as-json "Kopieer na JSON"
        :content/click-to-edit "Kliek om te wysig"
        :settings-page/edit-config-edn "Wysig config.edn (vir huidige stoor)"
        :settings-page/preferred-file-format "Voorkeur lêer formaat"
        :settings-page/preferred-workflow "Voorkeur werkstroom"
        :settings-page/dont-use-other-peoples-proxy-servers "Moenie ander mense se instaanbedieners gebruik nie. Dis gevaarlik, en kan veroorsaak dat jou toegang teken en notas gesteel word. Logseq sal nie verantwoording neem vir verlies indien jy ander se instaanbedieners gebruik nie. Jy kan self self een ontplooi "
        :settings-page/custom-cors-proxy-server "Persoonlike CORS instaanbediener"
        :settings-page/developer-mode "Ontwikkelaar modus"
        :settings-page/enable-developer-mode "Skakel ontwikkelaar modus aan"
        :settings-page/disable-developer-mode "Skakel ontwikkelaars modus af"
        :settings-page/developer-mode-desc "Ontwikkelaarmodus help bydraers en ontwikkelaars van uitbreidings om hul integrasie met Logseq doeltreffender te toets."
        :logseq "Logseq"
        :dot-mode "Punt modus"
        :on "AAN"
        :more-options "More options"
        :to "na"
        :yes "Ja"
        :submit "Stuur"
        :cancel "Kanselleer"
        :re-index "Herindekseer"
        :export-json "Uitvoer as JSON"
        :unlink "ontkoppel"
        :search "Soek"
        :new-page "Nuwe bladsy"
        :graph "Grafiek"
        :all-pages "Alle blaaie"
        :all-files "Alle lêers"
        :settings "Verstellings"
        :import "Invoer"
        :join-community "Sluit by die gemeenskap aan"
        :discord-title "Ons discord groep!"
        :sign-out "Teken af"
        :help-shortcut-title "Kliek op die kortpad en ander wenke"
        :loading "Laai tans"
        :cloning "Kloning"
        :parsing-files "Lêer ontleding"
        :loading-files "Laai lêers"
        :login-github "Aantekening deur Github"
        :login-google "Aantekening deur Google"
        :go-to "Gaan na "
        :or "of"
        :download "Laai af"
        :language "Taal"
        :white "Wit"
        :dark "Swart"}

   :tongue/fallback :en})

(def languages [{:label "English" :value :en}
                {:label "Français" :value :fr}
                {:label "简体中文" :value :zh-CN}
                {:label "繁體中文" :value :zh-Hant}
                {:label "Afrikaans" :value :af}])

(def translate
  (tongue/build-translate dicts))
