let strip_ansi s = s
let bold s = s
let dim s = s
let red s = s
let green s = s
let yellow s = s
let blue s = s
let magenta s = s
let cyan s = s
let bold_keywords s _ = s
let bold_options s = s
let with_color_enabled _ f = f ()
