#compdef logseq
# Auto-generated by `logseq completions zsh` — do not edit manually.

# --- dynamic helpers ---

_logseq_json_names() {
  python3 -c "
import sys, json
field = sys.argv[1]
try:
    data = json.load(sys.stdin)
    if isinstance(data, list):
        for item in data:
            v = item.get(field)
            if isinstance(v, str) and v:
                print(v)
except Exception:
    pass
" "$1" 2>/dev/null
}

_logseq_current_graph() {
  local i
  for (( i = 1; i < ${#words[@]}; i++ )); do
    if [[ "${words[i]}" == '--graph' && -n "${words[i+1]}" ]]; then
      print -r -- "${words[i+1]}"
      return
    fi
  done
}

_logseq_graphs() {
  local cache_id='logseq_graphs'
  local -a graphs
  if _cache_invalid "$cache_id" || ! _retrieve_cache "$cache_id"; then
    graphs=( ${(f)"$(logseq graph list --output json 2>/dev/null | _logseq_json_names name)"} )
    _store_cache "$cache_id" graphs
  fi
  compadd -a graphs
}

_logseq_pages() {
  local graph
  graph=$(_logseq_current_graph)
  local cache_id="logseq_pages_${graph:-__default__}"
  local -a pages
  if _cache_invalid "$cache_id" || ! _retrieve_cache "$cache_id"; then
    if [[ -n "$graph" ]]; then
      pages=( ${(f)"$(logseq list page --graph "$graph" --output json 2>/dev/null | _logseq_json_names title)"} )
    fi
    _store_cache "$cache_id" pages
  fi
  compadd -a pages
}

_logseq_queries() {
  local graph
  graph=$(_logseq_current_graph)
  local cache_id="logseq_queries_${graph:-__default__}"
  local -a queries
  if _cache_invalid "$cache_id" || ! _retrieve_cache "$cache_id"; then
    if [[ -n "$graph" ]]; then
      queries=( ${(f)"$(logseq query list --graph "$graph" --output json 2>/dev/null | _logseq_json_names name)"} )
    fi
    _store_cache "$cache_id" queries
  fi
  compadd -a queries
}

# --- per-command functions ---

_logseq_list_page() {
  _arguments -s \
    '--created-after=[Filter by created-at (ISO8601)]:value:' \
    '--updated-after=[Filter by updated-at (ISO8601)]:value:' \
    '--limit=[Limit results]:value:' \
    '--offset=[Offset results]:value:' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--fields=[Select output fields (comma separated)]:value:' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--journal-only[Only journal pages]' \
    '--order=[Sort order. Default: asc]:value:(asc desc)' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--include-hidden[Include hidden pages]' \
    '--expand[Include expanded metadata]' \
    '--sort=[Sort field]:value:(title created-at updated-at)' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--include-journal[Include journal pages]'
}

_logseq_list_tag() {
  _arguments -s \
    '--limit=[Limit results]:value:' \
    '--offset=[Offset results]:value:' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--include-built-in[Include built-in tags]' \
    '--fields=[Select output fields (comma separated)]:value:' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--order=[Sort order. Default: asc]:value:(asc desc)' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--with-extends[Include tag extends]' \
    '--expand[Include expanded metadata]' \
    '--with-properties[Include tag properties]' \
    '--sort=[Sort field]:value:(name title)' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_list_property() {
  _arguments -s \
    '--limit=[Limit results]:value:' \
    '--offset=[Offset results]:value:' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--include-built-in[Include built-in properties]' \
    '--fields=[Select output fields (comma separated)]:value:' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--order=[Sort order. Default: asc]:value:(asc desc)' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--with-type[Include property type]' \
    '--version[Show version]' \
    '--expand[Include expanded metadata]' \
    '--sort=[Sort field]:value:(name title)' \
    '--with-classes[Include property classes]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_server_list() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_server_status() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_server_start() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_server_stop() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_server_restart() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_graph_list() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_graph_create() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_graph_switch() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_graph_remove() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_graph_validate() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_graph_info() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_graph_export() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--file=[Export file path]:file:_files' \
    '--type=[Export type]:value:(edn sqlite)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_graph_import() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--type=[Import type]:value:(edn sqlite)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--input=[Input path]:file:_files' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_query() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--name=[Query name from cli.edn custom-queries or built-ins]:value:_logseq_queries' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--inputs=[EDN vector of query inputs]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--query=[Datascript query EDN]:value:' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_query_list() {
  _arguments -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]'
}

_logseq_upsert_block() {
  _arguments -s \
    '--blocks-file=[EDN file of blocks for create mode]:file:_files' \
    '--target-page=[Target page name]:value:_logseq_pages' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--content=[Block content for create mode]:value:' \
    '--remove-tags=[Tags to remove (EDN vector)]:value:' \
    '--target-uuid=[Target block UUID]:value:' \
    '--pos=[Position. Default: create=last-child, update=first-child]:value:(first-child last-child sibling)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--target-id=[Target block db/id]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--update-tags=[Tags to add/update (EDN vector)]:value:' \
    '--status=[Task status]:value:(todo doing done now later wait waiting backlog canceled cancelled in-review in-progress)' \
    '--update-properties=[Properties to add/update (EDN map)]:value:' \
    '--id=[Source block db/id (forces update mode)]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--blocks=[EDN vector of blocks for create mode]:value:' \
    '--uuid=[Source block UUID (forces update mode)]:value:' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--remove-properties=[Properties to remove (EDN vector)]:value:' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_upsert_page() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--remove-tags=[Tags to remove (EDN vector)]:value:' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--page=[Page name]:value:_logseq_pages' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--update-tags=[Tags to add/update (EDN vector)]:value:' \
    '--update-properties=[Properties to add/update (EDN map)]:value:' \
    '--id=[Target page db/id (forces update mode)]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--remove-properties=[Properties to remove (EDN vector)]:value:' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_upsert_tag() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--name=[Tag name]:value:' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--id=[Target tag db/id (forces update mode)]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_upsert_property() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--name=[Property name]:value:' \
    '--public[Set property public visibility]' \
    '--type=[Property type]:value:(default number date datetime checkbox url node json string)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--hide[Hide property]' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--id=[Target property db/id (forces update mode)]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--cardinality=[Property cardinality]:value:(one many)' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_completions() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--shell=[Shell (zsh, bash)]:value:(zsh bash)' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_show() {
  _arguments -s \
    '--linked-references[Include linked references (default true)]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--page=[Page name]:value:_logseq_pages' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--level=[Limit tree depth (default 10)]:value:' \
    '--id=[Block db/id or EDN vector of ids]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--uuid=[Block UUID]:value:' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_doctor() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--dev-script[Check static/db-worker-node.js instead of bundled dist runtime]' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_remove_block() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--id=[Block db/id or EDN vector of ids]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--uuid=[Block UUID]:value:' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_remove_page() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--name=[Page name]:value:_logseq_pages' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_remove_tag() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--name=[Entity name]:value:' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--id=[Entity db/id]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

_logseq_remove_property() {
  _arguments -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--name=[Entity name]:value:' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--id=[Entity db/id]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:'
}

# --- group dispatchers ---

_logseq_list() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments -C -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '1:subcommand:->subcmd' \
    '*::args:->args'

  case $state in
    subcmd)
      local -a subcmds
      subcmds=(
        'page:List pages'
        'tag:List tags'
        'property:List properties'
      )
      _describe 'subcommand' subcmds
      ;;
    args)
      case $line[1] in
        page) _logseq_list_page ;;
        tag) _logseq_list_tag ;;
        property) _logseq_list_property ;;
      esac
      ;;
  esac
}

_logseq_server() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments -C -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '1:subcommand:->subcmd' \
    '*::args:->args'

  case $state in
    subcmd)
      local -a subcmds
      subcmds=(
        'list:List db-worker-node servers'
        'status:Show server status for a graph'
        'start:Start db-worker-node for a graph'
        'stop:Stop db-worker-node for a graph'
        'restart:Restart db-worker-node for a graph'
      )
      _describe 'subcommand' subcmds
      ;;
    args)
      case $line[1] in
        list) _logseq_server_list ;;
        status) _logseq_server_status ;;
        start) _logseq_server_start ;;
        stop) _logseq_server_stop ;;
        restart) _logseq_server_restart ;;
      esac
      ;;
  esac
}

_logseq_graph() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments -C -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '1:subcommand:->subcmd' \
    '*::args:->args'

  case $state in
    subcmd)
      local -a subcmds
      subcmds=(
        'list:List graphs'
        'create:Create graph'
        'switch:Switch current graph'
        'remove:Remove graph'
        'validate:Validate graph'
        'info:Graph metadata'
        'export:Export graph'
        'import:Import graph'
      )
      _describe 'subcommand' subcmds
      ;;
    args)
      case $line[1] in
        list) _logseq_graph_list ;;
        create) _logseq_graph_create ;;
        switch) _logseq_graph_switch ;;
        remove) _logseq_graph_remove ;;
        validate) _logseq_graph_validate ;;
        info) _logseq_graph_info ;;
        export) _logseq_graph_export ;;
        import) _logseq_graph_import ;;
      esac
      ;;
  esac
}

_logseq_query() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments -C -s \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--name=[Query name from cli.edn custom-queries or built-ins]:value:_logseq_queries' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--inputs=[EDN vector of query inputs]:value:' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--query=[Datascript query EDN]:value:' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '1:subcommand:->subcmd' \
    '*::args:->args'

  case $state in
    subcmd)
      local -a subcmds
      subcmds=(
        'list:List available queries'
      )
      _describe 'subcommand' subcmds
      ;;
    args)
      case $line[1] in
        list) _logseq_query_list ;;
      esac
      ;;
  esac
}

_logseq_upsert() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments -C -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '1:subcommand:->subcmd' \
    '*::args:->args'

  case $state in
    subcmd)
      local -a subcmds
      subcmds=(
        'block:Upsert block'
        'page:Upsert page'
        'tag:Upsert tag'
        'property:Upsert property'
      )
      _describe 'subcommand' subcmds
      ;;
    args)
      case $line[1] in
        block) _logseq_upsert_block ;;
        page) _logseq_upsert_page ;;
        tag) _logseq_upsert_tag ;;
        property) _logseq_upsert_property ;;
      esac
      ;;
  esac
}

_logseq_remove() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments -C -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '1:subcommand:->subcmd' \
    '*::args:->args'

  case $state in
    subcmd)
      local -a subcmds
      subcmds=(
        'block:Remove blocks'
        'page:Remove page'
        'tag:Remove tag'
        'property:Remove property'
      )
      _describe 'subcommand' subcmds
      ;;
    args)
      case $line[1] in
        block) _logseq_remove_block ;;
        page) _logseq_remove_page ;;
        tag) _logseq_remove_tag ;;
        property) _logseq_remove_property ;;
      esac
      ;;
  esac
}

# --- top-level dispatcher ---

_logseq() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments -C -s \
    '(-h --help)'{-h,--help}'[Show help]' \
    '--version[Show version]' \
    '--config=[Path to cli.edn (default ~/logseq/cli.edn)]:file:_files' \
    '--graph=[Graph name]:value:_logseq_graphs' \
    '--data-dir=[Path to db-worker data dir (default ~/logseq/graphs)]:dir:_files -/' \
    '--timeout-ms=[Request timeout in ms (default 10000)]:value:' \
    '--output=[Output format. Default: human]:value:(human json edn)' \
    '--verbose[Enable verbose debug logging to stderr]' \
    '1:command:->cmds' \
    '*::args:->args'

  case $state in
    cmds)
      local -a cmds
      cmds=(
        'completions:Generate shell completion script'
        'doctor:Run runtime diagnostics'
        'graph:graph commands'
        'list:list commands'
        'query:query commands'
        'remove:remove commands'
        'server:server commands'
        'show:Show tree'
        'upsert:upsert commands'
      )
      _describe 'command' cmds
      ;;
    args)
      case $line[1] in
        completions) _logseq_completions ;;
        doctor) _logseq_doctor ;;
        graph) _logseq_graph ;;
        list) _logseq_list ;;
        query) _logseq_query ;;
        remove) _logseq_remove ;;
        server) _logseq_server ;;
        show) _logseq_show ;;
        upsert) _logseq_upsert ;;
      esac
      ;;
  esac
}

_logseq "$@"
