# This workflow build iOS App as a .ipa file and upload it to TestFlight.

name: Build-iOS

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: "Release Git Ref (Which branch or tag to build?)"
        required: true
        default: "master"

permissions:
  contents: read

env:
  CLOJURE_VERSION: '1.12.4.1618'
  NODE_VERSION: '24'
  JAVA_VERSION: '21'

jobs:
  build-app:
    runs-on: macos-26
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: '26.0.1'
      - name: Show runtimes
        run: |
          xcrun simctl list > /dev/null
      - name: Install iOS platform
        run: |
          xcodebuild -downloadPlatform iOS
      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 10.33.0

      - name: Setup Java JDK
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache clojure deps
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clojure-lib-${{ hashFiles('**/deps.edn') }}

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@f556541eb28a9303896cee0679ba9f60b898300f # 13.5
        with:
          cli: ${{ env.CLOJURE_VERSION }}

      - name: Setup build tools
        run: sudo gem install fastlane -v 2.236.1 --no-document

      - name: Set Build Environment Variables
        run: |
          echo "ENABLE_FILE_SYNC_PRODUCTION=true" >> $GITHUB_ENV

      - name: Compile CLJS
        run: pnpm install --frozen-lockfile && pnpm release-mobile
        env:
          LOGSEQ_SENTRY_DSN: ${{ secrets.LOGSEQ_SENTRY_DSN }}
          LOGSEQ_POSTHOG_TOKEN: ${{ secrets.LOGSEQ_POSTHOG_TOKEN }}

      - name: Upload Sentry Sourcemaps (beta only)
        # if: ${{ github.repository == 'logseq/logseq' && (inputs.build-target == 'beta' || github.event.inputs.build-target == 'beta') }}
        run: |
          curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION=2.58.4 bash
          release_name="logseq-ios@${{ steps.ref.outputs.version }}"
          sentry-cli releases new "${release_name}"
          sentry-cli releases files "${release_name}" upload-sourcemaps --ext map --ext js ./static/js --url-prefix '~/static/js'
          sentry-cli releases finalize "${release_name}"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: logseq
          SENTRY_PROJECT: logseq

      - name: Prepare iOS build
        run: pnpm exec cap sync ios

      - name: Verify iOS web fonts
        run: pnpm test:ios-web-fonts

      - name: Build and upload iOS app
        run: fastlane beta
        working-directory: ./ios/App
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: true
          SLACK_URL: ${{ secrets.SLACK_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          XCODE_XCARGS: "-allowProvisioningUpdates"

      - name: Save Static File
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: static
          path: static
          retention-days: 3
