name: Build-Docker

on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [released]

env:
  NODE_VERSION: '24'
  OCAML_VERSION: '5.5.1'
  BABASHKA_VERSION: '1.12.215'

jobs:

  build-docker:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'true'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Set up Babashka
        uses: DeLaGuardo/setup-clojure@13.5
        with:
          bb: ${{ env.BABASHKA_VERSION }}

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ env.OCAML_VERSION }}
          dune-cache: true

      - name: Fetch pnpm deps
        run: pnpm install --frozen-lockfile

      - name: Fetch db-worker OCaml deps
        working-directory: deps/db-worker
        run: |
          sh scripts/install-opam-deps.sh
          pnpm install

      - name: Fetch UI OCaml deps
        working-directory: deps/ui
        run: sh scripts/install-opam-deps.sh

      - name: Build LUI web app
        run: pnpm release

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/logseq-webapp:latest
